{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.jeremylong",
    "module": "jcs3-slf4j",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jcs3-slf4j-1.0.5.jar",
          "url": "jcs3-slf4j-1.0.5.jar",
          "size": 5675,
          "sha512": "fef1fca0a93e56645fea818a4f7df64ceca8267be44144e31878a19e69d4d5b9992b5aa729eeb45d3b3e56a61fc5351f823b127b7d9830345f255bd4b614c094",
          "sha256": "5b2129a9115d17c9fb65b143f375ab0c15f850248fd5aa0f3307d2cc618df09b",
          "sha1": "a80c160fc4b507cd984d70ebc5ffd28898989f8c",
          "md5": "09ebdca35fd7741e09fcacb1d0e22162"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-jcs3-core",
          "version": {
            "requires": "3.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        }
      ],
      "files": [
        {
          "name": "jcs3-slf4j-1.0.5.jar",
          "url": "jcs3-slf4j-1.0.5.jar",
          "size": 5675,
          "sha512": "fef1fca0a93e56645fea818a4f7df64ceca8267be44144e31878a19e69d4d5b9992b5aa729eeb45d3b3e56a61fc5351f823b127b7d9830345f255bd4b614c094",
          "sha256": "5b2129a9115d17c9fb65b143f375ab0c15f850248fd5aa0f3307d2cc618df09b",
          "sha1": "a80c160fc4b507cd984d70ebc5ffd28898989f8c",
          "md5": "09ebdca35fd7741e09fcacb1d0e22162"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jcs3-slf4j-1.0.5-sources.jar",
          "url": "jcs3-slf4j-1.0.5-sources.jar",
          "size": 3617,
          "sha512": "963af2a9138aa9bd4c4cbf8305d53ef7623769fe6d4dff866df202a598656fe4c66c8cab55eb8dbc3f4c2f36641d5c0b84c0656f9764e6f464effa6d157d2c68",
          "sha256": "b2c84607a680f888f8313aeb6fc5cbd985f1185a4bcbc0cf260e417102ed1694",
          "sha1": "44f6a71b5638f6cc51cc0d495c7844dea1e5c912",
          "md5": "47fd2af4058343102edc57ee5d1ab056"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jcs3-slf4j-1.0.5-javadoc.jar",
          "url": "jcs3-slf4j-1.0.5-javadoc.jar",
          "size": 24395,
          "sha512": "50beb40bc9c9a0c77a9c74147ea6df54255c476b165d9848ce7bc51f6097a17c54e15b7cb09d72048a0697da42dcf9ff2b949b37372b1b8b8d20c4fff030a3ff",
          "sha256": "20c9d6ac8248e82ec95aa00e8605d90ba501118e251e80bd89e2784127f202b5",
          "sha1": "892026033d3b70e24c47469a1575800a0690fbbf",
          "md5": "e5b9ef1ee8ba0ceb20502c99ca49dc3e"
        }
      ]
    }
  ]
}
