{
  "formatVersion": "1.1",
  "component": {
    "group": "au.com.dius.pact.core",
    "module": "matchers",
    "version": "4.6.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "model",
          "version": {
            "requires": "4.6.17"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "matchers-4.6.17.jar",
          "url": "matchers-4.6.17.jar",
          "size": 310684,
          "sha512": "69d8513e62e0c8c68cf360f626d0f60be25cc6855de2d246484a143b235c201551424a3a49f187e3f294cdc4ba16d3fb16f8353f7c9be753250586ae2231deba",
          "sha256": "09e0fa9b1dc81e5101b5670f6a88765253cb719cea2030c995e1b2e7c219eee9",
          "sha1": "34014e51c652119319f8ae09a0554922311a26c4",
          "md5": "4d64146ebe6c32043854b08158e36f39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4"
        },
        {
          "group": "commons-codec",
          "module": "commons-codec"
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "com.github.mifmif",
          "module": "generex",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "javax.mail",
          "module": "mail",
          "version": {
            "requires": "1.5.0-b01"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core"
        },
        {
          "group": "io.github.java-diff-utils",
          "module": "java-diff-utils",
          "version": {
            "requires": "4.12"
          }
        },
        {
          "group": "org.atteo",
          "module": "evo-inflector",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "com.github.ajalt",
          "module": "mordant",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "excludes": [
            {
              "group": "au.com.dius.pact.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "model",
          "version": {
            "requires": "4.6.17"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-jvm",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls-certificates",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.108.Final"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        }
      ],
      "files": [
        {
          "name": "matchers-4.6.17.jar",
          "url": "matchers-4.6.17.jar",
          "size": 310684,
          "sha512": "69d8513e62e0c8c68cf360f626d0f60be25cc6855de2d246484a143b235c201551424a3a49f187e3f294cdc4ba16d3fb16f8353f7c9be753250586ae2231deba",
          "sha256": "09e0fa9b1dc81e5101b5670f6a88765253cb719cea2030c995e1b2e7c219eee9",
          "sha1": "34014e51c652119319f8ae09a0554922311a26c4",
          "md5": "4d64146ebe6c32043854b08158e36f39"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "matchers-4.6.17-javadoc.jar",
          "url": "matchers-4.6.17-javadoc.jar",
          "size": 673554,
          "sha512": "a41527438badc2137f1f8044f2e55aa20038ab52382deff2e6f483e7c10fd2fedea714d0cf0b3bbb6e699f18c2aa40fd1f2fe6a0321bc108cdddfdc96d7b4148",
          "sha256": "a4482b176b18e3938c90e04a0771896be2d4b5049dbd30e009f16d1c2559bd0b",
          "sha1": "f9c4659ed00ae57d70a491e7623c1f76ceb98281",
          "md5": "bdc19f09cd29fb6849369b7f97bf9019"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "matchers-4.6.17-sources.jar",
          "url": "matchers-4.6.17-sources.jar",
          "size": 40896,
          "sha512": "9aed7006935d28319e739ac5bb277c565bc49cd5ef0930233dc85f3981a08350fbf8ab98b0d4543600e9fe21e21171c3e6f426d11fea609ba66810a9745c74dd",
          "sha256": "69136e342976437101d3cef02dc8d4fe14cee7fd24ddc04e8f03c938df4b700c",
          "sha1": "67fa37df1ba009b7032815dd7f4baba21738725f",
          "md5": "ff12899d096b3d4c8892d02f656ea58b"
        }
      ]
    }
  ]
}
