{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-netty/2.3.8/ktor-server-netty-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-server-netty",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http2",
          "version": {
            "requires": "4.1.106.Final"
          }
        },
        {
          "group": "org.eclipse.jetty.alpn",
          "module": "alpn-api",
          "version": {
            "requires": "1.1.3.v20160715"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.106.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.106.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-netty-jvm-2.3.8.jar",
          "url": "ktor-server-netty-jvm-2.3.8.jar",
          "size": 200075,
          "sha512": "fd8fa6beb25372ccf756ee1633826a01b8e26d00d366660858eeb79a37b19718c218b1f0d5e4c93462de1396fd5b569286fdb61458310ba2b1620d3a3e9c39b9",
          "sha256": "7190a710e954c3f9df421c84cb6e02bfef4af3663bc5c6b34a152743fa0d8788",
          "sha1": "e081f7d602fa534e2861c96c08f68924d445a3d6",
          "md5": "4c74a2dc819b00007aa50f986a94ffa9"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-host-common",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-codec-http2",
          "version": {
            "requires": "4.1.106.Final"
          }
        },
        {
          "group": "org.eclipse.jetty.alpn",
          "module": "alpn-api",
          "version": {
            "requires": "1.1.3.v20160715"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-kqueue",
          "version": {
            "requires": "4.1.106.Final"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-transport-native-epoll",
          "version": {
            "requires": "4.1.106.Final"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-netty-jvm-2.3.8.jar",
          "url": "ktor-server-netty-jvm-2.3.8.jar",
          "size": 200075,
          "sha512": "fd8fa6beb25372ccf756ee1633826a01b8e26d00d366660858eeb79a37b19718c218b1f0d5e4c93462de1396fd5b569286fdb61458310ba2b1620d3a3e9c39b9",
          "sha256": "7190a710e954c3f9df421c84cb6e02bfef4af3663bc5c6b34a152743fa0d8788",
          "sha1": "e081f7d602fa534e2861c96c08f68924d445a3d6",
          "md5": "4c74a2dc819b00007aa50f986a94ffa9"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-netty-jvm-2.3.8-sources.jar",
          "url": "ktor-server-netty-jvm-2.3.8-sources.jar",
          "size": 36372,
          "sha512": "210eabc88cc28c879bd1e52e8617004cb302fcf81c734622b79cdac0383557defe4a6dd49158f66eabecc3e36a8ba4073e1849190179f30616cd1a0ef4b8d133",
          "sha256": "2b8ba09cfb4cc210d1b74186aa5fdf3c86bf26e60fc3350be5bd8d8f22365077",
          "sha1": "f036ecfead481c8f458131f849e2bf3b2c6b7b13",
          "md5": "97a18328631bf24b38fc36ade7903a83"
        }
      ]
    }
  ]
}
