{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/2.3.8/ktor-http-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-http",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-jvm-2.3.8.jar",
          "url": "ktor-http-jvm-2.3.8.jar",
          "size": 414281,
          "sha512": "5a3a8007e1e4c09cbfa9ee2b1ab17cb6aef8fe4d3f5ab678faffc2dddce592ac0d04ea38117b2113f3a7ec444aff5c02bf17574ce8e06066c6d248e7b280c5c0",
          "sha256": "5d729636363fc35e220ac31dd0103633c8ab1af1264c07fbccd3f2c25b0bb318",
          "sha1": "f2b16d1b2a8819ecdf5b0cbeabcc721e26a14ff8",
          "md5": "adfe7492bfc970849f8d3a8ee84e399b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-jvm-2.3.8.jar",
          "url": "ktor-http-jvm-2.3.8.jar",
          "size": 414281,
          "sha512": "5a3a8007e1e4c09cbfa9ee2b1ab17cb6aef8fe4d3f5ab678faffc2dddce592ac0d04ea38117b2113f3a7ec444aff5c02bf17574ce8e06066c6d248e7b280c5c0",
          "sha256": "5d729636363fc35e220ac31dd0103633c8ab1af1264c07fbccd3f2c25b0bb318",
          "sha1": "f2b16d1b2a8819ecdf5b0cbeabcc721e26a14ff8",
          "md5": "adfe7492bfc970849f8d3a8ee84e399b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-http-jvm-2.3.8-sources.jar",
          "url": "ktor-http-jvm-2.3.8-sources.jar",
          "size": 85980,
          "sha512": "fd98b68ef9b359b32ddad0f9e89d4ea232571fd693638da9e3d31b70995d7d9819b4435684d9c3fa06ed15a6fe674e42400f331b688c87e44065065cbc13ff7f",
          "sha256": "15ea934ee0137bc8a700cb980c775f3880e973f5daec2502d901c435aa3ca8b8",
          "sha1": "3d0817312dc5b312d6c078fdc8e6a3cdb34663c0",
          "md5": "6efd92d20860dc9e826dab062f489d85"
        }
      ]
    }
  ]
}
