{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-oauth2-client",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "6.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.3.7.jar",
          "url": "spring-boot-starter-oauth2-client-3.3.7.jar",
          "size": 4780,
          "sha512": "53bff2c9e530ccab75af5cf6b3970a49060274e1ac51a0bce3e7591ee483ec08517a6fe37a38a37ae65d5651c8e44d66dd120978d49168d53b119942df3ac9d1",
          "sha256": "ee82416797a324959fe6c96814d2ce86c4afebb7459b9f49444725bf4b1b48a1",
          "sha1": "e73945af77485293814ee8897a08b793c8a06d45",
          "md5": "ffb122b5c938cd8cce5110a8158fddf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-client",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-oauth2-jose",
          "version": {
            "requires": "6.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.3.7.jar",
          "url": "spring-boot-starter-oauth2-client-3.3.7.jar",
          "size": 4780,
          "sha512": "53bff2c9e530ccab75af5cf6b3970a49060274e1ac51a0bce3e7591ee483ec08517a6fe37a38a37ae65d5651c8e44d66dd120978d49168d53b119942df3ac9d1",
          "sha256": "ee82416797a324959fe6c96814d2ce86c4afebb7459b9f49444725bf4b1b48a1",
          "sha1": "e73945af77485293814ee8897a08b793c8a06d45",
          "md5": "ffb122b5c938cd8cce5110a8158fddf2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-oauth2-client-3.3.7-javadoc.jar",
          "size": 4780,
          "sha512": "53bff2c9e530ccab75af5cf6b3970a49060274e1ac51a0bce3e7591ee483ec08517a6fe37a38a37ae65d5651c8e44d66dd120978d49168d53b119942df3ac9d1",
          "sha256": "ee82416797a324959fe6c96814d2ce86c4afebb7459b9f49444725bf4b1b48a1",
          "sha1": "e73945af77485293814ee8897a08b793c8a06d45",
          "md5": "ffb122b5c938cd8cce5110a8158fddf2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-oauth2-client-3.3.7-sources.jar",
          "url": "spring-boot-starter-oauth2-client-3.3.7-sources.jar",
          "size": 4780,
          "sha512": "53bff2c9e530ccab75af5cf6b3970a49060274e1ac51a0bce3e7591ee483ec08517a6fe37a38a37ae65d5651c8e44d66dd120978d49168d53b119942df3ac9d1",
          "sha256": "ee82416797a324959fe6c96814d2ce86c4afebb7459b9f49444725bf4b1b48a1",
          "sha1": "e73945af77485293814ee8897a08b793c8a06d45",
          "md5": "ffb122b5c938cd8cce5110a8158fddf2"
        }
      ]
    }
  ]
}
