org.gradle.jvmargs=-Xmx4096m
# Gradle settings for Jenkins CI
org.gradle.daemon=false
org.gradle.daemon.idletimeout=10000
org.gradle.workers.max=3
org.gradle.parallel=true
org.gradle.configureondemand=true

# Temporary DTSCCI-6351 experiment: use c1 for the comparison; remove to disable benchmarking.
testJitBenchmark=default

