{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okhttp/5.3.2/okhttp-5.3.2.module",
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "5.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-jvm-5.3.2.jar",
          "url": "okhttp-jvm-5.3.2.jar",
          "size": 868403,
          "sha512": "302cba8ec649ecb20512b4878b9f347645cdeada2001e7469363b21ca251bbb05c00e48e426449a88780f0ec25c672f214112b101d8dfd059b5275999ab48768",
          "sha256": "c771f48075b763f6c322055e21129a94b7de4c1faf3f8f58ace320b0c9517a30",
          "sha1": "f31e8de27feebe1e56d6c9d354a0986b65be0e1d",
          "md5": "827a887aa959c1f1d6b12f3345df2484"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-jvm-5.3.2.jar",
          "url": "okhttp-jvm-5.3.2.jar",
          "size": 868403,
          "sha512": "302cba8ec649ecb20512b4878b9f347645cdeada2001e7469363b21ca251bbb05c00e48e426449a88780f0ec25c672f214112b101d8dfd059b5275999ab48768",
          "sha256": "c771f48075b763f6c322055e21129a94b7de4c1faf3f8f58ace320b0c9517a30",
          "sha1": "f31e8de27feebe1e56d6c9d354a0986b65be0e1d",
          "md5": "827a887aa959c1f1d6b12f3345df2484"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okhttp-jvm-5.3.2-sources.jar",
          "url": "okhttp-jvm-5.3.2-sources.jar",
          "size": 395535,
          "sha512": "c42b38e445a04d688248c48e58102d9799f98067280d3433d8a2091214fe33e549639d1531163dd8002d643681baec246434b56e0d81635c1922005752a63781",
          "sha256": "c44c549707d30d56084d0bc1bc00f36c7c326e30664b40c20c1ff8ab657afa5b",
          "sha1": "ac493fc3218691ecfbb832703f96da3079c5d7c4",
          "md5": "88bc7497f858335a39bfe94fba71e42d"
        }
      ]
    }
  ]
}
