{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "ccd-case-document-am-client",
    "version": "1.59.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ccd-case-document-am-client-1.59.2.jar",
          "url": "ccd-case-document-am-client-1.59.2.jar",
          "size": 27001,
          "sha512": "104b8cf4daeb94c34b499427b45f044e4fbeb88bf8cfd7e075a61c2126d42923fa3d1135ff27cd96c58981bf042d23e7c338a70a975476f3a6a8d3b28a12e116",
          "sha256": "88a44208fb4900f0da79c5e83760a8948d82809409a68cb638efb1a024471e8b",
          "sha1": "c0f497a9fd4b66a1bb5c181bbfeb9201a1eee2c1",
          "md5": "1d6b3faf414fe6e18079ba63f1d2c46f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-httpclient",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-okhttp",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ccd-case-document-am-client-1.59.2.jar",
          "url": "ccd-case-document-am-client-1.59.2.jar",
          "size": 27001,
          "sha512": "104b8cf4daeb94c34b499427b45f044e4fbeb88bf8cfd7e075a61c2126d42923fa3d1135ff27cd96c58981bf042d23e7c338a70a975476f3a6a8d3b28a12e116",
          "sha256": "88a44208fb4900f0da79c5e83760a8948d82809409a68cb638efb1a024471e8b",
          "sha1": "c0f497a9fd4b66a1bb5c181bbfeb9201a1eee2c1",
          "md5": "1d6b3faf414fe6e18079ba63f1d2c46f"
        }
      ]
    }
  ]
}
