{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor.addons",
    "module": "reactor-extra",
    "version": "3.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-extra-3.5.2.jar",
          "url": "reactor-extra-3.5.2.jar",
          "size": 104457,
          "sha512": "0a2d3aa1a3a575df1c7d3e0dd9a5b44aea879581dd0122b9283b01b8f37eb3fc7e96e446d704db77fd1a1d6d3130a4d62370895f342759fb8993808ff56db198",
          "sha256": "bd7e29402ba501b30e7bca6ee09b3a6a91d6666a4f3a730bb3858e80b6979ff4",
          "sha1": "163f7babfc93f949738a440ea8cae5079cdb4aaa",
          "md5": "02128822caa10df55b32bb866a6a88d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-extra-3.5.2.jar",
          "url": "reactor-extra-3.5.2.jar",
          "size": 104457,
          "sha512": "0a2d3aa1a3a575df1c7d3e0dd9a5b44aea879581dd0122b9283b01b8f37eb3fc7e96e446d704db77fd1a1d6d3130a4d62370895f342759fb8993808ff56db198",
          "sha256": "bd7e29402ba501b30e7bca6ee09b3a6a91d6666a4f3a730bb3858e80b6979ff4",
          "sha1": "163f7babfc93f949738a440ea8cae5079cdb4aaa",
          "md5": "02128822caa10df55b32bb866a6a88d5"
        }
      ]
    }
  ]
}
