{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "service-auth-provider-java-client",
    "version": "5.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "service-auth-provider-java-client-5.3.3.jar",
          "url": "service-auth-provider-java-client-5.3.3.jar",
          "size": 19071,
          "sha512": "59971a38e0c4287c20c9fcd2a08a48258d171e99db51aa0ab74b142fc585b9281c1a9219abb7b959d317688ad8bfdc9acf30a3281cc58f539da9714b1eb4bb43",
          "sha256": "df082914be6a2284d4ec3820e49a4cd8ec29f17db09356d441a99585df40437c",
          "sha1": "38d9e6945cc7dab8743814e6c9da9c96c08e26a7",
          "md5": "f70771a77808b7ca0f71ef98e1d09aea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "com.warrenstrange",
          "module": "googleauth",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.5.0"
          }
        },
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "service-auth-provider-java-client-5.3.3.jar",
          "url": "service-auth-provider-java-client-5.3.3.jar",
          "size": 19071,
          "sha512": "59971a38e0c4287c20c9fcd2a08a48258d171e99db51aa0ab74b142fc585b9281c1a9219abb7b959d317688ad8bfdc9acf30a3281cc58f539da9714b1eb4bb43",
          "sha256": "df082914be6a2284d4ec3820e49a4cd8ec29f17db09356d441a99585df40437c",
          "sha1": "38d9e6945cc7dab8743814e6c9da9c96c08e26a7",
          "md5": "f70771a77808b7ca0f71ef98e1d09aea"
        }
      ]
    }
  ]
}
