- MIGRATE_CASE
- NOTIFY_HEARING_PARTIES
- MANAGE_CONTACT_INFORMATION
- CASE_PROCEEDS_IN_CASEMAN
- UPDATE_NEXT_HEARING_INFO
- UPDATE_NEXT_HEARING_DETAILS
- DISPATCH_BUSINESS_PROCESS
- SEND_AND_REPLY
- QUERY_MANAGEMENT_RAISE_QUERY
- QUERY_MANAGEMENT_RESPOND_QUERY
- ADD_CASE_NOTE
- REMOVE_DOCUMENT
