- migrateCase
- UPDATE_CASE_DATA
- REMOVE_DOCUMENT
- SERVICE_REQUEST_RECEIVED
- CREATE_CLAIM_AFTER_PAYMENT
- CREATE_CLAIM_SPEC_AFTER_PAYMENT
- CITIZEN_HEARING_FEE_PAYMENT
- CITIZEN_CLAIM_ISSUE_PAYMENT
- INITIATE_GENERAL_APPLICATION_AFTER_PAYMENT
- APPLICATION_PROCEEDS_IN_HERITAGE
- MODIFY_STATE_AFTER_ADDITIONAL_FEE_PAID
- INITIATE_COSC_APPLICATION_AFTER_PAYMENT
