package uk.gov.hmcts.reform.civil.enums.sdo;

public enum SmallTrack {
    SMALL_CLAIM_CREDIT_HIRE,
    SMALL_CLAIM_ROAD_TRAFFIC_ACCIDENT,
    SMALL_CLAIM_DISPUTE_RESOLUTION_HEARING,
    SMALL_CLAIM_FLIGHT_DELAY,
    SMALL_CLAIM_HOUSING_DISREPAIR,
    SMALL_CLAIM_PPI
}
