{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-jaxb-annotations",
    "version": "2.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.17.3.jar",
          "url": "jackson-module-jaxb-annotations-2.17.3.jar",
          "size": 36124,
          "sha512": "b4bf3e5cd2b119c4bcdc184e8e37bdc877e5837e8620807203c710d3b6a868218003e83dd98b39bdff3266c21a006ef431d2f3cc743227b63ea0a4a27c02bf0d",
          "sha256": "453dcdc2aa881887d8f6af3e3e2b27eda9dc96c82d8a4b9839ebb32a0122d4f9",
          "sha1": "7521c7d78a86f1e4467197d224004292b3997de4",
          "md5": "533c43103c0ea0575fe607e5fc9ac526"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "jakarta.activation",
          "module": "jakarta.activation-api",
          "version": {
            "requires": "1.2.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-jaxb-annotations-2.17.3.jar",
          "url": "jackson-module-jaxb-annotations-2.17.3.jar",
          "size": 36124,
          "sha512": "b4bf3e5cd2b119c4bcdc184e8e37bdc877e5837e8620807203c710d3b6a868218003e83dd98b39bdff3266c21a006ef431d2f3cc743227b63ea0a4a27c02bf0d",
          "sha256": "453dcdc2aa881887d8f6af3e3e2b27eda9dc96c82d8a4b9839ebb32a0122d4f9",
          "sha1": "7521c7d78a86f1e4467197d224004292b3997de4",
          "md5": "533c43103c0ea0575fe607e5fc9ac526"
        }
      ]
    }
  ]
}
