{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "idam-java-client",
    "version": "2.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "11.9.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-httpclient",
          "version": {
            "requires": "11.9.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "idam-java-client-2.1.2.jar",
          "url": "idam-java-client-2.1.2.jar",
          "size": 30586,
          "sha512": "96324729d21b2b4a2ad8ab8ec4a87181031e3b4809559ad6b74134c7980f52646aec2f0448987b7a38dfb33945dc758aee84da835d18cc18f03e6d6a72ca505a",
          "sha256": "65b50a386c7569461eb3a1daeb948b4f0f7b11379b60c5866cd9226334a5982a",
          "sha1": "433fac3754abe207970a7573558d93bd9c79374d",
          "md5": "9069a8ca05f65205263cbbb3c0b27376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "11.9.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-httpclient",
          "version": {
            "requires": "11.9.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "idam-java-client-2.1.2.jar",
          "url": "idam-java-client-2.1.2.jar",
          "size": 30586,
          "sha512": "96324729d21b2b4a2ad8ab8ec4a87181031e3b4809559ad6b74134c7980f52646aec2f0448987b7a38dfb33945dc758aee84da835d18cc18f03e6d6a72ca505a",
          "sha256": "65b50a386c7569461eb3a1daeb948b4f0f7b11379b60c5866cd9226334a5982a",
          "sha1": "433fac3754abe207970a7573558d93bd9c79374d",
          "md5": "9069a8ca05f65205263cbbb3c0b27376"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "idam-java-client-2.1.2-sources.jar",
          "url": "idam-java-client-2.1.2-sources.jar",
          "size": 12873,
          "sha512": "6a0fff11700301f6566cd6345fb8ea6fea7bf84e74c441dc61c9c0b8343dd7c6743706a65a66e4fa1b3384a3c4a9d6b16d4c56c604bd2cd18be73b06ac5fefd6",
          "sha256": "6d8bee998cc00b83df7e64a3264e60ceb829b882d51812218a4459407605e1bf",
          "sha1": "6972f358671837d7abd66c30b960f8a203ae89f9",
          "md5": "abf0667d33a5be57378cacffc4181414"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "idam-java-client-2.1.2-javadoc.jar",
          "url": "idam-java-client-2.1.2-javadoc.jar",
          "size": 365697,
          "sha512": "b07484ca72a7918606e52a7ff243e1e088bc20cfa6d62d1704eafaf986c48469f2a0ed40f3be36e3c8048cbb4dcabc9a48fc6e4ffe032bfd32d10e2d71a8db23",
          "sha256": "a08e8e98b642202e3c23cdee8fefd361a9972abd83cb8e1a728d328159ae33bc",
          "sha1": "78e66d12a2a9dd54c6dc114f0fc9bc5f95efc271",
          "md5": "6122d5c2f1040f763f72869412eff845"
        }
      ]
    }
  ]
}
