{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.3.7.jar",
          "url": "spring-boot-autoconfigure-3.3.7.jar",
          "size": 1967146,
          "sha512": "c9be70d6a251a7e0d8df7a7abfeea55adee7a0d40ede13dab4870db2e9b855ed181250e0230197e64e19bfb7c8daf2ea97184e1c21188437ee0196b40ecd468b",
          "sha256": "2c0c38050800f0003d300f9d7590dfdd336a20192cd3d6a4fdfe3a49a5423506",
          "sha1": "2c0bf81965c43562b51d52511dc4eb58b1d437c8",
          "md5": "bc04e59369e4c85c1c282d59403759e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.3.7.jar",
          "url": "spring-boot-autoconfigure-3.3.7.jar",
          "size": 1967146,
          "sha512": "c9be70d6a251a7e0d8df7a7abfeea55adee7a0d40ede13dab4870db2e9b855ed181250e0230197e64e19bfb7c8daf2ea97184e1c21188437ee0196b40ecd468b",
          "sha256": "2c0c38050800f0003d300f9d7590dfdd336a20192cd3d6a4fdfe3a49a5423506",
          "sha1": "2c0bf81965c43562b51d52511dc4eb58b1d437c8",
          "md5": "bc04e59369e4c85c1c282d59403759e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.3.7-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.3.7-javadoc.jar",
          "size": 3050299,
          "sha512": "236a7752dbef5ed633e434962a4d5e7632012f92cee445bf67891fe49682cb1de55f559d825b0e784a42e3f6a74644ebf928c6e5d243f4d84ea5e70271532e75",
          "sha256": "b18856a7f189666727a4c9543360d5f118475c06b745f2f8f5bec083847330bc",
          "sha1": "1968edb940c4dc3351089bd505b9998dc3f48e93",
          "md5": "30c561b10295b72018338a9f92a916a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.3.7-sources.jar",
          "url": "spring-boot-autoconfigure-3.3.7-sources.jar",
          "size": 1133593,
          "sha512": "dbc57963a720cabdd12630f1acd7e891e657b8dbc02f791460c96502e6d111a4b2e0315815040a3a8b1fa1ee74aa02e5708995420779ae13b1f3f07718db1a99",
          "sha256": "491cc6c6617e10bd796fbdc189a745d149676eb9f8f498d34e4cea9d331b3a61",
          "sha1": "c05ed939a6232d2b4be1d75d8b0458b09d27a79f",
          "md5": "dce144b06b03f760c8dfec0bc34d2405"
        }
      ]
    }
  ]
}
