{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.4.41",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.4.41.jar",
          "url": "reactor-core-3.4.41.jar",
          "size": 1744967,
          "sha512": "f18895cfa8388d3a4f0a197b831d19679900f6787414c0c92537c14d5b469197cc6ccff679a148c9b03e97c0b8f591e75952865799a355e2ffbe2ca31d9b2424",
          "sha256": "27ffc421736b78481e815c407acc8a169a417d2bea6ed79bf56eb2a32d80ade8",
          "sha1": "251308e6bd658515b35e91ec702fc52e7b62916f",
          "md5": "69de578ed53528d5d2092568dcd8436a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.4.41.jar",
          "url": "reactor-core-3.4.41.jar",
          "size": 1744967,
          "sha512": "f18895cfa8388d3a4f0a197b831d19679900f6787414c0c92537c14d5b469197cc6ccff679a148c9b03e97c0b8f591e75952865799a355e2ffbe2ca31d9b2424",
          "sha256": "27ffc421736b78481e815c407acc8a169a417d2bea6ed79bf56eb2a32d80ade8",
          "sha1": "251308e6bd658515b35e91ec702fc52e7b62916f",
          "md5": "69de578ed53528d5d2092568dcd8436a"
        }
      ]
    }
  ]
}
