{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-devtools",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-3.3.7.jar",
          "url": "spring-boot-devtools-3.3.7.jar",
          "size": 202872,
          "sha512": "a6e54e3441beb0ba752305b7b4072f9853b607497cf8da865c823fa1d93babe9d344394eef4659287d4f3b888a6abe4037aca220087944658211cf7e3133ce28",
          "sha256": "a291ffed599b279bfbb44f8f6e34990276d46eaacf071d4e5d97339dd5f89d83",
          "sha1": "d9b55ae1055ad53e262cf30f1355fded17c997c2",
          "md5": "77691195921a0c60d19134db570329c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-devtools-3.3.7.jar",
          "url": "spring-boot-devtools-3.3.7.jar",
          "size": 202872,
          "sha512": "a6e54e3441beb0ba752305b7b4072f9853b607497cf8da865c823fa1d93babe9d344394eef4659287d4f3b888a6abe4037aca220087944658211cf7e3133ce28",
          "sha256": "a291ffed599b279bfbb44f8f6e34990276d46eaacf071d4e5d97339dd5f89d83",
          "sha1": "d9b55ae1055ad53e262cf30f1355fded17c997c2",
          "md5": "77691195921a0c60d19134db570329c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-3.3.7-javadoc.jar",
          "url": "spring-boot-devtools-3.3.7-javadoc.jar",
          "size": 345030,
          "sha512": "ba53d5454d6acadb3334a6db640724b2756c92ed50427c9a117f33d9a30c58df4684f81d21ec95cbbf2019126760a6334788c96b517281ded54936e5f61e6319",
          "sha256": "52954e58797a682b375fec79d18f828f5959f390bfef7a329f4b71d82c9074ff",
          "sha1": "9b72889c1a1aff9b2ac624a0af754f6f06b23194",
          "md5": "d81d1dae4d3c9a8f68bfaba08afb5bfc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-devtools-3.3.7-sources.jar",
          "url": "spring-boot-devtools-3.3.7-sources.jar",
          "size": 139128,
          "sha512": "265fa2876dca2421794056efa76d945aa241885040e5cd8f614e57f4648ade3ca7d684c0f78ed2cc50b541fb5a9e1f53fff7267309e0e45c77fdf3a5d22e8e84",
          "sha256": "f6c8a92b6a7971d56ccb088d89b6bd3881e99aece099a16343028c266bbb9d86",
          "sha1": "e1525831346793c53a29b0fd66dc72a8df2b98f7",
          "md5": "0509840ee437202517e0820f599ea99d"
        }
      ]
    }
  ]
}
