{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.49.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.49.5.jar",
          "url": "checker-qual-3.49.5.jar",
          "size": 238219,
          "sha512": "7e1cd29c38a47c789f63abc230e590b8b539bc205ddfa21669534ae2b8a140a9dec58b3bf3cc39e6b7b2021e6c97521a3820d60c9eb829491bbf39e065859f44",
          "sha256": "508c83c62c344f6f7ee28f47b88a8797d6116d043bfd1ca0576c828dd1df2880",
          "sha1": "f0d119b5a4adb4164e9d6fa9fd3ffa5d0e458963",
          "md5": "a6525c2747603fb3ec22d18c4adc7419"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.49.5.jar",
          "url": "checker-qual-3.49.5.jar",
          "size": 238219,
          "sha512": "7e1cd29c38a47c789f63abc230e590b8b539bc205ddfa21669534ae2b8a140a9dec58b3bf3cc39e6b7b2021e6c97521a3820d60c9eb829491bbf39e065859f44",
          "sha256": "508c83c62c344f6f7ee28f47b88a8797d6116d043bfd1ca0576c828dd1df2880",
          "sha1": "f0d119b5a4adb4164e9d6fa9fd3ffa5d0e458963",
          "md5": "a6525c2747603fb3ec22d18c4adc7419"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.49.5-javadoc.jar",
          "url": "checker-qual-3.49.5-javadoc.jar",
          "size": 1103495,
          "sha512": "fad15081141889c679dd8013992daff19d67671ef5baac028fcaabc849925b582eda5937e5f604f9f761b57fb3a4856783050f9bf8ec192c0a9e501e85929287",
          "sha256": "20147311d4949bd43dea1f394d272fc99adb0ffa104d8bb1690d6e6ff89f371d",
          "sha1": "544cf03e0a64aeb18ef195f4f0c2dbf7fdd71ac2",
          "md5": "a32592b5c78c00b3ac9368a2899c1227"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.49.5-sources.jar",
          "url": "checker-qual-3.49.5-sources.jar",
          "size": 272549,
          "sha512": "f993075a72f631078ecf1f8aa603c24366c3768ce02d8d28211c91530fe8dadc5c0dde020c3b1348e1b2b800cd0e00f0844ebb09790e7d07deb68fdc2f5e29bb",
          "sha256": "7a5b44b1fcad095b5677ab31819cbd82aa3579a7bec9ddf4f21a3571a117b5ff",
          "sha1": "f6aa5e830446fbe864dc30e300f6ab29b65133fc",
          "md5": "c688928165db46c4f2f3b912342492e2"
        }
      ]
    }
  ]
}
