{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls-certificates/2.3.8/ktor-network-tls-certificates-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-network-tls-certificates",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-certificates-jvm-2.3.8.jar",
          "url": "ktor-network-tls-certificates-jvm-2.3.8.jar",
          "size": 61523,
          "sha512": "c1f5e9ce4ef64ab07ec4ed05d9db373eb55ce00676b4cebcd51ada2c8d899f6b9a06809a4e71dc665833e979a5c9e66a170506c081231979e04695db67b86d79",
          "sha256": "55a01594b6a877ae1ded411bb69f69ccdc213266729a7a314f81df02f73261aa",
          "sha1": "d6683f200bbedb1527fc083237dfa7399b9ab734",
          "md5": "276507eac69dbc213fc5b4184183d0ce"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-certificates-jvm-2.3.8.jar",
          "url": "ktor-network-tls-certificates-jvm-2.3.8.jar",
          "size": 61523,
          "sha512": "c1f5e9ce4ef64ab07ec4ed05d9db373eb55ce00676b4cebcd51ada2c8d899f6b9a06809a4e71dc665833e979a5c9e66a170506c081231979e04695db67b86d79",
          "sha256": "55a01594b6a877ae1ded411bb69f69ccdc213266729a7a314f81df02f73261aa",
          "sha1": "d6683f200bbedb1527fc083237dfa7399b9ab734",
          "md5": "276507eac69dbc213fc5b4184183d0ce"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-network-tls-certificates-jvm-2.3.8-sources.jar",
          "url": "ktor-network-tls-certificates-jvm-2.3.8-sources.jar",
          "size": 7435,
          "sha512": "75c0aba0c7d3d4b27b5c03ee05b85f1a61ed0aa6bf94e4488524d55d3ef1263b72cc60426288fa858ddc724b39cb1e6304151eab5bc5616b82d18dd258e74dae",
          "sha256": "eda09b02069f78e94c30c152940b32b5b394fbc8a2af688dad549a7119dc7ec0",
          "sha1": "cdf58ffd4471c27e37581d676e4fe00fb411d7df",
          "md5": "577ab01c37148f0f0bc55921b730ffbc"
        }
      ]
    }
  ]
}
