package uk.gov.hmcts.reform.hmc.model.messaging;

public enum HmcStatus {
    HEARING_REQUESTED,
    AWAITING_LISTING,
    UPDATE_REQUESTED,
    UPDATE_SUBMITTED,
    LISTED,
    AWAITING_ACTUALS,
    CANCELLATION_REQUESTED,
    CANCELLATION_SUBMITTED,
    CANCELLED,
    ADJOURNED,
    CLOSED,
    COMPLETED,
    EXCEPTION
}
