package uk.gov.hmcts.reform.civil.enums;

public enum CaseState {
    PENDING_CASE_ISSUED,
    CASE_ISSUED,
    AWAITING_CASE_DETAILS_NOTIFICATION,
    AWAITING_RESPONDENT_ACKNOWLEDGEMENT,
    CASE_DISMISSED,
    AWAITING_APPLICANT_INTENTION,
    PROCEEDS_IN_HERITAGE_SYSTEM,
    JUDICIAL_REFERRAL,

    //General Application states
    PENDING_APPLICATION_ISSUED,
    AWAITING_RESPONDENT_RESPONSE,
    APPLICATION_SUBMITTED_AWAITING_JUDICIAL_DECISION,
    ADDITIONAL_RESPONSE_TIME_EXPIRED,
    ADDITIONAL_RESPONSE_TIME_PROVIDED,
    AWAITING_DIRECTIONS_ORDER_DOCS,
    ORDER_MADE,
    LISTING_FOR_A_HEARING,
    AWAITING_WRITTEN_REPRESENTATIONS,
    AWAITING_ADDITIONAL_INFORMATION,
    APPLICATION_DISMISSED,
    APPLICATION_CLOSED,
    RESPOND_TO_JUDGE_WRITTEN_REPRESENTATION;

}

