package uk.gov.hmcts.reform.civil.enums;

public enum CaseState {
    PENDING_CASE_ISSUED,
    CASE_ISSUED,
    AWAITING_CASE_DETAILS_NOTIFICATION,
    AWAITING_RESPONDENT_ACKNOWLEDGEMENT,
    CASE_DISMISSED,
    AWAITING_APPLICANT_INTENTION,
    PROCEEDS_IN_HERITAGE_SYSTEM,
    JUDICIAL_REFERRAL,
    CASE_PROGRESSION,
    HEARING_READINESS,
    PREPARE_FOR_HEARING_CONDUCT_HEARING,
    DECISION_OUTCOME,
    IN_MEDIATION,
    CASE_STAYED,
    All_FINAL_ORDERS_ISSUED,
    CASE_SETTLED
}

