package uk.gov.hmcts.reform.civil.enums;

public enum PartySelected {
    CLAIMANT_ONE,
    CLAIMANT_ONE_LITIGATION_FRIEND,
    CLAIMANT_TWO,
    CLAIMANT_TWO_LITIGATION_FRIEND,
    CLAIMANT_ONE_EXPERTS,
    CLAIMANT_ONE_WITNESSES,
    DEFENDANT_ONE,
    DEFENDANT_ONE_LITIGATION_FRIEND,
    DEFENDANT_ONE_EXPERTS,
    DEFENDANT_ONE_WITNESSES,
    DEFENDANT_TWO,
    DEFENDANT_TWO_LITIGATION_FRIEND,
    DEFENDANT_TWO_EXPERTS,
    DEFENDANT_TWO_WITNESSES
}
