package uk.gov.hmcts.reform.civil.notification.handlers;

public enum CamundaProcessIdentifier {
    ClaimDismissedNotifyParties,
    LitigationFriendAddedNotifier,
    GenerateDJFormNotifyParties,
    ClaimProceedsOfflineUnspecNotifyApplicantSolicitor,
    UnspecNotifyClaimNotifier,
    UnspecNotifyClaimDetailsNotifier,
    AcknowledgeClaimUnspecNotifyParties,
    GenerateOrderNotifyPartiesCourtOfficerOrder,
    GenerateOrderNotifyParties,
    DefendantResponseUnspecFullDefenceNotifyParties,
    DefendantResponseUnspecCaseHandedOfflineNotifyParties,
    DefendantResponseSpecCaseHandedOfflineNotifyParties,
    DefendantResponseSpecFullDefenceFullPartAdmitNotifyParties,
    DefendantResponseSpecOneRespRespondedNotifyParties,
    DefendantResponseSpecLipvLRFullOrPartAdmit,
    CreateClaimAfterPaymentContinuingOfflineNotifier,
    CreateClaimAfterPaymentContinuingOnlineNotifier,
    JudgmentVariedDeterminationOfMeansNotifyParties,
    ClaimSubmittedApplicantNotifier,
    ClaimantLipHelpWithFeesNotifier,
    ClaimantResponseConfirmsNotToProceedNotify,
    ClaimantConfirmsToProceedNotify,
    ClaimantDefendantAgreedMediationNotify,
    ClaimantResponseNotAgreedRepaymentNotify,
    ClaimantResponseAgreedRepaymentNotify,
    ClaimantResponseAgreedSettledPartAdmitNotify,
    ClaimantResponseConfirmsNotToProceedLipNotify,
    ApplicantNotifyOthersTrialReady,
    Respondent1NotifyOthersTrialReady,
    Respondent2NotifyOthersTrialReady,
}
