package uk.gov.hmcts.reform.civil.handler.callback.user.spec.show;

public enum ResponseOneVOneShowTag {
    ONE_V_ONE_FULL_ADMIT,
    ONE_V_ONE_FULL_ADMIT_HAS_PAID,
    ONE_V_ONE_FULL_ADMIT_PAY_IMMEDIATELY,
    ONE_V_ONE_FULL_ADMIT_PAY_BY_SET_DATE,
    ONE_V_ONE_FULL_ADMIT_PAY_INSTALMENT,
    ONE_V_ONE_FULL_DEFENCE,
    ONE_V_ONE_PART_ADMIT,
    ONE_V_ONE_PART_ADMIT_HAS_PAID,
    ONE_V_ONE_PART_ADMIT_PAY_IMMEDIATELY,
    ONE_V_ONE_PART_ADMIT_PAY_BY_SET_DATE,
    ONE_V_ONE_PART_ADMIT_PAY_INSTALMENT,
    ONE_V_ONE_COUNTER_CLAIM
}
