{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-parameter-names",
    "version": "2.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.14.2.jar",
          "url": "jackson-module-parameter-names-2.14.2.jar",
          "size": 8606,
          "sha512": "dc6596ae7ee4afc27779d50f27a9442e4cc500ffa5404901112fc7cbe4ef0bd24b3dba4926a6fd32acf53bc91830ff5ad690c0eeadf6c441810a91d00c97b9f0",
          "sha256": "727311bf8bc2c33c9d5c14406ee8eb05b69418494a1b34da2202b82759e6bc6c",
          "sha1": "8dade108267ab956802cdfb62b2fcfcbdd309c70",
          "md5": "b3ab700bb690e9b3e83dcdef11fbf4a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.14.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-parameter-names-2.14.2.jar",
          "url": "jackson-module-parameter-names-2.14.2.jar",
          "size": 8606,
          "sha512": "dc6596ae7ee4afc27779d50f27a9442e4cc500ffa5404901112fc7cbe4ef0bd24b3dba4926a6fd32acf53bc91830ff5ad690c0eeadf6c441810a91d00c97b9f0",
          "sha256": "727311bf8bc2c33c9d5c14406ee8eb05b69418494a1b34da2202b82759e6bc6c",
          "sha1": "8dade108267ab956802cdfb62b2fcfcbdd309c70",
          "md5": "b3ab700bb690e9b3e83dcdef11fbf4a"
        }
      ]
    }
  ]
}
