package uk.gov.hmcts.reform.civil.model.documents;

public enum DocumentType {
    SEALED_CLAIM,
    ACKNOWLEDGEMENT_OF_CLAIM,
    ACKNOWLEDGEMENT_OF_SERVICE,
    DIRECTIONS_QUESTIONNAIRE,
    DEFENDANT_DEFENCE,
    DEFENDANT_DRAFT_DIRECTIONS,
    DEFAULT_JUDGMENT
}
