package uk.gov.hmcts.reform.civil.model.citizenui;

public enum DashboardClaimStatus {
    NO_STATUS,
    NO_RESPONSE,
    RESPONSE_OVERDUE,
    RESPONSE_DUE_NOW,
    ADMIT_PAY_IMMEDIATELY,
    ADMIT_PAY_BY_SET_DATE,
    ADMIT_PAY_INSTALLMENTS,
    ELIGIBLE_FOR_CCJ,
    MORE_TIME_REQUESTED,
    CLAIMANT_ACCEPTED_STATES_PAID,
    TRANSFERRED,
    REQUESTED_COUNTRY_COURT_JUDGEMENT,
    SETTLED
}
