package uk.gov.hmcts.reform.civil.model.citizenui;

public enum DefendantResponseStatus {
    NO_RESPONSE,
    ELIGIBLE_FOR_CCJ_AFTER_FULL_ADMIT_PAY_IMMEDIATELY_PAST_DEADLINE,
    ELIGIBLE_FOR_CCJ,
    MORE_TIME_REQUESTED,
    PAID_IN_FULL,
    CLAIMANT_ACCEPTED_STATES_PAID,
    PAID_IN_FULL_CCJ_CANCELLED,
    PAID_IN_FULL_CCJ_SATISFIED,
    TRANSFERRED,
    REDETERMINATION_BY_JUDGE
}
