package uk.gov.hmcts.reform.civil.model.citizenui;

public enum TranslatedDocumentType {
    DEFENDANT_RESPONSE,
    CLAIM_ISSUE,
    CLAIMANT_INTENTION,
    ORDER_NOTICE,
    STANDARD_DIRECTION_ORDER,
    INTERLOCUTORY_JUDGMENT,
    NOTICE_OF_DISCONTINUANCE_CLAIMANT,
    NOTICE_OF_DISCONTINUANCE_DEFENDANT,
    MANUAL_DETERMINATION;
}
