package uk.gov.hmcts.reform.civil.model.citizenui;

public enum TranslatedDocumentType {
    DEFENDANT_RESPONSE,
    CLAIM_ISSUE,
    CLAIMANT_INTENTION,
    ORDER_NOTICE,
    STANDARD_DIRECTION_ORDER,
    INTERLOCUTORY_JUDGMENT,
    MANUAL_DETERMINATION,
    DECISION_MADE_ON_APPLICATIONS,
    NOTICE_OF_DISCONTINUANCE_DEFENDANT,
    FINAL_ORDER,
    SETTLEMENT_AGREEMENT,
    COURT_OFFICER_ORDER;
}
