{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-server-core",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-core-metadata-2.3.8.jar",
          "url": "ktor-server-core-2.3.8.jar",
          "size": 43382,
          "sha512": "90c3755655d7bc9783bd776ef2134514538cccf5c97a57e61c93c802b1201dd5694d228caf69d23bde420b4ab37a79971974b9455dcdc18d8d563e731a0e8d1b",
          "sha256": "3f3b54035ba1f0a5dfcaadcba0977ad890d50c451aee22d53ef4d56b53a6fcee",
          "sha1": "7a7e40f3485ecfe233b2e5d6d9c3cf441df9290b",
          "md5": "d15ae02039f07e722eb8d32e13eae9b8"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-server-core-kotlin-2.3.8-sources.jar",
          "url": "ktor-server-core-2.3.8-sources.jar",
          "size": 78254,
          "sha512": "98f6866185e06c5a33a380b79e74f0dbdef7ed1c65bad66f72d9ee9968e389db6c7dc555ad157c16d5e911d06bb76200cc9162e05c506de1fb686fe1b7383df1",
          "sha256": "3dcf649db836b72d11bafae1dfdfe1f2339fee42172e3712464493df5210d379",
          "sha1": "6429bc929bdd4b7b07eba0ca48290dce39aad206",
          "md5": "7b47117a52347a79e96cea8cab397916"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iosarm64/2.3.8/ktor-server-core-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iosarm64/2.3.8/ktor-server-core-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iosarm64/2.3.8/ktor-server-core-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iossimulatorarm64/2.3.8/ktor-server-core-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iossimulatorarm64/2.3.8/ktor-server-core-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iossimulatorarm64/2.3.8/ktor-server-core-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iosx64/2.3.8/ktor-server-core-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iosx64/2.3.8/ktor-server-core-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-iosx64/2.3.8/ktor-server-core-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-core-jvm/2.3.8/ktor-server-core-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-core-jvm/2.3.8/ktor-server-core-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-core-jvm/2.3.8/ktor-server-core-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-linuxarm64/2.3.8/ktor-server-core-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-linuxarm64/2.3.8/ktor-server-core-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-linuxx64/2.3.8/ktor-server-core-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-linuxx64/2.3.8/ktor-server-core-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-macosarm64/2.3.8/ktor-server-core-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-macosarm64/2.3.8/ktor-server-core-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-macosarm64/2.3.8/ktor-server-core-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-macosx64/2.3.8/ktor-server-core-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-macosx64/2.3.8/ktor-server-core-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-macosx64/2.3.8/ktor-server-core-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvosarm64/2.3.8/ktor-server-core-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvosarm64/2.3.8/ktor-server-core-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvosarm64/2.3.8/ktor-server-core-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvossimulatorarm64/2.3.8/ktor-server-core-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvossimulatorarm64/2.3.8/ktor-server-core-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvossimulatorarm64/2.3.8/ktor-server-core-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvosx64/2.3.8/ktor-server-core-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvosx64/2.3.8/ktor-server-core-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-tvosx64/2.3.8/ktor-server-core-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosarm32/2.3.8/ktor-server-core-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosarm32/2.3.8/ktor-server-core-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosarm32/2.3.8/ktor-server-core-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosarm64/2.3.8/ktor-server-core-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosarm64/2.3.8/ktor-server-core-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosarm64/2.3.8/ktor-server-core-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchossimulatorarm64/2.3.8/ktor-server-core-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchossimulatorarm64/2.3.8/ktor-server-core-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchossimulatorarm64/2.3.8/ktor-server-core-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosx64/2.3.8/ktor-server-core-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosx64/2.3.8/ktor-server-core-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-server-core-watchosx64/2.3.8/ktor-server-core-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-core-watchosx64",
        "version": "2.3.8"
      }
    }
  ]
}
