{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy",
    "version": "4.0.18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "groovydocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "groovydoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-4.0.18-groovydoc.jar",
          "url": "groovy-4.0.18-groovydoc.jar",
          "size": 6184836,
          "sha512": "86f5cedec0aa56a11b1edf1f4ff15f3f61d7641d54ee26c1275925ddda4b952d98a6b9bde96f8f5cb19fa42852fef16c7f00764d627bea00db8d2f0a10b503d7",
          "sha256": "22d9eacea5761717611b340099fb6d8c0bfdaff69ce703dadca6c4561749d27e",
          "sha1": "fe4b2e476519702c21faf0ce04c6e627b24fb1f0",
          "md5": "fd442ad34868ea12f26a7066a9a42b17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-4.0.18-javadoc.jar",
          "url": "groovy-4.0.18-javadoc.jar",
          "size": 6714492,
          "sha512": "b03995e18f8d4bfaf827a669fb0ee5cdc2b5a8620707ee180bcabee32c34918db8f28d828a0acbd3d57e651c14ecee8575160bf4223f671aa095bda577ddaa59",
          "sha256": "f81d2d6e2b1118d3e1edfd632ca9b22d5957ec125651f97491d20ba41e36f6fd",
          "sha1": "4dca51c3cb54951a20626a3369e8330c6413eb10",
          "md5": "bfaebd38779be8fc6988c7d3600cfd1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-4.0.18-sources.jar",
          "url": "groovy-4.0.18-sources.jar",
          "size": 2580847,
          "sha512": "f3a2b30c80043a85e349c65517eeefe14453338b75aa18c87657df3af285375f7f229dee044611373fccc332814aa91b77ee8d34ef429b1aef36c4d2efe7c0df",
          "sha256": "95a4fb3f7b25d6e9d2386a820be2d39fa8ad830635c1c1a2caa940539deec9e6",
          "sha1": "b2bc7fbed84271bbf548c3f87fdbe7b28de082ae",
          "md5": "beaa43142ca5cca5caf2cae660ce70e7"
        }
      ]
    },
    {
      "name": "groovyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.18"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "groovy-4.0.18.jar",
          "url": "groovy-4.0.18.jar",
          "size": 7596659,
          "sha512": "590ed748bd3ba81b6822c54126174b807cd6c9dde56860c9696f34e547dce75146238135724d7d5b9893b9aa4bf1d59cdb1eafaca1527c5050e97806b846048a",
          "sha256": "65e531f1583a3c23d4247a6d8db33a35d01724af47f0f3b04ca7b814f82a323f",
          "sha1": "4036d7d22135c92b5ecbbe6ea1880e4e32d15f95",
          "md5": "ac66d9507926277b17fea070640cfacf"
        }
      ],
      "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy",
          "version": "4.0.18"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "groovyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.18"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "groovy-4.0.18.jar",
          "url": "groovy-4.0.18.jar",
          "size": 7596659,
          "sha512": "590ed748bd3ba81b6822c54126174b807cd6c9dde56860c9696f34e547dce75146238135724d7d5b9893b9aa4bf1d59cdb1eafaca1527c5050e97806b846048a",
          "sha256": "65e531f1583a3c23d4247a6d8db33a35d01724af47f0f3b04ca7b814f82a323f",
          "sha1": "4036d7d22135c92b5ecbbe6ea1880e4e32d15f95",
          "md5": "ac66d9507926277b17fea070640cfacf"
        }
      ],
      "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy",
          "version": "4.0.18"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "gparsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-gpars",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "gparsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.codehaus.gpars",
          "module": "gpars",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-all"
            }
          ]
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-gpars",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "grapesApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-grapes",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "grapesRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.ivy",
          "module": "ivy",
          "version": {
            "requires": "2.5.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-grapes",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "loggingApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-logging",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "loggingRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-logging",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "xstreamAstApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-xstream-ast",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "xstreamAstRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.thoughtworks.xstream",
          "module": "xstream",
          "version": {
            "requires": "1.4.20"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "xpp3",
              "module": "xpp3_min"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "jmock",
              "module": "jmock"
            }
          ]
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-xstream-ast",
          "version": "4.0.18"
        }
      ]
    },
    {
      "name": "androidRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-4.0.18-grooid.jar",
          "url": "groovy-4.0.18-grooid.jar",
          "size": 7813140,
          "sha512": "b85c4799c1f6146f8b2890ffa9859ce024c08350b3e5828aa77853b4a75b956a09d231da850e245c8725508871660362e01305677b616792527cae56b415661e",
          "sha256": "4f65f4138386a685fecb24a250ef106344af3f03a608ee02678bc94845520e5c",
          "sha1": "4f6c119d112e9ee9c71ce3420b3f68fa8157077f",
          "md5": "3216ef45a5568470543d1bc6367fa8c1"
        }
      ],
      "capabilities": [
        {
          "group": "org.apache.groovy",
          "name": "groovy-grooid",
          "version": "4.0.18"
        }
      ]
    }
  ]
}
