{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-blackbird",
    "version": "2.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-blackbird-2.20.1.jar",
          "url": "jackson-module-blackbird-2.20.1.jar",
          "size": 64938,
          "sha512": "029e29f66d296719e97ffabdaedf60779d7bc93226de14e23600c94198c51084fd4313d7b2eb44540e28855c1c6413f741dabd450a7ad93ce00433c59cb66832",
          "sha256": "88fbdf758e6d6dd039273a92ced50eacfc7383aebe31330dfaeb3ecffcf8c886",
          "sha1": "d52c1163e91f31a839ec8242c213b1ece06ceccb",
          "md5": "6eae3ff8e3733a52a30d310e0fbaa8f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-blackbird-2.20.1.jar",
          "url": "jackson-module-blackbird-2.20.1.jar",
          "size": 64938,
          "sha512": "029e29f66d296719e97ffabdaedf60779d7bc93226de14e23600c94198c51084fd4313d7b2eb44540e28855c1c6413f741dabd450a7ad93ce00433c59cb66832",
          "sha256": "88fbdf758e6d6dd039273a92ced50eacfc7383aebe31330dfaeb3ecffcf8c886",
          "sha1": "d52c1163e91f31a839ec8242c213b1ece06ceccb",
          "md5": "6eae3ff8e3733a52a30d310e0fbaa8f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-module-blackbird-2.20.1-javadoc.jar",
          "url": "jackson-module-blackbird-2.20.1-javadoc.jar",
          "size": 117673,
          "sha512": "f72d930d64d847f96f6d9022baa27d9f9474d7bdaf6d4b6c27858dc2232be2431d1a547dc5500aa6e951877e0d45eb511275e064eb4a0ac296ee928a5e57d2f0",
          "sha256": "ab3f6bc6e23d0b0e2b5787838531d8cd4de5b2f240bb8870365381a11a8a91f9",
          "sha1": "f48644def358a3e4f71a3896ed320a91dbf15feb",
          "md5": "60727e51c54975765f1ff9d91a17486a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-module-blackbird-2.20.1-sources.jar",
          "url": "jackson-module-blackbird-2.20.1-sources.jar",
          "size": 40166,
          "sha512": "8be1d548aa167c61782de64955238019d9c43cc70d00f009699f294b492a6f961e94c8fcea6a51b7bb3f0abccf6f867612b1d172c1de6704a97e0b95cd3850dd",
          "sha256": "79796350f4bb71b543bca3ecd1a8d9dadb3c3efe86c69f098dbb88bb2877c9d5",
          "sha1": "6329c0ee4471b0eba1ae468028dae8101e057025",
          "md5": "2cbfa492c309bdf34ce1e319a75a8554"
        }
      ]
    }
  ]
}
