#!/usr/bin/env bash
LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

VALID_BRANCH_REGEX="^(feat|spike|fix|test|refactor)\/CIV-[0-9]|CIV-[a-zA-Z]+|renovate\/"

MESSAGE="The branch names in this project must adhere to this contract: $VALID_BRANCH_REGEX. You should rename your branch to a valid name and try again."

if [[ ! $LOCAL_BRANCH =~ $VALID_BRANCH_REGEX ]]
then
    echo "$MESSAGE"
    echo "Example for valid branch names"
    echo "feat/CIV-1234,renovate/something"
    echo "spike/CIV-2345"
    echo "fix/CIV-1234 or fix/CIV-1234-taskname"
    echo "test/CIV-2346"
    echo "refactor/CIV-2349"
    echo "renovate/CIV-2347 or renovate/taskname"
    exit 1
fi

exit 0
