{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls/2.3.8/ktor-network-tls-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-network-tls",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-2.3.8.jar",
          "url": "ktor-network-tls-jvm-2.3.8.jar",
          "size": 208395,
          "sha512": "1ad079916ae6c869bfb95dd5d54c204c283ef290aaedf5f4b379542b16e625efe1336fe0818bbcd5c9e8c0aea9115cb33488e80c1ae5f7c672a62b5f12e36d90",
          "sha256": "aac910965317afb70024e4de01c65dc2150601513ffda30cc74049cd5435dc6f",
          "sha1": "f3c211a57001d2d246d5e24d887ee37058248f7e",
          "md5": "6b8a2bbc0c058ab6ea6e2665c307d77b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-2.3.8.jar",
          "url": "ktor-network-tls-jvm-2.3.8.jar",
          "size": 208395,
          "sha512": "1ad079916ae6c869bfb95dd5d54c204c283ef290aaedf5f4b379542b16e625efe1336fe0818bbcd5c9e8c0aea9115cb33488e80c1ae5f7c672a62b5f12e36d90",
          "sha256": "aac910965317afb70024e4de01c65dc2150601513ffda30cc74049cd5435dc6f",
          "sha1": "f3c211a57001d2d246d5e24d887ee37058248f7e",
          "md5": "6b8a2bbc0c058ab6ea6e2665c307d77b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-network-tls-jvm-2.3.8-sources.jar",
          "url": "ktor-network-tls-jvm-2.3.8-sources.jar",
          "size": 37724,
          "sha512": "4434313fd52da683ee328c85ba7a070710815afcef7866f42dc83c084fb5edf77010232334e17f39dbe33f829e0428d1e78a90d986c5e189d232103b6d3f924c",
          "sha256": "559d1b02a5d70116feb605d12d26f9614ab974f2e7a7b588fa321b7ea26c8f50",
          "sha1": "1541d73362b9ba60625a3a57ed20b6d71a400bf6",
          "md5": "02599065854f7e368c6ad823b31cfe61"
        }
      ]
    }
  ]
}
