{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "idam-java-client",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-httpclient",
          "version": {
            "requires": "13.6"
          }
        }
      ],
      "files": [
        {
          "name": "idam-java-client-3.0.5.jar",
          "url": "idam-java-client-3.0.5.jar",
          "size": 32103,
          "sha512": "22ab31d1827f397bae489c056f62ba56882c96e619279d3b4a974270dba780dd301aa26a3e02eb25f05e07f9d32d6c64934496a4cb1cfc3a62eddd10815d67db",
          "sha256": "25da58da34e2b64cf250cd4ca2d2591b1b763d750043ea55e6e4485be93c187f",
          "sha1": "d7bd37799cca6441a119b4eb07448567f37785a4",
          "md5": "6e31564b858c5c42e36735973040c09f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-httpclient",
          "version": {
            "requires": "13.6"
          }
        }
      ],
      "files": [
        {
          "name": "idam-java-client-3.0.5.jar",
          "url": "idam-java-client-3.0.5.jar",
          "size": 32103,
          "sha512": "22ab31d1827f397bae489c056f62ba56882c96e619279d3b4a974270dba780dd301aa26a3e02eb25f05e07f9d32d6c64934496a4cb1cfc3a62eddd10815d67db",
          "sha256": "25da58da34e2b64cf250cd4ca2d2591b1b763d750043ea55e6e4485be93c187f",
          "sha1": "d7bd37799cca6441a119b4eb07448567f37785a4",
          "md5": "6e31564b858c5c42e36735973040c09f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "idam-java-client-3.0.5-sources.jar",
          "url": "idam-java-client-3.0.5-sources.jar",
          "size": 13287,
          "sha512": "bd9a0620844efc95dc63437e81acc3b8ecdf215cf351867fa780cb27cb3dce029928347ad2ff7d298c25b54386c7435a511bb09c6d9c8113d16726c58e33d466",
          "sha256": "263e5fff67f4f79c8f72af68a4da70792133a58e1055e651428c735cf8c5c79d",
          "sha1": "15950f37a308cc3c0a903194f568ea315c467a84",
          "md5": "88c4ca42ba17234df62abae99cfcb642"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "idam-java-client-3.0.5-javadoc.jar",
          "url": "idam-java-client-3.0.5-javadoc.jar",
          "size": 139526,
          "sha512": "dd70581c3d07aac72556e706bfdb19fb0b91ab37c9d2152b15be2ab10d4b4ee317aea7e22bdc22d6759f995bcd03f8e07d470df3aae62830db5c3f5fc6d9c171",
          "sha256": "e662ed91bc58f75a415cd046c49e6b6b14ab44ad5cc50a91569a83a5517077a7",
          "sha1": "12dece52338b190e1e49d071d2822337eafb2ea2",
          "md5": "92630a96785c0980174bb45cecd6b2c4"
        }
      ]
    }
  ]
}
