{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts.rse-cft-lib",
    "module": "test-runner",
    "version": "0.19.2017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-runner-0.19.2017.jar",
          "url": "test-runner-0.19.2017.jar",
          "size": 2707,
          "sha512": "3180730de7f0f94bc388425d502ee36a920b88d7dca935e3d7cbf50124c40fe63e4e881db136080130f98649eddc54c60589b63fc544d2cdc613a9c7e2c4cf2e",
          "sha256": "bd8766390717ecc4e85cfa49c12431be77f479a326775846b3a65d14e5418652",
          "sha1": "8ca3743fc9c54b7dc35f025809958c5209f0583c",
          "md5": "80b08833143d5bf5f92877085a6a9036"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-console-standalone",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "3.18.3"
          }
        }
      ],
      "files": [
        {
          "name": "test-runner-0.19.2017.jar",
          "url": "test-runner-0.19.2017.jar",
          "size": 2707,
          "sha512": "3180730de7f0f94bc388425d502ee36a920b88d7dca935e3d7cbf50124c40fe63e4e881db136080130f98649eddc54c60589b63fc544d2cdc613a9c7e2c4cf2e",
          "sha256": "bd8766390717ecc4e85cfa49c12431be77f479a326775846b3a65d14e5418652",
          "sha1": "8ca3743fc9c54b7dc35f025809958c5209f0583c",
          "md5": "80b08833143d5bf5f92877085a6a9036"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-runner-0.19.2017-sources.jar",
          "url": "test-runner-0.19.2017-sources.jar",
          "size": 1741,
          "sha512": "6286260a5ac3723ab84546ea038a1e5d1a224ddf94b1473d998f14699842d3047055cfb6277a21989075ba18041eca3b1ce0854c9db63291e9608fadd28b8285",
          "sha256": "0f35341b8e9926132445ae21f4a577c21c95959243e77c9f7040501bec73badf",
          "sha1": "946e809a7e5327729e0b2f4bae4d8dd77dd67667",
          "md5": "14b644ebf140da18c455b277442b6e3a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "test-runner-0.19.2017-javadoc.jar",
          "url": "test-runner-0.19.2017-javadoc.jar",
          "size": 92184,
          "sha512": "2e37c848cb2f00f8799f43a22d5f3c6f980abe906143944b23858af109a075e6d53140b0e0a560be3b4f69e378bc4a85b5c03cbf2f3aac0648240b9e238adf35",
          "sha256": "fc0d2da3d7aa6d2ccd0125dc5fa6d64f6c96be9219cba707ab968653700ee310",
          "sha1": "49adf5019d5a2da7edcf05412dbbc3f028a74f44",
          "md5": "94e7e6267fb1ed6a5bbd4c61228dfacc"
        }
      ]
    }
  ]
}
