{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.3.7.jar",
          "url": "spring-boot-starter-json-3.3.7.jar",
          "size": 4747,
          "sha512": "33ffa5425cd3cf9eb65d46ec7e724af8709d17edb9edd9bf67436e43a66a841a0e197c14b9959dbe750006bf3038d5dd9b20a2f12434462b17c1c363477df28a",
          "sha256": "5993e61b88dc5c95d086935d677ac3e602d6511a3e563f75ccc25a8f8a546e0d",
          "sha1": "d3ced6ed8c17d8b8616ec45ac95c213c5a1ca7a2",
          "md5": "8b393f15c7bdc161793dce62e5d9db4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.3.7.jar",
          "url": "spring-boot-starter-json-3.3.7.jar",
          "size": 4747,
          "sha512": "33ffa5425cd3cf9eb65d46ec7e724af8709d17edb9edd9bf67436e43a66a841a0e197c14b9959dbe750006bf3038d5dd9b20a2f12434462b17c1c363477df28a",
          "sha256": "5993e61b88dc5c95d086935d677ac3e602d6511a3e563f75ccc25a8f8a546e0d",
          "sha1": "d3ced6ed8c17d8b8616ec45ac95c213c5a1ca7a2",
          "md5": "8b393f15c7bdc161793dce62e5d9db4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-json-3.3.7-javadoc.jar",
          "size": 4747,
          "sha512": "eb551d3a2a432b5f6358b41616246a46ee9f5a999d9212aaa8b4c620325c791da7db2e1d201823b29181d767a9c5dd78649ffecab64183b3588b512adff1c97e",
          "sha256": "de2925dd36a1db640978bd6188301ca4f23162b219cf51efcbee767ad0cf6295",
          "sha1": "e46a104bde8a16cdf85fcf2152feb36272dbca1d",
          "md5": "cd9a7d358b44dad30071040d374d48ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.3.7-sources.jar",
          "url": "spring-boot-starter-json-3.3.7-sources.jar",
          "size": 4747,
          "sha512": "eb551d3a2a432b5f6358b41616246a46ee9f5a999d9212aaa8b4c620325c791da7db2e1d201823b29181d767a9c5dd78649ffecab64183b3588b512adff1c97e",
          "sha256": "de2925dd36a1db640978bd6188301ca4f23162b219cf51efcbee767ad0cf6295",
          "sha1": "e46a104bde8a16cdf85fcf2152feb36272dbca1d",
          "md5": "cd9a7d358b44dad30071040d374d48ad"
        }
      ]
    }
  ]
}
