{
  "formatVersion": "1.1",
  "component": {
    "group": "tools.jackson.core",
    "module": "jackson-databind",
    "version": "3.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-3.0.1.jar",
          "url": "jackson-databind-3.0.1.jar",
          "size": 1852602,
          "sha512": "2a321c1774ddd3ea619a5d3943007355318c1091c117bf66c838769ea5176b1df43934505f46f9c4aecb8f433f5a4599e282f36a7767e01c9e134566868ed789",
          "sha256": "48ea069ae615237e53a625ff1f08a378634d3ea3f9ee906dd3c03e1e781e3121",
          "sha1": "90cde5eb4380dd2ff5c3b5ba2d7181bbad55e674",
          "md5": "98daade99446031a372437a121a3a4f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.20"
          }
        },
        {
          "group": "tools.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "tools.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "3.0.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-3.0.1.jar",
          "url": "jackson-databind-3.0.1.jar",
          "size": 1852602,
          "sha512": "2a321c1774ddd3ea619a5d3943007355318c1091c117bf66c838769ea5176b1df43934505f46f9c4aecb8f433f5a4599e282f36a7767e01c9e134566868ed789",
          "sha256": "48ea069ae615237e53a625ff1f08a378634d3ea3f9ee906dd3c03e1e781e3121",
          "sha1": "90cde5eb4380dd2ff5c3b5ba2d7181bbad55e674",
          "md5": "98daade99446031a372437a121a3a4f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-3.0.1-javadoc.jar",
          "url": "jackson-databind-3.0.1-javadoc.jar",
          "size": 6500675,
          "sha512": "6fd6662ed5ed5a5a556ace39316f7a34424ad33f8c181036214319b1fc989571343cb4d369c76fa92f9a4eed96dc97590e879c9ccdf86671b5351db6ce6a0571",
          "sha256": "51a20811d9f2235937bc3c46a6300cfa23069dbdf83267ba0e2ac4a05580214e",
          "sha1": "1e3dcfa990053950e82ec41ba46639d7d94943d5",
          "md5": "f02d70487072a3822c11ababb175790b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-databind-3.0.1-sources.jar",
          "url": "jackson-databind-3.0.1-sources.jar",
          "size": 1278960,
          "sha512": "660619cba8d863fb1230a303fa6f0ea8dcd421250200dbddf644ecbf6bf6b3562ba6e2edc3e2d95e5d4f29bb9d8d38cf7c0a504c0aaee305e09a5520e8954837",
          "sha256": "69ce40b1d2ffd267f7ddd4e41e2ed0f3e450e39d6764ca5650235788da913c5c",
          "sha1": "d17b80252f418b7abd0fc68165e03bcce0bc061c",
          "md5": "d0bebb27f2dcd39f91325bee15fa418b"
        }
      ]
    }
  ]
}
