{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-actuator",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.3.7.jar",
          "url": "spring-boot-actuator-3.3.7.jar",
          "size": 676386,
          "sha512": "453439631b07aabc0d070290cd933fc7f7dcc91a46cb4d90ab68cab1e8bc50408fda27eb97b6be8f3438953f0d09c96400ed1064bbc2f4f5c478512932bf6ee5",
          "sha256": "5612834958c5f587818fd6d676c9b67df0493d504015fc8e190ffd8dc8a3ab6d",
          "sha1": "5e0746f1dc5ae2889910ab6a52616cef3faeb84a",
          "md5": "316fe6a78409941a7afa6b14c646a97f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-actuator-3.3.7.jar",
          "url": "spring-boot-actuator-3.3.7.jar",
          "size": 676386,
          "sha512": "453439631b07aabc0d070290cd933fc7f7dcc91a46cb4d90ab68cab1e8bc50408fda27eb97b6be8f3438953f0d09c96400ed1064bbc2f4f5c478512932bf6ee5",
          "sha256": "5612834958c5f587818fd6d676c9b67df0493d504015fc8e190ffd8dc8a3ab6d",
          "sha1": "5e0746f1dc5ae2889910ab6a52616cef3faeb84a",
          "md5": "316fe6a78409941a7afa6b14c646a97f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.3.7-javadoc.jar",
          "url": "spring-boot-actuator-3.3.7-javadoc.jar",
          "size": 1472891,
          "sha512": "11776e38423d4f91e1a154b251d7813502e5c4fcbc25896948178d5762647b6730619273096501d3866065a4b9d75145652920aa317a13a20070c58a95952004",
          "sha256": "7ecf74ddd9ea29474c3f1d65fe6f4963aefaa5a32493c3c97b6fdfa9e7e90929",
          "sha1": "f8229dba8ee0eaea9b4ec4613493fef229fe8684",
          "md5": "76afe0da16c53565488e3843f69155e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-actuator-3.3.7-sources.jar",
          "url": "spring-boot-actuator-3.3.7-sources.jar",
          "size": 459105,
          "sha512": "fade68b325ea736c47ad00a253db67387534b1a079137eef5619b5dbcdadc71aaa085725ab3f6848ea1d759765f05b744477a18c0dbceb327bd14927c4ce5cd7",
          "sha256": "3d8a459d6d55436968b68451415df8ab5aaf8e71a1e627cda58f03be6a6c6d31",
          "sha1": "9fdf7e10dd35088c01ebf4e2161e7d47bacdc3d3",
          "md5": "dd498d3d947ae1e69cbd11f600785696"
        }
      ]
    }
  ]
}
