{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.7.jar",
          "url": "spring-boot-starter-tomcat-3.3.7.jar",
          "size": 4792,
          "sha512": "df06c8d762db67676f7d6b6fa280d24dee65a8d288f708e5a9d6001f0975d60a1a3823db9d32a2df67478aecb55bff5e37a809df74aae257bc05ad416054246b",
          "sha256": "ea689f193710ec946eb4b147db290770a43572d632044b0eab8cc4354a46397d",
          "sha1": "be9823245c71c798a5e10ccf0292ccc078b71e4f",
          "md5": "09371006c4845daf6b947a072a26292e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.34"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.34"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.7.jar",
          "url": "spring-boot-starter-tomcat-3.3.7.jar",
          "size": 4792,
          "sha512": "df06c8d762db67676f7d6b6fa280d24dee65a8d288f708e5a9d6001f0975d60a1a3823db9d32a2df67478aecb55bff5e37a809df74aae257bc05ad416054246b",
          "sha256": "ea689f193710ec946eb4b147db290770a43572d632044b0eab8cc4354a46397d",
          "sha1": "be9823245c71c798a5e10ccf0292ccc078b71e4f",
          "md5": "09371006c4845daf6b947a072a26292e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.3.7-javadoc.jar",
          "size": 4792,
          "sha512": "7fba28942222f9d9666c11b612903249301128cfb62b2beda19cfd6977eab0e40fea401017aa8d52fbb258e27eaef8212b9959b0ca7bdc735939f2bc152cd899",
          "sha256": "f1cfa43013e9c82565b910a473d4b7dedee1a4a637af53ed5c7819d5a8196858",
          "sha1": "50fec3bba2b7aeadbd27f874c6001310b98bf596",
          "md5": "1b47cc2ad232a93c343daadbc92bb82d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.3.7-sources.jar",
          "url": "spring-boot-starter-tomcat-3.3.7-sources.jar",
          "size": 4792,
          "sha512": "7fba28942222f9d9666c11b612903249301128cfb62b2beda19cfd6977eab0e40fea401017aa8d52fbb258e27eaef8212b9959b0ca7bdc735939f2bc152cd899",
          "sha256": "f1cfa43013e9c82565b910a473d4b7dedee1a4a637af53ed5c7819d5a8196858",
          "sha1": "50fec3bba2b7aeadbd27f874c6001310b98bf596",
          "md5": "1b47cc2ad232a93c343daadbc92bb82d"
        }
      ]
    }
  ]
}
