{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "document-management-client",
    "version": "7.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "rrultpgq5rfgjd4ondxcbcxe5e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "11.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "document-management-client-7.0.1.jar",
          "url": "document-management-client-7.0.1.jar",
          "size": 16832,
          "sha512": "37dab670f1e6fcf428f15536b564d5337e38a37c4b2773f5a75e1a33f2899d0f7ac0569e1df5119f75d32130c55f9302e52dd0e028304eac094b02d232215c3b",
          "sha256": "6ba435a62943d3a683fa517ffeb2499c1dec760c117aa31e3905129053c26c6a",
          "sha1": "c68db845cbb68b9b9c3e934cb82a2b8b5b39522b",
          "md5": "d486bd98461b84c41f594fc93c3427e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "11.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "document-management-client-7.0.1.jar",
          "url": "document-management-client-7.0.1.jar",
          "size": 16832,
          "sha512": "37dab670f1e6fcf428f15536b564d5337e38a37c4b2773f5a75e1a33f2899d0f7ac0569e1df5119f75d32130c55f9302e52dd0e028304eac094b02d232215c3b",
          "sha256": "6ba435a62943d3a683fa517ffeb2499c1dec760c117aa31e3905129053c26c6a",
          "sha1": "c68db845cbb68b9b9c3e934cb82a2b8b5b39522b",
          "md5": "d486bd98461b84c41f594fc93c3427e7"
        }
      ]
    }
  ]
}
