#!/bin/bash

REGEX_ISSUE_ID="^(CIV-[0-9]+|CIV-[a-zA-Z])"
REGEX_RENOVATE_ID="^(Update)"
ISSUE_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_ISSUE_ID")

if [[ -z "$ISSUE_ID_IN_COMMIT" ]]; then
    BRANCH_NAME=$(git symbolic-ref --short HEAD)
    ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "renovate\/")
	ISSUE_ID_IN_RENOVATE_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_RENOVATE_ID")

    if [[ ! -z "$ISSUE_ID" ]]; then
	echo "renovate branch"
		if [[ -z "$ISSUE_ID_IN_RENOVATE_COMMIT" ]]; then
			echo "$(cat "$1")"
			echo "$ISSUE_ID_IN_RENOVATE_COMMIT"
			echo "[commit-msg-hook] Your commit message is not valid. Please update the commit message in the format $REGEX_ISSUE_ID Eg: CIV-1234, CIV-TASKNAME, Update(for renovate changes"
			exit 1
		fi
    fi
			
    echo "$ISSUE_ID | $(cat "$1")" > "$1"
fi
