#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^(feat|spike|fix|test|refactor|renovate)\/CIV-[0-9]+|renovate\/"

message="The branch names in this project must adhere to this contract: $valid_branch_regex. You should rename your branch to a valid name and try again. Eg:feat/CIV-1234, fix/CIV-1234-something,renovate/something"

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
