{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-logging",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.7.jar",
          "url": "spring-boot-starter-logging-3.3.7.jar",
          "size": 4757,
          "sha512": "4aad2bc159fd859954e19b84b9310f65e33adec7c927f3d2b1137006a292e4d78ac32cc1f47e495d06591b823ac39171baa2f2e744c20c16a05e4a545bf7f1cf",
          "sha256": "03dd7c431f4066d940acf4be3938a3bcb4545a7735bf0e9b2ad85988910f35cf",
          "sha1": "9081faa5b4a318a9366960e982845189f2b86f08",
          "md5": "c749b972ad34fa9d70428e9ef2d39a1d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.5.12"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-to-slf4j",
          "version": {
            "requires": "2.23.1"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jul-to-slf4j",
          "version": {
            "requires": "2.0.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.7.jar",
          "url": "spring-boot-starter-logging-3.3.7.jar",
          "size": 4757,
          "sha512": "4aad2bc159fd859954e19b84b9310f65e33adec7c927f3d2b1137006a292e4d78ac32cc1f47e495d06591b823ac39171baa2f2e744c20c16a05e4a545bf7f1cf",
          "sha256": "03dd7c431f4066d940acf4be3938a3bcb4545a7735bf0e9b2ad85988910f35cf",
          "sha1": "9081faa5b4a318a9366960e982845189f2b86f08",
          "md5": "c749b972ad34fa9d70428e9ef2d39a1d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-logging-3.3.7-javadoc.jar",
          "size": 4757,
          "sha512": "2d994d6b930d337fead13b134b511130298805d8a73e6eced77340abe6640f4996dfbab71753b93dad704d48a947a729e41c159a993e5928deffcf1e601b3a0c",
          "sha256": "ecbd8043d9ef9353eca27611fe446ab594ebde4f1e65b1c18076eee92234e023",
          "sha1": "768574f568671b696eade8fd705c61341798ef8e",
          "md5": "174546b333791dd9fd9af28bcb0d1fb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-logging-3.3.7-sources.jar",
          "url": "spring-boot-starter-logging-3.3.7-sources.jar",
          "size": 4757,
          "sha512": "2d994d6b930d337fead13b134b511130298805d8a73e6eced77340abe6640f4996dfbab71753b93dad704d48a947a729e41c159a993e5928deffcf1e601b3a0c",
          "sha256": "ecbd8043d9ef9353eca27611fe446ab594ebde4f1e65b1c18076eee92234e023",
          "sha1": "768574f568671b696eade8fd705c61341798ef8e",
          "md5": "174546b333791dd9fd9af28bcb0d1fb2"
        }
      ]
    }
  ]
}
