---
version: '2.4'

name: cft-lib-camunda

services:
  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:7.20.0-alpha1
    ports:
      - 9404:8080
    networks:
      - cftlib_default

networks:
  cftlib_default:
    external: true
