package uk.gov.hmcts.reform.unspec.enums;

public enum CaseState {
    PENDING_CASE_ISSUED,
    AWAITING_CASE_NOTIFICATION,
    AWAITING_CASE_DETAILS_NOTIFICATION,
    CREATED,
    AWAITING_CLAIMANT_INTENTION,
    CLOSED,
    PROCEEDS_WITH_OFFLINE_JOURNEY,
    CLAIM_DISMISSED
}

