{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-server-host-common/2.3.8/ktor-server-host-common-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-server-host-common",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-jvm-2.3.8.jar",
          "url": "ktor-server-host-common-jvm-2.3.8.jar",
          "size": 237564,
          "sha512": "1c0d4cf95bc81ad9144696e6fc92aec4d6b68bbd5f184607562a494cb8e68dd9b384bd236877cc9c954a4559b15f543d87f2c89c781c414b3ea0a6deebb7cf9d",
          "sha256": "fedfad16c0de46a3c3568be4f5c2734aca14980603f3f04935feff5cd0adf041",
          "sha1": "fdd3a3b68db3ce8843f2e0dd945ad76390acf3a4",
          "md5": "d8a5e67c5f6f92bb639b31987baccd5f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-host-common-jvm-2.3.8.jar",
          "url": "ktor-server-host-common-jvm-2.3.8.jar",
          "size": 237564,
          "sha512": "1c0d4cf95bc81ad9144696e6fc92aec4d6b68bbd5f184607562a494cb8e68dd9b384bd236877cc9c954a4559b15f543d87f2c89c781c414b3ea0a6deebb7cf9d",
          "sha256": "fedfad16c0de46a3c3568be4f5c2734aca14980603f3f04935feff5cd0adf041",
          "sha1": "fdd3a3b68db3ce8843f2e0dd945ad76390acf3a4",
          "md5": "d8a5e67c5f6f92bb639b31987baccd5f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-server-host-common-jvm-2.3.8-sources.jar",
          "url": "ktor-server-host-common-jvm-2.3.8-sources.jar",
          "size": 41853,
          "sha512": "e5c319bac549b20b30d6259c097cca22c1b954e7068543dfd8b23c8352c9954d628511c17ae69fd24231d456cd0fdbd227295e1156ba0a647b5a89757d76575a",
          "sha256": "24938ededf032be62242e59b6ac74958b34269add6754141da7bd0588e76f12d",
          "sha1": "a2e42401ccab27c8efc331d77c18582b7b5e93f5",
          "md5": "2d22d86aed98262592c1771898eace44"
        }
      ]
    }
  ]
}
