apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.releaseNameOverride }}-mocks
data:
  liveness-mock.json: |
    {
      "request": {
        "method": "GET",
        "url": "/health/liveness"
      },
      "response": {
        "status": 200
      }
    }
  readiness-mock.json: |
    {
      "request": {
        "method": "GET",
        "url": "/health/readiness"
      },
      "response": {
        "status": 200
      }
    }

