{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.logging.log4j",
    "module": "log4j-to-slf4j",
    "version": "2.25.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.9.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "biz.aQute.bnd",
          "module": "biz.aQute.bnd.annotation",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.38.0"
          }
        },
        {
          "group": "org.osgi",
          "module": "org.osgi.annotation.bundle",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.osgi",
          "module": "org.osgi.annotation.versioning",
          "version": {
            "requires": "1.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "log4j-to-slf4j-2.25.3.jar",
          "url": "log4j-to-slf4j-2.25.3.jar",
          "size": 24173,
          "sha512": "894109d47f7990036a4f04e9383fb8971348f6d427f0435b39a4f197f091b621638a6d4e91688733d2ee8c8f5205beff32e43ec7b0138460b72ac8027eae7552",
          "sha256": "90a09280390c54a28ac1514ded7c5293f3fe62f4448bf371b4e2415272e67a3d",
          "sha1": "30adfb40cca243ec88cf7ec1fddb411ab55faa4f",
          "md5": "f515a81b64474e5faf389ab8611e123a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.25.3"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        }
      ],
      "files": [
        {
          "name": "log4j-to-slf4j-2.25.3.jar",
          "url": "log4j-to-slf4j-2.25.3.jar",
          "size": 24173,
          "sha512": "894109d47f7990036a4f04e9383fb8971348f6d427f0435b39a4f197f091b621638a6d4e91688733d2ee8c8f5205beff32e43ec7b0138460b72ac8027eae7552",
          "sha256": "90a09280390c54a28ac1514ded7c5293f3fe62f4448bf371b4e2415272e67a3d",
          "sha1": "30adfb40cca243ec88cf7ec1fddb411ab55faa4f",
          "md5": "f515a81b64474e5faf389ab8611e123a"
        }
      ]
    }
  ]
}
