{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.module",
    "module": "jackson-module-kotlin",
    "version": "2.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-2.17.3.jar",
          "url": "jackson-module-kotlin-2.17.3.jar",
          "size": 188421,
          "sha512": "3a09bd94ac3769f02d7eb801b6edfdbe820c7b8f76efbc9ecd0df908b591a71e43661c588513f45026ece386ad5b09618e38ba15287e85e716af674cec8eca6c",
          "sha256": "bb77fe67fbe24830b54f98e4124407a414c0d6f8a3060ec4c44011473d59ed14",
          "sha1": "25497a88d2768c96da47c224d101055b6bbcbe23",
          "md5": "bbfb8095d5a72a4e96469064d238dd7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-module-kotlin-2.17.3.jar",
          "url": "jackson-module-kotlin-2.17.3.jar",
          "size": 188421,
          "sha512": "3a09bd94ac3769f02d7eb801b6edfdbe820c7b8f76efbc9ecd0df908b591a71e43661c588513f45026ece386ad5b09618e38ba15287e85e716af674cec8eca6c",
          "sha256": "bb77fe67fbe24830b54f98e4124407a414c0d6f8a3060ec4c44011473d59ed14",
          "sha1": "25497a88d2768c96da47c224d101055b6bbcbe23",
          "md5": "bbfb8095d5a72a4e96469064d238dd7e"
        }
      ]
    }
  ]
}
