{
  "formatVersion": "1.1",
  "component": {
    "group": "org.hibernate.common",
    "module": "hibernate-commons-annotations",
    "version": "6.0.6.Final",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "hibernate-commons-annotations-6.0.6.Final.jar",
          "url": "hibernate-commons-annotations-6.0.6.Final.jar",
          "size": 67807,
          "sha512": "f670bfed87c66897660da90a3d94e4d21de8fb726757858d18d331999c3d223badc24af6437046f01e8c90f2b2427001500b9679f29c3465c402ae082a97712c",
          "sha256": "cd974e0a8481fafdbaf9b4a0f08bb5a6c969b0365482763eedf77e6fd7f493b7",
          "sha1": "77a5f94b56d49508e0ee334751db5b78e5ccd50c",
          "md5": "c155df7d9f04d15f3f6bbe79f4907074"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-commons-annotations-6.0.6.Final.jar",
          "url": "hibernate-commons-annotations-6.0.6.Final.jar",
          "size": 67807,
          "sha512": "f670bfed87c66897660da90a3d94e4d21de8fb726757858d18d331999c3d223badc24af6437046f01e8c90f2b2427001500b9679f29c3465c402ae082a97712c",
          "sha256": "cd974e0a8481fafdbaf9b4a0f08bb5a6c969b0365482763eedf77e6fd7f493b7",
          "sha1": "77a5f94b56d49508e0ee334751db5b78e5ccd50c",
          "md5": "c155df7d9f04d15f3f6bbe79f4907074"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-commons-annotations-6.0.6.Final-javadoc.jar",
          "url": "hibernate-commons-annotations-6.0.6.Final-javadoc.jar",
          "size": 455233,
          "sha512": "15ef16feb0cd0cfa7fba7c64cab0a2065f349bec873b61b9f05805d98e1e52f8c3e8a5eeb2e67b268b3ceda476762584d61f846a949be26061455e043753fb10",
          "sha256": "22d7007337f536d99663b98d224609f30d5f0941ec0dff1769cf98e42ff6b5a5",
          "sha1": "971a971e4b9d5b12a0e1c6ac0625f18721fbec87",
          "md5": "84d9921a87ccc4410445efc1028665bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hibernate-commons-annotations-6.0.6.Final-sources.jar",
          "url": "hibernate-commons-annotations-6.0.6.Final-sources.jar",
          "size": 42927,
          "sha512": "22ae05a23321b3dd768c03cf478624966f9e7d7921e999944a9abe5a6005af0be3e1cd54905dda4c76d253d25c7968be3adf62d1f55ba017f04cecd2f4e6ac66",
          "sha256": "5f9ef9fcd3a6942102f4857a4c7fb2a85e203d9a6ece7d700ec7d1f789411991",
          "sha1": "113904346d97dbdf52883c90ef1ccd0bb8ffb74d",
          "md5": "5fc8f4be2be37472c7f8577f38012d74"
        }
      ]
    }
  ]
}
