package uk.gov.hmcts.reform.civil.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
public class APPSOLSPECPROFILECITIZENCLAIMANTPROFILECuAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.APP_SOL_SPEC_PROFILE, Permission.C);
        grants.put(UserRole.APP_SOL_SPEC_PROFILE, Permission.U);
        grants.put(UserRole.CITIZEN_CLAIMANT_PROFILE, Permission.C);
        grants.put(UserRole.CITIZEN_CLAIMANT_PROFILE, Permission.U);
        return grants;
    }
}
