package uk.gov.hmcts.reform.civil.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
public class CaseworkerCivilSystemFieldReaderRPlus7RolesIlgoorAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_CIVIL_SYSTEM_FIELD_READER, Permission.R);
        grants.put(UserRole.CTSC, Permission.C);
        grants.put(UserRole.CTSC, Permission.U);
        grants.put(UserRole.CTSC_TEAM_LEADER, Permission.C);
        grants.put(UserRole.CTSC_TEAM_LEADER, Permission.R);
        grants.put(UserRole.CTSC_TEAM_LEADER, Permission.U);
        grants.put(UserRole.HEARING_CENTRE_ADMIN, Permission.C);
        grants.put(UserRole.HEARING_CENTRE_ADMIN, Permission.R);
        grants.put(UserRole.HEARING_CENTRE_ADMIN, Permission.U);
        grants.put(UserRole.HEARING_CENTRE_TEAM_LEADER, Permission.C);
        grants.put(UserRole.HEARING_CENTRE_TEAM_LEADER, Permission.R);
        grants.put(UserRole.HEARING_CENTRE_TEAM_LEADER, Permission.U);
        grants.put(UserRole.JUDGE, Permission.C);
        grants.put(UserRole.JUDGE, Permission.R);
        grants.put(UserRole.JUDGE, Permission.U);
        grants.put(UserRole.NATIONAL_BUSINESS_CENTRE, Permission.C);
        grants.put(UserRole.NATIONAL_BUSINESS_CENTRE, Permission.U);
        grants.put(UserRole.NBC_TEAM_LEADER, Permission.C);
        grants.put(UserRole.NBC_TEAM_LEADER, Permission.R);
        grants.put(UserRole.NBC_TEAM_LEADER, Permission.U);
        return grants;
    }
}
