package uk.gov.hmcts.reform.civil.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
public class CITIZENCLAIMANTPROFILECruPlus10RolesYbbobmAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CITIZEN_CLAIMANT_PROFILE, Permission.C);
        grants.put(UserRole.CITIZEN_CLAIMANT_PROFILE, Permission.R);
        grants.put(UserRole.CITIZEN_CLAIMANT_PROFILE, Permission.U);
        grants.put(UserRole.CASEFLAGS_VIEWER, Permission.R);
        grants.put(UserRole.CASEWORKER_CIVIL_ADMIN, Permission.R);
        grants.put(UserRole.CASEWORKER_CIVIL_SOLICITOR, Permission.C);
        grants.put(UserRole.CASEWORKER_CIVIL_SOLICITOR, Permission.R);
        grants.put(UserRole.CASEWORKER_CIVIL_SOLICITOR, Permission.U);
        grants.put(UserRole.CASEWORKER_CIVIL_SYSTEM_FIELD_READER, Permission.R);
        grants.put(UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_RAS_VALIDATION, Permission.R);
        grants.put(UserRole.CASEWORKER_WA_TASK_CONFIGURATION, Permission.R);
        grants.put(UserRole.JUDGE_PROFILE, Permission.R);
        grants.put(UserRole.LEGAL_ADVISER, Permission.R);
        grants.put(UserRole.PAYMENT_ACCESS, Permission.R);
        return grants;
    }
}
