{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts.rse-cft-lib",
    "module": "bootstrapper",
    "version": "0.19.2017",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bootstrapper-0.19.2017.jar",
          "url": "bootstrapper-0.19.2017.jar",
          "size": 12243,
          "sha512": "d9f2cb7e0984fce65689e41b3493966dfab1abea48c1579d6256b45bea84b6c1b69324ef3623328392dd477035870c3a85231c8ed026ca3b7faae3b3d4c6f91d",
          "sha256": "52c75e8043dffc304825d0e3423c78a2f09682756a85afe2a00359034ee43014",
          "sha1": "0a689c76aaa24a8d4028e0be3b1d5da2d3e6dbaf",
          "md5": "b6d954bae9065bd2afabc5b0bcb8b686"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrapper-0.19.2017.jar",
          "url": "bootstrapper-0.19.2017.jar",
          "size": 12243,
          "sha512": "d9f2cb7e0984fce65689e41b3493966dfab1abea48c1579d6256b45bea84b6c1b69324ef3623328392dd477035870c3a85231c8ed026ca3b7faae3b3d4c6f91d",
          "sha256": "52c75e8043dffc304825d0e3423c78a2f09682756a85afe2a00359034ee43014",
          "sha1": "0a689c76aaa24a8d4028e0be3b1d5da2d3e6dbaf",
          "md5": "b6d954bae9065bd2afabc5b0bcb8b686"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrapper-0.19.2017-sources.jar",
          "url": "bootstrapper-0.19.2017-sources.jar",
          "size": 7411,
          "sha512": "238a9f7fb2a03d29a16cb3ba929cc0bc3860e5d7aa7821ba6ae79a894210ac5ccd93a918d1ff22662c813a12702129d8b32f14c8d1e93268b98dbc85923f1ddc",
          "sha256": "f2c2df470c7edd92046136db195d0c6101d56480691ebbd6632422601af11d5b",
          "sha1": "db0726ee700a926a9bdcc07923cdb1118e873afa",
          "md5": "0c91103fd10482a85e0ebe554aaae6ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bootstrapper-0.19.2017-javadoc.jar",
          "url": "bootstrapper-0.19.2017-javadoc.jar",
          "size": 113994,
          "sha512": "0e42fdb923d92c090b717a5aaeb4611789993752a2ac370475b478edce7a65bf90301e269d3732dce8bd9a9671520824a80fbdc2d01872e9f8f8088fa70927e1",
          "sha256": "208977f988a5bfb0f68f39e2a81151ba3d13d3e203b0cf9801478b645ed2f881",
          "sha1": "0f9a46147fe202076a3d3f996cb6bb7056232048",
          "md5": "b115ec79855bde1bebb5ccb95469f18f"
        }
      ]
    }
  ]
}
