{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization/2.3.8/ktor-serialization-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-serialization",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.8.jar",
          "url": "ktor-serialization-jvm-2.3.8.jar",
          "size": 24737,
          "sha512": "8c69c2eca81329718a15491dba05bea0b2d10848af71f4d0ee08f5cf9443fb5322085b8c4e562dab6b25575c5629da3f80687487620b35ce04789855fadfd985",
          "sha256": "7d942475bf3995fe080c5f103532e51736d0c474aea3d9f6133a4031ae08799a",
          "sha1": "98a74aad6aec7a59a97c6736d8af343f71a352da",
          "md5": "820cd1f0fe7130d20993643a4b94da00"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.8.jar",
          "url": "ktor-serialization-jvm-2.3.8.jar",
          "size": 24737,
          "sha512": "8c69c2eca81329718a15491dba05bea0b2d10848af71f4d0ee08f5cf9443fb5322085b8c4e562dab6b25575c5629da3f80687487620b35ce04789855fadfd985",
          "sha256": "7d942475bf3995fe080c5f103532e51736d0c474aea3d9f6133a4031ae08799a",
          "sha1": "98a74aad6aec7a59a97c6736d8af343f71a352da",
          "md5": "820cd1f0fe7130d20993643a4b94da00"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.8-sources.jar",
          "url": "ktor-serialization-jvm-2.3.8-sources.jar",
          "size": 3629,
          "sha512": "49fe12b9539306c0695c4e3271e3cfdf7e904d91a665eb256cc0f86c6b3c78e5b27a1bfedf51172a4d915f2a3e9daa0bfdc412ebef511edef268ae03566ab6ce",
          "sha256": "051d868621eaea7fcad8286bc90742ebca6b31f3f0759318850c3df3c138b3b7",
          "sha1": "85a50d9fd68216cc09f00bc3f88e87785c21613c",
          "md5": "f598d58db690f0b956deff64e9df7841"
        }
      ]
    }
  ]
}
