{
  "formatVersion": "1.1",
  "component": {
    "group": "au.com.dius.pact.consumer",
    "module": "junit5",
    "version": "4.6.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "au.com.dius.pact",
          "module": "consumer",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit5-4.6.17.jar",
          "url": "junit5-4.6.17.jar",
          "size": 69680,
          "sha512": "1ccf8ad115edec2105b7863959249216da83d12867ad33f453d5e288ffe25c3eb3ffcaa0e45d83f3f05e0b31b0a8a72c9b4f0213f3f2264ebe03f36d66d7a1ba",
          "sha256": "efb32bcbea280578180ddf3ddbf2f2d139b69fad72a7181e8327faf811b1eb84",
          "sha1": "d87bdbfb149daea8e3af5e98bdfcfb7af4f844c9",
          "md5": "4237eec2715b7e0aa8ed87127b6dd5b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "au.com.dius.pact",
          "module": "consumer",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-jvm",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls-certificates",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.108.Final"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        }
      ],
      "files": [
        {
          "name": "junit5-4.6.17.jar",
          "url": "junit5-4.6.17.jar",
          "size": 69680,
          "sha512": "1ccf8ad115edec2105b7863959249216da83d12867ad33f453d5e288ffe25c3eb3ffcaa0e45d83f3f05e0b31b0a8a72c9b4f0213f3f2264ebe03f36d66d7a1ba",
          "sha256": "efb32bcbea280578180ddf3ddbf2f2d139b69fad72a7181e8327faf811b1eb84",
          "sha1": "d87bdbfb149daea8e3af5e98bdfcfb7af4f844c9",
          "md5": "4237eec2715b7e0aa8ed87127b6dd5b5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit5-4.6.17-javadoc.jar",
          "url": "junit5-4.6.17-javadoc.jar",
          "size": 461329,
          "sha512": "106b6c86c23d9848141bdab5d532eff81779e61e644d97fdd2a39ea7b3dabe82a02eadc00b86a9d484c0390cc8774da9817947fcf746266a8132567c28d2fd22",
          "sha256": "5e034f1bdf67fcb7f338f0589deb6bff2040f3f1de7166a467462ed871bfccba",
          "sha1": "37498fb1592ec058e94f643fac6cfb87c1636015",
          "md5": "810043471836607b38d898b30a1f2cb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit5-4.6.17-sources.jar",
          "url": "junit5-4.6.17-sources.jar",
          "size": 10863,
          "sha512": "13d02d6bdf2d8470dde6b7d5bc254124909bc2777e08913027a01b2ce474f9cff8ba071672fafcb4184bc470fdbc9d7982345f225f6fe8ec6080cab093cba03f",
          "sha256": "8f3cca62ff9e1e0a74ce25ca43b867a5ac194f48fec69b64c60c5a975abef6f3",
          "sha1": "98a6f270cc56ca424bd6270f99ec1ec3a384630c",
          "md5": "f146ee9cfdfa8e1f76ec5ecf01d36bdb"
        }
      ]
    }
  ]
}
