package uk.gov.hmcts.reform.civil.model.finalorders;

public enum AssistedCostTypesList {
    COSTS_IN_THE_CASE,
    NO_ORDER_TO_COST,
    COSTS_RESERVED,
    DEFENDANT_COST_STANDARD_BASE,
    CLAIMANT_COST_STANDARD_BASE,
    DEFENDANT_COST_SUMMARILY_BASE,
    CLAIMANT_COST_SUMMARILY_BASE,
    BESPOKE_COSTS_ORDER
}
