{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-server-call-logging",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-server-call-logging-metadata-2.3.8.jar",
          "url": "ktor-server-call-logging-2.3.8.jar",
          "size": 705,
          "sha512": "ba023bf6207437b9e44cd61ca53ed6e2bf5b16dbd3aa325a424e14972f792b49c4cf2638cdeca7cb3cf6b4efcf24db3b7cb1c0e0b047f8173edc0585c786507b",
          "sha256": "f5b7014b3c7cf65c8d3c91cf9a5319d8dbe6302dfa8b72b525d80cfe3e2b615a",
          "sha1": "0089098825f7792f63536c84975e1e956edaecb3",
          "md5": "3f82653fc917c2d9a668c2d0e706e8fa"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-server-call-logging-kotlin-2.3.8-sources.jar",
          "url": "ktor-server-call-logging-2.3.8-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-call-logging-jvm/2.3.8/ktor-server-call-logging-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-call-logging-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-call-logging-jvm/2.3.8/ktor-server-call-logging-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-call-logging-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-server-call-logging-jvm/2.3.8/ktor-server-call-logging-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-server-call-logging-jvm",
        "version": "2.3.8"
      }
    }
  ]
}
