{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-io/2.3.8/ktor-io-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-io",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-jvm-2.3.8.jar",
          "url": "ktor-io-jvm-2.3.8.jar",
          "size": 810513,
          "sha512": "cb1aea63f3cbba62d21b5c90e19c4c17386b30282390a54faaebe3e0a00f997f83eef20f421f38979ef683aaf506fb336f6106b519d4abf61437b62e48e215c0",
          "sha256": "4c33dd51a1d6d734c8c127cea96a1cfa024dc1d451ed1e2a86c297fa05f1dc29",
          "sha1": "421b2f4e1330d07f89855c35127b6eadafb5ec4b",
          "md5": "43cb4df9c9d607b2b4199e60cbad26a1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-io-jvm-2.3.8.jar",
          "url": "ktor-io-jvm-2.3.8.jar",
          "size": 810513,
          "sha512": "cb1aea63f3cbba62d21b5c90e19c4c17386b30282390a54faaebe3e0a00f997f83eef20f421f38979ef683aaf506fb336f6106b519d4abf61437b62e48e215c0",
          "sha256": "4c33dd51a1d6d734c8c127cea96a1cfa024dc1d451ed1e2a86c297fa05f1dc29",
          "sha1": "421b2f4e1330d07f89855c35127b6eadafb5ec4b",
          "md5": "43cb4df9c9d607b2b4199e60cbad26a1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-io-jvm-2.3.8-sources.jar",
          "url": "ktor-io-jvm-2.3.8-sources.jar",
          "size": 150937,
          "sha512": "ae6135fc7dcd865b3ea5ed77b7c56114d44d028324bbaedef53104a8fd78ab24a6cca3ec791aa74638d9a7bc6437273402e988233a038a156a2d0afa7b40623d",
          "sha256": "f3a8d1835fd26acd0cd90a51e667fe707c1f0c853d1d5fc2ad97b3a75d10eaa6",
          "sha1": "553fbbd4f206c8f9d19f451e221cd7ee08c9b093",
          "md5": "d381e4f12489b2b02df44a2c63bcaace"
        }
      ]
    }
  ]
}
