package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.ADDDEFENDANTLITIGATIONFRIENDNonprodCommonLitigationFriendPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.ADDDEFENDANTLITIGATIONFRIENDNonprodDefendant2LitigationFriendPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.ADDDEFENDANTLITIGATIONFRIENDNonprodLitigationFriendPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.ADDDEFENDANTLITIGATIONFRIENDNonprodSelectALitigationFriendPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code ADD_DEFENDANT_LITIGATION_FRIEND} for case type {@code CIVIL}.
 */
@Component
public class ADDDEFENDANTLITIGATIONFRIENDNonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADD_DEFENDANT_LITIGATION_FRIEND = "ADD_DEFENDANT_LITIGATION_FRIEND";

    /**
     * Registers overlay event {@code ADD_DEFENDANT_LITIGATION_FRIEND} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(ADD_DEFENDANT_LITIGATION_FRIEND)
            .forStates(CaseState.PENDING_CASE_ISSUED, CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED, CaseState.AWAITING_APPLICANT_INTENTION)
            .name("Add litigation friend")
            .displayOrder(5)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        ADDDEFENDANTLITIGATIONFRIENDNonprodLitigationFriendPage.apply(fields);
        ADDDEFENDANTLITIGATIONFRIENDNonprodSelectALitigationFriendPage.apply(fields);
        ADDDEFENDANTLITIGATIONFRIENDNonprodDefendant2LitigationFriendPage.apply(fields);
        ADDDEFENDANTLITIGATIONFRIENDNonprodCommonLitigationFriendPage.apply(fields);
    }
}
