package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code AMEND_RESTITCH_BUNDLE} for case type {@code CIVIL}.
 */
@Component
public class AMENDRESTITCHBUNDLE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String AMEND_RESTITCH_BUNDLE = "AMEND_RESTITCH_BUNDLE";

    /**
     * Registers event {@code AMEND_RESTITCH_BUNDLE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(AMEND_RESTITCH_BUNDLE)
            .forState(CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING)
            .name("Amend and restitch bundle")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE, UserRole.CUI_ADMIN_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.JUDGE_PROFILE)
            .fields();
        fields.page("RestitchBundle");
        fields.readonlyNoSummary(CaseData::getBundleText);
        fields.readonlyNoSummary(CaseData::getBundleWarning);
    }
}
