package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code ASSIGN_CASE_TO_APPLICANT_SOLICITOR1} for case type {@code CIVIL}.
 */
@Component
public class ASSIGNCASETOAPPLICANTSOLICITOR1 implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ASSIGN_CASE_TO_APPLICANT_SOLICITOR1 = "ASSIGN_CASE_TO_APPLICANT_SOLICITOR1";

    /**
     * Registers event {@code ASSIGN_CASE_TO_APPLICANT_SOLICITOR1}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(ASSIGN_CASE_TO_APPLICANT_SOLICITOR1)
            .forAllStates()
            .name("Assign to applicantSolicitor1")
            .description("Assign case to applicant solicitor 1")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
