package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code asyncStitchingComplete} for case type {@code CIVIL}.
 */
@Component
public class AsyncStitchingComplete implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ASYNC_STITCHING_COMPLETE = "asyncStitchingComplete";

    /**
     * Registers event {@code asyncStitchingComplete}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(ASYNC_STITCHING_COMPLETE)
            .forStates(CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING)
            .name("Bundle Stitching Complete")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN)
            .fields();
        fields.page("WorkAllocationIntegrationFields");
        fields.readonlyNoSummary(CaseData::getBundleError);
    }
}
