package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CASEPROCEEDSINCASEMANProdCaseProceedsInCasemanLRPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CASEPROCEEDSINCASEMANProdCaseProceedsInCasemanPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CASE_PROCEEDS_IN_CASEMAN} for case type {@code CIVIL}.
 */
@Component
public class CASEPROCEEDSINCASEMANProd implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_PROCEEDS_IN_CASEMAN = "CASE_PROCEEDS_IN_CASEMAN";

    /**
     * Registers overlay event {@code CASE_PROCEEDS_IN_CASEMAN} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(CASE_PROCEEDS_IN_CASEMAN)
            .forStateTransition(EnumSet.of(CaseState.IN_MEDIATION, CaseState.PENDING_CASE_ISSUED, CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.CASE_DISMISSED, CaseState.CASE_PROGRESSION, CaseState.JUDICIAL_REFERRAL, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.DECISION_OUTCOME, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.CASE_STAYED), CaseState.PROCEEDS_IN_HERITAGE_SYSTEM)
            .name("Case proceeds in Caseman")
            .description("Case will proceed offline in Caseman system")
            .displayOrder(9)
            .showSummary(false)
            .endButtonLabel("Take offline")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        CASEPROCEEDSINCASEMANProdCaseProceedsInCasemanPage.apply(fields);
        CASEPROCEEDSINCASEMANProdCaseProceedsInCasemanLRPage.apply(fields);
    }
}
