package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEApplicantDefenceResponseDocumentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDeterminationWithoutHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDisclosureOfElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDisclosureOfNonElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDisclosureReportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDraftDirectionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEFileDirectionsQuestionnairePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEFixedRecoverableCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEFurtherInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEHearingSupportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSELanguagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSERespondentResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEVulnerabilityQuestionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEWitnessesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CLAIMANT_RESPONSE} for case type {@code CIVIL}.
 */
@Component
public class CLAIMANTRESPONSE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_RESPONSE = "CLAIMANT_RESPONSE";

    /**
     * Registers event {@code CLAIMANT_RESPONSE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CLAIMANT_RESPONSE)
            .forState(CaseState.AWAITING_APPLICANT_INTENTION)
            .name("View and respond to defence")
            .description("View and respond to defendant")
            .displayOrder(7)
            .showSummary()
            .endButtonLabel("Submit your response")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_UNSPEC_PROFILE)
            .fields();
        CLAIMANTRESPONSEFixedRecoverableCostsPage.apply(fields);
        CLAIMANTRESPONSERespondentResponsePage.apply(fields);
        CLAIMANTRESPONSEApplicantDefenceResponseDocumentPage.apply(fields);
        CLAIMANTRESPONSEFileDirectionsQuestionnairePage.apply(fields);
        CLAIMANTRESPONSEDisclosureOfElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSEDisclosureOfNonElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSEDisclosureReportPage.apply(fields);
        CLAIMANTRESPONSEDeterminationWithoutHearingPage.apply(fields);
        CLAIMANTRESPONSEExpertsPage.apply(fields);
        CLAIMANTRESPONSEWitnessesPage.apply(fields);
        CLAIMANTRESPONSELanguagePage.apply(fields);
        CLAIMANTRESPONSEHearingPage.apply(fields);
        CLAIMANTRESPONSEDraftDirectionsPage.apply(fields);
        CLAIMANTRESPONSEHearingSupportPage.apply(fields);
        CLAIMANTRESPONSEVulnerabilityQuestionsPage.apply(fields);
        CLAIMANTRESPONSEFurtherInformationPage.apply(fields);
        CLAIMANTRESPONSEStatementOfTruthPage.apply(fields);
        CLAIMANTRESPONSEWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
