package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEApplicantDefenceResponseDocumentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDeterminationWithoutHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDisclosureOfElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDisclosureOfNonElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDisclosureReportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEDraftDirectionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEFileDirectionsQuestionnairePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEFixedRecoverableCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEFurtherInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEHearingSupportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSELanguagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSERespondentResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEVulnerabilityQuestionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEWitnessesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSEWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.DeterWithoutHearing;
import uk.gov.hmcts.reform.civil.model.UnavailableDate;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Applicant1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Applicant2DQ;
import uk.gov.hmcts.reform.civil.model.dq.DisclosureReport;
import uk.gov.hmcts.reform.civil.model.dq.Expert;
import uk.gov.hmcts.reform.civil.model.dq.Experts;
import uk.gov.hmcts.reform.civil.model.dq.FixedRecoverableCosts;
import uk.gov.hmcts.reform.civil.model.dq.FurtherInformation;
import uk.gov.hmcts.reform.civil.model.dq.Hearing;
import uk.gov.hmcts.reform.civil.model.dq.WelshLanguageRequirements;
import uk.gov.hmcts.reform.civil.model.dq.Witness;
import uk.gov.hmcts.reform.civil.model.dq.Witnesses;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CLAIMANT_RESPONSE} for case type {@code CIVIL}.
 */
@Component
public class CLAIMANTRESPONSE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_RESPONSE = "CLAIMANT_RESPONSE";

    /**
     * Registers event {@code CLAIMANT_RESPONSE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CLAIMANT_RESPONSE)
            .forState(CaseState.AWAITING_APPLICANT_INTENTION)
            .name("View and respond to defence")
            .description("View and respond to defendant")
            .displayOrder(7)
            .showSummary()
            .endButtonLabel("Submit your response")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_UNSPEC_PROFILE)
            .fields();
        CLAIMANTRESPONSEFixedRecoverableCostsPage.apply(fields);
        CLAIMANTRESPONSERespondentResponsePage.apply(fields);
        CLAIMANTRESPONSEApplicantDefenceResponseDocumentPage.apply(fields);
        CLAIMANTRESPONSEFileDirectionsQuestionnairePage.apply(fields);
        CLAIMANTRESPONSEDisclosureOfElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSEDisclosureOfNonElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSEDisclosureReportPage.apply(fields);
        CLAIMANTRESPONSEDeterminationWithoutHearingPage.apply(fields);
        CLAIMANTRESPONSEExpertsPage.apply(fields);
        CLAIMANTRESPONSEWitnessesPage.apply(fields);
        CLAIMANTRESPONSELanguagePage.apply(fields);
        CLAIMANTRESPONSEHearingPage.apply(fields);
        CLAIMANTRESPONSEDraftDirectionsPage.apply(fields);
        CLAIMANTRESPONSEHearingSupportPage.apply(fields);
        CLAIMANTRESPONSEVulnerabilityQuestionsPage.apply(fields);
        CLAIMANTRESPONSEFurtherInformationPage.apply(fields);
        CLAIMANTRESPONSEStatementOfTruthPage.apply(fields);
        CLAIMANTRESPONSEWorkAllocationIntegrationFieldsPage.apply(fields);
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQFixedRecoverableCostsIntermediate)
                    .mandatory(FixedRecoverableCosts::getIsSubjectToFixedRecoverableCostRegime)
                    .mandatory(FixedRecoverableCosts::getComplexityBandingAgreed)
                    .mandatory(FixedRecoverableCosts::getBand)
                    .optional(FixedRecoverableCosts::getReasons)
                    .optional(FixedRecoverableCosts::getFrcSupportingDocument).done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQFixedRecoverableCostsIntermediate)
                    .mandatory(FixedRecoverableCosts::getIsSubjectToFixedRecoverableCostRegime)
                    .mandatory(FixedRecoverableCosts::getComplexityBandingAgreed)
                    .mandatory(FixedRecoverableCosts::getBand)
                    .optional(FixedRecoverableCosts::getReasons)
                    .optional(FixedRecoverableCosts::getFrcSupportingDocument).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getDeterWithoutHearing)
                    .mandatory(DeterWithoutHearing::getDeterWithoutHearingLabel)
                    .mandatory(DeterWithoutHearing::getDeterWithoutHearingYesNo)
                    .mandatory(DeterWithoutHearing::getDeterWithoutHearingWhyNot)
                    .fieldShowCondition("deterWithoutHearing.deterWithoutHearingYesNo = \"No\"").done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQExperts)
                    .mandatory(Experts::getExpertRequired)
                    .mandatory(Experts::getExpertReportsSent)
                    .mandatory(Experts::getJointExpertSuitable)
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getFirstName).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getLastName).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getEmailAddress).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getPhoneNumber).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getFieldOfExpertise).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getWhyRequired).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getEstimatedCost).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getEventAdded)
                    .fieldShowCondition("applicant1DQExperts=\"DO NOT SHOW IN UI\"").done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getDateAdded)
                    .fieldShowCondition("applicant1DQExperts=\"DO NOT SHOW IN UI\"").done().done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQWitnesses)
                    .mandatory(Witnesses::getWitnessesToAppear)
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getReasonForWitness).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getFirstName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getLastName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getPhoneNumber).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEmailAddress).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEventAdded)
                    .fieldShowCondition("applicant1DQWitnesses=\"DO NOT SHOW IN UI\"").done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getDateAdded)
                    .fieldShowCondition("applicant1DQWitnesses=\"DO NOT SHOW IN UI\"").done().done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQDisclosureReport)
                    .optional(DisclosureReport::getDisclosureFormFiledAndServed)
                    .optional(DisclosureReport::getDisclosureProposalAgreed)
                    .optional(DisclosureReport::getDraftOrderNumber).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQFurtherInformation)
                    .mandatory(FurtherInformation::getFutureApplications)
                    .mandatory(FurtherInformation::getReasonForFutureApplications)
                    .optional(FurtherInformation::getOtherInformationForJudge).done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQExperts)
                    .mandatory(Experts::getExpertRequired)
                    .mandatory(Experts::getExpertReportsSent)
                    .mandatory(Experts::getJointExpertSuitable)
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getFieldOfExpertise).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getWhyRequired).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getEstimatedCost).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getFirstName).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getLastName).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getEmailAddress).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getPhoneNumber).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getEventAdded)
                    .fieldShowCondition("applicant2DQExperts=\"DO NOT SHOW IN UI\"").done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getDateAdded)
                    .fieldShowCondition("applicant2DQExperts=\"DO NOT SHOW IN UI\"").done().done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQDisclosureReport)
                    .optional(DisclosureReport::getDisclosureFormFiledAndServed)
                    .optional(DisclosureReport::getDisclosureProposalAgreed)
                    .optional(DisclosureReport::getDraftOrderNumber).done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQWitnesses)
                    .mandatory(Witnesses::getWitnessesToAppear)
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getReasonForWitness).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getFirstName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getLastName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getPhoneNumber).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEmailAddress).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEventAdded)
                    .fieldShowCondition("applicant2DQWitnesses=\"DO NOT SHOW IN UI\"").done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getDateAdded)
                    .fieldShowCondition("applicant2DQWitnesses=\"DO NOT SHOW IN UI\"").done().done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQFurtherInformation)
                    .mandatory(FurtherInformation::getFutureApplications)
                    .mandatory(FurtherInformation::getReasonForFutureApplications)
                    .optional(FurtherInformation::getOtherInformationForJudge).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQHearing)
                    .mandatory(Hearing::getUnavailableDatesRequired)
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getUnavailableDateType).done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getFromDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getToDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .optional(UnavailableDate::getEventAdded)
                    .fieldShowCondition("applicant1DQHearing=\"DO NOT SHOW IN UI\"").done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .optional(UnavailableDate::getDateAdded)
                    .fieldShowCondition("applicant1DQHearing=\"DO NOT SHOW IN UI\"").done().done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQHearing)
                    .mandatory(Hearing::getUnavailableDatesRequired)
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getUnavailableDateType).done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getFromDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getToDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .optional(UnavailableDate::getEventAdded)
                    .fieldShowCondition("applicant2DQHearing=\"DO NOT SHOW IN UI\"").done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .optional(UnavailableDate::getDateAdded)
                    .fieldShowCondition("applicant2DQHearing=\"DO NOT SHOW IN UI\"").done().done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQFixedRecoverableCosts)
                    .mandatory(FixedRecoverableCosts::getIsSubjectToFixedRecoverableCostRegime)
                    .mandatory(FixedRecoverableCosts::getBandLabel)
                    .eventLabel("<div class='form-label'>For information on complexity bands see</span> <a href='https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part26' rel=\"noreferrer noopener\" target=\"_blank\">CPR26.15 Table 1</a></div><br />")
                    .mandatory(FixedRecoverableCosts::getBand)
                    .mandatory(FixedRecoverableCosts::getComplexityBandingAgreed)
                    .optional(FixedRecoverableCosts::getReasons).done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQFixedRecoverableCosts)
                    .mandatory(FixedRecoverableCosts::getIsSubjectToFixedRecoverableCostRegime)
                    .mandatory(FixedRecoverableCosts::getBandLabel)
                    .eventLabel("<div class='form-label'>For information on complexity bands see</span> <a href='https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part26' rel=\"noreferrer noopener\" target=\"_blank\">CPR26.15 Table 1</a></div><br />")
                    .mandatory(FixedRecoverableCosts::getBand)
                    .mandatory(FixedRecoverableCosts::getComplexityBandingAgreed)
                    .optional(FixedRecoverableCosts::getReasons).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQLanguage)
                    .mandatory(WelshLanguageRequirements::getCourt)
                    .mandatory(WelshLanguageRequirements::getDocuments).done().done();
        fields.complex(CaseData::getApplicant2DQ)
                    .complexScope(Applicant2DQ::getApplicant2DQLanguage)
                    .mandatory(WelshLanguageRequirements::getCourt)
                    .mandatory(WelshLanguageRequirements::getDocuments).done().done();
    }
}
