package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECApplicantCourtLocationLRspecPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECApplicantDefenceResponseDocumentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECApplicationsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECCcjJudgmentSummaryPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECCcjPaymentPaidSomePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDeterminationWithoutHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDisclosureOfElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDisclosureOfNonElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDisclosureReportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDraftDirectionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFileDirectionsQuestionnairePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFixedCostPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFixedRecoverableCostsIntermediatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFixedRecoverableCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFurtherInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECHearingSupportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECIntentionToSettleClaimPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECLanguagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECMediationAvailabilityPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECMediationContactInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECMediationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECPaymentDatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECRespondentProposedRepaymentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECRespondentResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECRespondentResponsePayImmediatelyPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECSmallClaimExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECSmallClaimWitnessesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECSuggestInstalmentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECVulnerabilityQuestionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECWitnessesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.DeterWithoutHearing;
import uk.gov.hmcts.reform.civil.model.RespondToClaimAdmitPartLRspec;
import uk.gov.hmcts.reform.civil.model.ResponseDocument;
import uk.gov.hmcts.reform.civil.model.UnavailableDate;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Applicant1DQ;
import uk.gov.hmcts.reform.civil.model.dq.DisclosureReport;
import uk.gov.hmcts.reform.civil.model.dq.Expert;
import uk.gov.hmcts.reform.civil.model.dq.ExpertDetails;
import uk.gov.hmcts.reform.civil.model.dq.Experts;
import uk.gov.hmcts.reform.civil.model.dq.FixedRecoverableCosts;
import uk.gov.hmcts.reform.civil.model.dq.FurtherInformation;
import uk.gov.hmcts.reform.civil.model.dq.Hearing;
import uk.gov.hmcts.reform.civil.model.dq.RemoteHearingLRspec;
import uk.gov.hmcts.reform.civil.model.dq.SmallClaimHearing;
import uk.gov.hmcts.reform.civil.model.dq.WelshLanguageRequirements;
import uk.gov.hmcts.reform.civil.model.dq.Witness;
import uk.gov.hmcts.reform.civil.model.dq.Witnesses;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CLAIMANT_RESPONSE_SPEC} for case type {@code CIVIL}.
 */
@Component
public class CLAIMANTRESPONSESPEC implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_RESPONSE_SPEC = "CLAIMANT_RESPONSE_SPEC";

    /**
     * Registers event {@code CLAIMANT_RESPONSE_SPEC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CLAIMANT_RESPONSE_SPEC)
            .forState(CaseState.AWAITING_APPLICANT_INTENTION)
            .name("View and respond to defence")
            .description("View and respond to defendant (Specified)")
            .displayOrder(7)
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit your response")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.WLU_ADMIN)
            .grant(Permission.CRU, UserRole.APP_SOL_SPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE)
            .fields();
        CLAIMANTRESPONSESPECRespondentResponsePage.apply(fields);
        CLAIMANTRESPONSESPECFixedCostPage.apply(fields);
        CLAIMANTRESPONSESPECCcjJudgmentSummaryPage.apply(fields);
        CLAIMANTRESPONSESPECRespondentProposedRepaymentPage.apply(fields);
        CLAIMANTRESPONSESPECApplicantDefenceResponseDocumentPage.apply(fields);
        CLAIMANTRESPONSESPECCcjPaymentPaidSomePage.apply(fields);
        CLAIMANTRESPONSESPECIntentionToSettleClaimPage.apply(fields);
        CLAIMANTRESPONSESPECPaymentDatePage.apply(fields);
        CLAIMANTRESPONSESPECSuggestInstalmentsPage.apply(fields);
        CLAIMANTRESPONSESPECMediationPage.apply(fields);
        CLAIMANTRESPONSESPECFileDirectionsQuestionnairePage.apply(fields);
        CLAIMANTRESPONSESPECDisclosureOfElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSESPECDisclosureOfNonElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSESPECDisclosureReportPage.apply(fields);
        CLAIMANTRESPONSESPECExpertsPage.apply(fields);
        CLAIMANTRESPONSESPECSmallClaimExpertsPage.apply(fields);
        CLAIMANTRESPONSESPECSmallClaimWitnessesPage.apply(fields);
        CLAIMANTRESPONSESPECWitnessesPage.apply(fields);
        CLAIMANTRESPONSESPECLanguagePage.apply(fields);
        CLAIMANTRESPONSESPECHearingPage.apply(fields);
        CLAIMANTRESPONSESPECApplicantCourtLocationLRspecPage.apply(fields);
        CLAIMANTRESPONSESPECHearingSupportPage.apply(fields);
        CLAIMANTRESPONSESPECVulnerabilityQuestionsPage.apply(fields);
        CLAIMANTRESPONSESPECApplicationsPage.apply(fields);
        CLAIMANTRESPONSESPECStatementOfTruthPage.apply(fields);
        CLAIMANTRESPONSESPECMediationContactInformationPage.apply(fields);
        CLAIMANTRESPONSESPECMediationAvailabilityPage.apply(fields);
        CLAIMANTRESPONSESPECFixedRecoverableCostsPage.apply(fields);
        CLAIMANTRESPONSESPECDeterminationWithoutHearingPage.apply(fields);
        CLAIMANTRESPONSESPECFurtherInformationPage.apply(fields);
        CLAIMANTRESPONSESPECRespondentResponsePayImmediatelyPage.apply(fields);
        CLAIMANTRESPONSESPECFixedRecoverableCostsIntermediatePage.apply(fields);
        CLAIMANTRESPONSESPECDraftDirectionsPage.apply(fields);
        CLAIMANTRESPONSESPECWorkAllocationIntegrationFieldsPage.apply(fields);
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1RespondToClaimExperts)
                    .readonly(ExpertDetails::getExpertDetails)
                    .mandatory(ExpertDetails::getFirstName)
                    .hintText("If the name is unknown at this time please add TBC to both the first name and last name lines. Then use the Manage Contact Information event to provide the name when known\n")
                    .mandatory(ExpertDetails::getLastName)
                    .optional(ExpertDetails::getPhoneNumber)
                    .optional(ExpertDetails::getEmailAddress)
                    .mandatory(ExpertDetails::getFieldofExpertise)
                    .mandatory(ExpertDetails::getWhyRequired)
                    .mandatory(ExpertDetails::getEstimatedCost).done().done();
        fields.complexScope(CaseData::getRespondent1SpecDefenceResponseDocument)
                    .optional(ResponseDocument::getFile)
                    .eventLabel("Upload file")
                    .eventHint("We accept documents sized 10MB or smaller, in these formats: pdf, doc, docx, jpg, jpeg, xls, xlsx, png.")
                    .noHintText().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getDeterWithoutHearing)
                    .mandatory(DeterWithoutHearing::getDeterWithoutHearingLabel)
                    .mandatory(DeterWithoutHearing::getDeterWithoutHearingYesNo)
                    .mandatory(DeterWithoutHearing::getDeterWithoutHearingWhyNot)
                    .fieldShowCondition("deterWithoutHearing.deterWithoutHearingYesNo = \"No\"").done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQExperts)
                    .mandatory(Experts::getExpertRequired)
                    .mandatory(Experts::getExpertReportsSent)
                    .mandatory(Experts::getJointExpertSuitable)
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getFirstName).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getLastName).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getPhoneNumber).done()
                    .complex(Experts::getDetails, Expert.class)
                    .optional(Expert::getEmailAddress).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getFieldOfExpertise).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getWhyRequired).done()
                    .complex(Experts::getDetails, Expert.class)
                    .mandatory(Expert::getEstimatedCost).done().done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQHearingLRspec)
                    .mandatory(Hearing::getHearingLengthHours)
                    .noHintText()
                    .mandatory(Hearing::getHearingLengthDays)
                    .noHintText()
                    .mandatory(Hearing::getUnavailableDatesRequired)
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getUnavailableDateType).done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getFromDate)
                    .noHintText().done()
                    .complex(Hearing::getUnavailableDates, UnavailableDate.class)
                    .mandatory(UnavailableDate::getToDate)
                    .noHintText().done().done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQDisclosureReport)
                    .optional(DisclosureReport::getDisclosureFormFiledAndServed)
                    .optional(DisclosureReport::getDisclosureProposalAgreed)
                    .optional(DisclosureReport::getDraftOrderNumber).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQFurtherInformation)
                    .mandatory(FurtherInformation::getFutureApplications)
                    .mandatory(FurtherInformation::getReasonForFutureApplications)
                    .optional(FurtherInformation::getOtherInformationForJudge).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQRemoteHearingLRspec)
                    .mandatory(RemoteHearingLRspec::getRemoteHearingRequested)
                    .noHintText()
                    .optional(RemoteHearingLRspec::getReasonForRemoteHearing)
                    .fieldShowCondition("applicant1DQRemoteHearingLRspec.remoteHearingRequested = \"Yes\"").done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQSmallClaimHearing)
                    .mandatory(SmallClaimHearing::getUnavailableDatesRequired)
                    .noHintText()
                    .mandatory(SmallClaimHearing::getSmallClaimUnavailableDate)
                    .complex(SmallClaimHearing::getSmallClaimUnavailableDate, UnavailableDate.class)
                    .mandatory(UnavailableDate::getUnavailableDateType).done()
                    .complex(SmallClaimHearing::getSmallClaimUnavailableDate, UnavailableDate.class)
                    .mandatory(UnavailableDate::getDate)
                    .noHintText().done()
                    .complex(SmallClaimHearing::getSmallClaimUnavailableDate, UnavailableDate.class)
                    .mandatory(UnavailableDate::getFromDate)
                    .noHintText().done()
                    .complex(SmallClaimHearing::getSmallClaimUnavailableDate, UnavailableDate.class)
                    .mandatory(UnavailableDate::getToDate)
                    .noHintText().done().done().done();
        fields.complexScope(CaseData::getRespondToClaimAdmitPartLRspec)
                    .mandatory(RespondToClaimAdmitPartLRspec::getWhenWillThisAmountBePaid)
                    .noHintText().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQWitnesses)
                    .mandatory(Witnesses::getWitnessesToAppear)
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getFirstName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getLastName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getPhoneNumber).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEmailAddress).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getReasonForWitness).done().done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQFixedRecoverableCosts)
                    .mandatory(FixedRecoverableCosts::getIsSubjectToFixedRecoverableCostRegime)
                    .mandatory(FixedRecoverableCosts::getBandLabel)
                    .eventLabel("<div class='form-label'>For information on which complexity band the claim should be in see</span> <a href='https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part26' rel=\"noreferrer noopener\" target=\"_blank\">CPR26.15 Table 1</a></div><br />")
                    .mandatory(FixedRecoverableCosts::getBand)
                    .mandatory(FixedRecoverableCosts::getComplexityBandingAgreed)
                    .optional(FixedRecoverableCosts::getReasons).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQFixedRecoverableCostsIntermediate)
                    .mandatory(FixedRecoverableCosts::getIsSubjectToFixedRecoverableCostRegime)
                    .mandatory(FixedRecoverableCosts::getComplexityBandingAgreed)
                    .mandatory(FixedRecoverableCosts::getBand)
                    .optional(FixedRecoverableCosts::getReasons)
                    .optional(FixedRecoverableCosts::getFrcSupportingDocument).done().done();
        fields.complex(CaseData::getApplicant1DQ)
                    .complexScope(Applicant1DQ::getApplicant1DQLanguage)
                    .mandatory(WelshLanguageRequirements::getCourt)
                    .mandatory(WelshLanguageRequirements::getDocuments).done().done();
    }
}
