package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECApplicantCourtLocationLRspecPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECApplicantDefenceResponseDocumentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECApplicationsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECCcjJudgmentSummaryPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECCcjPaymentPaidSomePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDeterminationWithoutHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDisclosureOfElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDisclosureOfNonElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDisclosureReportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECDraftDirectionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFileDirectionsQuestionnairePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFixedCostPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFixedRecoverableCostsIntermediatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFixedRecoverableCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECFurtherInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECHearingSupportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECIntentionToSettleClaimPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECLanguagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECMediationAvailabilityPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECMediationContactInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECMediationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECPaymentDatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECRespondentProposedRepaymentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECRespondentResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECRespondentResponsePayImmediatelyPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECSmallClaimExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECSmallClaimWitnessesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECSuggestInstalmentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECVulnerabilityQuestionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECWitnessesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CLAIMANTRESPONSESPECWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CLAIMANT_RESPONSE_SPEC} for case type {@code CIVIL}.
 */
@Component
public class CLAIMANTRESPONSESPEC implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT_RESPONSE_SPEC = "CLAIMANT_RESPONSE_SPEC";

    /**
     * Registers event {@code CLAIMANT_RESPONSE_SPEC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CLAIMANT_RESPONSE_SPEC)
            .forState(CaseState.AWAITING_APPLICANT_INTENTION)
            .name("View and respond to defence")
            .description("View and respond to defendant (Specified)")
            .displayOrder(7)
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit your response")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.WLU_ADMIN)
            .grant(Permission.CRU, UserRole.APP_SOL_SPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE)
            .fields();
        CLAIMANTRESPONSESPECRespondentResponsePage.apply(fields);
        CLAIMANTRESPONSESPECFixedCostPage.apply(fields);
        CLAIMANTRESPONSESPECCcjJudgmentSummaryPage.apply(fields);
        CLAIMANTRESPONSESPECRespondentProposedRepaymentPage.apply(fields);
        CLAIMANTRESPONSESPECApplicantDefenceResponseDocumentPage.apply(fields);
        CLAIMANTRESPONSESPECCcjPaymentPaidSomePage.apply(fields);
        CLAIMANTRESPONSESPECIntentionToSettleClaimPage.apply(fields);
        CLAIMANTRESPONSESPECPaymentDatePage.apply(fields);
        CLAIMANTRESPONSESPECSuggestInstalmentsPage.apply(fields);
        CLAIMANTRESPONSESPECMediationPage.apply(fields);
        CLAIMANTRESPONSESPECFileDirectionsQuestionnairePage.apply(fields);
        CLAIMANTRESPONSESPECDisclosureOfElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSESPECDisclosureOfNonElectronicDocumentsPage.apply(fields);
        CLAIMANTRESPONSESPECDisclosureReportPage.apply(fields);
        CLAIMANTRESPONSESPECExpertsPage.apply(fields);
        CLAIMANTRESPONSESPECSmallClaimExpertsPage.apply(fields);
        CLAIMANTRESPONSESPECSmallClaimWitnessesPage.apply(fields);
        CLAIMANTRESPONSESPECWitnessesPage.apply(fields);
        CLAIMANTRESPONSESPECLanguagePage.apply(fields);
        CLAIMANTRESPONSESPECHearingPage.apply(fields);
        CLAIMANTRESPONSESPECApplicantCourtLocationLRspecPage.apply(fields);
        CLAIMANTRESPONSESPECHearingSupportPage.apply(fields);
        CLAIMANTRESPONSESPECVulnerabilityQuestionsPage.apply(fields);
        CLAIMANTRESPONSESPECApplicationsPage.apply(fields);
        CLAIMANTRESPONSESPECStatementOfTruthPage.apply(fields);
        CLAIMANTRESPONSESPECMediationContactInformationPage.apply(fields);
        CLAIMANTRESPONSESPECMediationAvailabilityPage.apply(fields);
        CLAIMANTRESPONSESPECFixedRecoverableCostsPage.apply(fields);
        CLAIMANTRESPONSESPECDeterminationWithoutHearingPage.apply(fields);
        CLAIMANTRESPONSESPECFurtherInformationPage.apply(fields);
        CLAIMANTRESPONSESPECRespondentResponsePayImmediatelyPage.apply(fields);
        CLAIMANTRESPONSESPECFixedRecoverableCostsIntermediatePage.apply(fields);
        CLAIMANTRESPONSESPECDraftDirectionsPage.apply(fields);
        CLAIMANTRESPONSESPECWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
