package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CLAIMANT1_HWF_DASHBOARD_NOTIFICATION} for case type {@code CIVIL}.
 */
@Component
public class CLAIMANT1HWFDASHBOARDNOTIFICATION implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLAIMANT1_HWF_DASHBOARD_NOTIFICATION = "CLAIMANT1_HWF_DASHBOARD_NOTIFICATION";

    /**
     * Registers event {@code CLAIMANT1_HWF_DASHBOARD_NOTIFICATION}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(CLAIMANT1_HWF_DASHBOARD_NOTIFICATION)
            .forAllStates()
            .name("Dashboard: HWF Notification")
            .description("Dashboard Notification for HwF.")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
