package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CONTACT_INFORMATION_UPDATED_WA} for case type {@code CIVIL}.
 */
@Component
public class CONTACTINFORMATIONUPDATEDWA implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CONTACT_INFORMATION_UPDATED_WA = "CONTACT_INFORMATION_UPDATED_WA";

    /**
     * Registers event {@code CONTACT_INFORMATION_UPDATED_WA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CONTACT_INFORMATION_UPDATED_WA)
            .forAllStates()
            .name("Contact Information Updated WA")
            .description(" ")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        fields.page("WorkAllocation");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA);
    }
}
