package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_DASHBOARD_NOTIFICATION_COSC_GEN_FOR_DEFENDANT} for case type {@code CIVIL}.
 */
@Component
public class CREATEDASHBOARDNOTIFICATIONCOSCGENFORDEFENDANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_DASHBOARD_NOTIFICATION_COSC_GEN_FOR_DEFENDANT = "CREATE_DASHBOARD_NOTIFICATION_COSC_GEN_FOR_DEFENDANT";

    /**
     * Registers event {@code CREATE_DASHBOARD_NOTIFICATION_COSC_GEN_FOR_DEFENDANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(CREATE_DASHBOARD_NOTIFICATION_COSC_GEN_FOR_DEFENDANT)
            .forAllStates()
            .name("Defendant mark paid full")
            .description("Defendant Dashboard Notification certificate generated")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
