package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOClaimsTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDODisposalHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOFastTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOOrderPreviewPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOOrderTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSDOPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSdoR2FastTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSdoR2SmallClaimsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSmallClaimsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_SDO} for case type {@code CIVIL}.
 */
@Component
public class CREATESDO implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_SDO = "CREATE_SDO";

    /**
     * Registers event {@code CREATE_SDO}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CREATE_SDO)
            .forStateTransition(EnumSet.of(CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION), CaseState.CASE_PROGRESSION)
            .name("Standard Direction Order")
            .displayOrder(17)
            .showCondition("detailsOfDirection = \"Only available through tasks\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Permission.CRU, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        CREATESDOSDOPage.apply(fields);
        CREATESDOClaimsTrackPage.apply(fields);
        CREATESDOOrderTypePage.apply(fields);
        CREATESDODisposalHearingPage.apply(fields);
        CREATESDOSmallClaimsPage.apply(fields);
        CREATESDOSdoR2FastTrackPage.apply(fields);
        CREATESDOSdoR2SmallClaimsPage.apply(fields);
        CREATESDOFastTrackPage.apply(fields);
        CREATESDOOrderPreviewPage.apply(fields);
        CREATESDOWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
