package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOClaimsTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDODisposalHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOFastTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOOrderPreviewPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOOrderTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSDOPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSdoR2FastTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSdoR2SmallClaimsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOSmallClaimsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATESDOWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.FastTrackCosts;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.sdo.FastTrackCreditHire;
import uk.gov.hmcts.reform.civil.model.sdo.FastTrackWitnessOfFact;
import uk.gov.hmcts.reform.civil.model.sdo.SmallClaimsWitnessStatement;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_SDO} for case type {@code CIVIL}.
 */
@Component
public class CREATESDO implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_SDO = "CREATE_SDO";

    /**
     * Registers event {@code CREATE_SDO}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CREATE_SDO)
            .forStateTransition(EnumSet.of(CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION), CaseState.CASE_PROGRESSION)
            .name("Standard Direction Order")
            .displayOrder(17)
            .showCondition("detailsOfDirection = \"Only available through tasks\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Permission.CRU, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        CREATESDOSDOPage.apply(fields);
        CREATESDOClaimsTrackPage.apply(fields);
        CREATESDOOrderTypePage.apply(fields);
        CREATESDODisposalHearingPage.apply(fields);
        CREATESDOSmallClaimsPage.apply(fields);
        CREATESDOSdoR2FastTrackPage.apply(fields);
        CREATESDOSdoR2SmallClaimsPage.apply(fields);
        CREATESDOFastTrackPage.apply(fields);
        CREATESDOOrderPreviewPage.apply(fields);
        CREATESDOWorkAllocationIntegrationFieldsPage.apply(fields);
        fields.complexScope(CaseData::getSmallClaimsWitnessStatement)
                    .readonly(SmallClaimsWitnessStatement::getLabel)
                    .mandatory(SmallClaimsWitnessStatement::getInput1)
                    .optional(SmallClaimsWitnessStatement::getSmallClaimsNumberOfWitnessesToggle)
                    .mandatory(SmallClaimsWitnessStatement::getInput2)
                    .eventHint("Limit number of witnesses (claimant), e.g. 4")
                    .mandatory(SmallClaimsWitnessStatement::getInput3)
                    .eventHint("Limit number of witnesses (defendant), e.g. 4")
                    .optional(SmallClaimsWitnessStatement::getInput4)
                    .readonly(SmallClaimsWitnessStatement::getText).done();
        fields.complexScope(CaseData::getFastTrackWitnessOfFact)
                    .readonly(FastTrackWitnessOfFact::getLabel)
                    .mandatory(FastTrackWitnessOfFact::getInput1)
                    .mandatory(FastTrackWitnessOfFact::getInput2)
                    .eventHint("Number of witnesses (claimant), e.g. 4")
                    .mandatory(FastTrackWitnessOfFact::getInput3)
                    .eventHint("Number of witnesses (defendant), e.g. 4")
                    .mandatory(FastTrackWitnessOfFact::getInput4)
                    .mandatory(FastTrackWitnessOfFact::getInput5)
                    .mandatory(FastTrackWitnessOfFact::getInput6)
                    .eventHint("Number of pages, e.g. 4")
                    .mandatory(FastTrackWitnessOfFact::getInput7)
                    .mandatory(FastTrackWitnessOfFact::getInput8)
                    .optional(FastTrackWitnessOfFact::getDate)
                    .mandatory(FastTrackWitnessOfFact::getInput9).done();
        fields.complexScope(CaseData::getFastTrackCosts)
                    .readonly(FastTrackCosts::getLabel)
                    .mandatory(FastTrackCosts::getText).done();
        fields.complexScope(CaseData::getFastTrackCreditHire)
                    .readonly(FastTrackCreditHire::getLabel)
                    .mandatory(FastTrackCreditHire::getInput1)
                    .readonly(FastTrackCreditHire::getText)
                    .eventLabel("A failure to comply with the paragraph above will result in the claimant being debarred from asserting impecuniosity at the final hearing\n"
                        + "\n")
                    .mandatory(FastTrackCreditHire::getInput2)
                    .readonly(FastTrackCreditHire::getDateText)
                    .optional(FastTrackCreditHire::getDate1)
                    .mandatory(FastTrackCreditHire::getInput3)
                    .mandatory(FastTrackCreditHire::getInput4)
                    .optional(FastTrackCreditHire::getDate2)
                    .mandatory(FastTrackCreditHire::getInput5)
                    .mandatory(FastTrackCreditHire::getInput6)
                    .optional(FastTrackCreditHire::getDate3)
                    .mandatory(FastTrackCreditHire::getInput7)
                    .optional(FastTrackCreditHire::getDate4)
                    .mandatory(FastTrackCreditHire::getInput8)
                    .readonly(FastTrackCreditHire::getLine).done();
    }
}
