package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMAddAnotherClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMAddAnotherDefendantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimDeclarationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimValuePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimantLitigationFriendPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMClaimantSolicitorServiceAddressPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMCourtPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMDefendantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMDefendantSolicitorEmailPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMDefendantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMDefendantSolicitorServiceAddressPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMEligibilityPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMHumanRightsActPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMLegalRepresentationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMNotificationsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMPbaNumberPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMPersonalInjuryTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMReferencesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSameLegalRepresentativePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondClaimantLitigationFriendPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondDefendantLegalRepresentationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondDefendantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondDefendantSolicitorEmailPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondDefendantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondDefendantSolicitorReferencePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSecondDefendantSolicitorServiceAddressPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMUploadPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMUploadParticularsOfClaimPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_CLAIM} for case type {@code CIVIL}.
 */
@Component
public class CREATECLAIM implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_CLAIM = "CREATE_CLAIM";

    /**
     * Registers event {@code CREATE_CLAIM}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CREATE_CLAIM)
            .initialState(CaseState.PENDING_CASE_ISSUED)
            .name("Create claim - Unspecified")
            .description("Case created, post actions triggered")
            .displayOrder(1)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        CREATECLAIMEligibilityPage.apply(fields);
        CREATECLAIMReferencesPage.apply(fields);
        CREATECLAIMCourtPage.apply(fields);
        CREATECLAIMClaimantPage.apply(fields);
        CREATECLAIMClaimantLitigationFriendPage.apply(fields);
        CREATECLAIMNotificationsPage.apply(fields);
        CREATECLAIMClaimantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMClaimantSolicitorServiceAddressPage.apply(fields);
        CREATECLAIMDefendantPage.apply(fields);
        CREATECLAIMLegalRepresentationPage.apply(fields);
        CREATECLAIMDefendantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMDefendantSolicitorServiceAddressPage.apply(fields);
        CREATECLAIMDefendantSolicitorEmailPage.apply(fields);
        CREATECLAIMDetailsPage.apply(fields);
        CREATECLAIMUploadParticularsOfClaimPage.apply(fields);
        CREATECLAIMUploadPage.apply(fields);
        CREATECLAIMClaimValuePage.apply(fields);
        CREATECLAIMAddAnotherClaimantPage.apply(fields);
        CREATECLAIMSecondClaimantPage.apply(fields);
        CREATECLAIMSecondClaimantLitigationFriendPage.apply(fields);
        CREATECLAIMAddAnotherDefendantPage.apply(fields);
        CREATECLAIMSecondDefendantPage.apply(fields);
        CREATECLAIMSecondDefendantLegalRepresentationPage.apply(fields);
        CREATECLAIMSameLegalRepresentativePage.apply(fields);
        CREATECLAIMSecondDefendantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMSecondDefendantSolicitorServiceAddressPage.apply(fields);
        CREATECLAIMSecondDefendantSolicitorReferencePage.apply(fields);
        CREATECLAIMSecondDefendantSolicitorEmailPage.apply(fields);
        CREATECLAIMClaimTypePage.apply(fields);
        CREATECLAIMClaimDeclarationPage.apply(fields);
        CREATECLAIMHumanRightsActPage.apply(fields);
        CREATECLAIMPersonalInjuryTypePage.apply(fields);
        CREATECLAIMPbaNumberPage.apply(fields);
        CREATECLAIMStatementOfTruthPage.apply(fields);
    }
}
