package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECAddAnotherClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECAddAnotherDefendantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECBreakDownInterestPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECCheckListPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimAmountDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimAmountPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimInterestOptionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimInterestPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimTimelinePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimTimelineUploadPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECClaimantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECDefendantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECDefendantSolicitorEmailPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECDefendantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECEligibilityPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECEvidenceListPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECFixedCommencementCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECFlightDelayClaimPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECInterestClaimFromPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECInterestClaimUntilPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECInterestFromSpecificDatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECInterestSummaryPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECLegalRepresentationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECLegalRepresentationRespondent2Page;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECNotificationsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECPaymentReferencePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECPbaNumberPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECReferencesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSameLegalRepresentativePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSameRateInterestSelectionPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSecondClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSecondDefendantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSecondDefendantSolicitorEmailPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSecondDefendantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSpecCorrespondenceAddressPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSpecRespondent2CorrespondenceAddressPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECSpecRespondentCorrespondenceAddressPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECUnRegisteredDefendantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECUnRegisteredSecondDefendantSolicitorOrganisationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.CREATECLAIMSPECUploadClaimDocumentPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_CLAIM_SPEC} for case type {@code CIVIL}.
 */
@Component
public class CREATECLAIMSPEC implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_CLAIM_SPEC = "CREATE_CLAIM_SPEC";

    /**
     * Registers event {@code CREATE_CLAIM_SPEC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(CREATE_CLAIM_SPEC)
            .initialState(CaseState.PENDING_CASE_ISSUED)
            .name("Create claim - Specified")
            .description("Case created, post actions triggered")
            .displayOrder(1)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.CITIZEN_CLAIMANT_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        CREATECLAIMSPECCheckListPage.apply(fields);
        CREATECLAIMSPECEligibilityPage.apply(fields);
        CREATECLAIMSPECReferencesPage.apply(fields);
        CREATECLAIMSPECClaimantPage.apply(fields);
        CREATECLAIMSPECAddAnotherClaimantPage.apply(fields);
        CREATECLAIMSPECSecondClaimantPage.apply(fields);
        CREATECLAIMSPECNotificationsPage.apply(fields);
        CREATECLAIMSPECClaimantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMSPECSpecCorrespondenceAddressPage.apply(fields);
        CREATECLAIMSPECDefendantPage.apply(fields);
        CREATECLAIMSPECLegalRepresentationPage.apply(fields);
        CREATECLAIMSPECDefendantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMSPECDefendantSolicitorEmailPage.apply(fields);
        CREATECLAIMSPECUnRegisteredDefendantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMSPECSpecRespondentCorrespondenceAddressPage.apply(fields);
        CREATECLAIMSPECSecondDefendantPage.apply(fields);
        CREATECLAIMSPECLegalRepresentationRespondent2Page.apply(fields);
        CREATECLAIMSPECSameLegalRepresentativePage.apply(fields);
        CREATECLAIMSPECSecondDefendantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMSPECSecondDefendantSolicitorEmailPage.apply(fields);
        CREATECLAIMSPECUnRegisteredSecondDefendantSolicitorOrganisationPage.apply(fields);
        CREATECLAIMSPECSpecRespondent2CorrespondenceAddressPage.apply(fields);
        CREATECLAIMSPECDetailsPage.apply(fields);
        CREATECLAIMSPECUploadClaimDocumentPage.apply(fields);
        CREATECLAIMSPECClaimTimelinePage.apply(fields);
        CREATECLAIMSPECClaimTimelineUploadPage.apply(fields);
        CREATECLAIMSPECEvidenceListPage.apply(fields);
        CREATECLAIMSPECClaimAmountPage.apply(fields);
        CREATECLAIMSPECClaimAmountDetailsPage.apply(fields);
        CREATECLAIMSPECClaimInterestPage.apply(fields);
        CREATECLAIMSPECClaimInterestOptionsPage.apply(fields);
        CREATECLAIMSPECSameRateInterestSelectionPage.apply(fields);
        CREATECLAIMSPECBreakDownInterestPage.apply(fields);
        CREATECLAIMSPECInterestClaimFromPage.apply(fields);
        CREATECLAIMSPECInterestFromSpecificDatePage.apply(fields);
        CREATECLAIMSPECInterestClaimUntilPage.apply(fields);
        CREATECLAIMSPECInterestSummaryPage.apply(fields);
        CREATECLAIMSPECPbaNumberPage.apply(fields);
        CREATECLAIMSPECPaymentReferencePage.apply(fields);
        CREATECLAIMSPECFixedCommencementCostsPage.apply(fields);
        CREATECLAIMSPECStatementOfTruthPage.apply(fields);
        CREATECLAIMSPECAddAnotherDefendantPage.apply(fields);
        CREATECLAIMSPECFlightDelayClaimPage.apply(fields);
    }
}
