package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_CLAIM_SPEC_AFTER_PAYMENT} for case type {@code CIVIL}.
 */
@Component
public class CREATECLAIMSPECAFTERPAYMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_CLAIM_SPEC_AFTER_PAYMENT = "CREATE_CLAIM_SPEC_AFTER_PAYMENT";

    /**
     * Registers event {@code CREATE_CLAIM_SPEC_AFTER_PAYMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(CREATE_CLAIM_SPEC_AFTER_PAYMENT)
            .forState(CaseState.PENDING_CASE_ISSUED)
            .name("Case issued after payment")
            .description("Move to case issued when fee paid")
            .showSummary(false)
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE, UserRole.CITIZEN_CLAIMANT_PROFILE);
    }
}
