package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code CREATE_MESSAGES_TASK_CATEGORIES} for case type {@code CIVIL}.
 */
@Component
public class CREATEMESSAGESTASKCATEGORIES implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_MESSAGES_TASK_CATEGORIES = "CREATE_MESSAGES_TASK_CATEGORIES";

    /**
     * Registers event {@code CREATE_MESSAGES_TASK_CATEGORIES}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(CREATE_MESSAGES_TASK_CATEGORIES)
            .forAllStates()
            .name("Create QM task categories")
            .description("Create messages task categories")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
