package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFAULTJUDGEMENTAbandonOtherRemedyPagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFAULTJUDGEMENTDefendantDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFAULTJUDGEMENTHearingSupportRequirementsFieldDJPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFAULTJUDGEMENTHearingTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFAULTJUDGEMENTShowcertifystatementPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFAULTJUDGEMENTShowcertifystatementbothPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code DEFAULT_JUDGEMENT} for case type {@code CIVIL}.
 */
@Component
public class DEFAULTJUDGEMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DEFAULT_JUDGEMENT = "DEFAULT_JUDGEMENT";

    /**
     * Registers event {@code DEFAULT_JUDGEMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(DEFAULT_JUDGEMENT)
            .forState(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT)
            .name("Request Default Judgment")
            .displayOrder(17)
            .showCondition("applicantSolicitor1ServiceAddressRequired = \"No\" OR applicantSolicitor1ServiceAddressRequired =  \"Yes\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CREATOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        DEFAULTJUDGEMENTDefendantDetailsPage.apply(fields);
        DEFAULTJUDGEMENTShowcertifystatementPage.apply(fields);
        DEFAULTJUDGEMENTShowcertifystatementbothPage.apply(fields);
        DEFAULTJUDGEMENTHearingTypePage.apply(fields);
        DEFAULTJUDGEMENTHearingSupportRequirementsFieldDJPage.apply(fields);
        DEFAULTJUDGEMENTAbandonOtherRemedyPagePage.apply(fields);
    }
}
