package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdConfirmDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdDeterminationWithoutHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdDisclosureOfElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdDisclosureOfNonElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdDisclosureReportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdDraftDirectionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdFileDirectionsQuestionnairePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdFixedRecoverableCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdFurtherInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdHearingSupportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdLanguagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdRequestedCourtPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdRespondentResponseTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdSingleResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdSolicitorReferencesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdUploadPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdVulnerabilityQuestionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSEProdWitnessesPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code DEFENDANT_RESPONSE} for case type {@code CIVIL}.
 */
@Component
public class DEFENDANTRESPONSEProd implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DEFENDANT_RESPONSE = "DEFENDANT_RESPONSE";

    /**
     * Registers overlay event {@code DEFENDANT_RESPONSE} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(DEFENDANT_RESPONSE)
            .forState(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT)
            .name("Respond to claim")
            .description("Defendant response to claim")
            .displayOrder(6)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        DEFENDANTRESPONSEProdFixedRecoverableCostsPage.apply(fields);
        DEFENDANTRESPONSEProdStatementOfTruthPage.apply(fields);
        DEFENDANTRESPONSEProdFurtherInformationPage.apply(fields);
        DEFENDANTRESPONSEProdVulnerabilityQuestionsPage.apply(fields);
        DEFENDANTRESPONSEProdHearingSupportPage.apply(fields);
        DEFENDANTRESPONSEProdRequestedCourtPage.apply(fields);
        DEFENDANTRESPONSEProdDraftDirectionsPage.apply(fields);
        DEFENDANTRESPONSEProdHearingPage.apply(fields);
        DEFENDANTRESPONSEProdLanguagePage.apply(fields);
        DEFENDANTRESPONSEProdWitnessesPage.apply(fields);
        DEFENDANTRESPONSEProdDeterminationWithoutHearingPage.apply(fields);
        DEFENDANTRESPONSEProdExpertsPage.apply(fields);
        DEFENDANTRESPONSEProdDisclosureReportPage.apply(fields);
        DEFENDANTRESPONSEProdDisclosureOfNonElectronicDocumentsPage.apply(fields);
        DEFENDANTRESPONSEProdDisclosureOfElectronicDocumentsPage.apply(fields);
        DEFENDANTRESPONSEProdFileDirectionsQuestionnairePage.apply(fields);
        DEFENDANTRESPONSEProdUploadPage.apply(fields);
        DEFENDANTRESPONSEProdSolicitorReferencesPage.apply(fields);
        DEFENDANTRESPONSEProdRespondentResponseTypePage.apply(fields);
        DEFENDANTRESPONSEProdConfirmDetailsPage.apply(fields);
        DEFENDANTRESPONSEProdSingleResponsePage.apply(fields);
    }
}
