package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code DEFENDANT_SIGN_SETTLEMENT_AGREEMENT} for case type {@code CIVIL}.
 */
@Component
public class DEFENDANTSIGNSETTLEMENTAGREEMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DEFENDANT_SIGN_SETTLEMENT_AGREEMENT = "DEFENDANT_SIGN_SETTLEMENT_AGREEMENT";

    /**
     * Registers event {@code DEFENDANT_SIGN_SETTLEMENT_AGREEMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(DEFENDANT_SIGN_SETTLEMENT_AGREEMENT)
            .forAllStates()
            .name("defendant sign agreement")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CITIZEN_DEFENDANT_PROFILE);
    }
}
