package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodConfirmDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodDeterminationWithoutHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodDisclosureOfElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodDisclosureOfNonElectronicDocumentsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodDisclosureReportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodDraftDirectionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodFileDirectionsQuestionnairePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodFixedRecoverableCostsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodFurtherInformationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodHearingPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodHearingSupportPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodLanguagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodRequestedCourtPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodRespondentResponseTypePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodSingleResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodSolicitorReferencesPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodUploadPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodVulnerabilityQuestionsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.DEFENDANTRESPONSENonprodWitnessesPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code DEFENDANT_RESPONSE} for case type {@code CIVIL}.
 */
@Component
public class DEFENDANTRESPONSENonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DEFENDANT_RESPONSE = "DEFENDANT_RESPONSE";

    /**
     * Registers overlay event {@code DEFENDANT_RESPONSE} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(DEFENDANT_RESPONSE)
            .forStates(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED)
            .name("Respond to claim")
            .description("Defendant response to claim")
            .displayOrder(6)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        DEFENDANTRESPONSENonprodFixedRecoverableCostsPage.apply(fields);
        DEFENDANTRESPONSENonprodStatementOfTruthPage.apply(fields);
        DEFENDANTRESPONSENonprodFurtherInformationPage.apply(fields);
        DEFENDANTRESPONSENonprodVulnerabilityQuestionsPage.apply(fields);
        DEFENDANTRESPONSENonprodHearingSupportPage.apply(fields);
        DEFENDANTRESPONSENonprodRequestedCourtPage.apply(fields);
        DEFENDANTRESPONSENonprodDraftDirectionsPage.apply(fields);
        DEFENDANTRESPONSENonprodHearingPage.apply(fields);
        DEFENDANTRESPONSENonprodLanguagePage.apply(fields);
        DEFENDANTRESPONSENonprodWitnessesPage.apply(fields);
        DEFENDANTRESPONSENonprodDeterminationWithoutHearingPage.apply(fields);
        DEFENDANTRESPONSENonprodExpertsPage.apply(fields);
        DEFENDANTRESPONSENonprodDisclosureReportPage.apply(fields);
        DEFENDANTRESPONSENonprodDisclosureOfNonElectronicDocumentsPage.apply(fields);
        DEFENDANTRESPONSENonprodDisclosureOfElectronicDocumentsPage.apply(fields);
        DEFENDANTRESPONSENonprodFileDirectionsQuestionnairePage.apply(fields);
        DEFENDANTRESPONSENonprodUploadPage.apply(fields);
        DEFENDANTRESPONSENonprodSolicitorReferencesPage.apply(fields);
        DEFENDANTRESPONSENonprodRespondentResponseTypePage.apply(fields);
        DEFENDANTRESPONSENonprodConfirmDetailsPage.apply(fields);
        DEFENDANTRESPONSENonprodSingleResponsePage.apply(fields);
    }
}
