package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code DISCONTINUE_CLAIM} for case type {@code CIVIL}.
 */
@Component
public class DISCONTINUECLAIMNonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DISCONTINUE_CLAIM = "DISCONTINUE_CLAIM";

    /**
     * Registers overlay event {@code DISCONTINUE_CLAIM} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(DISCONTINUE_CLAIM)
            .forStateTransition(EnumSet.of(CaseState.PENDING_CASE_ISSUED, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED, CaseState.AWAITING_APPLICANT_INTENTION), CaseState.CASE_DISMISSED)
            .name("Discontinue claim")
            .description("Discontinue a claim")
            .displayOrder(11)
            .showSummary(false)
            .endButtonLabel("Discontinue claim")
            .explicitGrants()
            .fields();
        fields.page("DiscontinueReason");
        fields.complex(CaseData::getDiscontinueClaim, false).done();
    }
}
