package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code DISMISS_CLAIM} for case type {@code CIVIL}.
 */
@Component
public class DISMISSCLAIMProd implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DISMISS_CLAIM = "DISMISS_CLAIM";

    /**
     * Registers overlay event {@code DISMISS_CLAIM} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(DISMISS_CLAIM)
            .forStateTransition(EnumSet.of(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION), CaseState.CASE_DISMISSED)
            .name("Move claim to dismissed")
            .description("Moves a claim to dismissed")
            .displayOrder(8)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
