package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.breathing.BreathingSpaceInfo;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code ENTER_BREATHING_SPACE_SPEC} for case type {@code CIVIL}.
 */
@Component
public class ENTERBREATHINGSPACESPEC implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ENTER_BREATHING_SPACE_SPEC = "ENTER_BREATHING_SPACE_SPEC";

    /**
     * Registers event {@code ENTER_BREATHING_SPACE_SPEC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(ENTER_BREATHING_SPACE_SPEC)
            .forStates(CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.AWAITING_APPLICANT_INTENTION)
            .name("Enter Breathing Space")
            .displayOrder(7)
            .showCondition("CaseAccessCategory=\"DO_NOT_SHOW_IN_UI\"")
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_SPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE)
            .fields();
        fields.page("EnterBreathingSpaceInfo");
        fields.pageLabel("Enter Breathing Space");
        fields.complex(CaseData::getBreathing)
                    .optional(BreathingSpaceInfo::getEnter).done();
    }
}
