package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADRESPONDENTDocumentSelectionFastTrackPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADRESPONDENTDocumentSelectionSmallClaimPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADRESPONDENTDocumentUploadPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADRESPONDENTEvidenceUploadPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADRESPONDENTSelectUploadOptionsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code EVIDENCE_UPLOAD_RESPONDENT} for case type {@code CIVIL}.
 */
@Component
public class EVIDENCEUPLOADRESPONDENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EVIDENCE_UPLOAD_RESPONDENT = "EVIDENCE_UPLOAD_RESPONDENT";

    /**
     * Registers event {@code EVIDENCE_UPLOAD_RESPONDENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(EVIDENCE_UPLOAD_RESPONDENT)
            .forStates(CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.DECISION_OUTCOME)
            .name("Upload Your Documents")
            .displayOrder(22)
            .showCondition("enableUploadEvent != \"No\"")
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.JUDGE_PROFILE)
            .fields();
        EVIDENCEUPLOADRESPONDENTDocumentSelectionFastTrackPage.apply(fields);
        EVIDENCEUPLOADRESPONDENTDocumentUploadPage.apply(fields);
        EVIDENCEUPLOADRESPONDENTEvidenceUploadPage.apply(fields);
        EVIDENCEUPLOADRESPONDENTSelectUploadOptionsPage.apply(fields);
        EVIDENCEUPLOADRESPONDENTDocumentSelectionSmallClaimPage.apply(fields);
    }
}
