package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code EVIDENCE_UPLOAD_CHECK} for case type {@code CIVIL}.
 */
@Component
public class EVIDENCEUPLOADCHECK implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EVIDENCE_UPLOAD_CHECK = "EVIDENCE_UPLOAD_CHECK";

    /**
     * Registers event {@code EVIDENCE_UPLOAD_CHECK}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(EVIDENCE_UPLOAD_CHECK)
            .forStates(CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.DECISION_OUTCOME)
            .name("EVIDENCE_UPLOAD_CHECK")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
