package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADJUDGECaseNoteSelectionNotePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADJUDGECaseNoteSelectionPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADJUDGEUploadDocumentAndNotePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.EVIDENCEUPLOADJUDGEUploadDocumentPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code EVIDENCE_UPLOAD_JUDGE} for case type {@code CIVIL}.
 */
@Component
public class EVIDENCEUPLOADJUDGE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EVIDENCE_UPLOAD_JUDGE = "EVIDENCE_UPLOAD_JUDGE";

    /**
     * Registers event {@code EVIDENCE_UPLOAD_JUDGE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(EVIDENCE_UPLOAD_JUDGE)
            .forAllStates()
            .name("Add a case note")
            .displayOrder(22)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.JUDGE_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL)
            .fields();
        EVIDENCEUPLOADJUDGECaseNoteSelectionPage.apply(fields);
        EVIDENCEUPLOADJUDGEUploadDocumentPage.apply(fields);
        EVIDENCEUPLOADJUDGECaseNoteSelectionNotePage.apply(fields);
        EVIDENCEUPLOADJUDGEUploadDocumentAndNotePage.apply(fields);
    }
}
