package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code EXTEND_RESPONSE_DEADLINE} for case type {@code CIVIL}.
 */
@Component
public class EXTENDRESPONSEDEADLINENonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String EXTEND_RESPONSE_DEADLINE = "EXTEND_RESPONSE_DEADLINE";

    /**
     * Registers overlay event {@code EXTEND_RESPONSE_DEADLINE} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(EXTEND_RESPONSE_DEADLINE)
            .forStates(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED)
            .name("Extend Response Deadline")
            .description("Extend response deadline")
            .displayOrder(2)
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE)
            .grant(Permission.CRU, UserRole.CUI_ADMIN_PROFILE)
            .fields();
        fields.page("ResponseDeadlineExtension");
        fields.mandatory(CaseData::getRespondentSolicitor1AgreedDeadlineExtension);
    }
}
