package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code GENERATE_CLAIM_FORM_SPEC} for case type {@code CIVIL}.
 */
@Component
public class GENERATECLAIMFORMSPEC implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_CLAIM_FORM_SPEC = "GENERATE_CLAIM_FORM_SPEC";

    /**
     * Registers event {@code GENERATE_CLAIM_FORM_SPEC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(GENERATE_CLAIM_FORM_SPEC)
            .forAllStates()
            .name("Generate claim form")
            .description("Generates claim form after successful payment")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
