package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERDownloadTemplatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERFinalOrderAssistedOrderPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERFinalOrderPreviewPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERFinalOrderSelectPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERFreeFormOrderPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERIntermediateTrackComplexityBandPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDEROrderAfterHearingDatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERSelectTemplatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERTrackAllocationPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERUploadOrderPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.GENERATEDIRECTIONSORDERWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code GENERATE_DIRECTIONS_ORDER} for case type {@code CIVIL}.
 */
@Component
public class GENERATEDIRECTIONSORDER implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_DIRECTIONS_ORDER = "GENERATE_DIRECTIONS_ORDER";

    /**
     * Registers event {@code GENERATE_DIRECTIONS_ORDER}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(GENERATE_DIRECTIONS_ORDER)
            .forStates(CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.DECISION_OUTCOME, CaseState.All_FINAL_ORDERS_ISSUED)
            .name("Make an order")
            .showCondition("eaCourtLocation != \"No\"")
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL, UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.HEARING_SCHEDULE_ACCESS, UserRole.WLU_ADMIN)
            .grant(Permission.CRU, UserRole.JUDGE_PROFILE)
            .fields();
        GENERATEDIRECTIONSORDERTrackAllocationPage.apply(fields);
        GENERATEDIRECTIONSORDERIntermediateTrackComplexityBandPage.apply(fields);
        GENERATEDIRECTIONSORDERFinalOrderSelectPage.apply(fields);
        GENERATEDIRECTIONSORDERSelectTemplatePage.apply(fields);
        GENERATEDIRECTIONSORDERFinalOrderAssistedOrderPage.apply(fields);
        GENERATEDIRECTIONSORDERFreeFormOrderPage.apply(fields);
        GENERATEDIRECTIONSORDERFinalOrderPreviewPage.apply(fields);
        GENERATEDIRECTIONSORDEROrderAfterHearingDatePage.apply(fields);
        GENERATEDIRECTIONSORDERDownloadTemplatePage.apply(fields);
        GENERATEDIRECTIONSORDERUploadOrderPage.apply(fields);
        GENERATEDIRECTIONSORDERWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
