package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.CaseDataLiP;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code GENERATE_RESPONSE_DQ_LIP_SEALED} for case type {@code CIVIL}.
 */
@Component
public class GENERATERESPONSEDQLIPSEALED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_RESPONSE_DQ_LIP_SEALED = "GENERATE_RESPONSE_DQ_LIP_SEALED";

    /**
     * Registers event {@code GENERATE_RESPONSE_DQ_LIP_SEALED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(GENERATE_RESPONSE_DQ_LIP_SEALED)
            .forAllStates()
            .name("Generate Sealed Form")
            .description("Generates Sealed DQ")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.WLU_ADMIN)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        fields.page("WorkAllocationIntegrationFields");
        fields.readonly(CaseData::getClaimantBilingualLanguagePreference);
        fields.complex(CaseData::getCaseDataLiP)
                    .readonlyNoSummary(CaseDataLiP::getRespondent1LiPResponse).done();
        fields.readonlyNoSummary(CaseData::getPreTranslationDocumentType);
    }
}
