package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code GENERATE_RESPONSE_SEALED} for case type {@code CIVIL}.
 */
@Component
public class GENERATERESPONSESEALED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GENERATE_RESPONSE_SEALED = "GENERATE_RESPONSE_SEALED";

    /**
     * Registers event {@code GENERATE_RESPONSE_SEALED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(GENERATE_RESPONSE_SEALED)
            .forAllStates()
            .name("Generate response sealed form")
            .description("Generates sealed form for claim response")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        fields.page("WAIntegrationFields");
        fields.readonly(CaseData::getPreTranslationDocumentType);
    }
}
