package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code GEN_JUDGMENT_BY_DETERMINATION_DOC_CLAIMANT} for case type {@code CIVIL}.
 */
@Component
public class GENJUDGMENTBYDETERMINATIONDOCCLAIMANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String GEN_JUDGMENT_BY_DETERMINATION_DOC_CLAIMANT = "GEN_JUDGMENT_BY_DETERMINATION_DOC_CLAIMANT";

    /**
     * Registers event {@code GEN_JUDGMENT_BY_DETERMINATION_DOC_CLAIMANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(GEN_JUDGMENT_BY_DETERMINATION_DOC_CLAIMANT)
            .forAllStates()
            .name("Judgment by determination app")
            .description("Gen Judgment By determination claimant")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
