package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.HEARINGFEEUNPAIDWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.HEARINGFEEUNPAIDWorkAllocationPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code HEARING_FEE_UNPAID} for case type {@code CIVIL}.
 */
@Component
public class HEARINGFEEUNPAID implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HEARING_FEE_UNPAID = "HEARING_FEE_UNPAID";

    /**
     * Registers event {@code HEARING_FEE_UNPAID}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(HEARING_FEE_UNPAID)
            .forStateTransition(CaseState.HEARING_READINESS, CaseState.CASE_DISMISSED)
            .name("Case Struck out for unpaid fee")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.JUDGE_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        HEARINGFEEUNPAIDWorkAllocationPage.apply(fields);
        HEARINGFEEUNPAIDWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
