package uk.gov.hmcts.reform.civil.ccd.event;

import uk.gov.hmcts.reform.civil.model.genapplication.GAPbaDetails;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGAHearingDatePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGAPBADetailsGAspecPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGARespondentAgreementPagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGATypePagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGAUploadN245FormPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGAUrgencyRecordPagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdGAWithOrWithoutNoticePagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdHearingDetailsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.INITIATEGENERALAPPLICATIONProdStatementOfTruthPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code INITIATE_GENERAL_APPLICATION} for case type {@code CIVIL}.
 */
@Component
public class INITIATEGENERALAPPLICATIONProd implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INITIATE_GENERAL_APPLICATION = "INITIATE_GENERAL_APPLICATION";

    /**
     * Registers overlay event {@code INITIATE_GENERAL_APPLICATION} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(INITIATE_GENERAL_APPLICATION)
            .forStates(CaseState.CASE_STAYED, CaseState.PENDING_CASE_ISSUED, CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.IN_MEDIATION, CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.DECISION_OUTCOME, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.CASE_DISCONTINUED, CaseState.CASE_SETTLED)
            .name("Make an application")
            .description("Application created, post actions triggered")
            .displayOrder(17)
            .showSummary()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.CITIZEN_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_STAFF)
            .fields();
        INITIATEGENERALAPPLICATIONProdGATypePagePage.apply(fields);
        INITIATEGENERALAPPLICATIONProdGAHearingDatePage.apply(fields);
        INITIATEGENERALAPPLICATIONProdGAUploadN245FormPage.apply(fields);
        INITIATEGENERALAPPLICATIONProdGARespondentAgreementPagePage.apply(fields);
        INITIATEGENERALAPPLICATIONProdGAUrgencyRecordPagePage.apply(fields);
        INITIATEGENERALAPPLICATIONProdGAWithOrWithoutNoticePagePage.apply(fields);
        INITIATEGENERALAPPLICATIONProdStatementOfTruthPage.apply(fields);
        INITIATEGENERALAPPLICATIONProdHearingDetailsPage.apply(fields);
        INITIATEGENERALAPPLICATIONProdGAPBADetailsGAspecPage.apply(fields);
    }
}
