package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodApplicant1PartyPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodApplicant2PartyPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodDefendant1PartyPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodDefendant2PartyPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodExpertsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodLegalRepresentativeIndividualsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodLitigationFriendPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodOrganisationIndividualsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodPartySelectionPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.MANAGECONTACTINFORMATIONNonprodWitnessesPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UpdateDetailsForm;
import uk.gov.hmcts.reform.civil.model.UpdatePartyDetailsForm;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code MANAGE_CONTACT_INFORMATION} for case type {@code CIVIL}.
 */
@Component
public class MANAGECONTACTINFORMATIONNonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_CONTACT_INFORMATION = "MANAGE_CONTACT_INFORMATION";

    /**
     * Registers overlay event {@code MANAGE_CONTACT_INFORMATION} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(MANAGE_CONTACT_INFORMATION)
            .forStates(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.DECISION_OUTCOME, CaseState.IN_MEDIATION, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.CASE_STAYED)
            .name("Manage Contact Information")
            .description("Updated party contact details")
            .displayOrder(99)
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SOLICITOR)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_STAFF, UserRole.GS_PROFILE)
            .fields();
        MANAGECONTACTINFORMATIONNonprodPartySelectionPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodApplicant1PartyPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodApplicant2PartyPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodDefendant1PartyPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodDefendant2PartyPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodOrganisationIndividualsPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodLegalRepresentativeIndividualsPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodExpertsPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodWitnessesPage.apply(fields);
        MANAGECONTACTINFORMATIONNonprodLitigationFriendPage.apply(fields);
        fields.complex(CaseData::getUpdateDetailsForm)
                    .complex(UpdateDetailsForm::getUpdateExpertsDetailsForm, UpdatePartyDetailsForm.class)
                    .mandatory(UpdatePartyDetailsForm::getFirstName)
                    .eventHint("Insert TBC, if expert name not known yet")
                    .mandatory(UpdatePartyDetailsForm::getLastName)
                    .eventHint("Insert TBC, if expert name not known yet")
                    .optional(UpdatePartyDetailsForm::getEmailAddress)
                    .optional(UpdatePartyDetailsForm::getPhoneNumber)
                    .mandatory(UpdatePartyDetailsForm::getFieldOfExpertise).done().done();
        fields.complex(CaseData::getUpdateDetailsForm)
                    .complex(UpdateDetailsForm::getUpdateLRIndividualsForm, UpdatePartyDetailsForm.class)
                    .mandatory(UpdatePartyDetailsForm::getFirstName)
                    .mandatory(UpdatePartyDetailsForm::getLastName)
                    .mandatory(UpdatePartyDetailsForm::getEmailAddress)
                    .eventHint("Please note this will not change your email for notifications")
                    .mandatory(UpdatePartyDetailsForm::getPhoneNumber).done().done();
        fields.complex(CaseData::getUpdateDetailsForm)
                    .complex(UpdateDetailsForm::getUpdateOrgIndividualsForm, UpdatePartyDetailsForm.class)
                    .mandatory(UpdatePartyDetailsForm::getFirstName)
                    .mandatory(UpdatePartyDetailsForm::getLastName)
                    .mandatory(UpdatePartyDetailsForm::getEmailAddress)
                    .mandatory(UpdatePartyDetailsForm::getPhoneNumber).done().done();
        fields.complex(CaseData::getUpdateDetailsForm)
                    .complex(UpdateDetailsForm::getUpdateWitnessesDetailsForm, UpdatePartyDetailsForm.class)
                    .mandatory(UpdatePartyDetailsForm::getFirstName)
                    .eventHint("Insert TBC, if witness name not known yet")
                    .mandatory(UpdatePartyDetailsForm::getLastName)
                    .eventHint("Insert TBC, if witness name not known yet")
                    .optional(UpdatePartyDetailsForm::getEmailAddress)
                    .optional(UpdatePartyDetailsForm::getPhoneNumber).done().done();
    }
}
