package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.LitigationFriend;
import uk.gov.hmcts.reform.civil.model.Party;
import uk.gov.hmcts.reform.civil.model.PartyFlagStructure;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code MANAGE_CASE_FLAGS} for case type {@code CIVIL}.
 */
@Component
public class MANAGECASEFLAGSNonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_CASE_FLAGS = "MANAGE_CASE_FLAGS";

    /**
     * Registers overlay event {@code MANAGE_CASE_FLAGS} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(MANAGE_CASE_FLAGS)
            .forStates(CaseState.PENDING_CASE_ISSUED, CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.CASE_DISMISSED, CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.IN_MEDIATION, CaseState.DECISION_OUTCOME, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.CASE_SETTLED, CaseState.CASE_STAYED)
            .name("Manage case flags")
            .displayOrder(24)
            .showSummary()
            .showEventNotes()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEFLAGS_ADMIN, UserRole.WLU_ADMIN)
            .fields();
        fields.page("ManageCaseFlags");
        fields.pageLabel(" ");
        fields.mandatory(CaseData::getFlagLauncher)
                    .displayContextParameter("#ARGUMENT(UPDATE)")
                    .publish(false);
        fields.optional(CaseData::getCaseFlags)
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue()
                    .publish(false);
        fields.complex(CaseData::getApplicant1)
                    .optional(Party::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicant2)
                    .optional(Party::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent1)
                    .optional(Party::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent2)
                    .optional(Party::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicant1LitigationFriend)
                    .optional(LitigationFriend::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicant2LitigationFriend)
                    .optional(LitigationFriend::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent1LitigationFriend)
                    .optional(LitigationFriend::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent2LitigationFriend)
                    .optional(LitigationFriend::getFlags).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicantWitnesses).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicantWitnesses, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getApplicantExperts).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicantExperts, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent1Witnesses).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent1Witnesses, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent1Experts).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent1Experts, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent2Witnesses).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent2Witnesses, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent2Experts).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent2Experts, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getApplicant1LRIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicant1LRIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent1LRIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent1LRIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent2LRIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent2LRIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getApplicant1OrgIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicant1OrgIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getApplicant2OrgIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getApplicant2OrgIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent1OrgIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent1OrgIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
        fields.complex(CaseData::getRespondent2OrgIndividuals).done()
                    .fieldShowCondition("flagLauncher = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue();
        fields.complex(CaseData::getRespondent2OrgIndividuals, PartyFlagStructure.class)
                    .optional(PartyFlagStructure::getFirstName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getLastName)
                    .eventLabel(" ")
                    .optional(PartyFlagStructure::getFlags)
                    .eventLabel(" ").done();
    }
}
