package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.CaseDataLiP;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code MORE_INFORMATION_HWF} for case type {@code CIVIL}.
 */
@Component
public class MOREINFORMATIONHWF implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MORE_INFORMATION_HWF = "MORE_INFORMATION_HWF";

    /**
     * Registers event {@code MORE_INFORMATION_HWF}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(MORE_INFORMATION_HWF)
            .forStates(CaseState.PENDING_CASE_ISSUED, CaseState.HEARING_READINESS)
            .name("More Information Required HwF")
            .displayOrder(6)
            .showCondition("hwfFeeType = \"CLAIMISSUED\" OR hwfFeeType = \"HEARING\"")
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Permission.CRU, UserRole.CUI_ADMIN_PROFILE)
            .fields();
        fields.page("moreInformationHwf");
        fields.readonly(CaseData::getCaseTitleWithHWFHearingNumber)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .publish(false);
        fields.readonly(CaseData::getHearingFeeLabel)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .publish(false);
        fields.mandatory(CaseData::getHelpWithFeesMoreInformationHearing)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getHearingHelpFeesReferenceNumber)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.complex(CaseData::getCaseDataLiP)
                    .readonlyNoSummary(CaseDataLiP::getHelpWithFees)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false).done();
        fields.readonlyNoSummary(CaseData::getHwfFeeType)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getApplicant1)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getRespondent1)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.readonly(CaseData::getCaseTitleWithHWFClaimFeeNumber)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .publish(false);
        fields.readonly(CaseData::getClaimFeeLabel)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .publish(false);
        fields.mandatory(CaseData::getHelpWithFeesMoreInformationClaimIssue)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .publish(false);
    }
}
