package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.citizenui.HelpWithFeesDetails;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.CaseDataLiP;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NO_REMISSION_HWF} for case type {@code CIVIL}.
 */
@Component
public class NOREMISSIONHWF implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NO_REMISSION_HWF = "NO_REMISSION_HWF";

    /**
     * Registers event {@code NO_REMISSION_HWF}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(NO_REMISSION_HWF)
            .forStates(CaseState.PENDING_CASE_ISSUED, CaseState.HEARING_READINESS)
            .name("No remission HwF")
            .description("No remission HWF")
            .showCondition("hwfFeeType = \"CLAIMISSUED\" OR hwfFeeType = \"HEARING\"")
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Permission.CRU, UserRole.CUI_ADMIN_PROFILE)
            .fields();
        fields.page("NoRemissionHWF");
        fields.readonly(CaseData::getHearingFeeLabel)
                    .fieldShowCondition("hwfFeeType=\"HEARING\"");
        fields.readonly(CaseData::getHearingHelpFeesReferenceNumber)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"");
        fields.readonly(CaseData::getCaseTitleWithHWFHearingNumber)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"");
        fields.complex(CaseData::getHearingHwfDetails)
                    .mandatory(HelpWithFeesDetails::getNoRemissionDetails)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .eventLabel("Details")
                    .mandatory(HelpWithFeesDetails::getNoRemissionDetailsSummary)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .eventLabel("Summary").done();
        fields.complex(CaseData::getCaseDataLiP)
                    .readonly(CaseDataLiP::getHelpWithFees)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"").done();
        fields.readonly(CaseData::getCaseTitleWithHWFClaimFeeNumber)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"");
        fields.complex(CaseData::getClaimIssuedHwfDetails)
                    .mandatory(HelpWithFeesDetails::getNoRemissionDetails)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .eventLabel("Details")
                    .mandatory(HelpWithFeesDetails::getNoRemissionDetailsSummary)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .eventLabel("Summary").done();
        fields.readonly(CaseData::getClaimFeeLabel)
                    .fieldShowCondition("hwfFeeType=\"CLAIMISSUED\"");
        fields.readonly(CaseData::getHwfFeeType)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"");
    }
}
