package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_PROCEEDS_IN_CASEMAN} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYAPPLICANTSOLICITOR1FORCASEPROCEEDSINCASEMAN implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_PROCEEDS_IN_CASEMAN = "NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_PROCEEDS_IN_CASEMAN";

    /**
     * Registers event {@code NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_PROCEEDS_IN_CASEMAN}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_APPLICANT_SOLICITOR1_FOR_CASE_PROCEEDS_IN_CASEMAN)
            .forAllStates()
            .name("Email: Transferred offline")
            .description("Notify applicant solicitor 1 for case proceeds in caseman")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_UNSPEC_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
