package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RPA_ON_CASE_HANDED_OFFLINE} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRPAONCASEHANDEDOFFLINE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RPA_ON_CASE_HANDED_OFFLINE = "NOTIFY_RPA_ON_CASE_HANDED_OFFLINE";

    /**
     * Registers event {@code NOTIFY_RPA_ON_CASE_HANDED_OFFLINE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RPA_ON_CASE_HANDED_OFFLINE)
            .forAllStates()
            .name("Notify RPA on case offline")
            .description("Notify by email with attached RPA JSON to robotics on case handed offline")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
