package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RESPONDENT1_PART_ADMIT_PAY_IMMEDIATELY_AGREED} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRESPONDENT1PARTADMITPAYIMMEDIATELYAGREED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RESPONDENT1_PART_ADMIT_PAY_IMMEDIATELY_AGREED = "NOTIFY_RESPONDENT1_PART_ADMIT_PAY_IMMEDIATELY_AGREED";

    /**
     * Registers event {@code NOTIFY_RESPONDENT1_PART_ADMIT_PAY_IMMEDIATELY_AGREED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RESPONDENT1_PART_ADMIT_PAY_IMMEDIATELY_AGREED)
            .forAllStates()
            .name("Notify Claimant agreed")
            .description("Notify Claimant immediate pay agreed")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE);
    }
}
