package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_LIP_CLAIMANT_CLAIM_SUBMISSION} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYLIPCLAIMANTCLAIMSUBMISSION implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_LIP_CLAIMANT_CLAIM_SUBMISSION = "NOTIFY_LIP_CLAIMANT_CLAIM_SUBMISSION";

    /**
     * Registers event {@code NOTIFY_LIP_CLAIMANT_CLAIM_SUBMISSION}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_LIP_CLAIMANT_CLAIM_SUBMISSION)
            .forAllStates()
            .name("Email Claimant Lip")
            .description("Notify claimant about claim submission if claimant is bilingual")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
