package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RESPONDENT_SOLICITOR2_FOR_CLAIM_ISSUE} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRESPONDENTSOLICITOR2FORCLAIMISSUE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RESPONDENT_SOLICITOR2_FOR_CLAIM_ISSUE = "NOTIFY_RESPONDENT_SOLICITOR2_FOR_CLAIM_ISSUE";

    /**
     * Registers event {@code NOTIFY_RESPONDENT_SOLICITOR2_FOR_CLAIM_ISSUE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RESPONDENT_SOLICITOR2_FOR_CLAIM_ISSUE)
            .forAllStates()
            .name("Email: Notify claim")
            .description("Notify respondent solicitor 2 for claim issue")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
