package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_DEFENDANT_LIP_CLAIMANT_REPRESENTED} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYDEFENDANTLIPCLAIMANTREPRESENTED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_DEFENDANT_LIP_CLAIMANT_REPRESENTED = "NOTIFY_DEFENDANT_LIP_CLAIMANT_REPRESENTED";

    /**
     * Registers event {@code NOTIFY_DEFENDANT_LIP_CLAIMANT_REPRESENTED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_DEFENDANT_LIP_CLAIMANT_REPRESENTED)
            .forAllStates()
            .name("Email: Claimant Represented")
            .description("Notify respondent for claimant represented")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CITIZEN_DEFENDANT_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
