package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_CLAIM_SET_ASIDE_JUDGMENT_CLAIMANT} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYCLAIMSETASIDEJUDGMENTCLAIMANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_CLAIM_SET_ASIDE_JUDGMENT_CLAIMANT = "NOTIFY_CLAIM_SET_ASIDE_JUDGMENT_CLAIMANT";

    /**
     * Registers event {@code NOTIFY_CLAIM_SET_ASIDE_JUDGMENT_CLAIMANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_CLAIM_SET_ASIDE_JUDGMENT_CLAIMANT)
            .forAllStates()
            .name("Notify Set Aside Judgement")
            .description("Notify Set Aside Judgement to claimant ")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF);
    }
}
