package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_APPLICANT_FOR_RECORD_JUDGMENT} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYAPPLICANTFORRECORDJUDGMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_APPLICANT_FOR_RECORD_JUDGMENT = "NOTIFY_APPLICANT_FOR_RECORD_JUDGMENT";

    /**
     * Registers event {@code NOTIFY_APPLICANT_FOR_RECORD_JUDGMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_APPLICANT_FOR_RECORD_JUDGMENT)
            .forAllStates()
            .name("Applicant notification")
            .description("Notify applicant solicitor for record judgment determination means")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF);
    }
}
