package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_OTHER_SOLICITOR_2} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYOTHERSOLICITOR2 implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_OTHER_SOLICITOR_2 = "NOTIFY_OTHER_SOLICITOR_2";

    /**
     * Registers event {@code NOTIFY_OTHER_SOLICITOR_2}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_OTHER_SOLICITOR_2)
            .forAllStates()
            .name("Email: Notify other side NOC")
            .description("Notify Other Solicitor 2")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SOLICITOR);
    }
}
