package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.NOTIFYINTERIMJUDGMENTRespondentResponsePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.NOTIFYINTERIMJUDGMENTWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_INTERIM_JUDGMENT} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYINTERIMJUDGMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_INTERIM_JUDGMENT = "NOTIFY_INTERIM_JUDGMENT";

    /**
     * Registers event {@code NOTIFY_INTERIM_JUDGMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(NOTIFY_INTERIM_JUDGMENT)
            .forStateTransition(EnumSet.allOf(CaseState.class), CaseState.JUDICIAL_REFERRAL)
            .name("Notify Interim Judgement")
            .description("Notify interim judgment")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.GS_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .fields();
        NOTIFYINTERIMJUDGMENTRespondentResponsePage.apply(fields);
        NOTIFYINTERIMJUDGMENTWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
