package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RESPONDENT1_FOR_REQUEST_JUDGEMENT_BY_ADMISSION} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRESPONDENT1FORREQUESTJUDGEMENTBYADMISSION implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RESPONDENT1_FOR_REQUEST_JUDGEMENT_BY_ADMISSION = "NOTIFY_RESPONDENT1_FOR_REQUEST_JUDGEMENT_BY_ADMISSION";

    /**
     * Registers event {@code NOTIFY_RESPONDENT1_FOR_REQUEST_JUDGEMENT_BY_ADMISSION}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RESPONDENT1_FOR_REQUEST_JUDGEMENT_BY_ADMISSION)
            .forAllStates()
            .name("Email: Transferred offline")
            .description("Notify respondent 1 for request judgment by admission")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
