package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RESPONDENT_SOLICITOR_DJ_RECEIVED} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRESPONDENTSOLICITORDJRECEIVED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RESPONDENT_SOLICITOR_DJ_RECEIVED = "NOTIFY_RESPONDENT_SOLICITOR_DJ_RECEIVED";

    /**
     * Registers event {@code NOTIFY_RESPONDENT_SOLICITOR_DJ_RECEIVED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RESPONDENT_SOLICITOR_DJ_RECEIVED)
            .forAllStates()
            .name("Email: Notify DJ")
            .description("Generates default judgment received email")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.JUDGE_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE);
    }
}
