package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_CLAIMANT_FOR_SUCCESSFUL_PAYMENT} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYCLAIMANTFORSUCCESSFULPAYMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_CLAIMANT_FOR_SUCCESSFUL_PAYMENT = "NOTIFY_CLAIMANT_FOR_SUCCESSFUL_PAYMENT";

    /**
     * Registers event {@code NOTIFY_CLAIMANT_FOR_SUCCESSFUL_PAYMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_CLAIMANT_FOR_SUCCESSFUL_PAYMENT)
            .forAllStates()
            .name("Email: claim issued")
            .description("Notify claimant for claim issued")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE, UserRole.CITIZEN_CLAIMANT_PROFILE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE);
    }
}
