package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RESPONSE_TO_QUERY} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRESPONSETOQUERY implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RESPONSE_TO_QUERY = "NOTIFY_RESPONSE_TO_QUERY";

    /**
     * Registers event {@code NOTIFY_RESPONSE_TO_QUERY}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RESPONSE_TO_QUERY)
            .forAllStates()
            .name("Email: Notify query response")
            .description("Notify response to query")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
