package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_RESPONDENT_SOLICITOR2_FOR_COURT_OFFICER_ORDER} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYRESPONDENTSOLICITOR2FORCOURTOFFICERORDER implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_RESPONDENT_SOLICITOR2_FOR_COURT_OFFICER_ORDER = "NOTIFY_RESPONDENT_SOLICITOR2_FOR_COURT_OFFICER_ORDER";

    /**
     * Registers event {@code NOTIFY_RESPONDENT_SOLICITOR2_FOR_COURT_OFFICER_ORDER}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_RESPONDENT_SOLICITOR2_FOR_COURT_OFFICER_ORDER)
            .forAllStates()
            .name("Notify defendant Court Officer")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
