package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_DEFENDANT_STAY_UPDATE_REQUESTED} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYDEFENDANTSTAYUPDATEREQUESTED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_DEFENDANT_STAY_UPDATE_REQUESTED = "NOTIFY_DEFENDANT_STAY_UPDATE_REQUESTED";

    /**
     * Registers event {@code NOTIFY_DEFENDANT_STAY_UPDATE_REQUESTED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_DEFENDANT_STAY_UPDATE_REQUESTED)
            .forAllStates()
            .name("Notify stay Update")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
