package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NOTIFY_DIRECTION_ORDER_DJ_CLAIMANT} for case type {@code CIVIL}.
 */
@Component
public class NOTIFYDIRECTIONORDERDJCLAIMANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOTIFY_DIRECTION_ORDER_DJ_CLAIMANT = "NOTIFY_DIRECTION_ORDER_DJ_CLAIMANT";

    /**
     * Registers event {@code NOTIFY_DIRECTION_ORDER_DJ_CLAIMANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(NOTIFY_DIRECTION_ORDER_DJ_CLAIMANT)
            .forAllStates()
            .name("Notify SDO-DJ Claim")
            .description("Notify SDO DJ to claimant")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
