package uk.gov.hmcts.reform.civil.ccd.event;

import uk.gov.hmcts.reform.civil.model.transferonlinecase.TocTransferCaseReason;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.sdo.ReasonNotSuitableSDO;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code NotSuitable_SDO} for case type {@code CIVIL}.
 */
@Component
public class NotSuitableSDOProd implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NOT_SUITABLE_SDO = "NotSuitable_SDO";

    /**
     * Registers overlay event {@code NotSuitable_SDO} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(NOT_SUITABLE_SDO)
            .forState(CaseState.JUDICIAL_REFERRAL)
            .name("Not suitable for SDO")
            .displayOrder(20)
            .showCondition("detailsOfDirection = \"Only available through tasks\"")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .grant(Permission.CRU, UserRole.JUDGE_PROFILE)
            .fields();
        fields.page("NotSuitableSDO");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA)
                    .fieldShowCondition("reasonNotSuitableSDO=\"DO NOT SHOW IN UI\"");
        fields.readonlyNoSummary(CaseData::getLblTransferCaseDetails)
                    .publish(false);
        fields.readonly(CaseData::getLblReasonNotSuitableSDO)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getNotSuitableSdoOptions);
        fields.complex(CaseData::getTocTransferCaseReason)
                    .readonly(TocTransferCaseReason::getTxtTransferCaseReason)
                    .mandatory(TocTransferCaseReason::getReasonForCaseTransferJudgeTxt).done()
                    .fieldShowCondition("notSuitableSdoOptions = \"CHANGE_LOCATION\"");
        fields.complex(CaseData::getReasonNotSuitableSDO)
                    .readonly(ReasonNotSuitableSDO::getLabel)
                    .readonly(ReasonNotSuitableSDO::getText)
                    .mandatory(ReasonNotSuitableSDO::getInput).done()
                    .fieldShowCondition("notSuitableSdoOptions = \"OTHER_REASONS\"");
    }
}
