package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code ORDER_REVIEW_OBLIGATION_CHECK} for case type {@code CIVIL}.
 */
@Component
public class ORDERREVIEWOBLIGATIONCHECK implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ORDER_REVIEW_OBLIGATION_CHECK = "ORDER_REVIEW_OBLIGATION_CHECK";

    /**
     * Registers event {@code ORDER_REVIEW_OBLIGATION_CHECK}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(ORDER_REVIEW_OBLIGATION_CHECK)
            .forAllStates()
            .name("Order Review Obligation Check")
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL, UserRole.JUDGE_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .fields();
        fields.page("obligationWAFlag");
        fields.complex(CaseData::getObligationWAFlag, false).done();
    }
}
