package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.citizenui.HelpWithFeesDetails;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.CaseDataLiP;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code PARTIAL_REMISSION_HWF_GRANTED} for case type {@code CIVIL}.
 */
@Component
public class PARTIALREMISSIONHWFGRANTED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PARTIAL_REMISSION_HWF_GRANTED = "PARTIAL_REMISSION_HWF_GRANTED";

    /**
     * Registers event {@code PARTIAL_REMISSION_HWF_GRANTED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(PARTIAL_REMISSION_HWF_GRANTED)
            .forStates(CaseState.PENDING_CASE_ISSUED, CaseState.HEARING_READINESS)
            .name("Part remission HwF - granted")
            .description("Part remission HwF granted")
            .showCondition("hwfFeeType = \"CLAIMISSUED\" OR hwfFeeType = \"HEARING\"")
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Permission.CRU, UserRole.CUI_ADMIN_PROFILE)
            .fields();
        fields.page("partRemissionHWF");
        fields.readonly(CaseData::getHearingHelpFeesReferenceNumber)
                    .fieldShowCondition("caseTitleWithHWFHearingNumber=\"DO_NOT_SHOW_IN_UI\"");
        fields.readonly(CaseData::getCaseTitleWithHWFHearingNumber)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"");
        fields.readonly(CaseData::getHearingFeeLabel)
                    .fieldShowCondition("hwfFeeType=\"HEARING\"");
        fields.complex(CaseData::getHearingHwfDetails)
                    .mandatory(HelpWithFeesDetails::getRemissionAmount)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .eventLabel("Remission Amount").done();
        fields.readonly(CaseData::getHwfFeeType)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"");
        fields.complex(CaseData::getCaseDataLiP)
                    .readonlyNoSummary(CaseDataLiP::getHelpWithFees)
                    .fieldShowCondition("caseTitleWithHWFClaimFeeNumber=\"DO_NOT_SHOW_IN_UI\"").done();
        fields.readonly(CaseData::getCaseTitleWithHWFClaimFeeNumber)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"");
        fields.readonly(CaseData::getRemissionFeeAmountWarningMessage);
        fields.readonly(CaseData::getClaimFeeLabel)
                    .fieldShowCondition("hwfFeeType=\"CLAIMISSUED\"");
        fields.complex(CaseData::getClaimIssuedHwfDetails)
                    .mandatory(HelpWithFeesDetails::getRemissionAmount)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .eventLabel("Remission Amount").done();
    }
}
