package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code PROCEEDS_IN_HERITAGE_SYSTEM} for case type {@code CIVIL}.
 */
@Component
public class PROCEEDSINHERITAGESYSTEM implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PROCEEDS_IN_HERITAGE_SYSTEM = "PROCEEDS_IN_HERITAGE_SYSTEM";

    /**
     * Registers event {@code PROCEEDS_IN_HERITAGE_SYSTEM}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(PROCEEDS_IN_HERITAGE_SYSTEM)
            .forStateTransition(EnumSet.allOf(CaseState.class), CaseState.PROCEEDS_IN_HERITAGE_SYSTEM)
            .name("Proceed in heritage system")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        fields.page("WorkAllocationIntegrationFields");
        fields.readonly(CaseData::getRespondent1ClaimResponseTypeForSpec);
        fields.readonly(CaseData::getApplicant1Represented);
        fields.readonly(CaseData::getRespondent1Represented);
    }
}
