package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code PROCESS_PART_ADMISSION_DEFENCE_SPEC} for case type {@code CIVIL}.
 */
@Component
public class PROCESSPARTADMISSIONDEFENCESPEC implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PROCESS_PART_ADMISSION_DEFENCE_SPEC = "PROCESS_PART_ADMISSION_DEFENCE_SPEC";

    /**
     * Registers event {@code PROCESS_PART_ADMISSION_DEFENCE_SPEC}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(PROCESS_PART_ADMISSION_DEFENCE_SPEC)
            .forState(CaseState.PROCEEDS_IN_HERITAGE_SYSTEM)
            .name("Part Admission")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER);
    }
}
