package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.QueryManagementRespondQueryQueryManagementRespondQueryPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.QueryManagementRespondQueryWorkAllocationPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code queryManagementRespondQuery} for case type {@code CIVIL}.
 */
@Component
public class QueryManagementRespondQuery implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String QUERY_MANAGEMENT_RESPOND_QUERY = "queryManagementRespondQuery";

    /**
     * Registers event {@code queryManagementRespondQuery}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(QUERY_MANAGEMENT_RESPOND_QUERY)
            .forAllStates()
            .name("Respond to a query")
            .displayOrder(2)
            .showSummary(false)
            .endButtonLabel("Respond to Query")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CTSC, UserRole.WLU_ADMIN)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.GS_PROFILE, UserRole.JUDGE_PROFILE, UserRole.NATIONAL_BUSINESS_CENTRE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_ONE_UNSPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.RES_SOL_TWO_UNSPEC_PROFILE)
            .fields();
        QueryManagementRespondQueryWorkAllocationPage.apply(fields);
        QueryManagementRespondQueryQueryManagementRespondQueryPage.apply(fields);
    }
}
