package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code REFER_JUDGE_DEFENCE_RECEIVED} for case type {@code CIVIL}.
 */
@Component
public class REFERJUDGEDEFENCERECEIVED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REFER_JUDGE_DEFENCE_RECEIVED = "REFER_JUDGE_DEFENCE_RECEIVED";

    /**
     * Registers event {@code REFER_JUDGE_DEFENCE_RECEIVED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(REFER_JUDGE_DEFENCE_RECEIVED)
            .forState(CaseState.All_FINAL_ORDERS_ISSUED)
            .name("Refer to judge-defended claim")
            .description("Refer to judge (defence received in time)")
            .displayOrder(3)
            .showCondition("joIsLiveJudgmentExists = \"Yes\" AND CaseAccessCategory = \"SPEC_CLAIM\"")
            .showSummary(false)
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF)
            .fields();
        fields.page("ReferJudgeDefenceReceived");
        fields.pageLabel("Refer to judge (defence received in time)");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA)
                    .fieldShowCondition("confirmReferToJudgeDefenceReceived=\"DO NOT SHOW IN UI\"");
        fields.readonlyNoSummary(CaseData::getLblRecordJudgment)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getJoPartiesNames)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getConfirmReferToJudgeDefenceReceived)
                    .publish(false);
    }
}
