package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code REQUEST_FOR_RECONSIDERATION_DEADLINE_CHECK} for case type {@code CIVIL}.
 */
@Component
public class REQUESTFORRECONSIDERATIONDEADLINECHECK implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REQUEST_FOR_RECONSIDERATION_DEADLINE_CHECK = "REQUEST_FOR_RECONSIDERATION_DEADLINE_CHECK";

    /**
     * Registers event {@code REQUEST_FOR_RECONSIDERATION_DEADLINE_CHECK}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(REQUEST_FOR_RECONSIDERATION_DEADLINE_CHECK)
            .forAllStates()
            .name("Request for reconsideration")
            .description("Request for reconsideration check")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.CITIZEN_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
