package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code RESUBMIT_CLAIM} for case type {@code CIVIL}.
 */
@Component
public class RESUBMITCLAIM implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RESUBMIT_CLAIM = "RESUBMIT_CLAIM";

    /**
     * Registers event {@code RESUBMIT_CLAIM}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(RESUBMIT_CLAIM)
            .forState(CaseState.PENDING_CASE_ISSUED)
            .name("Resubmit claim")
            .description("Resubmits claim for unsuccessful PBA payment")
            .displayOrder(11)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.LEGAL_ADVISER)
            .fields();
        fields.page("ResubmitClaim");
        fields.complex(CaseData::getClaimFee, false).done();
        fields.mandatory(CaseData::getApplicantSolicitor1PbaAccounts)
                    .caseEventFieldLabel("PBA number");
        fields.readonlyNoSummary(CaseData::getPbaPaymentFailedLabel);
    }
}
