package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code RETRIGGER_NOTIFY_INTERIM_JUDGMENT_DEFENDANT} for case type {@code CIVIL}.
 */
@Component
public class RETRIGGERNOTIFYINTERIMJUDGMENTDEFENDANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RETRIGGER_NOTIFY_INTERIM_JUDGMENT_DEFENDANT = "RETRIGGER_NOTIFY_INTERIM_JUDGMENT_DEFENDANT";

    /**
     * Registers event {@code RETRIGGER_NOTIFY_INTERIM_JUDGMENT_DEFENDANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(RETRIGGER_NOTIFY_INTERIM_JUDGMENT_DEFENDANT)
            .forAllStates()
            .name("Retrigger notify interim DJ")
            .displayOrder(1)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
