package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code REVIEW_HEARING_EXCEPTION} for case type {@code CIVIL}.
 */
@Component
public class REVIEWHEARINGEXCEPTION implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REVIEW_HEARING_EXCEPTION = "REVIEW_HEARING_EXCEPTION";

    /**
     * Registers event {@code REVIEW_HEARING_EXCEPTION}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(REVIEW_HEARING_EXCEPTION)
            .forAllStates()
            .name("Review hearing exception")
            .description("Triggered when hearing is in an EXCEPTION state")
            .displayOrder(1)
            .showSummary()
            .endButtonLabel("Submit")
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        fields.page("FeatureToggleWA");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA);
    }
}
