package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SEND_TRANSLATED_ORDER_TO_LIP_DEFENDANT} for case type {@code CIVIL}.
 */
@Component
public class SENDTRANSLATEDORDERTOLIPDEFENDANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_TRANSLATED_ORDER_TO_LIP_DEFENDANT = "SEND_TRANSLATED_ORDER_TO_LIP_DEFENDANT";

    /**
     * Registers event {@code SEND_TRANSLATED_ORDER_TO_LIP_DEFENDANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(SEND_TRANSLATED_ORDER_TO_LIP_DEFENDANT)
            .forAllStates()
            .name("Send translated order")
            .description("Bulk print translated order claimant")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
