package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SEND_HEARING_TO_LIP_DEFENDANT} for case type {@code CIVIL}.
 */
@Component
public class SENDHEARINGTOLIPDEFENDANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_HEARING_TO_LIP_DEFENDANT = "SEND_HEARING_TO_LIP_DEFENDANT";

    /**
     * Registers event {@code SEND_HEARING_TO_LIP_DEFENDANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(SEND_HEARING_TO_LIP_DEFENDANT)
            .forAllStates()
            .name("Send hearing to Defendant")
            .description("Bulk Email Send to Defendant")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE, UserRole.WLU_ADMIN);
    }
}
