package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SEND_SDO_ORDER_TO_LIP_CLAIMANT} for case type {@code CIVIL}.
 */
@Component
public class SENDSDOORDERTOLIPCLAIMANT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_SDO_ORDER_TO_LIP_CLAIMANT = "SEND_SDO_ORDER_TO_LIP_CLAIMANT";

    /**
     * Registers event {@code SEND_SDO_ORDER_TO_LIP_CLAIMANT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(SEND_SDO_ORDER_TO_LIP_CLAIMANT)
            .forAllStates()
            .name("Send SDO order to Claimant.")
            .description("Send SDO order to Claimant")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE);
    }
}
