package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.SENDANDREPLYProdReplyToMessagePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SENDANDREPLYProdSendAndReplyOptionPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SENDANDREPLYProdSendMessageContentPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SENDANDREPLYProdSendMessageMetadataPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SENDANDREPLYProdWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SEND_AND_REPLY} for case type {@code CIVIL}.
 */
@Component
public class SENDANDREPLYProd implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_AND_REPLY = "SEND_AND_REPLY";

    /**
     * Registers overlay event {@code SEND_AND_REPLY} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (!EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(SEND_AND_REPLY)
            .forStates(CaseState.PENDING_CASE_ISSUED, CaseState.CASE_ISSUED, CaseState.AWAITING_CASE_DETAILS_NOTIFICATION, CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.CASE_PROGRESSION, CaseState.All_FINAL_ORDERS_ISSUED, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.JUDICIAL_REFERRAL, CaseState.CASE_SETTLED, CaseState.CLOSED, CaseState.CASE_DISCONTINUED, CaseState.HEARING_READINESS, CaseState.CASE_STAYED, CaseState.DECISION_OUTCOME)
            .name("Send and reply to messages")
            .displayOrder(25)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.JUDGE_PROFILE, UserRole.WLU_ADMIN)
            .fields();
        SENDANDREPLYProdSendAndReplyOptionPage.apply(fields);
        SENDANDREPLYProdSendMessageMetadataPage.apply(fields);
        SENDANDREPLYProdSendMessageContentPage.apply(fields);
        SENDANDREPLYProdReplyToMessagePage.apply(fields);
        SENDANDREPLYProdWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
