package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SEND_JUDGMENT_DETAILS_CJES_SA} for case type {@code CIVIL}.
 */
@Component
public class SENDJUDGMENTDETAILSCJESSA implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_JUDGMENT_DETAILS_CJES_SA = "SEND_JUDGMENT_DETAILS_CJES_SA";

    /**
     * Registers event {@code SEND_JUDGMENT_DETAILS_CJES_SA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(SEND_JUDGMENT_DETAILS_CJES_SA)
            .forAllStates()
            .name("Send judgment CJES Set aside")
            .description(" ")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
