package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SERVICE_REQUEST_RECEIVED} for case type {@code CIVIL}.
 */
@Component
public class SERVICEREQUESTRECEIVED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SERVICE_REQUEST_RECEIVED = "SERVICE_REQUEST_RECEIVED";

    /**
     * Registers event {@code SERVICE_REQUEST_RECEIVED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(SERVICE_REQUEST_RECEIVED)
            .forAllStates()
            .name("Update hearing fee status")
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.GS_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE);
    }
}
