package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.SETTLECLAIMMARKPAIDFULLNonprodMultipleClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SETTLECLAIMMARKPAIDFULLNonprodOptionsForSettlementPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SETTLECLAIMMARKPAIDFULLNonprodSingleClaimantPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.SETTLECLAIMMARKPAIDFULLNonprodWorkAllocationPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code SETTLE_CLAIM_MARK_PAID_FULL} for case type {@code CIVIL}.
 */
@Component
public class SETTLECLAIMMARKPAIDFULLNonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SETTLE_CLAIM_MARK_PAID_FULL = "SETTLE_CLAIM_MARK_PAID_FULL";

    /**
     * Registers overlay event {@code SETTLE_CLAIM_MARK_PAID_FULL} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(SETTLE_CLAIM_MARK_PAID_FULL)
            .forStates(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.IN_MEDIATION, CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.DECISION_OUTCOME, CaseState.All_FINAL_ORDERS_ISSUED)
            .name("Settle this claim")
            .displayOrder(13)
            .showSummary()
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.APP_SOL_SPEC_PROFILE, UserRole.APP_SOL_UNSPEC_PROFILE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF, UserRole.JUDGE_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE)
            .fields();
        SETTLECLAIMMARKPAIDFULLNonprodWorkAllocationPage.apply(fields);
        SETTLECLAIMMARKPAIDFULLNonprodOptionsForSettlementPage.apply(fields);
        SETTLECLAIMMARKPAIDFULLNonprodMultipleClaimantPage.apply(fields);
        SETTLECLAIMMARKPAIDFULLNonprodSingleClaimantPage.apply(fields);
    }
}
