package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code TRIGGER_TASK_RECONFIG_GA} for case type {@code CIVIL}.
 */
@Component
public class TRIGGERTASKRECONFIGGA implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TRIGGER_TASK_RECONFIG_GA = "TRIGGER_TASK_RECONFIG_GA";

    /**
     * Registers event {@code TRIGGER_TASK_RECONFIG_GA}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(TRIGGER_TASK_RECONFIG_GA)
            .forAllStates()
            .name("Update ga cases location")
            .description("Trigger event to reconfigure ga cases")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        fields.page("WorkAllocation");
        fields.showCondition("gaDraftDocRespondentSolTwo=\"DO NOT SHOW IN UI\"");
        fields.readonlyNoSummary(CaseData::getGaEaCourtLocation);
        fields.readonlyNoSummary(CaseData::getGaDraftDocRespondentSolTwo)
                    .publish(false);
    }
}
