package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code TRIGGER_APPLICATION_CLOSURE} for case type {@code CIVIL}.
 */
@Component
public class TRIGGERAPPLICATIONCLOSURE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TRIGGER_APPLICATION_CLOSURE = "TRIGGER_APPLICATION_CLOSURE";

    /**
     * Registers event {@code TRIGGER_APPLICATION_CLOSURE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(TRIGGER_APPLICATION_CLOSURE)
            .forAllStates()
            .name("Trigger Application Closure")
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_STAFF);
    }
}
