package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.UPDATECLAIMANTINTENTIONCLAIMSTATEWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.UPDATECLAIMANTINTENTIONCLAIMSTATEWorkAllocationPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code UPDATE_CLAIMANT_INTENTION_CLAIM_STATE} for case type {@code CIVIL}.
 */
@Component
public class UPDATECLAIMANTINTENTIONCLAIMSTATE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_CLAIMANT_INTENTION_CLAIM_STATE = "UPDATE_CLAIMANT_INTENTION_CLAIM_STATE";

    /**
     * Registers event {@code UPDATE_CLAIMANT_INTENTION_CLAIM_STATE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(UPDATE_CLAIMANT_INTENTION_CLAIM_STATE)
            .forAllStates()
            .name("Update claim state")
            .showCondition("CaseAccessCategory=\"DO_NOT_SHOW_IN_UI\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SOLICITOR, UserRole.JUDGE_PROFILE)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        UPDATECLAIMANTINTENTIONCLAIMSTATEWorkAllocationPage.apply(fields);
        UPDATECLAIMANTINTENTIONCLAIMSTATEWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
