package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.UPDATECLAIMSTATEAFTERDOCUPLOADEDWorkAllocationIntegrationFieldsPage;
import uk.gov.hmcts.reform.civil.ccd.event.page.UPDATECLAIMSTATEAFTERDOCUPLOADEDWorkAllocationPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code UPDATE_CLAIM_STATE_AFTER_DOC_UPLOADED} for case type {@code CIVIL}.
 */
@Component
public class UPDATECLAIMSTATEAFTERDOCUPLOADED implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_CLAIM_STATE_AFTER_DOC_UPLOADED = "UPDATE_CLAIM_STATE_AFTER_DOC_UPLOADED";

    /**
     * Registers event {@code UPDATE_CLAIM_STATE_AFTER_DOC_UPLOADED}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(UPDATE_CLAIM_STATE_AFTER_DOC_UPLOADED)
            .forAllStates()
            .name("Update claim state")
            .showCondition("CaseAccessCategory=\"DO_NOT_SHOW_IN_UI\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_CIVIL_STAFF, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.CUI_ADMIN_PROFILE, UserRole.JUDGE_PROFILE, UserRole.WLU_ADMIN)
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_SYSTEMUPDATE)
            .fields();
        UPDATECLAIMSTATEAFTERDOCUPLOADEDWorkAllocationPage.apply(fields);
        UPDATECLAIMSTATEAFTERDOCUPLOADEDWorkAllocationIntegrationFieldsPage.apply(fields);
    }
}
