package uk.gov.hmcts.reform.civil.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.CaseDataLiP;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code UPLOAD_TRANSLATED_DOCUMENT} for case type {@code CIVIL}.
 */
@Component
public class UPLOADTRANSLATEDDOCUMENT implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_TRANSLATED_DOCUMENT = "UPLOAD_TRANSLATED_DOCUMENT";

    /**
     * Registers event {@code UPLOAD_TRANSLATED_DOCUMENT}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        var fields = builder.event(UPLOAD_TRANSLATED_DOCUMENT)
            .forAllStates()
            .name("Upload translated document")
            .description("Upload Translated Document")
            .displayOrder(3)
            .showCondition("CaseAccessCategory=\"SPEC_CLAIM1\"")
            .showSummary()
            .showEventNotes()
            .endButtonLabel("Submit")
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CUI_ADMIN_PROFILE, UserRole.WLU_ADMIN)
            .grant(Set.of(Permission.R), UserRole.APP_SOL_SPEC_PROFILE, UserRole.CITIZEN_CLAIMANT_PROFILE, UserRole.CITIZEN_DEFENDANT_PROFILE, UserRole.RES_SOL_ONE_SPEC_PROFILE, UserRole.RES_SOL_TWO_SPEC_PROFILE)
            .fields();
        fields.page("UploadTranslatedDocument");
        fields.complex(CaseData::getCaseDataLiP)
                    .optional(CaseDataLiP::getTranslatedDocuments)
                    .caseEventFieldLabel("Translated Document").done();
    }
}
