package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.civil.ccd.event.page.VALIDATEDISCONTINUECLAIMCLAIMANTNonprodValidateDiscontinuancePage;
import uk.gov.hmcts.reform.civil.ccd.event.page.VALIDATEDISCONTINUECLAIMCLAIMANTNonprodWorkAllocationPage;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.EnvironmentFlags;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code VALIDATE_DISCONTINUE_CLAIM_CLAIMANT} for case type {@code CIVIL}.
 */
@Component
public class VALIDATEDISCONTINUECLAIMCLAIMANTNonprod implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String VALIDATE_DISCONTINUE_CLAIM_CLAIMANT = "VALIDATE_DISCONTINUE_CLAIM_CLAIMANT";

    /**
     * Registers overlay event {@code VALIDATE_DISCONTINUE_CLAIM_CLAIMANT} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(VALIDATE_DISCONTINUE_CLAIM_CLAIMANT)
            .forStates(CaseState.AWAITING_RESPONDENT_ACKNOWLEDGEMENT, CaseState.JUDGMENT_REQUESTED, CaseState.AWAITING_APPLICANT_INTENTION, CaseState.IN_MEDIATION, CaseState.JUDICIAL_REFERRAL, CaseState.CASE_PROGRESSION, CaseState.HEARING_READINESS, CaseState.PREPARE_FOR_HEARING_CONDUCT_HEARING, CaseState.DECISION_OUTCOME)
            .name("Validate discontinuance")
            .displayOrder(15)
            .showCondition("isPermissionGranted = \"YES\"")
            .showSummary(false)
            .publishToCamunda()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_CIVIL_ADMIN, UserRole.CASEWORKER_CIVIL_STAFF)
            .fields();
        VALIDATEDISCONTINUECLAIMCLAIMANTNonprodWorkAllocationPage.apply(fields);
        VALIDATEDISCONTINUECLAIMCLAIMANTNonprodValidateDiscontinuancePage.apply(fields);
    }
}
