package uk.gov.hmcts.reform.civil.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Event {@code VIEW_AND_RESPOND_TO_DEFENCE} for case type {@code CIVIL}.
 */
@Component
public class VIEWANDRESPONDTODEFENCE implements CCDConfig<CaseData, CaseState, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String VIEW_AND_RESPOND_TO_DEFENCE = "VIEW_AND_RESPOND_TO_DEFENCE";

    /**
     * Registers event {@code VIEW_AND_RESPOND_TO_DEFENCE}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<CaseData, CaseState, UserRole> builder) {
        builder.event(VIEW_AND_RESPOND_TO_DEFENCE)
            .forAllStates()
            .name("View And Respond To Defence")
            .displayOrder(18)
            .showSummary()
            .publishToCamunda()
            .explicitGrants();
    }
}
