{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-http-cio",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-metadata-2.3.8.jar",
          "url": "ktor-http-cio-2.3.8.jar",
          "size": 15528,
          "sha512": "607fc870e1942f583572e6a58d683539b398df6680e8d9c8d9aa2336b34f820c27dce4dbf3721580689457c1507343161b0493cdeed2873d5079822fc3995983",
          "sha256": "8075acc615c347be9134323ce27e6af856817650c6e8ff82b73dac62ae13af86",
          "sha1": "2b508e5d82a46255ed84707df2ab0dcd49fdbe65",
          "md5": "2adc6d94d458a57f5e91169c9dfa1952"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-http-cio-kotlin-2.3.8-sources.jar",
          "url": "ktor-http-cio-2.3.8-sources.jar",
          "size": 20607,
          "sha512": "e3d14133cd8a6a89d280f41b95be4a6b2620a83304285b76b4374d4babb37b6f142bbfad9f1e20c78d90ff997a82b8b53edc64fb460e8eeeea902f03937e4438",
          "sha256": "f22594f62f55f31b9adfceeb2095445329782350cfcebaa5252320230ff2d2e5",
          "sha1": "c5b410c3096af491999584b2b07f5cf41518d975",
          "md5": "98ac21bd1181c92904030357235ad922"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosarm64/2.3.8/ktor-http-cio-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosarm64/2.3.8/ktor-http-cio-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosarm64/2.3.8/ktor-http-cio-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iossimulatorarm64/2.3.8/ktor-http-cio-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iossimulatorarm64/2.3.8/ktor-http-cio-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iossimulatorarm64/2.3.8/ktor-http-cio-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosx64/2.3.8/ktor-http-cio-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosx64/2.3.8/ktor-http-cio-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-iosx64/2.3.8/ktor-http-cio-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-js/2.3.8/ktor-http-cio-js-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-js",
        "version": "2.3.8"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-js/2.3.8/ktor-http-cio-js-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-js",
        "version": "2.3.8"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-cio-js/2.3.8/ktor-http-cio-js-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-js",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-cio-jvm/2.3.8/ktor-http-cio-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-cio-jvm/2.3.8/ktor-http-cio-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-cio-jvm/2.3.8/ktor-http-cio-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxarm64/2.3.8/ktor-http-cio-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxarm64/2.3.8/ktor-http-cio-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxx64/2.3.8/ktor-http-cio-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-linuxx64/2.3.8/ktor-http-cio-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosarm64/2.3.8/ktor-http-cio-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosarm64/2.3.8/ktor-http-cio-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosarm64/2.3.8/ktor-http-cio-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosx64/2.3.8/ktor-http-cio-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosx64/2.3.8/ktor-http-cio-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-macosx64/2.3.8/ktor-http-cio-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-mingwx64/2.3.8/ktor-http-cio-mingwx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-mingwx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-mingwx64/2.3.8/ktor-http-cio-mingwx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-mingwx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosarm64/2.3.8/ktor-http-cio-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosarm64/2.3.8/ktor-http-cio-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosarm64/2.3.8/ktor-http-cio-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvossimulatorarm64/2.3.8/ktor-http-cio-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvossimulatorarm64/2.3.8/ktor-http-cio-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvossimulatorarm64/2.3.8/ktor-http-cio-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosx64/2.3.8/ktor-http-cio-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosx64/2.3.8/ktor-http-cio-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-tvosx64/2.3.8/ktor-http-cio-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm32/2.3.8/ktor-http-cio-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm32/2.3.8/ktor-http-cio-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm32/2.3.8/ktor-http-cio-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm64/2.3.8/ktor-http-cio-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm64/2.3.8/ktor-http-cio-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosarm64/2.3.8/ktor-http-cio-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchossimulatorarm64/2.3.8/ktor-http-cio-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchossimulatorarm64/2.3.8/ktor-http-cio-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchossimulatorarm64/2.3.8/ktor-http-cio-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosx64/2.3.8/ktor-http-cio-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosx64/2.3.8/ktor-http-cio-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-cio-watchosx64/2.3.8/ktor-http-cio-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-http-cio-watchosx64",
        "version": "2.3.8"
      }
    }
  ]
}
