{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "send-letter-client",
    "version": "5.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "send-letter-client-5.1.1.jar",
          "url": "send-letter-client-5.1.1.jar",
          "size": 22083,
          "sha512": "59b5219b7d61027c21777cf2ce3d775dcb604f43b0d114038cfed451782c5e4c4c16a5a7e39d3bcaca34b7eee6a54a85077c9ef25e1fddd554a44f7f6f065e27",
          "sha256": "96546035519a6bff7bafc825c63cdb40add4b400ccd7e198fd2ee893a30f45a0",
          "sha1": "d64f2906c9c9bc343f68cf4b0e867cadd8792227",
          "md5": "d4bc6d92f7073756c1d17647dc2ee58f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator"
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "4.3.0"
          }
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "13.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.12"
          }
        }
      ],
      "files": [
        {
          "name": "send-letter-client-5.1.1.jar",
          "url": "send-letter-client-5.1.1.jar",
          "size": 22083,
          "sha512": "59b5219b7d61027c21777cf2ce3d775dcb604f43b0d114038cfed451782c5e4c4c16a5a7e39d3bcaca34b7eee6a54a85077c9ef25e1fddd554a44f7f6f065e27",
          "sha256": "96546035519a6bff7bafc825c63cdb40add4b400ccd7e198fd2ee893a30f45a0",
          "sha1": "d64f2906c9c9bc343f68cf4b0e867cadd8792227",
          "md5": "d4bc6d92f7073756c1d17647dc2ee58f"
        }
      ]
    }
  ]
}
