{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts.java-logging",
    "module": "logging",
    "version": "8.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-8.0.0.jar",
          "url": "logging-8.0.0.jar",
          "size": 1491,
          "sha512": "ab982f87d662bb02959a7b1d18d15858de206bf9cd7ec544aa3f34de628c7a8702ba8e0b8e9e490890c45047d81dfe05f1afbef4101ba225fe8c9e2efa96684e",
          "sha256": "f544cf9137c0885556ab06ff921eda0c645d93a3216e303ca3c095de6f80d9bb",
          "sha1": "df210fae5856dee8534c7990ce525785b3f82ad4",
          "md5": "6409c4e605c664e703db04ca1f8249f2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-8.0.0.jar",
          "url": "logging-8.0.0.jar",
          "size": 1491,
          "sha512": "ab982f87d662bb02959a7b1d18d15858de206bf9cd7ec544aa3f34de628c7a8702ba8e0b8e9e490890c45047d81dfe05f1afbef4101ba225fe8c9e2efa96684e",
          "sha256": "f544cf9137c0885556ab06ff921eda0c645d93a3216e303ca3c095de6f80d9bb",
          "sha1": "df210fae5856dee8534c7990ce525785b3f82ad4",
          "md5": "6409c4e605c664e703db04ca1f8249f2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-8.0.0-javadoc.jar",
          "url": "logging-8.0.0-javadoc.jar",
          "size": 261,
          "sha512": "300427c7de24e1a6e5a028f1ace48b866392be76981c79efd21e8f146b635a5d9757ad2821450eb3cd40024073ccccb5b236f5c52f93d3ffff0703aabc25db09",
          "sha256": "bd1a207ef8ad88ae90b43fb96d9e601303b46cd64d489c9c20ef407d02f87ebf",
          "sha1": "0b0880939d7872aaacecaaa30287be56d1ae1e50",
          "md5": "302ed697e6dd4597ee580f64cd0cb71d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-8.0.0-sources.jar",
          "url": "logging-8.0.0-sources.jar",
          "size": 1491,
          "sha512": "309058df8d70b2f99c45078593b9e80aebd6c8910cd3ab1ef06fdd85bfed67558e2d4af9f5dfcdb0960a0ae0000963f94c39326d3c012833ddd41c83c8f142cb",
          "sha256": "54d5871735527ec8cdc332ac4c81e6fd880d7e6c6d46d9228b854060cd7b6b51",
          "sha1": "0c10c00d7ccb9f0bea219b7d88e3900d4ef799f4",
          "md5": "8aa044d32c2297755d28b4c82050cd87"
        }
      ]
    }
  ]
}
