{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.3.7.jar",
          "url": "spring-boot-starter-web-3.3.7.jar",
          "size": 4804,
          "sha512": "1e97f730a7e533859629a7004f7d70db62dcd0640b666a817b857a4fbfb68030e3d77d44d1bbbcaf37c93077385059c9ccfed62af69c0e5bb7c68e433c57cd55",
          "sha256": "21804a95d783768aca38d9347e955b97bfbd47a0b1232a188da767159c233634",
          "sha1": "75a362710036e1e597fb92df9f793561517cc821",
          "md5": "802493d36f068e8a167bfe64f4de8b73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.3.7.jar",
          "url": "spring-boot-starter-web-3.3.7.jar",
          "size": 4804,
          "sha512": "1e97f730a7e533859629a7004f7d70db62dcd0640b666a817b857a4fbfb68030e3d77d44d1bbbcaf37c93077385059c9ccfed62af69c0e5bb7c68e433c57cd55",
          "sha256": "21804a95d783768aca38d9347e955b97bfbd47a0b1232a188da767159c233634",
          "sha1": "75a362710036e1e597fb92df9f793561517cc821",
          "md5": "802493d36f068e8a167bfe64f4de8b73"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-web-3.3.7-javadoc.jar",
          "size": 4804,
          "sha512": "7796b3a8ece4cdb2ffe82127d5079b59753c81b29757222d99973d8ce2d4c9ee0335a12443d9747cd4f238c9b729ce49e2578de25f608c0eafe6a44e0478649f",
          "sha256": "7f037027dc8b93d4803f1e38a0624e595a0a525f20d0a7e6836ba3b612f9b1a3",
          "sha1": "77c80fee8cb3c46aa1f8b07a9fb1b1c4cfdab333",
          "md5": "2f88f02a68e629a49e702cc7022809c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.3.7-sources.jar",
          "url": "spring-boot-starter-web-3.3.7-sources.jar",
          "size": 4804,
          "sha512": "7796b3a8ece4cdb2ffe82127d5079b59753c81b29757222d99973d8ce2d4c9ee0335a12443d9747cd4f238c9b729ce49e2578de25f608c0eafe6a44e0478649f",
          "sha256": "7f037027dc8b93d4803f1e38a0624e595a0a525f20d0a7e6836ba3b612f9b1a3",
          "sha1": "77c80fee8cb3c46aa1f8b07a9fb1b1c4cfdab333",
          "md5": "2f88f02a68e629a49e702cc7022809c9"
        }
      ]
    }
  ]
}
