{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.17.3.jar",
          "url": "jackson-dataformat-yaml-2.17.3.jar",
          "size": 54271,
          "sha512": "44c0060d0ea5e28785c5eb9d45e33409899da382b7d4b3530c4670499dc99c954ad3c3e09b3a08d6e397807d00c0af6620a98b67f94083e8c3bc8f6bae8fe4c0",
          "sha256": "67fdc75e8bec5a9862289385ed6c26f5ae494cd34e1ae46d882f500b67dbae2e",
          "sha1": "17f151f8efb2ee42ea22e780beaaa81770dbcfbe",
          "md5": "18211520623002e70dd9301d022a4f8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.17.3.jar",
          "url": "jackson-dataformat-yaml-2.17.3.jar",
          "size": 54271,
          "sha512": "44c0060d0ea5e28785c5eb9d45e33409899da382b7d4b3530c4670499dc99c954ad3c3e09b3a08d6e397807d00c0af6620a98b67f94083e8c3bc8f6bae8fe4c0",
          "sha256": "67fdc75e8bec5a9862289385ed6c26f5ae494cd34e1ae46d882f500b67dbae2e",
          "sha1": "17f151f8efb2ee42ea22e780beaaa81770dbcfbe",
          "md5": "18211520623002e70dd9301d022a4f8c"
        }
      ]
    }
  ]
}
