{
  "formatVersion": "1.1",
  "component": {
    "group": "au.com.dius.pact.core",
    "module": "support",
    "version": "4.6.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "support-4.6.17.jar",
          "url": "support-4.6.17.jar",
          "size": 229702,
          "sha512": "8f15f4a73aa0b691272775c8dfc9639adbef85a57d66381af32b4014129cbbb4007babe93c0ff3b5bc7e4e91314670db7be1de7072c0cccdbb8ecc692468ed30",
          "sha256": "f64e501f0ee4635334c5bb7ebf3458c94e6e1250b2378060e3dae3258049e93a",
          "sha1": "8fb4834cfd07fa6e663cfda84b1ee1ce2d5d8a23",
          "md5": "0346baa79466f5903f7712df12917cf6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text"
        },
        {
          "group": "commons-codec",
          "module": "commons-codec"
        },
        {
          "group": "com.github.mifmif",
          "module": "generex",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5"
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-jvm",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls-certificates",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.108.Final"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        }
      ],
      "files": [
        {
          "name": "support-4.6.17.jar",
          "url": "support-4.6.17.jar",
          "size": 229702,
          "sha512": "8f15f4a73aa0b691272775c8dfc9639adbef85a57d66381af32b4014129cbbb4007babe93c0ff3b5bc7e4e91314670db7be1de7072c0cccdbb8ecc692468ed30",
          "sha256": "f64e501f0ee4635334c5bb7ebf3458c94e6e1250b2378060e3dae3258049e93a",
          "sha1": "8fb4834cfd07fa6e663cfda84b1ee1ce2d5d8a23",
          "md5": "0346baa79466f5903f7712df12917cf6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "support-4.6.17-javadoc.jar",
          "url": "support-4.6.17-javadoc.jar",
          "size": 850139,
          "sha512": "c3167eb93c5f65c63126c3d7aac09b8a16fa7db3a9c2f25a37e2fa059b2b733623fe6fc92a998fe9d6a26776f9e52a38607428b485c4293712a607d879561d25",
          "sha256": "a02ae1b715210e8dd2e2e4cafecc59f7b683e493323ad64334cf315cd65eb95c",
          "sha1": "90f0b6b5a302c74d7e7e397d28db8d22792d410a",
          "md5": "67b05dca5307b140238376daed228448"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "support-4.6.17-sources.jar",
          "url": "support-4.6.17-sources.jar",
          "size": 34942,
          "sha512": "e80f2ade866dd040f35d99859c4ba3527715a527474bae1f237846c9807feb0dae8a29822ef507bd9c1f036c5e5f62e799be2dd4a91b55d94dd9707b9a1ee85f",
          "sha256": "fa794d104b3a6ac3397f5b2b0fe8a907f258b39de32ef2dd45d83eded5cea65b",
          "sha1": "7cd7fe7307916095e3e67ad2c8198167659eaec1",
          "md5": "6e934e9d3a8f11b16d3701bdd796c2da"
        }
      ]
    }
  ]
}
