{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-bom",
    "version": "2020.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.24"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.4.24"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-tools",
          "version": {
            "requires": "3.4.24"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-extra",
          "version": {
            "requires": "3.4.8"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-adapter",
          "version": {
            "requires": "3.4.8"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http-brave",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-pool",
          "version": {
            "requires": "0.2.10"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "io.projectreactor.rabbitmq",
          "module": "reactor-rabbitmq",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.7"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.4.24"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-test",
          "version": {
            "requires": "3.4.24"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-tools",
          "version": {
            "requires": "3.4.24"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-extra",
          "version": {
            "requires": "3.4.8"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-adapter",
          "version": {
            "requires": "3.4.8"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-core",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.netty",
          "module": "reactor-netty-http-brave",
          "version": {
            "requires": "1.0.24"
          }
        },
        {
          "group": "io.projectreactor.addons",
          "module": "reactor-pool",
          "version": {
            "requires": "0.2.10"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.13"
          }
        },
        {
          "group": "io.projectreactor.rabbitmq",
          "module": "reactor-rabbitmq",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "io.projectreactor.kotlin",
          "module": "reactor-kotlin-extensions",
          "version": {
            "requires": "1.1.7"
          }
        }
      ]
    }
  ]
}
