{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-network-tls-certificates",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-certificates-metadata-2.3.8.jar",
          "url": "ktor-network-tls-certificates-2.3.8.jar",
          "size": 690,
          "sha512": "797b75ef9187d0b7d09476f2b295f5597dba1161a9a1d95a0d413caaec632fe22346187568dd7480be0338d83be78830650668ae7333f63c9e78557402f802c3",
          "sha256": "5a46fdbc40fd2d78259883c4cc6eaf3b5e290dd07d1c46ea88eea3d48f505772",
          "sha1": "a780e883e5dd45c39b3b5482e14dbced38d83914",
          "md5": "21cc23e38423fad472d2d83683aaea9b"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-network-tls-certificates-kotlin-2.3.8-sources.jar",
          "url": "ktor-network-tls-certificates-2.3.8-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-tls-certificates-jvm/2.3.8/ktor-network-tls-certificates-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tls-certificates-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-tls-certificates-jvm/2.3.8/ktor-network-tls-certificates-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tls-certificates-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-tls-certificates-jvm/2.3.8/ktor-network-tls-certificates-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tls-certificates-jvm",
        "version": "2.3.8"
      }
    }
  ]
}
