{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.dataformat",
    "module": "jackson-dataformat-yaml",
    "version": "2.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.20.1.jar",
          "url": "jackson-dataformat-yaml-2.20.1.jar",
          "size": 60088,
          "sha512": "7141257127b072ae9d4bdd08de027f3f6cdb14b7667190f88b058f60d42e1d0556c3a2c3be0beb27397dc386f65be137dd280f9e53632922047b091c10b01bbc",
          "sha256": "030f1d91f7df278e86e1ba3e129fb520871ac16ce53017c735f708823be970db",
          "sha1": "e6da043059c9ec631a3429ded461d5d92f240c3f",
          "md5": "66dc3c5f31150557109b14182ed7ed8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.20.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.20.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.20.1.jar",
          "url": "jackson-dataformat-yaml-2.20.1.jar",
          "size": 60088,
          "sha512": "7141257127b072ae9d4bdd08de027f3f6cdb14b7667190f88b058f60d42e1d0556c3a2c3be0beb27397dc386f65be137dd280f9e53632922047b091c10b01bbc",
          "sha256": "030f1d91f7df278e86e1ba3e129fb520871ac16ce53017c735f708823be970db",
          "sha1": "e6da043059c9ec631a3429ded461d5d92f240c3f",
          "md5": "66dc3c5f31150557109b14182ed7ed8a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.20.1-javadoc.jar",
          "url": "jackson-dataformat-yaml-2.20.1-javadoc.jar",
          "size": 193250,
          "sha512": "4faa3d7633e4f95bc1f0e583a21ad03d28954182e81b07670800e5ac2182c1ce8a3a9639022d72fbfeb93433c2b6ebfd5295fb215cb410594a51f4f2fde31f54",
          "sha256": "1b2b7d0c5590e62a711e8469a0ef63a7e54d894da180dfda627bef8da77ae5aa",
          "sha1": "6a3a014a5c68c2e22bc0fdb83be027cef621c652",
          "md5": "35b57b88a3dc208e887fd8be98826a6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [],
      "files": [
        {
          "name": "jackson-dataformat-yaml-2.20.1-sources.jar",
          "url": "jackson-dataformat-yaml-2.20.1-sources.jar",
          "size": 48905,
          "sha512": "f6b5b6533c37ef68f714290a855be2bcc63434c07bb0183613cc4e24b48c9cfc128bd70c6ad5628f5dbe671634996a32905da1109d1dd35245a48d2f742415bf",
          "sha256": "cb01c1f4ccb2e1453304d999aae42a888353c09a30be6cf0c930a71dbca29e0c",
          "sha1": "9e8f6edbca480a988813e5919124dd8537f83ad8",
          "md5": "3d979b9907e20193dc1c56cbbe4bc0b5"
        }
      ]
    }
  ]
}
