{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.16.jar",
          "url": "spring-webmvc-6.1.16.jar",
          "size": 1048447,
          "sha512": "75855b242e8d7b3ddd73beacec2ae2e69d4e43d25de6f3ad3d6ea12bbe4ca3194ebb64c045c6f9922a77f8f352504c1235e683f4fea5c6fd9f5d66fdab7fd17e",
          "sha256": "f383a6f4d159111ea184441ec37c07113df470ad86cc42a3b0afe83b13c25ee8",
          "sha1": "a90b539656b99590ce19c327e317ad89967d1784",
          "md5": "baba4f6566e565eab7d667c6f36c9b89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.16.jar",
          "url": "spring-webmvc-6.1.16.jar",
          "size": 1048447,
          "sha512": "75855b242e8d7b3ddd73beacec2ae2e69d4e43d25de6f3ad3d6ea12bbe4ca3194ebb64c045c6f9922a77f8f352504c1235e683f4fea5c6fd9f5d66fdab7fd17e",
          "sha256": "f383a6f4d159111ea184441ec37c07113df470ad86cc42a3b0afe83b13c25ee8",
          "sha1": "a90b539656b99590ce19c327e317ad89967d1784",
          "md5": "baba4f6566e565eab7d667c6f36c9b89"
        }
      ]
    }
  ]
}
