{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-actuator",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.13.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.3.7.jar",
          "url": "spring-boot-starter-actuator-3.3.7.jar",
          "size": 4806,
          "sha512": "49c781bdf209e42d0d9baad9568acb617906a7453b51a4dbb069208b629ad33caecf6123b2e875a7f62bda4649e22caa9914e56ec4f2ac38cb78e286d16d30e4",
          "sha256": "9817c88d7157ff40cfdab0fc6dce277d85d0b7b8d70eb9cf97088addc8a4903e",
          "sha1": "ce26410783bf201fb9dd3b591ac8b13fed854c05",
          "md5": "44e2f1779956ff9df4517072de1f74cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-actuator-autoconfigure",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.13.9"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-jakarta9",
          "version": {
            "requires": "1.13.9"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.3.7.jar",
          "url": "spring-boot-starter-actuator-3.3.7.jar",
          "size": 4806,
          "sha512": "49c781bdf209e42d0d9baad9568acb617906a7453b51a4dbb069208b629ad33caecf6123b2e875a7f62bda4649e22caa9914e56ec4f2ac38cb78e286d16d30e4",
          "sha256": "9817c88d7157ff40cfdab0fc6dce277d85d0b7b8d70eb9cf97088addc8a4903e",
          "sha1": "ce26410783bf201fb9dd3b591ac8b13fed854c05",
          "md5": "44e2f1779956ff9df4517072de1f74cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-actuator-3.3.7-javadoc.jar",
          "size": 4806,
          "sha512": "54ca398d382e308b9bab82e8614868c64fa136f488d69a21399ee183d897043f566bd91b826d29d3ce58dde77017db434f80ec8a85b6057c9b8f82dcf6019791",
          "sha256": "9a1f5775a59c4293b91332fa7c32cc4c0956c90f6259b13f4977afaa55aafd4b",
          "sha1": "b2f6a138de585a15b9749ef6201bcab61f352f62",
          "md5": "408864ad572713f8a35fb9df20effcb2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-actuator-3.3.7-sources.jar",
          "url": "spring-boot-starter-actuator-3.3.7-sources.jar",
          "size": 4806,
          "sha512": "54ca398d382e308b9bab82e8614868c64fa136f488d69a21399ee183d897043f566bd91b826d29d3ce58dde77017db434f80ec8a85b6057c9b8f82dcf6019791",
          "sha256": "9a1f5775a59c4293b91332fa7c32cc4c0956c90f6259b13f4977afaa55aafd4b",
          "sha1": "b2f6a138de585a15b9749ef6201bcab61f352f62",
          "md5": "408864ad572713f8a35fb9df20effcb2"
        }
      ]
    }
  ]
}
