{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jspecify",
    "module": "jspecify",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jspecify-0.3.0.jar",
          "url": "jspecify-0.3.0.jar",
          "size": 2850,
          "sha512": "6bf95c4bde0953555e4aa734d15b8f6ba82c741d0f078956c468b4ac147bb6d5eff09db8b886aea7bdf4eb66f0065bd0abf4a0c89cea57743157d6870db58da7",
          "sha256": "e1c7e1832b6095fcfcbe57485700c7330d53d4e57e2c5bbf9c71819b02e978be",
          "sha1": "fc1a0c38a07667f2dbbece32164dac2d0056d205",
          "md5": "299339fcc251674841e11d099fde6130"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jspecify-0.3.0.jar",
          "url": "jspecify-0.3.0.jar",
          "size": 2850,
          "sha512": "6bf95c4bde0953555e4aa734d15b8f6ba82c741d0f078956c468b4ac147bb6d5eff09db8b886aea7bdf4eb66f0065bd0abf4a0c89cea57743157d6870db58da7",
          "sha256": "e1c7e1832b6095fcfcbe57485700c7330d53d4e57e2c5bbf9c71819b02e978be",
          "sha1": "fc1a0c38a07667f2dbbece32164dac2d0056d205",
          "md5": "299339fcc251674841e11d099fde6130"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jspecify-0.3.0-javadoc.jar",
          "url": "jspecify-0.3.0-javadoc.jar",
          "size": 105692,
          "sha512": "722cb2ee9ac457497f9568e9101f6e161af5c9585965901405c2b6c54c3cd096bf2be2b402462610fd6c54daeb702a02e2dbeca1531ab4d50430a38e75808681",
          "sha256": "f1d7dc3bf1d65227f91501c045cd2c03ed761ad4b865d1ba249f457bffb7d143",
          "sha1": "5d45eb5efca4470284b822584ee0889173933a7f",
          "md5": "4accf57116495e7d15fda7ae5122dfeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jspecify-0.3.0-sources.jar",
          "url": "jspecify-0.3.0-sources.jar",
          "size": 12879,
          "sha512": "11bf96905ccf4f196cc3ca9fbc01aec073a8e2baefd766701bf9fa11e13c08cfaa3a1be0cbcc465523b97e3b20ffeda48bb1fe3a763613fbab45a2936720ab9f",
          "sha256": "7c66077951afbdd89e76c11f75c81ed4deaba831994ca8f6a3648c4c89c5054b",
          "sha1": "5cbacba3af55bd8f7352c519be2f76ec2d0ccde4",
          "md5": "07a18c2261c3cadff87c7d5c97431345"
        }
      ]
    }
  ]
}
