{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.spotbugs",
    "module": "spotbugs-annotations",
    "version": "4.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotbugs-annotations-4.8.3.jar",
          "url": "spotbugs-annotations-4.8.3.jar",
          "size": 15204,
          "sha512": "1a64f6911a94654d440ce4918395af0cbdee79696acbcf727af79134b02e6be17956fffa8f39e05fa9e22e336041443eb31165b338164b48a1c70f947e66d68b",
          "sha256": "e5d4f60be8e57595766ba7f1d4535dc46aebf98dae05e16372a4d4120d3ebb6b",
          "sha1": "05d2dc4ca5b632976371155252499819aea372ed",
          "md5": "cd5917b77643c3a7ba5420aea78f940c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.1, 3[",
            "requires": "[2.17.1, 3["
          },
          "reason": "CVE-2021-44228, CVE-2021-45046, CVE-2021-45105, CVE-2021-44832: Log4j vulnerable to remote code execution and other critical security vulnerabilities"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-core",
          "version": {
            "strictly": "[1.2.9, 2[",
            "requires": "[1.2.9, 2["
          },
          "reason": "CVE-2021-42550: Logback vulnerable to remote code execution vulnerabilities"
        }
      ],
      "files": [
        {
          "name": "spotbugs-annotations-4.8.3.jar",
          "url": "spotbugs-annotations-4.8.3.jar",
          "size": 15204,
          "sha512": "1a64f6911a94654d440ce4918395af0cbdee79696acbcf727af79134b02e6be17956fffa8f39e05fa9e22e336041443eb31165b338164b48a1c70f947e66d68b",
          "sha256": "e5d4f60be8e57595766ba7f1d4535dc46aebf98dae05e16372a4d4120d3ebb6b",
          "sha1": "05d2dc4ca5b632976371155252499819aea372ed",
          "md5": "cd5917b77643c3a7ba5420aea78f940c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotbugs-annotations-4.8.3-javadoc.jar",
          "url": "spotbugs-annotations-4.8.3-javadoc.jar",
          "size": 208162,
          "sha512": "a1f91e5a5e7a2e03042a4fe78f5e43cb3d0db384bd3c75326719c507ca636a1925906aa3148e14da5b1d3ca8b684f2c3bd907bbf74871ad0be087a566413eb26",
          "sha256": "eb513a89ac812f50e3d7de5efbb0e135994849c18412b04759e6d67e991e356e",
          "sha1": "de4180753a9d518769c5c83c5e61d77e4df3d070",
          "md5": "f983dc587438824abb909552180f6798"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotbugs-annotations-4.8.3-sources.jar",
          "url": "spotbugs-annotations-4.8.3-sources.jar",
          "size": 24186,
          "sha512": "4a8e3c021261ada3bd6fb9741426ef14afffb49fcb8853ed86a7c42d711e5816ea553ff9ca826fd38c6516d6d3aadef0b8e345e37e15925dd78277353bc7480e",
          "sha256": "b5d0110b70b9c44915f2c3375d1b700acb6d409152baf70030787d17a684469b",
          "sha1": "062e2cc9cfe009786e8f7b5ac6421668cb8a62b1",
          "md5": "7b9d74e907169ff381e0f1a7a7a1b18f"
        }
      ]
    }
  ]
}
