{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-network",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.8"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-metadata-2.3.8.jar",
          "url": "ktor-network-2.3.8.jar",
          "size": 35260,
          "sha512": "864f31fc49f35258605f72d14b71563e6dcfec103771a14b0a60e6ea2aaeaecbaf03352404fc882873242acfd361e241a52c0182b00f0127517cfb6fd3fc0f4d",
          "sha256": "d69969f7a3ba55cead43aa6124742076285111c951b1a04e8a552c3de934c9d8",
          "sha1": "c8b1451ce034d35c2db524537f1a33408e0e9c84",
          "md5": "ade970b17f6b8d217e56adb2b84e974d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-network-kotlin-2.3.8-sources.jar",
          "url": "ktor-network-2.3.8-sources.jar",
          "size": 39362,
          "sha512": "8f74c1e8c0f8729b394d7a29a78d4dfea4f2a6f40f7c8153e21de56782e8563a3eeca22f4e975032991c8a09fecb8fed7ad72d3714023d033738991d034f639e",
          "sha256": "5ae3b15b85d93ee871bd56ab894a259f28ccb24a12816d81c54094c4fa7665ec",
          "sha1": "9e54943d9c3d6fa2cf1085830982656c9b449ae8",
          "md5": "33763acd6b40ce4afb88abe50fd96fcd"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosarm64/2.3.8/ktor-network-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosarm64/2.3.8/ktor-network-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosarm64/2.3.8/ktor-network-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iossimulatorarm64/2.3.8/ktor-network-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iossimulatorarm64/2.3.8/ktor-network-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iossimulatorarm64/2.3.8/ktor-network-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosx64/2.3.8/ktor-network-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosx64/2.3.8/ktor-network-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-iosx64/2.3.8/ktor-network-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-jvm/2.3.8/ktor-network-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-jvm/2.3.8/ktor-network-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-network-jvm/2.3.8/ktor-network-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxarm64/2.3.8/ktor-network-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxarm64/2.3.8/ktor-network-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxx64/2.3.8/ktor-network-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-linuxx64/2.3.8/ktor-network-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosarm64/2.3.8/ktor-network-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosarm64/2.3.8/ktor-network-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosarm64/2.3.8/ktor-network-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosx64/2.3.8/ktor-network-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosx64/2.3.8/ktor-network-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-macosx64/2.3.8/ktor-network-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosarm64/2.3.8/ktor-network-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosarm64/2.3.8/ktor-network-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosarm64/2.3.8/ktor-network-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvossimulatorarm64/2.3.8/ktor-network-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvossimulatorarm64/2.3.8/ktor-network-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvossimulatorarm64/2.3.8/ktor-network-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosx64/2.3.8/ktor-network-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosx64/2.3.8/ktor-network-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-tvosx64/2.3.8/ktor-network-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm32/2.3.8/ktor-network-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm32/2.3.8/ktor-network-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm32/2.3.8/ktor-network-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm64/2.3.8/ktor-network-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm64/2.3.8/ktor-network-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosarm64/2.3.8/ktor-network-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchossimulatorarm64/2.3.8/ktor-network-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchossimulatorarm64/2.3.8/ktor-network-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchossimulatorarm64/2.3.8/ktor-network-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosx64/2.3.8/ktor-network-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosx64/2.3.8/ktor-network-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-network-watchosx64/2.3.8/ktor-network-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-network-watchosx64",
        "version": "2.3.8"
      }
    }
  ]
}
