{
  "formatVersion": "1.1",
  "component": {
    "group": "io.pact.plugin.driver",
    "module": "core",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "core-0.5.1.jar",
          "url": "core-0.5.1.jar",
          "size": 769124,
          "sha512": "b00568db492d0bf347c539b51557345be64b0d400e106a637180e854828dedf6acfeaa62133244c78e8b510474c555573829a052421acfc93887671175ff00f9",
          "sha256": "ff9c6450e45bb67c9cf00d82666c3ae69fc5fe1752454935bedb9e1ec33b97e5",
          "sha1": "b16bee9208eb186f695438eb4889bef78950e508",
          "md5": "2015ee61831606da3cfc1fd99612038b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "au.com.dius.pact.core",
          "module": "model",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.5.12"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.0-jre"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "semver4j",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "6.0.9"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "io.grpc",
          "module": "grpc-netty",
          "version": {
            "requires": "1.66.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.66.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.66.0"
          }
        },
        {
          "group": "io.hotmoka",
          "module": "toml4j",
          "version": {
            "requires": "0.7.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.14.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.rauschig",
          "module": "jarchivelib",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.26.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.5.1.jar",
          "url": "core-0.5.1.jar",
          "size": 769124,
          "sha512": "b00568db492d0bf347c539b51557345be64b0d400e106a637180e854828dedf6acfeaa62133244c78e8b510474c555573829a052421acfc93887671175ff00f9",
          "sha256": "ff9c6450e45bb67c9cf00d82666c3ae69fc5fe1752454935bedb9e1ec33b97e5",
          "sha1": "b16bee9208eb186f695438eb4889bef78950e508",
          "md5": "2015ee61831606da3cfc1fd99612038b"
        }
      ]
    }
  ]
}
