{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aop",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.7.jar",
          "url": "spring-boot-starter-aop-3.3.7.jar",
          "size": 4769,
          "sha512": "fec4eb85555f16c6320c7898d763f98a8f45f8fde8f0ad38c141c8d9b23361dd2badb8637a0162eb7392a277cf4fe964bbe9e8b6055a08b105ff988ac7a31be1",
          "sha256": "4a354380e640fa03dd987f584bd118baa9f1384cc18c2a2e8039872d7141e26c",
          "sha1": "7ca61c90cf88acaa672d1db7096b45124b0d1d07",
          "md5": "b97e6e38aa606c1475678f29be4bae8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.22.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.7.jar",
          "url": "spring-boot-starter-aop-3.3.7.jar",
          "size": 4769,
          "sha512": "fec4eb85555f16c6320c7898d763f98a8f45f8fde8f0ad38c141c8d9b23361dd2badb8637a0162eb7392a277cf4fe964bbe9e8b6055a08b105ff988ac7a31be1",
          "sha256": "4a354380e640fa03dd987f584bd118baa9f1384cc18c2a2e8039872d7141e26c",
          "sha1": "7ca61c90cf88acaa672d1db7096b45124b0d1d07",
          "md5": "b97e6e38aa606c1475678f29be4bae8e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-aop-3.3.7-javadoc.jar",
          "size": 4769,
          "sha512": "4be2bc16d2a7f7def29453e1caff1fd01ec034d958436f3176e9e4207ee004b9cf2e1e8e221031ceab9de7b8d1fa03d3d13d47caa4e6c595c1718bd7145caed1",
          "sha256": "bd5b41a97010d47df8e7de965163d1a8aba891f3a368484f1949c7aebfac368b",
          "sha1": "74c1a01c4520988e4d4897ecf7b0a515ca71f3d7",
          "md5": "f039986b4882351978504a3def661f70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aop-3.3.7-sources.jar",
          "url": "spring-boot-starter-aop-3.3.7-sources.jar",
          "size": 4769,
          "sha512": "4be2bc16d2a7f7def29453e1caff1fd01ec034d958436f3176e9e4207ee004b9cf2e1e8e221031ceab9de7b8d1fa03d3d13d47caa4e6c595c1718bd7145caed1",
          "sha256": "bd5b41a97010d47df8e7de965163d1a8aba891f3a368484f1949c7aebfac368b",
          "sha1": "74c1a01c4520988e4d4897ecf7b0a515ca71f3d7",
          "md5": "f039986b4882351978504a3def661f70"
        }
      ]
    }
  ]
}
