package uk.gov.hmcts.reform.civil.handler.migration;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.reform.ccd.model.OrganisationPolicy;
import uk.gov.hmcts.reform.civil.bulkupdate.csv.CaseReference;
import uk.gov.hmcts.reform.civil.config.SystemUpdateUserConfiguration;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.LitigationFriend;
import uk.gov.hmcts.reform.civil.model.Party;
import uk.gov.hmcts.reform.civil.model.PartyFlagStructure;
import uk.gov.hmcts.reform.civil.model.common.Element;
import uk.gov.hmcts.reform.civil.service.UserService;
import uk.gov.hmcts.reform.hmc.model.hearing.Attendees;
import uk.gov.hmcts.reform.hmc.model.hearing.HearingDaySchedule;
import uk.gov.hmcts.reform.hmc.model.hearing.HearingGetResponse;
import uk.gov.hmcts.reform.hmc.model.hearing.IndividualDetailsModel;
import uk.gov.hmcts.reform.hmc.model.hearing.PartyDetailsModel;
import uk.gov.hmcts.reform.hmc.model.hearings.CaseHearing;
import uk.gov.hmcts.reform.hmc.model.hearings.HearingsResponse;
import uk.gov.hmcts.reform.hmc.service.HearingsService;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Read-only diagnostic task for DTSCCI-6366 (item 1 of the spike).
 *
 * <p>Hearing notice attendee names come from the HMC response, not from CCD
 * ({@code HmcDataUtils.getInPersonAttendeeNames} reads {@code hearing.getPartyDetails()}). Before we
 * can recommend deriving that section from case data, we need to know which shape the HMC data loss
 * takes on the cases already confirmed wrong in DTSCCI-5905 and DTSCCI-6070:</p>
 *
 * <ul>
 *   <li>{@code ID_IN_CCD_NAME_DIFFERS} - HMC holds the right party ID against a wrong name. A name
 *       lookup against case data fixes the notice outright.</li>
 *   <li>{@code ID_NOT_IN_CCD} - the attendee's party ID is not a party ID this case ever sent to HMC,
 *       so there is no case data name to resolve and the mitigation rests on the fallback rule.</li>
 * </ul>
 *
 * <p>Party IDs are generated by civil-service ({@code PartyUtils.populateWithPartyIds}) and sent out
 * by {@code HearingsPartyMapper}, so an ID coming back from HMC is expected to be one of ours. This
 * task makes no changes to CaseData and emits structured log lines (prefix {@code HMC_ATTENDEE_IDS})
 * for filtering in App Insights.</p>
 *
 * <p>Caveat for whoever reads the output: this reports the CURRENT HMC state. A notice found wrong
 * months ago was generated against an earlier request version, and HMC may have been re-listed or
 * corrected since. The logged version number and received date let the reader judge that.</p>
 */
@Component
@Slf4j
public class VerifyHmcAttendeePartyIdsTask extends MigrationTask<CaseReference> {

    private static final String LOG_PREFIX = "HMC_ATTENDEE_IDS";
    private static final String TASK_NAME = "VerifyHmcAttendeePartyIdsTask";
    private static final String EVENT_SUMMARY = "Check HMC attendee party IDs resolve against CCD case data";
    private static final String EVENT_DESCRIPTION =
        "Read-only diagnostic comparing HMC hearing attendee party IDs and names against the party IDs held in case data";

    private final HearingsService hearingsService;
    private final UserService userService;
    private final SystemUpdateUserConfiguration userConfig;

    public VerifyHmcAttendeePartyIdsTask(HearingsService hearingsService,
                                         UserService userService,
                                         SystemUpdateUserConfiguration userConfig) {
        super(CaseReference.class);
        this.hearingsService = hearingsService;
        this.userService = userService;
        this.userConfig = userConfig;
    }

    @Override
    public boolean isReadOnly() {
        return true;
    }

    @Override
    protected String getTaskName() {
        return TASK_NAME;
    }

    @Override
    protected String getEventSummary() {
        return EVENT_SUMMARY;
    }

    @Override
    protected String getEventDescription() {
        return EVENT_DESCRIPTION;
    }

    @Override
    protected CaseData migrateCaseData(CaseData caseData, CaseReference caseReference) {
        if (caseData == null || caseReference == null || caseReference.getCaseReference() == null) {
            throw new IllegalArgumentException("CaseData and CaseReference must not be null");
        }

        String caseId = caseReference.getCaseReference();
        Map<String, String> ccdParties = ccdPartyIdsToNames(caseData);
        String authorisation = getSystemUserToken();

        List<Long> hearingIds = hearingIds(caseId, authorisation);
        if (hearingIds.isEmpty()) {
            log.info("{} case={} result=NO_HEARINGS ccdPartyIds={}", LOG_PREFIX, caseId, ccdParties.keySet());
            return caseData;
        }

        for (Long hearingId : hearingIds) {
            inspectHearing(caseId, hearingId, ccdParties, authorisation);
        }

        return caseData;
    }

    private List<Long> hearingIds(String caseId, String authorisation) {
        List<Long> ids = new ArrayList<>();
        try {
            HearingsResponse hearings = hearingsService.getHearings(authorisation, Long.valueOf(caseId), null);
            if (hearings != null && hearings.getCaseHearings() != null) {
                hearings.getCaseHearings().stream()
                    .filter(hearing -> hearing != null && hearing.getHearingId() != null)
                    .map(CaseHearing::getHearingId)
                    .forEach(ids::add);
            }
        } catch (Exception e) {
            log.error("{} case={} result=ERROR stage=listHearings message={}", LOG_PREFIX, caseId, e.getMessage(), e);
        }
        return ids;
    }

    private void inspectHearing(String caseId, Long hearingId, Map<String, String> ccdParties, String authorisation) {
        try {
            HearingGetResponse hearing = hearingsService.getHearingResponse(authorisation, String.valueOf(hearingId));
            if (hearing == null) {
                log.info("{} case={} hearing={} result=NO_RESPONSE", LOG_PREFIX, caseId, hearingId);
                return;
            }

            Map<String, String> hmcParties = hmcPartyIdsToNames(hearing);
            long overlap = hmcParties.keySet().stream().filter(ccdParties::containsKey).count();
            String hearingResult = hearingVerdict(hmcParties.size(), overlap);

            log.info("{} case={} hearing={} version={} hmcCaseRef={} caseRefMatches={} hmcInternalCaseName=\"{}\" "
                         + "responseReceived={} result={} idOverlap={}/{} ccdPartyIds={} hmcPartyIds={}",
                     LOG_PREFIX, caseId, hearingId, versionNumber(hearing), hmcCaseRef(hearing),
                     caseId.equals(hmcCaseRef(hearing)), internalCaseName(hearing), receivedDateTime(hearing),
                     hearingResult, overlap, hmcParties.size(), ccdParties.keySet(), hmcParties.keySet());

            inspectAttendees(caseId, hearingId, hearing, ccdParties, hmcParties);
        } catch (Exception e) {
            log.error("{} case={} hearing={} result=ERROR stage=getHearing message={}",
                      LOG_PREFIX, caseId, hearingId, e.getMessage(), e);
        }
    }

    private void inspectAttendees(String caseId, Long hearingId, HearingGetResponse hearing,
                                  Map<String, String> ccdParties, Map<String, String> hmcParties) {
        List<Attendees> attendees = startDayAttendees(hearing);
        if (attendees.isEmpty()) {
            log.info("{} case={} hearing={} result=NO_ATTENDEES", LOG_PREFIX, caseId, hearingId);
            return;
        }

        for (Attendees attendee : attendees) {
            String partyId = attendee.getPartyID();
            String hmcName = hmcParties.get(partyId);
            String ccdName = ccdParties.get(partyId);
            String verdict = attendeeVerdict(ccdParties, partyId, hmcName, ccdName);

            log.info("{} case={} hearing={} attendee={} channel={} verdict={} hmcName=\"{}\" ccdName=\"{}\"",
                     LOG_PREFIX, caseId, hearingId, partyId, attendee.getHearingSubChannel(),
                     verdict, nullSafe(hmcName), nullSafe(ccdName));
        }
    }

    /**
     * The notice only lists attendees from the first scheduled day
     * ({@code HmcDataUtils.getAttendeesBySubChannels} uses {@code getHearingStartDay}), so this
     * mirrors that rather than reporting every day.
     */
    private List<Attendees> startDayAttendees(HearingGetResponse hearing) {
        if (hearing.getHearingResponse() == null || hearing.getHearingResponse().getHearingDaySchedule() == null) {
            return List.of();
        }
        return hearing.getHearingResponse().getHearingDaySchedule().stream()
            .filter(day -> day != null && day.getHearingStartDateTime() != null)
            .min(java.util.Comparator.comparing(HearingDaySchedule::getHearingStartDateTime))
            .map(HearingDaySchedule::getAttendees)
            .filter(java.util.Objects::nonNull)
            .orElse(List.of())
            .stream()
            .filter(attendee -> attendee != null && attendee.getPartyID() != null)
            .toList();
    }

    private String attendeeVerdict(Map<String, String> ccdParties, String partyId, String hmcName, String ccdName) {
        if (!ccdParties.containsKey(partyId)) {
            return "ID_NOT_IN_CCD";
        }
        if (hmcName == null || hmcName.isBlank()) {
            return "ID_IN_CCD_NO_HMC_NAME";
        }
        return normalise(hmcName).equals(normalise(ccdName)) ? "ID_IN_CCD_NAME_MATCHES" : "ID_IN_CCD_NAME_DIFFERS";
    }

    private String hearingVerdict(int hmcPartyCount, long overlap) {
        if (hmcPartyCount == 0) {
            return "HEARING_HAS_NO_PARTIES";
        }
        if (overlap == 0) {
            return "HEARING_PARTIES_ALL_FOREIGN";
        }
        return overlap == hmcPartyCount ? "HEARING_PARTIES_ALL_KNOWN" : "HEARING_PARTIES_PARTIAL";
    }

    private Map<String, String> hmcPartyIdsToNames(HearingGetResponse hearing) {
        Map<String, String> parties = new LinkedHashMap<>();
        if (hearing.getPartyDetails() == null) {
            return parties;
        }
        for (PartyDetailsModel party : hearing.getPartyDetails()) {
            if (party == null || party.getPartyID() == null) {
                continue;
            }
            parties.put(party.getPartyID(), hmcPartyName(party));
        }
        return parties;
    }

    /**
     * The name the notice would print for this party: {@code HmcDataUtils.getHearingAttendeeNames}
     * joins the individual first and last name, so that is compared first.
     */
    private String hmcPartyName(PartyDetailsModel party) {
        IndividualDetailsModel individual = party.getIndividualDetails();
        if (individual != null) {
            String name = joinName(individual.getFirstName(), individual.getLastName());
            if (!name.isEmpty()) {
                return name;
            }
        }
        if (party.getOrganisationDetails() != null && party.getOrganisationDetails().getName() != null) {
            return party.getOrganisationDetails().getName();
        }
        return party.getPartyName() == null ? "" : party.getPartyName();
    }

    /**
     * Every party ID this case would send to HMC, mirroring {@code HearingsPartyMapper}: parties,
     * litigation friends, experts, witnesses, legal rep and organisation individuals, and the
     * solicitor organisations (whose party ID is the organisation ID). Deliberately reads case data
     * directly rather than calling the mapper, to avoid a reference data lookup per case.
     */
    Map<String, String> ccdPartyIdsToNames(CaseData caseData) {
        Map<String, String> parties = new LinkedHashMap<>();
        addParty(parties, caseData.getApplicant1());
        addParty(parties, caseData.getApplicant2());
        addParty(parties, caseData.getRespondent1());
        addParty(parties, caseData.getRespondent2());
        addLitigationFriend(parties, caseData.getApplicant1LitigationFriend());
        addLitigationFriend(parties, caseData.getApplicant2LitigationFriend());
        addLitigationFriend(parties, caseData.getRespondent1LitigationFriend());
        addLitigationFriend(parties, caseData.getRespondent2LitigationFriend());
        addFlagStructures(parties, caseData.getApplicantExperts());
        addFlagStructures(parties, caseData.getApplicantWitnesses());
        addFlagStructures(parties, caseData.getRespondent1Experts());
        addFlagStructures(parties, caseData.getRespondent1Witnesses());
        addFlagStructures(parties, caseData.getRespondent2Experts());
        addFlagStructures(parties, caseData.getRespondent2Witnesses());
        addFlagStructures(parties, caseData.getApplicant1LRIndividuals());
        addFlagStructures(parties, caseData.getRespondent1LRIndividuals());
        addFlagStructures(parties, caseData.getRespondent2LRIndividuals());
        addFlagStructures(parties, caseData.getApplicant1OrgIndividuals());
        addFlagStructures(parties, caseData.getApplicant2OrgIndividuals());
        addFlagStructures(parties, caseData.getRespondent1OrgIndividuals());
        addFlagStructures(parties, caseData.getRespondent2OrgIndividuals());
        addSolicitorOrganisation(parties, caseData.getApplicant1OrganisationPolicy());
        addSolicitorOrganisation(parties, caseData.getRespondent1OrganisationPolicy());
        addSolicitorOrganisation(parties, caseData.getRespondent2OrganisationPolicy());
        return parties;
    }

    private void addParty(Map<String, String> parties, Party party) {
        if (party == null || party.getPartyID() == null) {
            return;
        }
        String first = party.getIndividualFirstName() == null
            ? party.getSoleTraderFirstName() : party.getIndividualFirstName();
        String last = party.getIndividualLastName() == null
            ? party.getSoleTraderLastName() : party.getIndividualLastName();
        String name = joinName(first, last);
        parties.put(party.getPartyID(), name.isEmpty() ? nullSafe(party.getPartyName()) : name);
    }

    private void addLitigationFriend(Map<String, String> parties, LitigationFriend litigationFriend) {
        if (litigationFriend != null && litigationFriend.getPartyID() != null) {
            parties.put(litigationFriend.getPartyID(),
                        joinName(litigationFriend.getFirstName(), litigationFriend.getLastName()));
        }
    }

    private void addFlagStructures(Map<String, String> parties, List<Element<PartyFlagStructure>> people) {
        if (people == null) {
            return;
        }
        people.stream()
            .filter(element -> element != null && element.getValue() != null)
            .map(Element::getValue)
            .filter(person -> person.getPartyID() != null)
            .forEach(person -> parties.put(person.getPartyID(),
                                           joinName(person.getFirstName(), person.getLastName())));
    }

    private void addSolicitorOrganisation(Map<String, String> parties, OrganisationPolicy policy) {
        if (policy != null && policy.getOrganisation() != null && policy.getOrganisation().getOrganisationID() != null) {
            // HearingsPartyMapper sends the organisation ID as the party ID; the organisation name is
            // only available from reference data, which this diagnostic does not need.
            parties.put(policy.getOrganisation().getOrganisationID(), "");
        }
    }

    private String versionNumber(HearingGetResponse hearing) {
        return hearing.getRequestDetails() == null ? null : String.valueOf(hearing.getRequestDetails().getVersionNumber());
    }

    private String hmcCaseRef(HearingGetResponse hearing) {
        return hearing.getCaseDetails() == null ? null : hearing.getCaseDetails().getCaseRef();
    }

    private String internalCaseName(HearingGetResponse hearing) {
        return hearing.getCaseDetails() == null ? null : hearing.getCaseDetails().getHmctsInternalCaseName();
    }

    private String receivedDateTime(HearingGetResponse hearing) {
        return hearing.getHearingResponse() == null ? null : String.valueOf(hearing.getHearingResponse().getReceivedDateTime());
    }

    private String joinName(String first, String last) {
        return ((first == null ? "" : first) + " " + (last == null ? "" : last)).trim();
    }

    private String nullSafe(String value) {
        return value == null ? "" : value;
    }

    private String normalise(String value) {
        return value == null ? "" : value.toLowerCase().replaceAll("\\s+", " ").trim();
    }

    private String getSystemUserToken() {
        return userService.getAccessToken(userConfig.getUserName(), userConfig.getPassword());
    }
}
