{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp-urlconnection",
    "version": "4.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-urlconnection-4.12.0.jar",
          "url": "okhttp-urlconnection-4.12.0.jar",
          "size": 4736,
          "sha512": "6fdd6a8f8985e15decbd80329679e9a16e8ff8e027df45e6f4056dfce5aad96d596897c8ee38b7fb049ece6c9690826c38b2a8aedafaf2e9667cac07720203ee",
          "sha256": "74c0e3f8c3df0b1d32ab9d839448c914586d3e8479611e4386fecfa6b3f0a26b",
          "sha1": "f182bfa2eaca0bb8086904c8b5710976e5b55d65",
          "md5": "3dae1b2c6bc07210d0ce526f3baf3576"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-urlconnection-4.12.0.jar",
          "url": "okhttp-urlconnection-4.12.0.jar",
          "size": 4736,
          "sha512": "6fdd6a8f8985e15decbd80329679e9a16e8ff8e027df45e6f4056dfce5aad96d596897c8ee38b7fb049ece6c9690826c38b2a8aedafaf2e9667cac07720203ee",
          "sha256": "74c0e3f8c3df0b1d32ab9d839448c914586d3e8479611e4386fecfa6b3f0a26b",
          "sha1": "f182bfa2eaca0bb8086904c8b5710976e5b55d65",
          "md5": "3dae1b2c6bc07210d0ce526f3baf3576"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-urlconnection-4.12.0-javadoc.jar",
          "url": "okhttp-urlconnection-4.12.0-javadoc.jar",
          "size": 261,
          "sha512": "50b5f3872d69226de8a75288848e8fbdb27c080a994a9c4cb5a3bf5495bb4055d015365146baa2f601a70e6df125972685936d65512534ef5c2fe5db9641ce60",
          "sha256": "fee88dc4dd68c45fa732e17474af125665dfd549dda0ff14e45739d1ffb5bd59",
          "sha1": "834c0429277ddc57aa7fb0c097713d4b5bacc7c9",
          "md5": "1da2f0c7a27b49d3273c4123ebbd8310"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-urlconnection-4.12.0-sources.jar",
          "url": "okhttp-urlconnection-4.12.0-sources.jar",
          "size": 2719,
          "sha512": "d03e126573ce8e0848b3242c33a4b43b958ae72fadd918182a5dbceb76a955897b8124f0543d9249b75e6dc6f0c4ed3c2c1d05f00c131dede93aa4d92acf620c",
          "sha256": "8963ebda32d671c91f2b5bd416524ff08bfb398c3fba50d268acb7702f15b7aa",
          "sha1": "d46676a65d33a32b7e75ad0607964317e567447b",
          "md5": "f89487b631e687e10c61271b2684821e"
        }
      ]
    }
  ]
}
