import CCDEvents from '../models/ccd/ccd-events';

const ccdEvents: CCDEvents = {
  CREATE_CLAIM: {
    id: 'CREATE_CLAIM',
    name: 'Create claim - Unspecified',
    description: 'Case created, post actions triggered',
    order: 1,
  },
  CREATE_CLAIM_AFTER_PAYMENT: {
    id: 'CREATE_CLAIM_AFTER_PAYMENT',
    name: 'Case issued after payment',
    description: 'Move to case issued when fee paid',
  },
  CREATE_CLAIM_SPEC: {
    id: 'CREATE_CLAIM_SPEC',
    name: 'Create claim - Specified',
    description: 'Case created, post actions triggered',
    order: 1,
  },
  CREATE_CLAIM_SPEC_AFTER_PAYMENT: {
    id: 'CREATE_CLAIM_SPEC_AFTER_PAYMENT',
    name: 'Case issued after payment',
    description: 'Move to case issued when fee paid',
  },
  NOTIFY_DEFENDANT_OF_CLAIM: {
    id: 'NOTIFY_DEFENDANT_OF_CLAIM',
    name: 'Notify claim',
    description: 'Notify defendant solicitor of claim',
    order: 2,
  },
  NOTIFY_DEFENDANT_OF_CLAIM_DETAILS: {
    id: 'NOTIFY_DEFENDANT_OF_CLAIM_DETAILS',
    name: 'Notify claim details',
    description: 'Inform the defendant of particulars of claim',
    order: 3,
  },
  ACKNOWLEDGE_CLAIM: {
    id: 'ACKNOWLEDGE_CLAIM',
    name: 'Acknowledge claim',
    description: 'Defendant solicitor is acknowledging claim',
    order: 4,
  },
  ACKNOWLEDGEMENT_OF_SERVICE: {
    description: 'Acknowledgement of Service (AoS)',
    id: 'ACKNOWLEDGEMENT_OF_SERVICE',
    name: 'Acknowledgement of Service',
    order: 4,
  },
  ADD_DEFENDANT_LITIGATION_FRIEND: {
    id: 'ADD_DEFENDANT_LITIGATION_FRIEND',
    name: 'Add litigation friend',
    description: 'Add litigation friend',
    order: 5,
  },
  DEFENDANT_RESPONSE: {
    id: 'DEFENDANT_RESPONSE',
    name: 'Respond to claim',
    description: 'Defendant response to claim',
    order: 6,
  },
  DEFENDANT_RESPONSE_SPEC: {
    id: 'DEFENDANT_RESPONSE_SPEC',
    name: 'Respond to claim',
    description: 'Defendant response to Specified claim',
    order: 6,
  },
  CLAIMANT_RESPONSE: {
    id: 'CLAIMANT_RESPONSE',
    name: 'View and respond to defence',
    description: 'View and respond to defendant',
    order: 7,
  },
  WITHDRAW_CLAIM: {
    id: 'WITHDRAW_CLAIM',
    name: 'Withdraw claim',
    description: 'Withdraw a claim',
    order: 10,
  },
  ADD_OR_AMEND_CLAIM_DOCUMENTS: {
    id: 'ADD_OR_AMEND_CLAIM_DOCUMENTS',
    name: 'Add or amend claim documents',
    description: 'Add or amend documents attached to the claim',
    order: 10,
  },
  DISCONTINUE_CLAIM: {
    id: 'DISCONTINUE_CLAIM',
    name: 'Discontinue claim',
    description: 'Discontinue a claim',
    order: 11,
  },
  CASE_PROCEEDS_IN_CASEMAN: {
    description: 'Case will proceed offline in Caseman system',
    id: 'CASE_PROCEEDS_IN_CASEMAN',
    name: 'Case proceeds in Caseman',
    order: 9,
  },
  RESUBMIT_CLAIM: {
    id: 'RESUBMIT_CLAIM',
    name: 'Resubmit claim',
    description: 'Resubmits claim for unsuccessful PBA payment',
    order: 12,
  },
  INFORM_AGREED_EXTENSION_DATE: {
    description: 'Enter an extension date that has already been agreed with other parties',
    id: 'INFORM_AGREED_EXTENSION_DATE',
    name: 'Inform agreed 28 day extension',
    order: 12,
  },
  INFORM_AGREED_EXTENSION_DATE_SPEC: {
    description:
      'Specified Enter an extension date that has already been agreed with other parties',
    id: 'INFORM_AGREED_EXTENSION_DATE_SPEC',
    name: 'Inform agreed extension date',
    order: 12,
  },
  AMEND_PARTY_DETAILS: {
    description: 'Update defendant and claimant solicitor email addresses',
    id: 'AMEND_PARTY_DETAILS',
    name: 'Amend party details',
    order: 13,
  },
  ADD_CASE_NOTE: {
    description: 'Add a case note',
    id: 'ADD_CASE_NOTE',
    name: 'Add a case note',
    order: 16,
  },
  CHANGE_SOLICITOR_EMAIL: {
    description: "Change solicitor's information",
    id: 'CHANGE_SOLICITOR_EMAIL',
    name: "Change solicitor's information",
    order: 17,
  },
  ENTER_BREATHING_SPACE_SPEC: {
    description: 'Enter Breathing Space',
    id: 'ENTER_BREATHING_SPACE_SPEC',
    name: 'Enter Breathing Space',
    order: 7,
  },
  LIFT_BREATHING_SPACE_SPEC: {
    description: 'Lift Breathing Space',
    id: 'LIFT_BREATHING_SPACE_SPEC',
    name: 'Lift Breathing Space',
    order: 8,
  },
  DEFAULT_JUDGEMENT: {
    id: 'DEFAULT_JUDGEMENT',
    name: 'Request Default Judgment',
    description: 'Request Default Judgment',
    order: 17,
  },
  DEFAULT_JUDGEMENT_SPEC: {
    id: 'DEFAULT_JUDGEMENT_SPEC',
    name: 'Request Default Judgment',
    description: 'Request Default Judgment',
    order: 18,
  },
  CREATE_SDO: {
    id: 'CREATE_SDO',
    name: 'Standard Direction Order',
    description: 'Standard Direction Order',
    order: 17,
  },
  CLAIMANT_RESPONSE_SPEC: {
    description: 'View and respond to defendant (Specified)',
    id: 'CLAIMANT_RESPONSE_SPEC',
    name: 'View and respond to defence',
    order: 7,
  },
  REFER_TO_JUDGE: {
    id: 'REFER_TO_JUDGE',
    name: 'Refer to Judge',
    description: 'Refer to Judge',
    order: 19,
  },
  INITIATE_GENERAL_APPLICATION: {
    id: 'INITIATE_GENERAL_APPLICATION',
    name: 'Make an application',
    description: 'Application created, post actions triggered',
    order: 17,
  },
  REQUEST_JUDGEMENT_ADMISSION_SPEC: {
    id: 'REQUEST_JUDGEMENT_ADMISSION_SPEC',
    name: 'Request Judgement by Admission',
    description: 'Request Judgement by Admission',
    order: 10,
  },
  MANAGE_CONTACT_INFORMATION: {
    id: 'MANAGE_CONTACT_INFORMATION',
    name: 'Manage Contact Information',
    description: 'Updated party contact details',
    order: 99,
  },
  MANAGE_DOCUMENTS: {
    id: 'MANAGE_DOCUMENTS',
    name: 'Manage Documents',
    description: 'Manage Documents',
    order: 4,
  },
  RESET_PIN: {
    id: 'RESET_PIN',
    name: 'Reset Pin',
    description: 'Reset Pin for case',
    order: 7,
  },
  CREATE_CASE_FLAGS: {
    id: 'CREATE_CASE_FLAGS',
    name: 'Create case flags',
    description: 'Create case flags',
    order: 23,
  },
  MANAGE_CASE_FLAGS: {
    id: 'MANAGE_CASE_FLAGS',
    name: 'Manage case flags',
    description: 'Manage case flags',
    order: 24,
  },
};

export default ccdEvents;
