{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.23"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.7.jar",
          "url": "spring-boot-buildpack-platform-3.3.7.jar",
          "size": 295972,
          "sha512": "ae8aae4bf9db5b29f4b108e9be83fbd95b336c0fc583a6a9ba0a7323fec92f83f601bd60b35c6c76a8d9866a61047fe0077b33dda94e19c9893b83951a4482d2",
          "sha256": "66abce66c50f9fb272be672944da26740563d521ddd4ae053008b6548d50622e",
          "sha1": "5a510efd672f7dedef09bebdd6f6e8bbe1cc01b4",
          "md5": "52a2136ebae7364aa1a657f65b4017f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.13.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.25.0"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.23"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.7.jar",
          "url": "spring-boot-buildpack-platform-3.3.7.jar",
          "size": 295972,
          "sha512": "ae8aae4bf9db5b29f4b108e9be83fbd95b336c0fc583a6a9ba0a7323fec92f83f601bd60b35c6c76a8d9866a61047fe0077b33dda94e19c9893b83951a4482d2",
          "sha256": "66abce66c50f9fb272be672944da26740563d521ddd4ae053008b6548d50622e",
          "sha1": "5a510efd672f7dedef09bebdd6f6e8bbe1cc01b4",
          "md5": "52a2136ebae7364aa1a657f65b4017f8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.7-javadoc.jar",
          "url": "spring-boot-buildpack-platform-3.3.7-javadoc.jar",
          "size": 420461,
          "sha512": "af067720ed197094bbd0fddd3ecc4bab47ffe202d8520e174eadad3eb7d195c02e6b2d6144c7c7f5b0816a75dedbae6388fc0339b2637cf7f38794ed75a4aa7b",
          "sha256": "d6cdb8b6cff2d784dcb76a9ef2c0a71b9b95f0a3e8a0334222e7088ee0bb6820",
          "sha1": "45788967cd08bd13d3b7c25e60622beb52f348ce",
          "md5": "f3e1e2efcbe2c3773969b2dcddb5351c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-3.3.7-sources.jar",
          "url": "spring-boot-buildpack-platform-3.3.7-sources.jar",
          "size": 179449,
          "sha512": "a99b1c09e022ed445e491e6f2a1643073dbb64aa6f812a24184464b24855055320ab271b02e26d03c7f5073259d8d4004979b4e07eaa98575adf543aebf710fc",
          "sha256": "91cf60c116ea1f4e7dd2a921a1f629a65d20c9c7f571c7e2a64321638065920c",
          "sha1": "7390976901640f3b586820895f3cae066d9a3642",
          "md5": "9a6a42994bd67a226beaf3c96c6caea6"
        }
      ]
    }
  ]
}
