{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts.java-logging",
    "module": "logging-appinsights",
    "version": "6.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "com.microsoft.azure",
          "module": "applicationinsights-logging-logback",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.microsoft.azure",
          "module": "applicationinsights-spring-boot-starter",
          "version": {
            "requires": "2.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "logging-appinsights-6.1.9.jar",
          "url": "logging-appinsights-6.1.9.jar",
          "size": 4640,
          "sha512": "3751daa814a7ca161818c497bd51e20768982d71cb72b406ef4ef5c0633841ad2e5dfbceb37d201e03ade2411ea8adac4f3245ae6a881971b132b31186f790ee",
          "sha256": "8896de358c694a1fdbbc0c5c424efbd0286545d3af2eb8af380d08106351cd47",
          "sha1": "026ed730e0d0ca308f6318c34237f240c999e2df",
          "md5": "3185e05fbfbffb0498d006279740f442"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure"
        },
        {
          "group": "com.microsoft.azure",
          "module": "applicationinsights-logging-logback",
          "version": {
            "requires": "2.6.4"
          }
        },
        {
          "group": "com.microsoft.azure",
          "module": "applicationinsights-spring-boot-starter",
          "version": {
            "requires": "2.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "logging-appinsights-6.1.9.jar",
          "url": "logging-appinsights-6.1.9.jar",
          "size": 4640,
          "sha512": "3751daa814a7ca161818c497bd51e20768982d71cb72b406ef4ef5c0633841ad2e5dfbceb37d201e03ade2411ea8adac4f3245ae6a881971b132b31186f790ee",
          "sha256": "8896de358c694a1fdbbc0c5c424efbd0286545d3af2eb8af380d08106351cd47",
          "sha1": "026ed730e0d0ca308f6318c34237f240c999e2df",
          "md5": "3185e05fbfbffb0498d006279740f442"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-appinsights-6.1.9-javadoc.jar",
          "url": "logging-appinsights-6.1.9-javadoc.jar",
          "size": 97431,
          "sha512": "98258e82b308a08fd564c9dde26953cb796cff7623b8799f6bd1045ecb70079e23f830f4a3419329f05e99c020484bbc7c193a37ec35ff2cbf0426c7218af7ee",
          "sha256": "1c5f444f1119fd4f6cb7a105bf693be3865932572e18eae63a4541493daee9da",
          "sha1": "2d450f9108d710cbf156490bfcb608b41f2fa52c",
          "md5": "2d5927698580ab5886912c58bf421808"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-appinsights-6.1.9-sources.jar",
          "url": "logging-appinsights-6.1.9-sources.jar",
          "size": 4190,
          "sha512": "8a0152c8108ae85e4bf7d71165fec59c70bbca1aac981f680c9492678971c36a88e97e2b7485f7e02a76c203dde372bfeaad68c235a3e15e18cf699a05ade416",
          "sha256": "cb8f5cc764d1ace7f5ab6606835f95c3cd409bd4b833aa03640083810a0649db",
          "sha1": "cc0db09374857570fb2d41d0b6993c4998a72d65",
          "md5": "b72915f232ce506845c71af24c83299f"
        }
      ]
    }
  ]
}
