{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jdbc",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.3.7.jar",
          "url": "spring-boot-starter-jdbc-3.3.7.jar",
          "size": 4769,
          "sha512": "8a628712cedaeba8bff9bc00f2e022c81254ff8c04c85c13b7f5e99e09b05c90fd58f4ea1f6b4f22bbda7400b5aa00b11dbce7d49f3b31e19059fc6d927f60d0",
          "sha256": "5ce08008c440fc969ac98125884311c251fc72c39d4d36ffb9ef2f20620bbf08",
          "sha1": "fa187caa903899f628a0bb6f336d4810ebcbf999",
          "md5": "32ed5070012dfc846f05f72ca7207e35"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "com.zaxxer",
          "module": "HikariCP",
          "version": {
            "requires": "5.1.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.3.7.jar",
          "url": "spring-boot-starter-jdbc-3.3.7.jar",
          "size": 4769,
          "sha512": "8a628712cedaeba8bff9bc00f2e022c81254ff8c04c85c13b7f5e99e09b05c90fd58f4ea1f6b4f22bbda7400b5aa00b11dbce7d49f3b31e19059fc6d927f60d0",
          "sha256": "5ce08008c440fc969ac98125884311c251fc72c39d4d36ffb9ef2f20620bbf08",
          "sha1": "fa187caa903899f628a0bb6f336d4810ebcbf999",
          "md5": "32ed5070012dfc846f05f72ca7207e35"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-jdbc-3.3.7-javadoc.jar",
          "size": 4769,
          "sha512": "05f8fbe4c29bb57e32f8cae4b3545f5ff8f4ef47e678cf8691448cd07a47899765e9096efcfd62b37f43fe0d75b7036a1f9c93c668b6a4a5a156f2b6c6a2604b",
          "sha256": "fe122b17d557ff9b2f8ea1739a9354d13ff4eca0c74eefc005b301c3552af1ea",
          "sha1": "0c59273592c104c37cf6fa135d95a99770dc9be2",
          "md5": "5d56884969da7ea7c409670c393fc5a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jdbc-3.3.7-sources.jar",
          "url": "spring-boot-starter-jdbc-3.3.7-sources.jar",
          "size": 4769,
          "sha512": "05f8fbe4c29bb57e32f8cae4b3545f5ff8f4ef47e678cf8691448cd07a47899765e9096efcfd62b37f43fe0d75b7036a1f9c93c668b6a4a5a156f2b6c6a2604b",
          "sha256": "fe122b17d557ff9b2f8ea1739a9354d13ff4eca0c74eefc005b301c3552af1ea",
          "sha1": "0c59273592c104c37cf6fa135d95a99770dc9be2",
          "md5": "5d56884969da7ea7c409670c393fc5a3"
        }
      ]
    }
  ]
}
