{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/2.3.8/ktor-utils-2.3.8.module",
    "group": "io.ktor",
    "module": "ktor-utils",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-jvm-2.3.8.jar",
          "url": "ktor-utils-jvm-2.3.8.jar",
          "size": 335802,
          "sha512": "a39c4e9fe60338986bdeb66f8dcc0772ad64a40062793b2b85007757d54051de35ed1f392113c850ba55238c454e62b9a46bde831faa2e6ab713bb233efc9a8d",
          "sha256": "1ce33e66d42d74828c2e09c75a8f68310023cdc0d2920db77dc0ddc37bea8628",
          "sha1": "75232444a9983a8ecd87363450c48c184f9ce700",
          "md5": "a0a296a651ab4e8fcb5ecb2cb1a7be1f"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-jvm-2.3.8.jar",
          "url": "ktor-utils-jvm-2.3.8.jar",
          "size": 335802,
          "sha512": "a39c4e9fe60338986bdeb66f8dcc0772ad64a40062793b2b85007757d54051de35ed1f392113c850ba55238c454e62b9a46bde831faa2e6ab713bb233efc9a8d",
          "sha256": "1ce33e66d42d74828c2e09c75a8f68310023cdc0d2920db77dc0ddc37bea8628",
          "sha1": "75232444a9983a8ecd87363450c48c184f9ce700",
          "md5": "a0a296a651ab4e8fcb5ecb2cb1a7be1f"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-utils-jvm-2.3.8-sources.jar",
          "url": "ktor-utils-jvm-2.3.8-sources.jar",
          "size": 82851,
          "sha512": "0a0fd8dabeca76f4f2eeb8e77ea07be13c26051dfb936fe0f4f746dbaf7b541a7346b98b4b275a48987d01b295149ab324961c88d7649d47e2ec799acc306666",
          "sha256": "75f20a8a71ca04f3f536e9ce28552086e3cdc6125ea6af23083830c72005adb6",
          "sha1": "1cc8ca1ada85406a6ea4533911b2b5e396c80bbd",
          "md5": "7c94fd994c60e7561435c45cba1681d3"
        }
      ]
    }
  ]
}
