package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.model.Address;
import uk.gov.hmcts.reform.civil.model.caseflags.Flags;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.Party;
import uk.gov.hmcts.reform.civil.model.SolicitorReferences;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code ConfirmDetails} of event {@code ACKNOWLEDGEMENT_OF_SERVICE}.
 */
public final class ACKNOWLEDGEMENTOFSERVICEProdConfirmDetailsPage {
    private ACKNOWLEDGEMENTOFSERVICEProdConfirmDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("ConfirmDetails");
        fields.pageLabel("Defendant's legal representative's reference (optional)");
        fields.complex(CaseData::getSolicitorReferences)
                    .optional(SolicitorReferences::getRespondentSolicitor1Reference).done()
                    .caseEventFieldLabel(" ");
        fields.readonlyNoSummary(CaseData::getRespondent1OrganisationPolicy);
        fields.complex(CaseData::getRespondent1, false)
                    .optional(Party::getIndividualDateOfBirth)
                    .eventLabel("Defendant's date of birth")
                    .eventHint("You must enter this if you know it.")
                    .optional(Party::getSoleTraderDateOfBirth)
                    .eventLabel("Defendant's date of birth")
                    .eventHint("You must enter this if you know it.")
                    .optional(Party::getFlags)
                    .fieldShowCondition("respondent1=\"DO_NOT_SHOW_IN_UI\"")
                    .complex(Party::getFlags)
                    .optional(Flags::getRoleOnCase)
                    .fieldShowCondition("respondent1=\"DO_NOT_SHOW_IN_UI\"").done()
                    .complex(Party::getFlags)
                    .optional(Flags::getPartyName)
                    .fieldShowCondition("respondent1=\"DO_NOT_SHOW_IN_UI\"").done().done()
                    .caseEventFieldLabel(" ");
        fields.complex(CaseData::getRespondent2, false)
                    .optional(Party::getIndividualDateOfBirth)
                    .eventLabel("Second defendant's date of birth")
                    .eventHint("You must enter this if you know it.")
                    .optional(Party::getSoleTraderDateOfBirth)
                    .eventLabel("Second defendant's date of birth")
                    .eventHint("You must enter this if you know it.")
                    .optional(Party::getFlags)
                    .fieldShowCondition("respondent2=\"DO_NOT_SHOW_IN_UI\"")
                    .complex(Party::getFlags)
                    .optional(Flags::getRoleOnCase)
                    .fieldShowCondition("respondent2=\"DO_NOT_SHOW_IN_UI\"").done()
                    .complex(Party::getFlags)
                    .optional(Flags::getPartyName)
                    .fieldShowCondition("respondent2=\"DO_NOT_SHOW_IN_UI\"").done().done()
                    .fieldShowCondition("addRespondent2 = \"Yes\" AND respondent2SameLegalRepresentative = \"Yes\"")
                    .caseEventFieldLabel(" ");
        fields.mandatory(CaseData::getSpecAoSRespondentCorrespondenceAddressRequired);
        fields.complex(CaseData::getSpecAoSRespondentCorrespondenceAddressdetails)
                    .mandatory(Address::getAddressLine1)
                    .optional(Address::getAddressLine2)
                    .optional(Address::getAddressLine3)
                    .optional(Address::getPostTown)
                    .optional(Address::getCounty)
                    .optional(Address::getCountry)
                    .mandatory(Address::getPostCode).done()
                    .fieldShowCondition("specAoSRespondentCorrespondenceAddressRequired=\"No\"");
    }
}
