package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.model.Address;
import uk.gov.hmcts.reform.ccd.model.OrganisationPolicy;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Respondent1SolicitorEmail} of event {@code CHANGE_SOLICITOR_EMAIL}.
 */
public final class CHANGESOLICITOREMAILProdRespondent1SolicitorEmailPage {
    private CHANGESOLICITOREMAILProdRespondent1SolicitorEmailPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Respondent1SolicitorEmail");
        fields.pageLabel("Defendant legal representative’s address");
        fields.showCondition("isRespondent1=\"Yes\"");
        fields.readonly(CaseData::getIsRespondent1)
                    .fieldShowCondition("respondentSolicitor1EmailAddress=\"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getIsRespondent2)
                    .fieldShowCondition("respondentSolicitor1EmailAddress=\"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getIsApplicant1)
                    .fieldShowCondition("respondentSolicitor1EmailAddress=\"DO_NOT_SHOW_IN_UI\"");
        fields.readonly(CaseData::getAmendRespondent1SolicitorEmailLabel);
        fields.mandatory(CaseData::getRespondentSolicitor1EmailAddress)
                    .caseEventFieldLabel("Defendant's legal representative's email address");
        fields.complex(CaseData::getRespondent1OrganisationPolicy)
                    .optional(OrganisationPolicy::getOrgPolicyReference)
                    .eventLabel("Defendant's legal representative's reference").done();
        fields.readonly(CaseData::getRespondentSolicitor1AddressLabel);
        fields.mandatory(CaseData::getRespondentSolicitor1ServiceAddressRequired);
        fields.complex(CaseData::getRespondentSolicitor1ServiceAddress)
                    .mandatory(Address::getAddressLine1)
                    .optional(Address::getAddressLine2)
                    .optional(Address::getAddressLine3)
                    .optional(Address::getPostTown)
                    .optional(Address::getCounty)
                    .optional(Address::getCountry)
                    .mandatory(Address::getPostCode).done()
                    .fieldShowCondition("respondentSolicitor1ServiceAddressRequired=\"Yes\"")
                    .caseEventFieldLabel(" ");
        fields.readonly(CaseData::getSpecRespondentCorrespondenceAddressdetails)
                    .fieldShowCondition("respondentSolicitor1ServiceAddress=\"DO NOT SHOW UI\"")
                    .caseEventFieldLabel(" ");
    }
}
