package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.model.Address;
import uk.gov.hmcts.reform.ccd.model.OrganisationPolicy;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Respondent2SolicitorEmail} of event {@code CHANGE_SOLICITOR_EMAIL}.
 */
public final class CHANGESOLICITOREMAILNonprodRespondent2SolicitorEmailPage {
    private CHANGESOLICITOREMAILNonprodRespondent2SolicitorEmailPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Respondent2SolicitorEmail");
        fields.pageLabel("Defendant legal representative’s address");
        fields.showCondition("isRespondent2=\"Yes\" AND isRespondent1=\"No\"");
        fields.readonly(CaseData::getAmendRespondent2SolicitorEmailLabel);
        fields.mandatory(CaseData::getRespondentSolicitor2EmailAddress)
                    .caseEventFieldLabel("Second Defendant's legal representative's email address");
        fields.complex(CaseData::getRespondent2OrganisationPolicy)
                    .optional(OrganisationPolicy::getOrgPolicyReference)
                    .eventLabel("Defendant's legal representative's reference").done();
        fields.readonly(CaseData::getRespondentSolicitor2AddressLabel);
        fields.mandatory(CaseData::getRespondentSolicitor2ServiceAddressRequired);
        fields.complex(CaseData::getRespondentSolicitor2ServiceAddress)
                    .mandatory(Address::getAddressLine1)
                    .optional(Address::getAddressLine2)
                    .optional(Address::getAddressLine3)
                    .optional(Address::getPostTown)
                    .optional(Address::getCounty)
                    .optional(Address::getCountry)
                    .mandatory(Address::getPostCode).done()
                    .fieldShowCondition("respondentSolicitor2ServiceAddressRequired=\"Yes\"")
                    .caseEventFieldLabel(" ");
        fields.readonly(CaseData::getSpecRespondent2CorrespondenceAddressdetails)
                    .fieldShowCondition("respondentSolicitor2ServiceAddress=\"DO NOT SHOW UI\"")
                    .caseEventFieldLabel(" ");
    }
}
