package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Applicant1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Applicant2DQ;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code DraftDirections} of event {@code CLAIMANT_RESPONSE}.
 */
public final class CLAIMANTRESPONSEDraftDirectionsPage {
    private CLAIMANTRESPONSEDraftDirectionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("DraftDirections");
        fields.showCondition("respondent1ClaimResponseType=\"FULL_DEFENCE\" AND applicantsProceedIntention = \"Yes\"");
        fields.readonlyNoSummary(CaseData::getApplicant1DQDraftDirectionsLabel)
                    .fieldShowCondition("claimant2ResponseFlag=\"No\"")
                    .publish(false);
        fields.complex(CaseData::getApplicant1DQ)
                    .mandatory(Applicant1DQ::getApplicant1DQDraftDirections)
                    .fieldShowCondition("claimant2ResponseFlag=\"No\"")
                    .publish(false).done();
        fields.readonlyNoSummary(CaseData::getApplicant2DQDraftDirectionsLabel)
                    .fieldShowCondition("claimant2ResponseFlag=\"Yes\"")
                    .publish(false);
        fields.complex(CaseData::getApplicant2DQ)
                    .mandatory(Applicant2DQ::getApplicant2DQDraftDirections)
                    .fieldShowCondition("claimant2ResponseFlag=\"Yes\"")
                    .publish(false).done();
    }
}
