package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Applicant1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Respondent1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Respondent2DQ;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Language} of event {@code CLAIMANT_RESPONSE_SPEC}.
 */
public final class CLAIMANTRESPONSESPECLanguagePage {
    private CLAIMANTRESPONSESPECLanguagePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Language");
        fields.showCondition("applicantDefenceResponseDocumentAndDQFlag =\"Yes\"");
        fields.complex(CaseData::getApplicant1DQ)
                    .optional(Applicant1DQ::getApplicant1DQLanguage)
                    .publish(false).done();
        fields.readonlyNoSummary(CaseData::getClaimantDQLanguageMediationHint)
                    .fieldShowCondition("responseClaimTrack = \"SMALL_CLAIM\"")
                    .publish(false);
        fields.complex(CaseData::getRespondent1DQ)
                    .readonlyNoSummary(Respondent1DQ::getRespondent1DQLanguage)
                    .fieldShowCondition("respondent1ClaimResponseTypeForSpec=\"DO NOT SHOW IN UI\"").done();
        fields.complex(CaseData::getRespondent2DQ)
                    .readonlyNoSummary(Respondent2DQ::getRespondent2DQLanguage)
                    .fieldShowCondition("respondent1ClaimResponseTypeForSpec=\"DO NOT SHOW IN UI\"").done();
    }
}
