package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Witness;
import uk.gov.hmcts.reform.civil.model.dq.Witnesses;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code SmallClaimWitnesses} of event {@code CLAIMANT_RESPONSE_SPEC}.
 */
public final class CLAIMANTRESPONSESPECSmallClaimWitnessesPage {
    private CLAIMANTRESPONSESPECSmallClaimWitnessesPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("SmallClaimWitnesses");
        fields.showCondition("applicantDefenceResponseDocumentAndDQFlag =\"Yes\" AND responseClaimTrack =\"SMALL_CLAIM\"");
        fields.readonlyNoSummary(CaseData::getApplicant1SmallClaimWitnessesLabel)
                    .publish(false);
        fields.mandatory(CaseData::getApplicant1ClaimWitnesses)
                    .publish(false);
        fields.complex(CaseData::getApplicant1DQWitnessesSmallClaim)
                    .mandatory(Witnesses::getWitnessesToAppear)
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getFirstName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getLastName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getPhoneNumber).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEmailAddress).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getReasonForWitness).done().done();
    }
}
