package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.CaseDataLiP;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code WorkAllocationIntegrationFields} of event {@code COURT_OFFICER_ORDER}.
 */
public final class COURTOFFICERORDERWorkAllocationIntegrationFieldsPage {
    private COURTOFFICERORDERWorkAllocationIntegrationFieldsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("WorkAllocationIntegrationFields");
        fields.showCondition("courtOfficerGiveReasonsComplex=\"DONOTSHOW\"");
        fields.readonly(CaseData::getClaimantBilingualLanguagePreference);
        fields.complex(CaseData::getCaseDataLiP)
                    .readonly(CaseDataLiP::getRespondent1LiPResponse).done();
        fields.readonly(CaseData::getApplicant1Represented);
        fields.readonly(CaseData::getRespondent1Represented);
        fields.readonly(CaseData::getHmcEaCourtLocation);
        fields.readonly(CaseData::getAllocatedTrack);
        fields.readonly(CaseData::getResponseClaimTrack);
    }
}
