package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.finalorders.CaseHearingLengthElement;
import uk.gov.hmcts.reform.civil.model.finalorders.DatesFinalOrders;
import uk.gov.hmcts.reform.civil.model.finalorders.FinalOrderFurtherHearing;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code PopulateOrder} of event {@code COURT_OFFICER_ORDER}.
 */
public final class COURTOFFICERORDERPopulateOrderPage {
    private COURTOFFICERORDERPopulateOrderPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("PopulateOrder");
        fields.pageLabel("Make an order");
        fields.readonlyNoSummary(CaseData::getCaseParticipants)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getCourtOfficerOrderedLabel)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getCourtOfficerOrdered)
                    .publish(false);
        fields.complex(CaseData::getCourtOfficerFurtherHearingComplex, false)
                    .readonly(FinalOrderFurtherHearing::getLabel)
                    .readonly(FinalOrderFurtherHearing::getListFromLabel)
                    .mandatory(FinalOrderFurtherHearing::getListFromDate)
                    .noHintText()
                    .readonly(FinalOrderFurtherHearing::getDateToLabel)
                    .optional(FinalOrderFurtherHearing::getDateToDate)
                    .noHintText()
                    .readonly(FinalOrderFurtherHearing::getLengthLabel)
                    .mandatory(FinalOrderFurtherHearing::getLengthList)
                    .mandatory(FinalOrderFurtherHearing::getLengthListOther)
                    .mandatory(FinalOrderFurtherHearing::getDatesToAvoidLabel)
                    .mandatory(FinalOrderFurtherHearing::getDatesToAvoidYesNo)
                    .mandatory(FinalOrderFurtherHearing::getDatesToAvoidDateDropdown)
                    .complex(FinalOrderFurtherHearing::getDatesToAvoidDateDropdown)
                    .mandatory(DatesFinalOrders::getDatesToAvoidDates).done()
                    .readonly(FinalOrderFurtherHearing::getAlternativeHearingLabel)
                    .mandatory(FinalOrderFurtherHearing::getHearingLocationList)
                    .readonly(FinalOrderFurtherHearing::getAlternativeHearingDropdownLabel)
                    .mandatory(FinalOrderFurtherHearing::getAlternativeHearingList)
                    .readonly(FinalOrderFurtherHearing::getHearingMethodLabel)
                    .mandatory(FinalOrderFurtherHearing::getHearingMethodList)
                    .noHintText()
                    .readonly(FinalOrderFurtherHearing::getHearingNotesLabel)
                    .optional(FinalOrderFurtherHearing::getHearingNotesText)
                    .noHintText()
                    .complex(FinalOrderFurtherHearing::getLengthListOther)
                    .readonly(CaseHearingLengthElement::getLengthListOtherLabel).done()
                    .complex(FinalOrderFurtherHearing::getLengthListOther)
                    .complexMember(CaseHearingLengthElement::getLengthListOtherDays)
                    .noHintText().done()
                    .complex(FinalOrderFurtherHearing::getLengthListOther)
                    .complexMember(CaseHearingLengthElement::getLengthListOtherHours)
                    .noHintText().done()
                    .complex(FinalOrderFurtherHearing::getLengthListOther)
                    .complexMember(CaseHearingLengthElement::getLengthListOtherMinutes)
                    .noHintText().done().done();
        fields.readonlyNoSummary(CaseData::getCourtOfficerGiveReasonsLabel)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getCourtOfficerGiveReasonsYesNo)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getCourtOfficerGiveReasonsComplex)
                    .fieldShowCondition("courtOfficerGiveReasonsYesNo = \"Yes\"")
                    .publish(false);
    }
}
