package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.sdo.FastTrackJudgesRecital;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2AddendumReport;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2DisclosureOfDocuments;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2EvidenceAcousticEngineer;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2ExpertEvidence;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2FastTrackAltDisputeResolution;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2FurtherAudiogram;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2PermissionToRelyOnExpert;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2QuestionsClaimantExpert;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2QuestionsToEntExpert;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2Settlement;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2VariationOfDirections;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Field placements for page {@code SdoR2FastTrack} of event {@code CREATE_SDO} (part 1 of 2).
 */
public final class CREATESDOSdoR2FastTrackPageFields1 {
    private CREATESDOSdoR2FastTrackPageFields1() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.readonlyNoSummary(CaseData::getSdoPartiesName)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSdoWarningDateFormat)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSdoWarning)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSdoJudgesRecitalLbl)
                    .publish(false);
        fields.complex(CaseData::getSdoFastTrackJudgesRecital, false)
                    .readonly(FastTrackJudgesRecital::getLabel)
                    .mandatory(FastTrackJudgesRecital::getInput).done();
        fields.readonlyNoSummary(CaseData::getSdoAllocation)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSdoAltDisputeResolutionLbl)
                    .publish(false);
        fields.complex(CaseData::getSdoAltDisputeResolution, false)
                    .mandatory(SdoR2FastTrackAltDisputeResolution::getIncludeInOrderToggle)
                    .readonly(SdoR2FastTrackAltDisputeResolution::getLabel).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorVariationOfDirections)
                    .publish(false);
        fields.complex(CaseData::getSdoVariationOfDirections, false)
                    .mandatory(SdoR2VariationOfDirections::getIncludeInOrderToggle)
                    .readonly(SdoR2VariationOfDirections::getLabel).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorSettlement)
                    .publish(false);
        fields.complex(CaseData::getSdoR2Settlement, false)
                    .mandatory(SdoR2Settlement::getIncludeInOrderToggle)
                    .readonly(SdoR2Settlement::getLabel).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorDisclosureOfDocument)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2DisclosureOfDocumentsToggle)
                    .publish(false);
        fields.complex(CaseData::getSdoR2DisclosureOfDocuments, false)
                    .mandatory(SdoR2DisclosureOfDocuments::getLabel)
                    .mandatory(SdoR2DisclosureOfDocuments::getStandardDisclosureTxt)
                    .mandatory(SdoR2DisclosureOfDocuments::getStandardDisclosureDate)
                    .mandatory(SdoR2DisclosureOfDocuments::getInspectionLabel)
                    .mandatory(SdoR2DisclosureOfDocuments::getInspectionTxt)
                    .mandatory(SdoR2DisclosureOfDocuments::getInspectionDate)
                    .mandatory(SdoR2DisclosureOfDocuments::getRequestsWillBeCompiledLabel).done()
                    .fieldShowCondition("sdoR2DisclosureOfDocumentsToggle = \"INCLUDE\"");
        fields.readonlyNoSummary(CaseData::getSdoSeparatorWitnessesOfFact)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorWitnessesOfFactToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2WitnessesOfFact)
                    .fieldShowCondition("sdoR2SeparatorWitnessesOfFactToggle = \"INCLUDE\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getSdoSeparatorExpertEvidence)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorExpertEvidenceToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2ExpertEvidence)
                    .fieldShowCondition("sdoR2SeparatorExpertEvidenceToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2ExpertEvidence)
                    .readonly(SdoR2ExpertEvidence::getLabel)
                    .mandatory(SdoR2ExpertEvidence::getSdoClaimantPermissionToRelyTxt).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorAddendumReport)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorAddendumReportToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2AddendumReport)
                    .fieldShowCondition("sdoR2SeparatorAddendumReportToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2AddendumReport)
                    .readonly(SdoR2AddendumReport::getLabel)
                    .mandatory(SdoR2AddendumReport::getSdoAddendumReportTxt)
                    .mandatory(SdoR2AddendumReport::getSdoAddendumReportDate).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorFurtherAudiogram)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorFurtherAudiogramToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2FurtherAudiogram)
                    .fieldShowCondition("sdoR2SeparatorFurtherAudiogramToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2FurtherAudiogram)
                    .readonly(SdoR2FurtherAudiogram::getSdoClaimantShallUndergoLbl)
                    .mandatory(SdoR2FurtherAudiogram::getSdoClaimantShallUndergoTxt)
                    .mandatory(SdoR2FurtherAudiogram::getSdoClaimantShallUndergoDate)
                    .readonly(SdoR2FurtherAudiogram::getSdoServiceReportLbl)
                    .mandatory(SdoR2FurtherAudiogram::getSdoServiceReportTxt)
                    .mandatory(SdoR2FurtherAudiogram::getSdoServiceReportDate).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorQuestionsClaimantExpert)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorQuestionsClaimantExpertToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2QuestionsClaimantExpert)
                    .fieldShowCondition("sdoR2SeparatorQuestionsClaimantExpertToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2QuestionsClaimantExpert)
                    .readonly(SdoR2QuestionsClaimantExpert::getSdoDefendantMayAskLbl)
                    .mandatory(SdoR2QuestionsClaimantExpert::getSdoDefendantMayAskTxt)
                    .mandatory(SdoR2QuestionsClaimantExpert::getSdoDefendantMayAskDate)
                    .readonly(SdoR2QuestionsClaimantExpert::getSdoQuestionsShallBeAnsweredLbl)
                    .mandatory(SdoR2QuestionsClaimantExpert::getSdoQuestionsShallBeAnsweredTxt)
                    .mandatory(SdoR2QuestionsClaimantExpert::getSdoQuestionsShallBeAnsweredDate)
                    .readonly(SdoR2QuestionsClaimantExpert::getSdoUploadedToDigitalPortalLbl)
                    .mandatory(SdoR2QuestionsClaimantExpert::getSdoUploadedToDigitalPortalTxt).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorPermissionToRelyOnExpert)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorPermissionToRelyOnExpertToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2PermissionToRelyOnExpert)
                    .fieldShowCondition("sdoR2SeparatorPermissionToRelyOnExpertToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2PermissionToRelyOnExpert)
                    .readonly(SdoR2PermissionToRelyOnExpert::getLabel)
                    .mandatory(SdoR2PermissionToRelyOnExpert::getSdoPermissionToRelyOnExpertTxt)
                    .mandatory(SdoR2PermissionToRelyOnExpert::getSdoPermissionToRelyOnExpertDate)
                    .readonly(SdoR2PermissionToRelyOnExpert::getSdoJointMeetingOfExpertsLbl)
                    .mandatory(SdoR2PermissionToRelyOnExpert::getSdoJointMeetingOfExpertsTxt)
                    .mandatory(SdoR2PermissionToRelyOnExpert::getSdoJointMeetingOfExpertsDate)
                    .readonly(SdoR2PermissionToRelyOnExpert::getSdoUploadedToDigitalPortalLbl)
                    .mandatory(SdoR2PermissionToRelyOnExpert::getSdoUploadedToDigitalPortalTxt).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorEvidenceAcousticEngineer)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorEvidenceAcousticEngineerToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2EvidenceAcousticEngineer)
                    .fieldShowCondition("sdoR2SeparatorEvidenceAcousticEngineerToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2EvidenceAcousticEngineer)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoEvidenceAcousticEngineerTxt)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoInstructionOfTheExpertLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoInstructionOfTheExpertTxt)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoInstructionOfTheExpertDate)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoInstructionOfTheExpertTxtArea)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoExpertReportLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoExpertReportTxt)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoExpertReportDate)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoExpertReportDigitalPortalLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoExpertReportDigitalPortalTxt)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoWrittenQuestionsLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoWrittenQuestionsTxt)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoWrittenQuestionsDate)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoWrittenQuestionsDigitalPortalLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoWrittenQuestionsDigitalPortalTxt)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoRepliesLbl)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoRepliesTheExpertLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoRepliesTxt)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoRepliesDate)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoRepliesDigitalPortalLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoRepliesDigitalPortalTxt)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoServiceOfOrderLbl)
                    .mandatory(SdoR2EvidenceAcousticEngineer::getSdoServiceOfOrderTxt)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoExpertMayApplyMainLbl)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoExpertMayApplyLbl)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoFeesAndExpensesMainLbl)
                    .readonly(SdoR2EvidenceAcousticEngineer::getSdoFeesAndExpensesLbl).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorQuestionsToEntExpert)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2SeparatorQuestionsToEntExpertToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2QuestionsToEntExpert)
                    .fieldShowCondition("sdoR2SeparatorQuestionsToEntExpertToggle = \"INCLUDE\"")
                    .publish(false);
        fields.complexScope(CaseData::getSdoR2QuestionsToEntExpert)
                    .readonly(SdoR2QuestionsToEntExpert::getSdoWrittenQuestionsLbl)
                    .mandatory(SdoR2QuestionsToEntExpert::getSdoWrittenQuestionsTxt)
                    .mandatory(SdoR2QuestionsToEntExpert::getSdoWrittenQuestionsDate)
                    .mandatory(SdoR2QuestionsToEntExpert::getSdoWrittenQuestionsDigPortalTxt)
                    .readonly(SdoR2QuestionsToEntExpert::getSdoQuestionsShallBeAnsweredLbl)
                    .mandatory(SdoR2QuestionsToEntExpert::getSdoQuestionsShallBeAnsweredTxt)
                    .mandatory(SdoR2QuestionsToEntExpert::getSdoQuestionsShallBeAnsweredDate)
                    .readonly(SdoR2QuestionsToEntExpert::getSdoShallBeUploadedLbl)
                    .mandatory(SdoR2QuestionsToEntExpert::getSdoShallBeUploadedTxt).done();
        fields.readonlyNoSummary(CaseData::getSdoSeparatorScheduleOfLoss)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2ScheduleOfLossToggle)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getSdoR2ScheduleOfLoss)
                    .fieldShowCondition("sdoR2ScheduleOfLossToggle = \"INCLUDE\"")
                    .publish(false);
    }
}
