package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingFinalDisposalHearing;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Field placements for page {@code DisposalHearing} of event {@code CREATE_SDO} (part 2 of 2).
 */
public final class CREATESDODisposalHearingPageFields2 {
    private CREATESDODisposalHearingPageFields2() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.complex(CaseData::getDisposalHearingFinalDisposalHearing, false)
                    .readonly(DisposalHearingFinalDisposalHearing::getLabel)
                    .mandatory(DisposalHearingFinalDisposalHearing::getInput)
                    .optional(DisposalHearingFinalDisposalHearing::getDate)
                    .mandatory(DisposalHearingFinalDisposalHearing::getTime).done()
                    .fieldShowCondition("disposalHearingFinalDisposalHearingToggle=\"DONT SHOW UI BEING UPDATED\"");
    }
}
