package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code SdoR2FastTrack} of event {@code CREATE_SDO}.
 */
public final class CREATESDOSdoR2FastTrackPage {
    private CREATESDOSdoR2FastTrackPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("SdoR2FastTrack");
        fields.pageLabel("Fast track noise induced hearing loss");
        fields.showCondition("setFastTrackFlag=\"Yes\" AND isSdoR2NewScreen=\"Yes\"");
        CREATESDOSdoR2FastTrackPageFields1.apply(fields);
        CREATESDOSdoR2FastTrackPageFields2.apply(fields);
    }
}
