package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code ClaimTimeline} of event {@code CREATE_CLAIM_SPEC}.
 */
public final class CREATECLAIMSPECClaimTimelinePage {
    private CREATECLAIMSPECClaimTimelinePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("ClaimTimeline");
        fields.showCondition("specClaimTimelineList = \"MANUAL\"");
        fields.readonlyNoSummary(CaseData::getSpecClaimTimeline);
        fields.mandatory(CaseData::getTimelineOfEvents);
    }
}
