package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.ccd.model.Organisation;
import uk.gov.hmcts.reform.ccd.model.OrganisationPolicy;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code SecondDefendantSolicitorOrganisation} of event {@code CREATE_CLAIM_SPEC}.
 */
public final class CREATECLAIMSPECSecondDefendantSolicitorOrganisationPage {
    private CREATECLAIMSPECSecondDefendantSolicitorOrganisationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("SecondDefendantSolicitorOrganisation");
        fields.pageLabel("Search for the second defendant's legal representative");
        fields.showCondition("specRespondent2Represented=\"Yes\" AND respondent2SameLegalRepresentative=\"No\"");
        fields.mandatory(CaseData::getRespondent2OrgRegistered);
        fields.complex(CaseData::getRespondent2OrganisationPolicy)
                    .complex(OrganisationPolicy::getOrganisation)
                    .mandatory(Organisation::getOrganisationID).done()
                    .complex(OrganisationPolicy::getOrganisation)
                    .optional(Organisation::getOrganisationName).done()
                    .optional(OrganisationPolicy::getOrgPolicyReference)
                    .optional(OrganisationPolicy::getOrgPolicyCaseAssignedRole)
                    .fieldShowCondition("claimType=\"IMPOSSIBLE_CLAIM_TYPE\"").done()
                    .fieldShowCondition("respondent2OrgRegistered=\"Yes\"");
    }
}
