package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.DisposalHearingClaimSettling;
import uk.gov.hmcts.reform.civil.model.DisposalHearingCosts;
import uk.gov.hmcts.reform.civil.model.DisposalHearingJudgementDeductionStatement;
import uk.gov.hmcts.reform.civil.model.DisposalHearingOrderAndHearingDetails;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingAddNewDirections;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingBundle;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingDisclosureOfDocuments;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingHearingTime;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingJudgementDeductionValue;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingJudgesRecital;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingMedicalEvidence;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingNotes;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingQuestionsToExperts;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingSchedulesOfLoss;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingWitnessOfFact;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalOrderWithoutHearing;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2WelshLanguageUsage;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Field placements for page {@code DisposalHearing} of event {@code CREATE_SDO} (part 1 of 2).
 */
public final class CREATESDODisposalHearingPageFields1 {
    private CREATESDODisposalHearingPageFields1() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.complex(CaseData::getDisposalHearingJudgesRecital, false)
                    .readonly(DisposalHearingJudgesRecital::getLabel)
                    .mandatory(DisposalHearingJudgesRecital::getInput).done();
        fields.complex(CaseData::getDisposalHearingJudgementDeductionStatement, false)
                    .readonly(DisposalHearingJudgementDeductionStatement::getLine)
                    .readonly(DisposalHearingJudgementDeductionStatement::getLabel).done()
                    .fieldShowCondition("drawDirectionsOrderRequired=\"Yes\"");
        fields.complex(CaseData::getDisposalHearingJudgementDeductionValue, false)
                    .readonly(DisposalHearingJudgementDeductionValue::getLabel)
                    .readonly(DisposalHearingJudgementDeductionValue::getText)
                    .readonly(DisposalHearingJudgementDeductionValue::getValue).done()
                    .fieldShowCondition("drawDirectionsOrderRequired=\"Yes\" AND drawDirectionsOrder.judgementSum!=\"\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingDisclosureOfDocumentsStartLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingDisclosureOfDocumentsTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingDisclosureOfDocumentsToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingDisclosureOfDocuments, false)
                    .readonly(DisposalHearingDisclosureOfDocuments::getLabel)
                    .mandatory(DisposalHearingDisclosureOfDocuments::getInput1)
                    .optional(DisposalHearingDisclosureOfDocuments::getDate1)
                    .mandatory(DisposalHearingDisclosureOfDocuments::getInput2)
                    .fieldShowCondition("input2=\"DO_NOT_SHOW_IN_UI\"")
                    .optional(DisposalHearingDisclosureOfDocuments::getDate2)
                    .fieldShowCondition("input2=\"DO_NOT_SHOW_IN_UI\"").done()
                    .fieldShowCondition("disposalHearingDisclosureOfDocumentsToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingDisclosureOfDocumentsEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingWitnessOfFactTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingWitnessOfFactToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingWitnessOfFact, false)
                    .readonly(DisposalHearingWitnessOfFact::getLabel)
                    .mandatory(DisposalHearingWitnessOfFact::getInput3)
                    .optional(DisposalHearingWitnessOfFact::getDate2)
                    .mandatory(DisposalHearingWitnessOfFact::getInput4)
                    .mandatory(DisposalHearingWitnessOfFact::getInput5)
                    .optional(DisposalHearingWitnessOfFact::getDate3)
                    .mandatory(DisposalHearingWitnessOfFact::getInput6).done()
                    .fieldShowCondition("disposalHearingWitnessOfFactToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingWitnessOfFactEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingMedicalEvidenceTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingMedicalEvidenceToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingMedicalEvidence, false)
                    .readonly(DisposalHearingMedicalEvidence::getLabel)
                    .mandatory(DisposalHearingMedicalEvidence::getInput)
                    .optional(DisposalHearingMedicalEvidence::getDate)
                    .fieldShowCondition("input1 = \"DO_NOT_SHOW_IN_UI\"").done()
                    .fieldShowCondition("disposalHearingMedicalEvidenceToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingMedicalEvidenceEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingQuestionsToExpertsTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingQuestionsToExpertsToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingQuestionsToExperts, false)
                    .readonly(DisposalHearingQuestionsToExperts::getLabel)
                    .readonly(DisposalHearingQuestionsToExperts::getText1)
                    .optional(DisposalHearingQuestionsToExperts::getDate)
                    .readonly(DisposalHearingQuestionsToExperts::getText2).done()
                    .fieldShowCondition("disposalHearingQuestionsToExpertsToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingQuestionsToExpertsEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingSchedulesOfLossTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingSchedulesOfLossToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingSchedulesOfLoss, false)
                    .readonly(DisposalHearingSchedulesOfLoss::getLabel)
                    .mandatory(DisposalHearingSchedulesOfLoss::getInput2)
                    .optional(DisposalHearingSchedulesOfLoss::getDate2)
                    .mandatory(DisposalHearingSchedulesOfLoss::getInput3)
                    .optional(DisposalHearingSchedulesOfLoss::getDate3)
                    .mandatory(DisposalHearingSchedulesOfLoss::getInput4)
                    .optional(DisposalHearingSchedulesOfLoss::getDate4)
                    .readonly(DisposalHearingSchedulesOfLoss::getText).done()
                    .fieldShowCondition("disposalHearingSchedulesOfLossToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingSchedulesOfLossEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingFinalDisposalHearingTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingFinalDisposalHearingToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingHearingTime, false)
                    .mandatory(DisposalHearingHearingTime::getInput)
                    .optional(DisposalHearingHearingTime::getDateFromLabel)
                    .mandatory(DisposalHearingHearingTime::getDateFrom)
                    .optional(DisposalHearingHearingTime::getDateToLabel)
                    .optional(DisposalHearingHearingTime::getDateTo)
                    .mandatory(DisposalHearingHearingTime::getTime)
                    .mandatory(DisposalHearingHearingTime::getOtherHours)
                    .fieldShowCondition("disposalHearingHearingTime.time = \"OTHER\"")
                    .mandatory(DisposalHearingHearingTime::getOtherMinutes)
                    .fieldShowCondition("disposalHearingHearingTime.time = \"OTHER\"").done()
                    .fieldShowCondition("disposalHearingFinalDisposalHearingToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingFinalDisposalHearingEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingMethodTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingBundleStartLine)
                    .fieldShowCondition("disposalHearingBundleToggle=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingBundleTitle)
                    .fieldShowCondition("disposalHearingBundleToggle=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingBundleToggle)
                    .fieldShowCondition("disposalHearingQuestionsToExpertsEndLine=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingBundle, false)
                    .readonly(DisposalHearingBundle::getLabel1)
                    .mandatory(DisposalHearingBundle::getInput)
                    .readonly(DisposalHearingBundle::getLabel2)
                    .mandatory(DisposalHearingBundle::getType).done()
                    .fieldShowCondition("disposalHearingBundleToggle=\"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingBundleEndLine)
                    .fieldShowCondition("disposalHearingBundleToggle=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingClaimSettlingTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingClaimSettlingToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingClaimSettling, false)
                    .readonly(DisposalHearingClaimSettling::getLabel)
                    .readonly(DisposalHearingClaimSettling::getText).done()
                    .fieldShowCondition("disposalHearingClaimSettlingToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingClaimSettlingEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingCostsTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingCostsToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingCosts, false)
                    .readonly(DisposalHearingCosts::getLabel)
                    .readonly(DisposalHearingCosts::getText).done()
                    .fieldShowCondition("disposalHearingCostsToggle=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getDisposalHearingCostsEndLine)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingAddNewDirections)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingAddNewDirections, DisposalHearingAddNewDirections.class)
                    .optional(DisposalHearingAddNewDirections::getDirectionComment).done();
        fields.readonlyNoSummary(CaseData::getDisposalHearingAddNewDirectionsEndLine)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingHearingNotesTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingHearingNotes)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getHearingMethodValuesDisposalHearing)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getDisposalHearingMethodInPerson)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingOrderAndHearingDetails, false)
                    .readonly(DisposalHearingOrderAndHearingDetails::getLabel)
                    .readonly(DisposalHearingOrderAndHearingDetails::getText)
                    .readonly(DisposalHearingOrderAndHearingDetails::getLine).done();
        fields.readonlyNoSummary(CaseData::getSdoR2DisposalHearingUseOfWelshLanguageTitle)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2DisposalHearingUseOfWelshToggle)
                    .publish(false);
        fields.complex(CaseData::getSdoR2DisposalHearingUseOfWelshLanguage, false)
                    .readonly(SdoR2WelshLanguageUsage::getDescription).done()
                    .fieldShowCondition("sdoR2DisposalHearingUseOfWelshToggle=\"SHOW\"");
        fields.mandatoryNoSummary(CaseData::getDisposalOrderWithoutHearing)
                    .publish(false);
        fields.complexScope(CaseData::getDisposalOrderWithoutHearing)
                    .readonly(DisposalOrderWithoutHearing::getLine)
                    .readonly(DisposalOrderWithoutHearing::getTitle)
                    .mandatory(DisposalOrderWithoutHearing::getInput).done();
        fields.complex(CaseData::getDisposalHearingNotes, false)
                    .readonly(DisposalHearingNotes::getLabel)
                    .mandatory(DisposalHearingNotes::getInput)
                    .mandatory(DisposalHearingNotes::getDate)
                    .readonly(DisposalHearingNotes::getLine).done()
                    .fieldShowCondition("disposalHearingCostsToggle=\"DONT SHOW IN UI\"");
    }
}
