package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code repaymentInformation} of event {@code DEFAULT_JUDGEMENT_SPEC}.
 */
public final class DEFAULTJUDGEMENTSPECRepaymentInformationPage {
    private DEFAULTJUDGEMENTSPECRepaymentInformationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("repaymentInformation");
        fields.showCondition("paymentTypeSelection = \"REPAYMENT_PLAN\"");
        fields.readonly(CaseData::getRepaymentDue)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getRepaymentDetailsLabel);
        fields.mandatory(CaseData::getRepaymentSuggestion);
        fields.mandatory(CaseData::getRepaymentFrequency);
        fields.mandatoryNoSummary(CaseData::getCurrentDatebox)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO_NOT_SHOW_IN_UI\"");
        fields.mandatory(CaseData::getRepaymentDate);
        fields.readonly(CaseData::getJoDefendantName1)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoDefendantName2)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoPaymentPlanSelected)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoRepaymentAmount)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoRepaymentFrequency)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoRepaymentStartDate)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoIssueDate)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoState)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoFullyPaymentMadeDate)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getJoRepaymentSummaryObject)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonly(CaseData::getJoIsDisplayInJudgmentTab)
                    .fieldShowCondition("repaymentDetailsLabel = \"DO NOT SHOW IN UI\"");
    }
}
