package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Upload} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECProdUploadPage {
    private DEFENDANTRESPONSESPECProdUploadPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Upload");
        fields.showCondition("showConditionFlags CONTAINS \"SOMEONE_DISPUTES\" OR showConditionFlags CONTAINS \"RESPONDENT_2_PAID_LESS\" OR showConditionFlags CONTAINS \"RESPONDENT_1_PAID_LESS\"");
        fields.readonly(CaseData::getSpecDefenceRouteUploadDocumentLabel)
                    .fieldShowCondition("showConditionFlags CONTAINS \"ONLY_RESPONDENT_1_DISPUTES\"");
        fields.readonly(CaseData::getSpecDefenceRouteUploadDocumentMPLabel)
                    .fieldShowCondition("showConditionFlags CONTAINS \"BOTH_RESPONDENTS_DISPUTE\"");
        fields.readonly(CaseData::getSpecDefenceRouteUploadDocumentLabelRespondent2)
                    .fieldShowCondition("showConditionFlags CONTAINS \"ONLY_RESPONDENT_2_DISPUTES\"");
        fields.readonly(CaseData::getSpecDefenceRouteUploadDocumentLabel2)
                    .fieldShowCondition("showConditionFlags CONTAINS \"RESPONDENT_1_PAID_LESS\"");
        fields.readonly(CaseData::getSpecDefenceRouteUploadDocumentLabel2Respondent2)
                    .fieldShowCondition("showConditionFlags CONTAINS \"RESPONDENT_2_PAID_LESS\"");
        fields.readonlyNoSummary(CaseData::getSpecDefenceRouteUploadDocumentLabel4)
                    .fieldShowCondition("showConditionFlags CONTAINS \"ONLY_RESPONDENT_1_DISPUTES\" OR showConditionFlags CONTAINS \"ONLY_RESPONDENT_2_DISPUTES\"  OR showConditionFlags CONTAINS \"BOTH_RESPONDENTS_DISPUTE\"");
        fields.readonlyNoSummary(CaseData::getSpecDefenceRouteUploadDocumentLabel3)
                    .fieldShowCondition("showConditionFlags CONTAINS \"RESPONDENT_2_PAID_LESS\" OR showConditionFlags CONTAINS \"RESPONDENT_1_PAID_LESS\"");
        fields.mandatory(CaseData::getDetailsOfWhyDoesYouDisputeTheClaim)
                    .fieldShowCondition("isRespondent1 = \"Yes\"");
        fields.mandatory(CaseData::getDetailsOfWhyDoesYouDisputeTheClaim2)
                    .fieldShowCondition("isRespondent2 = \"Yes\"");
        fields.readonly(CaseData::getSpecDefenceRouteUploadDocumentHelpLabel);
        fields.readonlyNoSummary(CaseData::getSpecDefenceRouteUploadDocumentHelpLabel2);
        fields.optional(CaseData::getRespondent1SpecDefenceResponseDocument)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\"");
        fields.optional(CaseData::getRespondent2SpecDefenceResponseDocument)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2SameLegalRepresentative !=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getSpecDisputesOrPartAdmission)
                    .fieldShowCondition("respondent1ClaimResponseTypeForSpec=\"DO NOT SHOW IN UI\"");
    }
}
