package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code HowToAddEmploymentDetails} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodHowToAddEmploymentDetailsPage {
    private DEFENDANTRESPONSESPECNonprodHowToAddEmploymentDetailsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("HowToAddEmploymentDetails");
        fields.showCondition("respondentClaimResponseTypeForSpecGeneric !=\"FULL_DEFENCE\" AND respondentClaimResponseTypeForSpecGeneric !=\"COUNTER_CLAIM\" AND defenceAdmitPartEmploymentTypeRequired =\"Yes\" AND respondToClaimAdmitPartEmploymentTypeLRspec CONTAINS \"EMPLOYED\" AND respondent1Copy.partyTypeDisplayValue !=\"Company\" AND respondent1Copy.partyTypeDisplayValue !=\"Organisation\"");
        fields.readonly(CaseData::getResponseClaimAdmitPartOfClaimEmploymentSpecLabel);
        fields.mandatory(CaseData::getResponseClaimAdmitPartEmployer)
                    .fieldShowCondition("isRespondent1 = \"Yes\"");
        fields.mandatory(CaseData::getResponseClaimAdmitPartEmployer2)
                    .fieldShowCondition("isRespondent2 = \"Yes\"");
    }
}
