package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Respondent1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Respondent2DQ;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code FixedRecoverableCostsIntermediate} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECProdFixedRecoverableCostsIntermediatePage {
    private DEFENDANTRESPONSESPECProdFixedRecoverableCostsIntermediatePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("FixedRecoverableCostsIntermediate");
        fields.showCondition("showConditionFlags CONTAINS \"SOMEONE_DISPUTES\" AND responseClaimTrack= \"INTERMEDIATE_CLAIM\"");
        fields.readonly(CaseData::getRespondentDQFixedRecoverableCostsIntermediateLabel);
        fields.complex(CaseData::getRespondent1DQ)
                    .optional(Respondent1DQ::getRespondent1DQFixedRecoverableCostsIntermediate)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\"")
                    .caseEventFieldLabel("Fixed Recoverable Costs").done();
        fields.complex(CaseData::getRespondent2DQ)
                    .optional(Respondent2DQ::getRespondent2DQFixedRecoverableCostsIntermediate)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2SameLegalRepresentative !=\"Yes\"")
                    .caseEventFieldLabel("Fixed Recoverable Costs").done();
    }
}
