package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.mediation.MediationContactInformation;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code MediationContactInformation} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodMediationContactInformationPage {
    private DEFENDANTRESPONSESPECNonprodMediationContactInformationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("MediationContactInformation");
        fields.pageLabel("Mediation contact information");
        fields.showCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\" OR showConditionFlags CONTAINS \"SOMEONE_DISPUTES\" AND responseClaimTrack = \"SMALL_CLAIM\" AND showCarmFields=\"Yes\" AND respondentClaimResponseTypeForSpecGeneric != \"FULL_ADMISSION\"");
        fields.readonlyNoSummary(CaseData::getContactDetailsLabel);
        fields.complex(CaseData::getResp1MediationContactInfo)
                    .mandatory(MediationContactInformation::getFirstName)
                    .mandatory(MediationContactInformation::getLastName)
                    .mandatory(MediationContactInformation::getEmailAddress)
                    .mandatory(MediationContactInformation::getTelephoneNumber).done()
                    .fieldShowCondition("isRespondent1 = \"Yes\"")
                    .caseEventFieldLabel("Mediation contact information")
                    .retainHiddenValue();
        fields.complex(CaseData::getResp2MediationContactInfo)
                    .mandatory(MediationContactInformation::getFirstName)
                    .mandatory(MediationContactInformation::getLastName)
                    .mandatory(MediationContactInformation::getEmailAddress)
                    .mandatory(MediationContactInformation::getTelephoneNumber).done()
                    .fieldShowCondition("isRespondent2 = \"Yes\"")
                    .caseEventFieldLabel("Mediation contact information")
                    .retainHiddenValue();
    }
}
