package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Witness;
import uk.gov.hmcts.reform.civil.model.dq.Witnesses;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code SmallClaimWitnesses} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodSmallClaimWitnessesPage {
    private DEFENDANTRESPONSESPECNonprodSmallClaimWitnessesPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("SmallClaimWitnesses");
        fields.showCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\" OR showConditionFlags CONTAINS \"SOMEONE_DISPUTES\" AND responseClaimTrack = \"SMALL_CLAIM\" AND respondentClaimResponseTypeForSpecGeneric != \"FULL_ADMISSION\"");
        fields.readonly(CaseData::getRespondent1SmallClaimWitnessesLabel);
        fields.complex(CaseData::getRespondent1DQWitnessesSmallClaim)
                    .mandatory(Witnesses::getWitnessesToAppear)
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getFirstName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getLastName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getPhoneNumber).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEmailAddress).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getReasonForWitness).done().done()
                    .fieldShowCondition("isRespondent1 = \"Yes\"");
        fields.complex(CaseData::getRespondent2DQWitnessesSmallClaim)
                    .mandatory(Witnesses::getWitnessesToAppear)
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getFirstName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getLastName).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getPhoneNumber).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .optional(Witness::getEmailAddress).done()
                    .complex(Witnesses::getDetails, Witness.class)
                    .mandatory(Witness::getReasonForWitness).done().done()
                    .fieldShowCondition("isRespondent2 = \"Yes\"");
    }
}
