package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Respondent1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Respondent2DQ;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code HearingSupport} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodHearingSupportPage {
    private DEFENDANTRESPONSESPECNonprodHearingSupportPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("HearingSupport");
        fields.showCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\" OR showConditionFlags CONTAINS \"SOMEONE_DISPUTES\" AND respondentClaimResponseTypeForSpecGeneric != \"FULL_ADMISSION\"");
        fields.complex(CaseData::getRespondent1DQ)
                    .mandatory(Respondent1DQ::getRespondent1DQHearingSupport)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\"")
                    .caseEventFieldLabel("Support with access needs").done();
        fields.complex(CaseData::getRespondent2DQ)
                    .mandatory(Respondent2DQ::getRespondent2DQHearingSupport)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2SameLegalRepresentative !=\"Yes\"")
                    .caseEventFieldLabel("Support with access needs").done();
        fields.readonlyNoSummary(CaseData::getDefendantDQSupportMediationHint)
                    .fieldShowCondition("responseClaimTrack = \"SMALL_CLAIM\"");
    }
}
