package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.RespondToClaim;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code defenceAdmittedPartRoute} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodDefenceAdmittedPartRoutePage {
    private DEFENDANTRESPONSESPECNonprodDefenceAdmittedPartRoutePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("defenceAdmittedPartRoute");
        fields.showCondition("showConditionFlags CONTAINS \"CURRENT_ADMITS_PART_OR_FULL\" AND showConditionFlags CONTAINS \"SHOW_ADMITTED_AMOUNT_SCREEN\" AND respondentResponseIsSame != \"No\"");
        fields.readonlyNoSummary(CaseData::getPartAdmit1v1Defendant)
                    .fieldShowCondition("respondent1ClaimResponseTypeForSpec=\"DO NOT SHOW IN UI\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(CaseData::getResponseToClaimAdmitPartTotalAmountWithInterestLabel1)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND specDefenceAdmittedRequired = \"No\" AND isRespondent1 = \"Yes\"");
        fields.readonlyNoSummary(CaseData::getResponseToClaimAdmitPartTotalAmountWithInterestLabel2)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND specDefenceAdmitted2Required = \"No\" AND isRespondent2 = \"Yes\"");
        fields.complex(CaseData::getRespondToAdmittedClaim)
                    .mandatory(RespondToClaim::getHowMuchWasPaidLabel)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric != \"PART_ADMISSION\"")
                    .mandatory(RespondToClaim::getHowMuchWasPaidWithInterestLabel)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric = \"PART_ADMISSION\"")
                    .mandatory(RespondToClaim::getHowMuchWasPaid)
                    .mandatory(RespondToClaim::getWhenWasThisAmountPaid)
                    .noHintText()
                    .mandatory(RespondToClaim::getHowWasThisAmountPaid)
                    .mandatory(RespondToClaim::getHowWasThisAmountPaidOther)
                    .fieldShowCondition("respondToAdmittedClaim.howWasThisAmountPaid = \"OTHER\"").done()
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND specDefenceAdmittedRequired = \"Yes\"  AND isRespondent1 = \"Yes\"");
        fields.complex(CaseData::getRespondToAdmittedClaim2)
                    .mandatory(RespondToClaim::getHowMuchWasPaidLabel)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric != \"PART_ADMISSION\"")
                    .mandatory(RespondToClaim::getHowMuchWasPaidWithInterestLabel)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric = \"PART_ADMISSION\"")
                    .mandatory(RespondToClaim::getHowMuchWasPaid)
                    .mandatory(RespondToClaim::getWhenWasThisAmountPaid)
                    .noHintText()
                    .mandatory(RespondToClaim::getHowWasThisAmountPaid)
                    .mandatory(RespondToClaim::getHowWasThisAmountPaidOther)
                    .fieldShowCondition("respondToAdmittedClaim2.howWasThisAmountPaid = \"OTHER\"").done()
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND specDefenceAdmitted2Required = \"Yes\"  AND isRespondent2 = \"Yes\"");
        fields.mandatory(CaseData::getRespondToAdmittedClaimOwingAmount)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND specDefenceAdmittedRequired = \"No\" AND isRespondent1 = \"Yes\"");
        fields.mandatory(CaseData::getRespondToAdmittedClaimOwingAmount2)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND specDefenceAdmitted2Required = \"No\" AND isRespondent2 = \"Yes\"");
        fields.readonlyNoSummary(CaseData::getRespondToAdmittedClaimOwingAmountPounds)
                    .fieldShowCondition("specAoSRespondentDetails = \"DO_NOT_SHOW_IN_UI\" OR respondent1ClaimResponseTypeForSpec = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getRespondToAdmittedClaimOwingAmountPounds2)
                    .fieldShowCondition("specAoSRespondentDetails = \"DO_NOT_SHOW_IN_UI\" OR respondent1ClaimResponseTypeForSpec = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonly(CaseData::getSpecDefenceRouteAdmittedAmountClaimedLabel)
                    .fieldShowCondition("showConditionFlags CONTAINS \"RESPONDENT_1_ADMITS_PART_OR_FULL\" AND defendantSingleResponseToBothClaimants != \"Yes\" AND showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\" AND respondentResponseIsSame != \"Yes\"");
        fields.readonly(CaseData::getSpecDefenceRouteAdmittedAmountClaimed2Label)
                    .fieldShowCondition("showConditionFlags CONTAINS \"RESPONDENT_2_ADMITS_PART_OR_FULL\" AND defendantSingleResponseToBothClaimants != \"Yes\" AND showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondentResponseIsSame != \"Yes\"");
        fields.readonly(CaseData::getSpecDefenceRouteAdmittedAmountClaimedLabel2V1)
                    .fieldShowCondition("specFullAdmissionOrPartAdmission=\"Yes\" AND defendantSingleResponseToBothClaimants = \"Yes\"");
        fields.readonly(CaseData::getSpecDefenceRouteAdmittedAmountClaimedMPLabel)
                    .fieldShowCondition("respondentResponseIsSame =\"Yes\"");
        fields.mandatory(CaseData::getSpecDefenceAdmittedRequired)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND isRespondent1 = \"Yes\"");
        fields.mandatory(CaseData::getSpecDefenceAdmitted2Required)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"PART_ADMISSION\" AND showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2SameLegalRepresentative!=\"Yes\"");
        fields.mandatory(CaseData::getSpecDefenceFullAdmittedRequired)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"FULL_ADMISSION\" AND isRespondent1 = \"Yes\"");
        fields.mandatory(CaseData::getSpecDefenceFullAdmitted2Required)
                    .fieldShowCondition("respondentClaimResponseTypeForSpecGeneric=\"FULL_ADMISSION\" AND isRespondent2 = \"Yes\"");
    }
}
