package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Respondent1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Respondent2DQ;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code DisclosureOfElectronicDocumentsLRspec} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodDisclosureOfElectronicDocumentsLRspecPage {
    private DEFENDANTRESPONSESPECNonprodDisclosureOfElectronicDocumentsLRspecPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("DisclosureOfElectronicDocumentsLRspec");
        fields.showCondition("responseClaimTrack != \"SMALL_CLAIM\" AND showConditionFlags CONTAINS \"SOMEONE_DISPUTES\"");
        fields.complex(CaseData::getRespondent1DQ)
                    .mandatory(Respondent1DQ::getSpecRespondent1DQDisclosureOfElectronicDocuments)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\"")
                    .caseEventFieldLabel("Disclosure of electronic documents").done();
        fields.complex(CaseData::getRespondent2DQ)
                    .mandatory(Respondent2DQ::getSpecRespondent2DQDisclosureOfElectronicDocuments)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2SameLegalRepresentative !=\"Yes\"")
                    .caseEventFieldLabel("Disclosure of electronic documents").done();
    }
}
