package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.model.Address;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code ResponseConfirmNameAddress} of event {@code DEFENDANT_RESPONSE_SPEC}.
 */
public final class DEFENDANTRESPONSESPECNonprodResponseConfirmNameAddressPage {
    private DEFENDANTRESPONSESPECNonprodResponseConfirmNameAddressPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("ResponseConfirmNameAddress");
        fields.readonly(CaseData::getSpecAoSRespondentDetailLabel);
        fields.readonlyNoSummary(CaseData::getRespondent2SameLegalRepresentative)
                    .fieldShowCondition("specAoSRespondentDetails=\"DO NOT SHOW IN UI\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(CaseData::getSpecAoSRespondentDetails);
        fields.readonlyNoSummary(CaseData::getRespondent1Copy)
                    .fieldShowCondition("specAoSRespondentDetails = \"DO_NOT_SHOW_IN_UI\" OR respondent1ClaimResponseTypeForSpec = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getRespondent2Copy)
                    .fieldShowCondition("specAoSRespondentDetails = \"DO_NOT_SHOW_IN_UI\" OR respondent1ClaimResponseTypeForSpec = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonly(CaseData::getSpecAoSRespondentInformation)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\" AND respondent1Copy.type!=\"COMPANY\" AND respondent1Copy.type!=\"ORGANISATION\"");
        fields.readonly(CaseData::getSpecAoSCompanyOrganisationRespondentInformation)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\" AND respondent1Copy.type!=\"INDIVIDUAL\" AND respondent1Copy.type!=\"SOLE_TRADER\"");
        fields.mandatory(CaseData::getSpecAoSApplicantCorrespondenceAddressRequired)
                    .fieldShowCondition("showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_1\"");
        fields.complex(CaseData::getSpecAoSApplicantCorrespondenceAddressdetails)
                    .mandatory(Address::getAddressLine1)
                    .optional(Address::getAddressLine2)
                    .optional(Address::getAddressLine3)
                    .optional(Address::getPostTown)
                    .optional(Address::getCounty)
                    .optional(Address::getCountry)
                    .mandatory(Address::getPostCode).done()
                    .fieldShowCondition("specAoSApplicantCorrespondenceAddressRequired=\"No\"");
        fields.readonly(CaseData::getSpecAoSRespondent2Information)
                    .fieldShowCondition("addRespondent2 = \"Yes\" AND showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2Copy.type!=\"COMPANY\" AND respondent2Copy.type!=\"ORGANISATION\"");
        fields.readonly(CaseData::getSpecAoSCompanyOrganisationRespondent2Information)
                    .fieldShowCondition("addRespondent2 = \"Yes\" AND showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\" AND respondent2Copy.type!=\"INDIVIDUAL\" AND respondent2Copy.type!=\"SOLE_TRADER\"");
        fields.mandatory(CaseData::getSpecAoSRespondent2HomeAddressRequired)
                    .fieldShowCondition("addRespondent2 = \"Yes\" AND showConditionFlags CONTAINS \"CAN_ANSWER_RESPONDENT_2\"");
        fields.complex(CaseData::getSpecAoSRespondent2HomeAddressDetails)
                    .mandatory(Address::getAddressLine1)
                    .optional(Address::getAddressLine2)
                    .optional(Address::getAddressLine3)
                    .optional(Address::getPostTown)
                    .optional(Address::getCounty)
                    .optional(Address::getCountry)
                    .mandatory(Address::getPostCode).done()
                    .fieldShowCondition("specAoSRespondent2HomeAddressRequired=\"No\"");
    }
}
