package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.dq.Respondent1DQ;
import uk.gov.hmcts.reform.civil.model.dq.Respondent2DQ;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code FileDirectionsQuestionnaire} of event {@code DEFENDANT_RESPONSE}.
 */
public final class DEFENDANTRESPONSENonprodFileDirectionsQuestionnairePage {
    private DEFENDANTRESPONSENonprodFileDirectionsQuestionnairePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("FileDirectionsQuestionnaire");
        fields.pageLabel("Respond to claim");
        fields.showCondition("multiPartyResponseTypeFlags=\"FULL_DEFENCE\" AND allocatedTrack !=\"SMALL_CLAIM\"");
        fields.complex(CaseData::getRespondent1DQ)
                    .mandatory(Respondent1DQ::getRespondent1DQFileDirectionsQuestionnaire)
                    .fieldShowCondition("respondent1ClaimResponseType=\"FULL_DEFENCE\" OR respondent1ClaimResponseTypeToApplicant2=\"FULL_DEFENCE\"").done();
        fields.readonly(CaseData::getApplicant1PartyNameLabelFileDirectionsQuestionnaire1)
                    .fieldShowCondition("respondent1ClaimResponseType=\"FULL_DEFENCE\" AND respondent2ClaimResponseType=\"FULL_DEFENCE\"");
        fields.readonly(CaseData::getRespondent2PartyNameLabelFileDirectionsQuestionnaire)
                    .fieldShowCondition("respondent1ClaimResponseType=\"FULL_DEFENCE\" AND respondent2ClaimResponseType=\"FULL_DEFENCE\"");
        fields.complex(CaseData::getRespondent2DQ)
                    .mandatory(Respondent2DQ::getRespondent2DQFileDirectionsQuestionnaire)
                    .fieldShowCondition("respondent2ClaimResponseType=\"FULL_DEFENCE\"").done();
        fields.readonly(CaseData::getApplicant1PartyNameLabelFileDirectionsQuestionnaire2)
                    .fieldShowCondition("respondent1ClaimResponseType=\"FULL_DEFENCE\" AND respondent2ClaimResponseType=\"FULL_DEFENCE\"");
        fields.readonly(CaseData::getRespondent1PartyNameLabelFileDirectionsQuestionnaire)
                    .fieldShowCondition("respondent1ClaimResponseType=\"FULL_DEFENCE\" AND respondent2ClaimResponseType=\"FULL_DEFENCE\"");
    }
}
