package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code PermissionGranted} of event {@code DISCONTINUE_CLAIM_CLAIMANT}.
 */
public final class DISCONTINUECLAIMCLAIMANTProdPermissionGrantedPage {
    private DISCONTINUECLAIMCLAIMANTProdPermissionGrantedPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("PermissionGranted");
        fields.pageLabel("Permission granted by the court");
        fields.showCondition("courtPermissionNeeded = \"YES\"");
        fields.readonlyNoSummary(CaseData::getPartiesNames4)
                    .publish(false);
        fields.mandatory(CaseData::getIsPermissionGranted)
                    .publish(false);
        fields.mandatory(CaseData::getPermissionGrantedComplex)
                    .fieldShowCondition("isPermissionGranted=\"YES\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getPermissionNotGrantedText)
                    .fieldShowCondition("isPermissionGranted=\"NO\"")
                    .publish(false);
    }
}
