package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code CourtPermission} of event {@code DISCONTINUE_CLAIM_CLAIMANT}.
 */
public final class DISCONTINUECLAIMCLAIMANTProdCourtPermissionPage {
    private DISCONTINUECLAIMCLAIMANTProdCourtPermissionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("CourtPermission");
        fields.pageLabel("Permission from the court");
        fields.readonlyNoSummary(CaseData::getPartiesNames3)
                    .publish(false);
        fields.mandatory(CaseData::getCourtPermissionNeeded);
        fields.readonlyNoSummary(CaseData::getCourtPermissionNeededText)
                    .fieldShowCondition("courtPermissionNeeded=\"NO\"")
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getCourtPermissionNeededChecked)
                    .fieldShowCondition("courtPermissionNeeded=\"NO\"")
                    .publish(false);
    }
}
