package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code UploadDocumentAndNote} of event {@code EVIDENCE_UPLOAD_JUDGE}.
 */
public final class EVIDENCEUPLOADJUDGEUploadDocumentAndNotePage {
    private EVIDENCEUPLOADJUDGEUploadDocumentAndNotePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("UploadDocumentAndNote");
        fields.pageLabel("Add a document with a note?");
        fields.showCondition("caseNoteType = \"DOCUMENT_AND_NOTE\"");
        fields.mandatory(CaseData::getDocumentAndNoteToAdd)
                    .fieldShowCondition("caseNoteType = \"DOCUMENT_AND_NOTE\"")
                    .retainHiddenValue();
    }
}
