package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.citizenui.FeePaymentOutcomeDetails;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code FeePaymentOutcomeGrantedRemission} of event {@code FEE_PAYMENT_OUTCOME}.
 */
public final class FEEPAYMENTOUTCOMEFeePaymentOutcomeGrantedRemissionPage {
    private FEEPAYMENTOUTCOMEFeePaymentOutcomeGrantedRemissionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("FeePaymentOutcomeGrantedRemission");
        fields.complex(CaseData::getFeePaymentOutcomeDetails)
                    .mandatory(FeePaymentOutcomeDetails::getHwfFullRemissionGrantedForHearingFee)
                    .fieldShowCondition("hwfFeeType = \"HEARING\"")
                    .caseEventFieldLabel("Was this a Full Remission HwF - granted outcome?")
                    .publish(false)
                    .mandatory(FeePaymentOutcomeDetails::getHwfOutstandingFeePaymentDoneForHearingFee)
                    .fieldShowCondition("hwfFeeType = \"HEARING\" AND hwfFullRemissionGrantedForHearingFee = \"No\"")
                    .publish(false).done();
        fields.readonlyNoSummary(CaseData::getCaseTitle2)
                    .publish(false);
        fields.complex(CaseData::getFeePaymentOutcomeDetails)
                    .mandatory(FeePaymentOutcomeDetails::getHwfFullRemissionGrantedForClaimIssue)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\"")
                    .caseEventFieldLabel("Was this a Full Remission HwF - granted outcome?")
                    .publish(false)
                    .mandatory(FeePaymentOutcomeDetails::getHwfOutstandingFeePaymentDoneForClaimIssue)
                    .fieldShowCondition("hwfFeeType = \"CLAIMISSUED\" AND hwfFullRemissionGrantedForClaimIssue = \"No\"")
                    .publish(false).done();
    }
}
