package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code FinalOrderSelect} of event {@code GENERATE_DIRECTIONS_ORDER}.
 */
public final class GENERATEDIRECTIONSORDERFinalOrderSelectPage {
    private GENERATEDIRECTIONSORDERFinalOrderSelectPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("FinalOrderSelect");
        fields.pageLabel("Make an order");
        fields.showCondition("finalOrderTrackToggle= \"SMALL_CLAIM\" OR finalOrderTrackToggle= \"FAST_CLAIM\"");
        fields.readonlyNoSummary(CaseData::getCaseParticipants)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getBilingualHint)
                    .fieldShowCondition("finalOrderAllocateToTrack=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getBilingualHintTextNotification)
                    .fieldShowCondition("bilingualHint=\"Yes\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getFinalOrderSelectionLabel)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getFinalOrderSelection)
                    .publish(false);
    }
}
