package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.GAN245FormUpload;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code GAUploadN245Form} of event {@code INITIATE_GENERAL_APPLICATION}.
 */
public final class INITIATEGENERALAPPLICATIONProdGAUploadN245FormPage {
    private INITIATEGENERALAPPLICATIONProdGAUploadN245FormPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("GAUploadN245Form");
        fields.showCondition("generalAppVaryJudgementType=\"Yes\" AND generalAppParentClaimantIsApplicant=\"No\"");
        fields.readonlyNoSummary(CaseData::getGeneralAppParentClaimantIsApplicant)
                    .fieldShowCondition("generalAppTypeLR.types = \"DO_NOT_SHOW_IN_UI\"");
        fields.complex(CaseData::getGaUploadN245FormUploadLabel, false)
                    .mandatory(GAN245FormUpload::getGeneralAppN245Download)
                    .mandatory(GAN245FormUpload::getGeneralAppN245Label).done();
        fields.mandatory(CaseData::getGeneralAppN245FormUpload);
    }
}
