package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.Address;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.Party;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.caseflags.Flags;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Defendant1Party} of event {@code MANAGE_CONTACT_INFORMATION}.
 */
public final class MANAGECONTACTINFORMATIONNonprodDefendant1PartyPage {
    private MANAGECONTACTINFORMATIONNonprodDefendant1PartyPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Defendant1Party");
        fields.showCondition("partyChosenId = \"DEFENDANT_1\"");
        fields.readonlyNoSummary(CaseData::getRespondent1PartyNameManageContactLabel);
        fields.readonlyNoSummary(CaseData::getDefendant1PartyTypeIndividualLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_INDIVIDUAL\"");
        fields.readonlyNoSummary(CaseData::getDefendant1PartyTypeCompanyLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_ORGANISATION\" OR partyChosenType=\"DEFENDANT_1_ADMIN_COMPANY\"");
        fields.readonlyNoSummary(CaseData::getDefendant1PartyTypeSoleTraderLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_SOLE_TRADER\"");
        fields.readonlyNoSummary(CaseData::getRespondent1IndividualTypeLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_LR_INDIVIDUAL\"");
        fields.readonlyNoSummary(CaseData::getRespondent1OrganisationTypeLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_LR_ORGANISATION\" OR partyChosenType=\"DEFENDANT_1_LR_COMPANY\"");
        fields.readonlyNoSummary(CaseData::getRespondent1SoleTraderTypeLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_LR_SOLE_TRADER\"");
        fields.complex(CaseData::getRespondent1)
                    .complex(Party::getFlags)
                    .optional(Flags::getRoleOnCase)
                    .fieldShowCondition("applicant2 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue().done()
                    .complex(Party::getFlags)
                    .optional(Flags::getPartyName)
                    .fieldShowCondition("applicant2 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue().done()
                    .optional(Party::getIndividualTitle)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_INDIVIDUAL\"")
                    .retainHiddenValue()
                    .mandatory(Party::getIndividualFirstName)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_INDIVIDUAL\"")
                    .retainHiddenValue()
                    .mandatory(Party::getIndividualLastName)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_INDIVIDUAL\"")
                    .retainHiddenValue()
                    .optional(Party::getIndividualDateOfBirth)
                    .mandatory(Party::getCompanyName)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_COMPANY\"")
                    .retainHiddenValue()
                    .mandatory(Party::getOrganisationName)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_ORGANISATION\"")
                    .retainHiddenValue()
                    .optional(Party::getSoleTraderTitle)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_SOLE_TRADER\"")
                    .retainHiddenValue()
                    .mandatory(Party::getSoleTraderFirstName)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_SOLE_TRADER\"")
                    .retainHiddenValue()
                    .mandatory(Party::getSoleTraderLastName)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_SOLE_TRADER\"")
                    .retainHiddenValue()
                    .optional(Party::getSoleTraderTradingAs)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_SOLE_TRADER\"")
                    .optional(Party::getSoleTraderDateOfBirth)
                    .mandatory(Party::getPrimaryAddress)
                    .complex(Party::getPrimaryAddress)
                    .mandatory(Address::getAddressLine1).done()
                    .complex(Party::getPrimaryAddress)
                    .optional(Address::getAddressLine2).done()
                    .complex(Party::getPrimaryAddress)
                    .optional(Address::getAddressLine3).done()
                    .complex(Party::getPrimaryAddress)
                    .optional(Address::getPostTown).done()
                    .complex(Party::getPrimaryAddress)
                    .optional(Address::getCounty).done()
                    .complex(Party::getPrimaryAddress)
                    .optional(Address::getCountry).done()
                    .complex(Party::getPrimaryAddress)
                    .mandatory(Address::getPostCode).done()
                    .optional(Party::getPartyEmail)
                    .fieldShowCondition("respondent1.type = \"INDIVIDUAL\" OR respondent1.type = \"SOLE_TRADER\" OR respondent1.type = \"ORGANISATION\" OR respondent1.type = \"COMPANY\"")
                    .retainHiddenValue()
                    .optional(Party::getPartyPhone)
                    .fieldShowCondition("respondent1.type = \"INDIVIDUAL\" OR respondent1.type = \"SOLE_TRADER\"")
                    .retainHiddenValue()
                    .mandatory(Party::getPartyID)
                    .fieldShowCondition("respondent1 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue()
                    .optional(Party::getFlags)
                    .fieldShowCondition("respondent1 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue()
                    .complex(Party::getFlags)
                    .optional(Flags::getRoleOnCase)
                    .fieldShowCondition("respondent1 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue().done()
                    .complex(Party::getFlags)
                    .optional(Flags::getPartyName)
                    .fieldShowCondition("respondent1 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue().done()
                    .complex(Party::getFlags)
                    .optional(Flags::getRoleOnCase)
                    .fieldShowCondition("respondent2 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue().done()
                    .complex(Party::getFlags)
                    .optional(Flags::getPartyName)
                    .fieldShowCondition("respondent2 = \"DO_NOT_SHOW_IN_UI\"")
                    .retainHiddenValue().done().done()
                    .caseEventFieldLabel(" ");
    }
}
