package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UpdateDetailsForm;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code PartySelection} of event {@code MANAGE_CONTACT_INFORMATION}.
 */
public final class MANAGECONTACTINFORMATIONProdPartySelectionPage {
    private MANAGECONTACTINFORMATIONProdPartySelectionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("PartySelection");
        fields.readonlyNoSummary(CaseData::getChoosePartyHeader);
        fields.complex(CaseData::getUpdateDetailsForm)
                    .mandatory(UpdateDetailsForm::getPartyChosen)
                    .caseEventFieldLabel("Select party")
                    .readonly(UpdateDetailsForm::getPartyChosenId)
                    .fieldShowCondition("partyChosen = \"DO_NOT_SHOW_IN_UI\"")
                    .readonly(UpdateDetailsForm::getPartyChosenType)
                    .fieldShowCondition("partyChosen = \"DO_NOT_SHOW_IN_UI\"").done();
    }
}
