package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code manageStayOptions} of event {@code MANAGE_STAY}.
 */
public final class MANAGESTAYManageStayOptionsPage {
    private MANAGESTAYManageStayOptionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("manageStayOptions");
        fields.readonlyNoSummary(CaseData::getManageStayOptionsLabel)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getManageStayOption)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getPreStayState)
                    .fieldShowCondition("manageStayOption = \"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getManageStayRequestUpdateHintText)
                    .fieldShowCondition("manageStayOption = \"REQUEST_UPDATE\"")
                    .publish(false);
    }
}
