package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Defendant1Party} of event {@code MANAGE_CONTACT_INFORMATION}.
 */
public final class MANAGECONTACTINFORMATIONNonprodDefendant1PartyPage {
    private MANAGECONTACTINFORMATIONNonprodDefendant1PartyPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Defendant1Party");
        fields.showCondition("partyChosenId = \"DEFENDANT_1\"");
        fields.readonlyNoSummary(CaseData::getRespondent1PartyNameManageContactLabel);
        fields.readonlyNoSummary(CaseData::getDefendant1PartyTypeIndividualLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_INDIVIDUAL\"");
        fields.readonlyNoSummary(CaseData::getDefendant1PartyTypeCompanyLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_ORGANISATION\" OR partyChosenType=\"DEFENDANT_1_ADMIN_COMPANY\"");
        fields.readonlyNoSummary(CaseData::getDefendant1PartyTypeSoleTraderLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_ADMIN_SOLE_TRADER\"");
        fields.readonlyNoSummary(CaseData::getRespondent1IndividualTypeLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_LR_INDIVIDUAL\"");
        fields.readonlyNoSummary(CaseData::getRespondent1OrganisationTypeLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_LR_ORGANISATION\" OR partyChosenType=\"DEFENDANT_1_LR_COMPANY\"");
        fields.readonlyNoSummary(CaseData::getRespondent1SoleTraderTypeLabel)
                    .fieldShowCondition("partyChosenType=\"DEFENDANT_1_LR_SOLE_TRADER\"");
        fields.complex(CaseData::getRespondent1).done()
                    .caseEventFieldLabel(" ");
    }
}
