package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.Mediation;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code mediationUnsuccessful} of event {@code MEDIATION_UNSUCCESSFUL}.
 */
public final class MEDIATIONUNSUCCESSFULMediationUnsuccessfulPage {
    private MEDIATIONUNSUCCESSFULMediationUnsuccessfulPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("mediationUnsuccessful");
        fields.readonlyNoSummary(CaseData::getCaseTitle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDefendantNameLabel)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDefendantName)
                    .publish(false);
        fields.readonly(CaseData::getShowCarmFields)
                    .fieldShowCondition("defendantName=\"DO NOT SHOW IN UI\"")
                    .publish(false);
        fields.complex(CaseData::getMediation)
                    .mandatory(Mediation::getUnsuccessfulMediationReason)
                    .fieldShowCondition("showCarmFields=\"No\"")
                    .publish(false)
                    .mandatory(Mediation::getMediationUnsuccessfulReasonsMultiSelect)
                    .fieldShowCondition("showCarmFields=\"Yes\"")
                    .publish(false).done();
    }
}
