package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.reform.civil.model.CertificateOfService;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code CertificateOfService2} of event {@code NOTIFY_DEFENDANT_OF_CLAIM}.
 */
public final class NOTIFYDEFENDANTOFCLAIMCertificateOfService2Page {
    private NOTIFYDEFENDANTOFCLAIMCertificateOfService2Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("CertificateOfService2");
        fields.pageLabel("Certificate Of Service - notify claim details for defendant 2");
        fields.showCondition("defendant2LIPAtClaimIssued=\"Yes\"");
        fields.readonly(CaseData::getCosLabelDef2);
        fields.readonly(CaseData::getCosLabelForClaimant1_2);
        fields.readonly(CaseData::getCosLabelForDefendant2);
        fields.complex(CaseData::getCosNotifyClaimDefendant2)
                    .mandatory(CertificateOfService::getCosDateOfServiceForDefendant)
                    .mandatory(CertificateOfService::getCosDateDeemedServedForDefendant)
                    .mandatory(CertificateOfService::getCosServedDocumentFiles)
                    .eventLabel("What documents did you serve?")
                    .mandatory(CertificateOfService::getCosRecipient)
                    .noHintText()
                    .mandatory(CertificateOfService::getCosRecipientServeType)
                    .mandatory(CertificateOfService::getCosRecipientServeLocation)
                    .noHintText()
                    .mandatory(CertificateOfService::getCosRecipientServeLocationOwnerType)
                    .mandatory(CertificateOfService::getCosRecipientServeLocationType)
                    .optional(CertificateOfService::getCosRecipientServeLocationTypeOther)
                    .noHintText()
                    .optional(CertificateOfService::getCosStatementOfTruthLabel)
                    .mandatory(CertificateOfService::getCosSender)
                    .mandatory(CertificateOfService::getCosSenderFirm)
                    .mandatory(CertificateOfService::getCosUISenderStatementOfTruthLabel).done();
    }
}
