package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code CertificateOfService1} of event {@code NOTIFY_DEFENDANT_OF_CLAIM_DETAILS}.
 */
public final class NOTIFYDEFENDANTOFCLAIMDETAILSCertificateOfService1Page {
    private NOTIFYDEFENDANTOFCLAIMDETAILSCertificateOfService1Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("CertificateOfService1");
        fields.pageLabel("Certificate Of Service - notify claim details for defendant 1");
        fields.showCondition("defendant1LIPAtClaimIssued=\"Yes\"");
        fields.mandatory(CaseData::getRespondent1)
                    .fieldShowCondition("cosLabelForDefendant1=\"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getCosLabelDef1);
        fields.readonly(CaseData::getCosLabelForClaimant1_1);
        fields.readonly(CaseData::getCosLabelForDefendant1);
        fields.complex(CaseData::getCosNotifyClaimDetails1).done();
    }
}
