package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.DocumentOrImageWithRegex;
import uk.gov.hmcts.reform.civil.model.ServedDocumentFiles;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code Upload} of event {@code NOTIFY_DEFENDANT_OF_CLAIM_DETAILS}.
 */
public final class NOTIFYDEFENDANTOFCLAIMDETAILSUploadPage {
    private NOTIFYDEFENDANTOFCLAIMDETAILSUploadPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("Upload");
        fields.showCondition("respondent1Represented=\"Yes\" OR respondent2Represented=\"Yes\"");
        fields.readonlyNoSummary(CaseData::getDocumentUploadWarning);
        fields.complex(CaseData::getServedDocumentFiles)
                    .readonly(ServedDocumentFiles::getDocumentsLabel)
                    .optional(ServedDocumentFiles::getParticularsOfClaimDocument)
                    .optional(ServedDocumentFiles::getParticularsOfClaimText)
                    .eventLabel("If you prefer you can copy and paste the details of claim here.")
                    .complex(ServedDocumentFiles::getMedicalReport, DocumentOrImageWithRegex.class)
                    .optional(DocumentOrImageWithRegex::getDocument).done()
                    .complex(ServedDocumentFiles::getScheduleOfLoss, DocumentOrImageWithRegex.class)
                    .optional(DocumentOrImageWithRegex::getDocument).done()
                    .complex(ServedDocumentFiles::getCertificateOfSuitability, DocumentOrImageWithRegex.class)
                    .optional(DocumentOrImageWithRegex::getDocument).done().done();
    }
}
