package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.sdo.ReasonForReconsideration;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code RequestForReconsideration} of event {@code REQUEST_FOR_RECONSIDERATION}.
 */
public final class REQUESTFORRECONSIDERATIONRequestForReconsiderationPage {
    private REQUESTFORRECONSIDERATIONRequestForReconsiderationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("RequestForReconsideration");
        fields.pageLabel("Request For Reconsideration");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA)
                    .fieldShowCondition("reasonForReconsiderationPartiesName=\"DO NOT SHOW IN UI\"");
        fields.readonlyNoSummary(CaseData::getReasonForReconsiderationPartiesName)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getReasonForReconsiderationSeparator)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getCasePartyRequestForReconsideration)
                    .fieldShowCondition("reasonForReconsiderationPartiesName = \"DO_NOT_SHOW\"")
                    .publish(false);
        fields.complex(CaseData::getReasonForReconsiderationApplicant)
                    .mandatory(ReasonForReconsideration::getReasonForReconsiderationTxt)
                    .fieldShowCondition("casePartyRequestForReconsideration = \"Applicant\"")
                    .noHintText().done()
                    .fieldShowCondition("casePartyRequestForReconsideration = \"Applicant\"");
        fields.complex(CaseData::getReasonForReconsiderationRespondent1)
                    .mandatory(ReasonForReconsideration::getReasonForReconsiderationTxt)
                    .fieldShowCondition("casePartyRequestForReconsideration = \"Respondent1\"")
                    .noHintText().done()
                    .fieldShowCondition("casePartyRequestForReconsideration = \"Respondent1\"");
        fields.complex(CaseData::getReasonForReconsiderationRespondent2)
                    .mandatory(ReasonForReconsideration::getReasonForReconsiderationTxt)
                    .fieldShowCondition("casePartyRequestForReconsideration = \"Respondent2\"")
                    .noHintText().done()
                    .fieldShowCondition("casePartyRequestForReconsideration = \"Respondent2\"");
        fields.readonly(CaseData::getAllocatedTrack)
                    .fieldShowCondition("reasonForReconsiderationPartiesName=\"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getClaimValue)
                    .fieldShowCondition("reasonForReconsiderationPartiesName=\"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getTotalClaimAmount)
                    .fieldShowCondition("reasonForReconsiderationPartiesName=\"DO NOT SHOW IN UI\"");
        fields.readonly(CaseData::getResponseClaimTrack)
                    .fieldShowCondition("reasonForReconsiderationPartiesName=\"DO NOT SHOW IN UI\"");
    }
}
