package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code RespondentResponse} of event {@code RETRIGGER_CLAIMANT_RESPONSE}.
 */
public final class RETRIGGERCLAIMANTRESPONSERespondentResponsePage {
    private RETRIGGERCLAIMANTRESPONSERespondentResponsePage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("RespondentResponse");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA);
        fields.readonly(CaseData::getClaimType);
        fields.readonly(CaseData::getAllocatedTrack);
        fields.readonlyNoSummary(CaseData::getClaimantResponseScenarioFlag);
        fields.readonlyNoSummary(CaseData::getRespondent1ClaimResponseType);
        fields.readonlyNoSummary(CaseData::getRespondent2ClaimResponseType);
    }
}
