package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code sendAndReplyOption} of event {@code SEND_AND_REPLY}.
 */
public final class SENDANDREPLYNonprodSendAndReplyOptionPage {
    private SENDANDREPLYNonprodSendAndReplyOptionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("sendAndReplyOption");
        fields.pageLabel(" ");
        fields.readonlyNoSummary(CaseData::getBilingualHint)
                    .fieldShowCondition("sendAndReplyOption=\"DO_NOT_SHOW\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getBilingualHintTextNotification)
                    .fieldShowCondition("bilingualHint=\"Yes\"")
                    .publish(false);
        fields.mandatory(CaseData::getSendAndReplyOption)
                    .caseEventFieldLabel("Do you want to send or reply to a message?")
                    .publish(false);
        fields.mandatory(CaseData::getMessagesToReplyTo)
                    .fieldShowCondition("sendAndReplyOption=\"REPLY\"")
                    .caseEventFieldLabel("Select a message to reply to")
                    .publish(false);
    }
}
