package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code SettleClaim} of event {@code SETTLE_CLAIM}.
 */
public final class SETTLECLAIMProdSettleClaimPage {
    private SETTLECLAIMProdSettleClaimPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("SettleClaim");
        fields.pageLabel("Reason for settlement");
        fields.readonlyNoSummary(CaseData::getPartiesNames)
                    .publish(false);
        fields.mandatory(CaseData::getSettleReason)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getHearingDate)
                    .fieldShowCondition("settleReason=\"DO NOT SHOW IN UI\"");
    }
}
