package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code WorkAllocation} of event {@code SETTLE_CLAIM_MARK_PAID_FULL}.
 */
public final class SETTLECLAIMMARKPAIDFULLProdWorkAllocationPage {
    private SETTLECLAIMMARKPAIDFULLProdWorkAllocationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("WorkAllocation");
        fields.showCondition("partiesNames=\"DO NOT SHOW IN UI\"");
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA);
        fields.readonly(CaseData::getApplicant1Represented);
        fields.readonly(CaseData::getRespondent1Represented);
        fields.readonly(CaseData::getAllocatedTrack);
        fields.readonly(CaseData::getResponseClaimTrack);
        fields.readonly(CaseData::getPreStayState);
    }
}
