package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingAddNewDirectionsDJ;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingDisclosureOfDocumentsDJ;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingFinalDisposalHearingDJ;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingFinalDisposalHearingTimeDJ;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingHearingNotesDJ;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingJudgesRecitalDJ;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingNotesDJ;
import uk.gov.hmcts.reform.civil.model.DisposalHearingOrderAndHearingDetailsDJ;
import uk.gov.hmcts.reform.civil.model.sdo.DisposalHearingOrderMadeWithoutHearingDJ;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingQuestionsToExpertsDJ;
import uk.gov.hmcts.reform.civil.model.defaultjudgment.DisposalHearingSchedulesOfLossDJ;
import uk.gov.hmcts.reform.civil.model.sdo.SdoR2WelshLanguageUsage;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code DisposalHearing} of event {@code STANDARD_DIRECTION_ORDER_DJ}.
 */
public final class STANDARDDIRECTIONORDERDJDisposalHearingPage {
    private STANDARDDIRECTIONORDERDJDisposalHearingPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("DisposalHearing");
        fields.showCondition("caseManagementOrderSelection = \"DISPOSAL_HEARING\"");
        fields.readonly(CaseData::getCaseManagementOrderDisposal)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingOrderAndHearingDetailsDJ, false)
                    .readonly(DisposalHearingOrderAndHearingDetailsDJ::getText).done();
        fields.complex(CaseData::getDisposalHearingJudgesRecitalDJ, false)
                    .readonly(DisposalHearingJudgesRecitalDJ::getLabel)
                    .mandatory(DisposalHearingJudgesRecitalDJ::getInput)
                    .readonly(DisposalHearingJudgesRecitalDJ::getLine).done();
        fields.readonlyNoSummary(CaseData::getDisposalHearingJudgementStatementDJ)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingDisclosureOfDocumentsDJToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingDisclosureOfDocumentsDJ, false)
                    .readonly(DisposalHearingDisclosureOfDocumentsDJ::getLabel)
                    .mandatory(DisposalHearingDisclosureOfDocumentsDJ::getInput)
                    .optional(DisposalHearingDisclosureOfDocumentsDJ::getDate).done()
                    .fieldShowCondition("disposalHearingDisclosureOfDocumentsDJToggle=\"SHOW\"");
        fields.optionalNoSummary(CaseData::getDisposalHearingWitnessOfFactDJToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingWitnessOfFactDJ, false).done()
                    .fieldShowCondition("disposalHearingWitnessOfFactDJToggle=\"SHOW\"");
        fields.optionalNoSummary(CaseData::getDisposalHearingMedicalEvidenceDJToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingMedicalEvidenceDJ, false).done()
                    .fieldShowCondition("disposalHearingMedicalEvidenceDJToggle=\"SHOW\"");
        fields.optionalNoSummary(CaseData::getDisposalHearingQuestionsToExpertsDJToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingQuestionsToExpertsDJ, false)
                    .readonly(DisposalHearingQuestionsToExpertsDJ::getText1)
                    .optional(DisposalHearingQuestionsToExpertsDJ::getDate)
                    .readonly(DisposalHearingQuestionsToExpertsDJ::getText2).done()
                    .fieldShowCondition("disposalHearingQuestionsToExpertsDJToggle=\"SHOW\"");
        fields.optionalNoSummary(CaseData::getDisposalHearingSchedulesOfLossDJToggle)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingSchedulesOfLossDJ, false)
                    .readonly(DisposalHearingSchedulesOfLossDJ::getLabel)
                    .mandatory(DisposalHearingSchedulesOfLossDJ::getInput1)
                    .optional(DisposalHearingSchedulesOfLossDJ::getDate1)
                    .mandatory(DisposalHearingSchedulesOfLossDJ::getInput2)
                    .optional(DisposalHearingSchedulesOfLossDJ::getDate2)
                    .mandatory(DisposalHearingSchedulesOfLossDJ::getInput3)
                    .optional(DisposalHearingSchedulesOfLossDJ::getDate3)
                    .mandatory(DisposalHearingSchedulesOfLossDJ::getInputText4).done()
                    .fieldShowCondition("disposalHearingSchedulesOfLossDJToggle=\"SHOW\"");
        fields.complex(CaseData::getDisposalHearingFinalDisposalHearingTimeDJ, false)
                    .mandatory(DisposalHearingFinalDisposalHearingTimeDJ::getInput)
                    .optional(DisposalHearingFinalDisposalHearingTimeDJ::getDateLabel)
                    .optional(DisposalHearingFinalDisposalHearingTimeDJ::getDate)
                    .mandatory(DisposalHearingFinalDisposalHearingTimeDJ::getTime)
                    .mandatory(DisposalHearingFinalDisposalHearingTimeDJ::getOtherHours)
                    .fieldShowCondition("disposalHearingFinalDisposalHearingTimeDJ.time = \"OTHER\"")
                    .mandatory(DisposalHearingFinalDisposalHearingTimeDJ::getOtherMinutes)
                    .fieldShowCondition("disposalHearingFinalDisposalHearingTimeDJ.time = \"OTHER\"").done();
        fields.readonlyNoSummary(CaseData::getDisposalHearingMethodTitleDJ)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getHearingMethodValuesDisposalHearingDJ)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getDisposalHearingMethodInPersonDJ)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingBundleDJToggle)
                    .fieldShowCondition("disposalHearingMethodInPersonDJ=\"DO_NOT_SHOW_IN_UI\"")
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingBundleDJ, false).done()
                    .fieldShowCondition("disposalHearingBundleDJToggle=\"DO_NOT_SHOW_IN_UI\"");
        fields.optionalNoSummary(CaseData::getDisposalHearingClaimSettlingDJToggle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingClaimSettlingDJ)
                    .fieldShowCondition("disposalHearingClaimSettlingDJToggle=\"SHOW\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getDisposalHearingCostsDJToggle)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getDisposalHearingCostsDJ)
                    .fieldShowCondition("disposalHearingCostsDJToggle=\"SHOW\"")
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingHearingNotesDJ, false)
                    .readonly(DisposalHearingHearingNotesDJ::getLabel)
                    .optional(DisposalHearingHearingNotesDJ::getInput)
                    .readonly(DisposalHearingHearingNotesDJ::getLine).done();
        fields.readonlyNoSummary(CaseData::getUseOfWelshLanguageDisposal)
                    .publish(false);
        fields.optionalNoSummary(CaseData::getSdoR2DisposalHearingUseOfWelshLangToggleDJ)
                    .publish(false);
        fields.complex(CaseData::getSdoR2DisposalHearingWelshLanguageDJ, false)
                    .readonly(SdoR2WelshLanguageUsage::getDescription).done()
                    .fieldShowCondition("sdoR2DisposalHearingUseOfWelshLangToggleDJ=\"SHOW\"");
        fields.readonlyNoSummary(CaseData::getSdoR2DisposalHearingWelshLanguageEndLineDJ)
                    .publish(false);
        fields.complex(CaseData::getDisposalHearingOrderMadeWithoutHearingDJ, false)
                    .readonly(DisposalHearingOrderMadeWithoutHearingDJ::getTitle)
                    .mandatory(DisposalHearingOrderMadeWithoutHearingDJ::getInput)
                    .readonly(DisposalHearingOrderMadeWithoutHearingDJ::getLine).done();
        fields.complex(CaseData::getDisposalHearingAddNewDirectionsDJ, false).done();
        fields.complex(CaseData::getDisposalHearingAddNewDirectionsDJ, DisposalHearingAddNewDirectionsDJ.class)
                    .optional(DisposalHearingAddNewDirectionsDJ::getDirectionComment).done();
        fields.complex(CaseData::getDisposalHearingFinalDisposalHearingDJ, false)
                    .readonly(DisposalHearingFinalDisposalHearingDJ::getLabel)
                    .mandatory(DisposalHearingFinalDisposalHearingDJ::getInput)
                    .optional(DisposalHearingFinalDisposalHearingDJ::getDate)
                    .mandatory(DisposalHearingFinalDisposalHearingDJ::getTime).done()
                    .fieldShowCondition("disposalHearingSchedulesOfLossDJToggle=\"DONOTSHOW\"");
        fields.complex(CaseData::getDisposalHearingNotesDJ, false)
                    .readonly(DisposalHearingNotesDJ::getLabel)
                    .mandatory(DisposalHearingNotesDJ::getInput)
                    .optional(DisposalHearingNotesDJ::getDate).done()
                    .fieldShowCondition("disposalHearingCostsDJToggle=\"DONOTSHOW\"");
    }
}
