package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code CaseManagementOrder} of event {@code STANDARD_DIRECTION_ORDER_DJ}.
 */
public final class STANDARDDIRECTIONORDERDJCaseManagementOrderPage {
    private STANDARDDIRECTIONORDERDJCaseManagementOrderPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("CaseManagementOrder");
        fields.readonlyNoSummary(CaseData::getApplicantVRespondentText)
                    .fieldShowCondition("caseManagementOrder=\"DO_NOT_SHOW_UI\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getCaseManagementOrder)
                    .publish(false);
        fields.mandatoryNoSummary(CaseData::getCaseManagementOrderSelection);
        fields.readonlyNoSummary(CaseData::getHearingDisposalText2)
                    .fieldShowCondition("caseManagementOrderSelection = \"DISPOSAL_HEARING\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getHearingTrialText2)
                    .fieldShowCondition("caseManagementOrderSelection = \"TRIAL_HEARING\"")
                    .publish(false);
        fields.optionalNoSummary(CaseData::getCaseManagementOrderAdditional)
                    .fieldShowCondition("caseManagementOrderSelection = \"TRIAL_HEARING\"")
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getFeatureToggleWA)
                    .fieldShowCondition("caseManagementOrder=\"DO_NOT_SHOW_UI\"")
                    .retainHiddenValue();
    }
}
