package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.caseprogression.HearingOtherComments;
import uk.gov.hmcts.reform.civil.model.caseprogression.RevisedHearingRequirements;
import uk.gov.hmcts.reform.civil.model.UserRole;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code ConfirmReadyClaimant} of event {@code TRIAL_READINESS}.
 */
public final class TRIALREADINESSConfirmReadyClaimantPage {
    private TRIALREADINESSConfirmReadyClaimantPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("ConfirmReadyClaimant");
        fields.pageLabel("Confirm this case is ready for trial or hearing");
        fields.showCondition("isApplicant1 = \"Yes\"");
        fields.readonlyNoSummary(CaseData::getIsApplicant1)
                    .fieldShowCondition("trialReadyApplicant = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getHearingDurationTextApplicant)
                    .fieldShowCondition("trialReadyApplicant = \"DO_NOT_SHOW_IN_UI\"");
        fields.readonlyNoSummary(CaseData::getCaseNameLabelApplicant);
        fields.readonlyNoSummary(CaseData::getTrialReadyLabelApplicant);
        fields.mandatory(CaseData::getTrialReadyApplicant);
        fields.readonlyNoSummary(CaseData::getApplicationNotReadyApplicant)
                    .fieldShowCondition("trialReadyApplicant = \"No\"");
        fields.complex(CaseData::getApplicantRevisedHearingRequirements)
                    .readonly(RevisedHearingRequirements::getStartLabel)
                    .mandatory(RevisedHearingRequirements::getRevisedHearingRequirements)
                    .noHintText()
                    .mandatory(RevisedHearingRequirements::getRevisedHearingComments)
                    .noHintText()
                    .mandatory(RevisedHearingRequirements::getEndLabel)
                    .mandatory(RevisedHearingRequirements::getEndLine).done()
                    .fieldShowCondition("trialReadyApplicant=\"Yes\" OR trialReadyApplicant=\"No\"");
        fields.readonlyNoSummary(CaseData::getHearingDurationNotReadyApplicant)
                    .fieldShowCondition("trialReadyApplicant=\"No\"");
        fields.readonlyNoSummary(CaseData::getHearingDurationReadyApplicant)
                    .fieldShowCondition("trialReadyApplicant=\"Yes\"");
        fields.complex(CaseData::getApplicantHearingOtherComments)
                    .readonly(HearingOtherComments::getStartLabel)
                    .optional(HearingOtherComments::getHearingOtherComments)
                    .noHintText().done()
                    .fieldShowCondition("trialReadyApplicant=\"Yes\" OR trialReadyApplicant=\"No\"");
    }
}
