package uk.gov.hmcts.reform.civil.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.model.CaseData;
import uk.gov.hmcts.reform.civil.model.UserRole;
import uk.gov.hmcts.reform.civil.model.mediation.UploadMediationDocumentsForm;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 *
 * <p>Wizard page {@code DocumentUpload} of event {@code UPLOAD_MEDIATION_DOCUMENTS}.
 */
public final class UPLOADMEDIATIONDOCUMENTSDocumentUploadPage {
    private UPLOADMEDIATIONDOCUMENTSDocumentUploadPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<CaseData, CaseState, Event.EventBuilder<CaseData, UserRole, CaseState>> fields) {
        fields.page("DocumentUpload");
        fields.pageLabel("Upload documents");
        fields.readonlyNoSummary(CaseData::getMediationDocumentUploadWarning)
                    .publish(false);
        fields.readonlyNoSummary(CaseData::getMediationDocumentUploadLabel)
                    .publish(false);
        fields.complex(CaseData::getUploadMediationDocumentsForm)
                    .mandatory(UploadMediationDocumentsForm::getNonAttendanceStatementForm)
                    .fieldShowCondition("mediationDocumentsType CONTAINS \"NON_ATTENDANCE_STATEMENT\"")
                    .publish(false)
                    .mandatory(UploadMediationDocumentsForm::getDocumentsReferredForm)
                    .fieldShowCondition("mediationDocumentsType CONTAINS \"REFERRED_DOCUMENTS\"")
                    .publish(false).done();
    }
}
