package uk.gov.hmcts.reform.civil.enums.finalorders;

public enum FinalOrdersClaimantRepresentationList {
    COUNSEL_FOR_CLAIMANT,
    SOLICITOR_FOR_CLAIMANT,
    COST_DRAFTSMAN_FOR_THE_CLAIMANT,
    THE_CLAIMANT_IN_PERSON,
    LAY_REPRESENTATIVE_FOR_THE_CLAIMANT,
    LEGAL_EXECUTIVE_FOR_THE_CLAIMANT,
    SOLICITORS_AGENT_FOR_THE_CLAIMANT,
    CLAIMANT_NOT_ATTENDING
}
