{
  "formatVersion": "1.1",
  "component": {
    "group": "org.apache.groovy",
    "module": "groovy-json",
    "version": "4.0.24",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "groovydocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "groovydoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-json-4.0.24-groovydoc.jar",
          "url": "groovy-json-4.0.24-groovydoc.jar",
          "size": 260098,
          "sha512": "92096a973d591280f90ad585b43403ebbd32f770e6f5fc8b9d1a44328c1500cc908af2a0294e2b09de7d3893213d7742de2da81aeea6f95ffe7dc2b34f3d2bd5",
          "sha256": "01b0c7055925ff0cbbef27d384e58c180ff0e819e80ff850b65c85a99de60fd2",
          "sha1": "4e9411cf7cdbc830e9e4dba3a7f019dc589d910b",
          "md5": "11cddc17e9b3f32fe9ebd183e88c12c0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-json-4.0.24-javadoc.jar",
          "url": "groovy-json-4.0.24-javadoc.jar",
          "size": 318166,
          "sha512": "1b28862af1d737a49b2aff7ec58cc46a0193807ef5aba377d19fbdbdb461f0a027519ebd03ebec104d230c09af5244e4a126f1c89a7eb9e023393f539512b0d2",
          "sha256": "637094df05335eb101dc31011a52f3417f7778ffacf3855593b1b9a876a6403f",
          "sha1": "0ff90cd9373b82be3f2700a7acc5c3040ceb42bc",
          "md5": "6f77dd936973dc57e2d32e1b55a28aa1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovy-json-4.0.24-sources.jar",
          "url": "groovy-json-4.0.24-sources.jar",
          "size": 106430,
          "sha512": "ba01e75b910e8170993e01567b4f8d04482e36d18a1a011c877057bf7b3ecdbd6b0a71b921b8da4d3bbb7f5be285ca0af20c8c7574a11ea9a3c606a258ccbf0f",
          "sha256": "dfefac0bb07030397d78e0ad61784e4a62d3ac1217794f0435dda209a288b720",
          "sha1": "c25639b4cc67cc4b7d250b25a8dd6249d976d143",
          "md5": "ba23c1d6c5d9d5d29a9c62005951fd80"
        }
      ]
    },
    {
      "name": "groovyApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.24"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-json-4.0.24.jar",
          "url": "groovy-json-4.0.24.jar",
          "size": 130013,
          "sha512": "da0019ba3393bfda9a400a06abae6064f79833ed44a6402e7a2f5862fd05462f57dd1b39f0a37d1066f08bfd0a6823ba8efbd848112c8ab5ae1c66358b1ce170",
          "sha256": "e813df50d6544b90bbdc3552105be9a69758d9134e3b6990d882f35fca3c858f",
          "sha1": "a735e5b44d96e17d1c370625a493e6a8a7e11be8",
          "md5": "4d7ea4c19441578749c52c7bfa2f0521"
        }
      ],
      "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-json",
          "version": "4.0.24"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy-json",
          "version": "4.0.24"
        }
      ]
    },
    {
      "name": "groovyRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.groovy",
          "module": "groovy-bom",
          "version": {
            "requires": "4.0.24"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.24"
          }
        }
      ],
      "files": [
        {
          "name": "groovy-json-4.0.24.jar",
          "url": "groovy-json-4.0.24.jar",
          "size": 130013,
          "sha512": "da0019ba3393bfda9a400a06abae6064f79833ed44a6402e7a2f5862fd05462f57dd1b39f0a37d1066f08bfd0a6823ba8efbd848112c8ab5ae1c66358b1ce170",
          "sha256": "e813df50d6544b90bbdc3552105be9a69758d9134e3b6990d882f35fca3c858f",
          "sha1": "a735e5b44d96e17d1c370625a493e6a8a7e11be8",
          "md5": "4d7ea4c19441578749c52c7bfa2f0521"
        }
      ],
      "capabilities": [
        {
          "group": "org.codehaus.groovy",
          "name": "groovy-json",
          "version": "4.0.24"
        },
        {
          "group": "org.apache.groovy",
          "name": "groovy-json",
          "version": "4.0.24"
        }
      ]
    }
  ]
}
