package uk.gov.hmcts.reform.civil.service.flowstate;

public enum FlowFlag {
    ONE_RESPONDENT_REPRESENTATIVE,
    TWO_RESPONDENT_REPRESENTATIVES,
    UNREPRESENTED_DEFENDANT_ONE,
    UNREPRESENTED_DEFENDANT_TWO,
    PIP_ENABLED,
    AGREED_TO_MEDIATION,
    IS_MULTI_TRACK,
    SDO_ENABLED,
    CONTACT_DETAILS_CHANGE,
    GENERAL_APPLICATION_ENABLED,
    BULK_CLAIM_ENABLED,
    RESPONDENT_RESPONSE_LANGUAGE_IS_BILINGUAL,
    LR_V_LIP_ENABLED,
    LIP_CASE;
}
