package uk.gov.hmcts.reform.civil.utils;

public enum NotificationCriterion {

    JUDGE_DISMISSED_APPLICATION,
    JUDGE_APPROVED_THE_ORDER,
    JUDGE_DIRECTION_ORDER,
    REQUEST_FOR_INFORMATION,
    LIST_FOR_HEARING,
    CONCURRENT_WRITTEN_REP,
    SEQUENTIAL_WRITTEN_REP,
    JUDGE_FREE_FORM_ORDER,
    NON_CRITERION
}
