/**
 * Add scenario for claimant
 */
INSERT INTO dbs.scenario (name, notifications_to_delete, notifications_to_create)
VALUES ('Scenario.AAA6.Update.CaseProceedsInCaseman.Claimant',
        '{"Notice.AAA6.ClaimIssue.ClaimSubmit.Required",
          "Notice.AAA6.ClaimIssue.ClaimFee.Required",
          "Notice.AAA6.ClaimIssue.Response.Await",
          "Notice.AAA6.ClaimIssue.Response.Required",
          "Notice.AAA6.DefResponse.MoretimeRequested.Claimant",
          "Notice.AAA6.DefResponse.FullAdmit.PayImmediately.Claimant",
          "Notice.AAA6.DefResponse.PartAdmit.PayImmediately.Claimant",
          "Notice.AAA6.DefResponse.FullOrPartAdmit.PayBySetDate.Claimant",
          "Notice.AAA6.DefResponse.FullOrPartAdmit.PayByInstallments.Claimant",
          "Notice.AAA6.DefResponse.OrgOrLtdCompany.FullOrPartAdmit.PayBySetDate.Claimant",
          "Notice.AAA6.DefResponse.OrgOrLtdCompany.FullOrPartAdmit.PayByInstallments.Claimant",
          "Notice.AAA6.DefResponse.PartAdmit.AlreadyPaid.Claimant",
          "Notice.AAA6.DefResponse.FullDefence.AlreadyPaid.Claimant",
          "Notice.AAA6.DefResponse.FullDefence.FullDispute.RefusedMediation.Claimant",
          "Notice.AAA6.DefResponse.FullDefence.FullDispute.SuggestedMediation.Claimant",
          "Notice.AAA6.DefResponse.ResponseTimeElapsed.Claimant",
          "Notice.AAA6.DefResponse.FullDefence.FullDispute.Multi.Int.Fast.Claimant",
          "Notice.AAA6.DefResponse.BilingualFlagSet.Claimant",
          "Notice.AAA6.ClaimantIntent.CCJ.Requested.Claimant",
          "Notice.AAA6.ClaimantIntent.ClaimSettled.Claimant",
          "Notice.AAA6.ClaimantIntent.ClaimSettledEvent.Claimant",
          "Notice.AAA6.ClaimantIntent.PartAdmit.Claimant",
          "Notice.AAA6.ClaimantIntent.FullAdmit.Claimant",
          "Notice.AAA6.ClaimantIntent.Mediation.Claimant",
          "Notice.AAA6.ClaimantIntent.GoToHearing.Claimant",
          "Notice.AAA6.ClaimantIntent.SettlementAgreement.AcceptOrRejectDefPlan.Claimant",
          "Notice.AAA6.ClaimantIntent.SettlementNoResponse.Claimant",
          "Notice.AAA6.ClaimantIntent.Settlement.DefendantResponseAccepts.Claimant",
          "Notice.AAA6.ClaimantIntent.SettlementAgreement.DefendantRejected.Claimant",
          "Notice.AAA6.ClaimantIntent.RequestedCCJ.Claimant",
          "Notice.AAA6.ClaimantIntent.MediationUnsuccessful.Claimant",
          "Notice.AAA6.JudgmentsOnline.JudgmentDeterminationIssued.Claimant",
          "Notice.AAA6.JudgmentsOnline.IssuedCCJ.Claimant",
          "Notice.AAA6.JudgmentsOnline.SetAsideError.Claimant",
          "Notice.AAA6.JudgmentsOnline.DefaultJudgmentIssued.Claimant",
          "Notice.AAA6.MediationUnsuccessful.TrackChange.CARM.Claimant",
          "Notice.AAA6.MediationUnsuccessful.Claimant1NonAttendance.CARM.Claimant",
          "Notice.AAA6.MediationUnsuccessful.NOTClaimant1NonContactable.CARM.Claimant",
          "Notice.AAA6.MediationSuccessful.CARM.Claimant",
          "Notice.AAA6.ClaimantIntent.Mediation.CARM.Claimant",
          "Notice.AAA6.DefResponse.FullDefence.FullDispute.CARM.Claimant",
          "Notice.AAA6.ClaimantIntent.SDODrawn.PreCaseProgression.Claimant",
          "Notice.AAA6.ClaimantIntent.MediationSuccessful.Claimant",
          "Notice.AAA6.ClaimantIntent.Defendant.OrgLtdCo.Claimant",
          "Notice.AAA6.ClaimantIntent.RequestJudgePlan.RequestedCCJ.Claimant"}',
        '{"Notice.AAA6.CaseProceedsInCaseman.Claimant": []}');

