{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-serialization",
    "version": "2.3.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-metadata-2.3.8.jar",
          "url": "ktor-serialization-2.3.8.jar",
          "size": 5186,
          "sha512": "ec2acdb4b8f63df91d9a6cc8e451ee606bd81e2fdedcac767604fe74825c3af875473afadabc6349984d80a0959927b3b5df8d72a5c5d46ab2b09981b3496cb7",
          "sha256": "23fa05b2fa1f74c8bee49b2fa4d0a6cd169776f5cbc3b7b4d08e677e6afb9f5e",
          "sha1": "173696ff496a3fb4154d0910c38955bbc9dcb33b",
          "md5": "c04e1343c0f4adf2da7c040b56a73202"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlin-2.3.8-sources.jar",
          "url": "ktor-serialization-2.3.8-sources.jar",
          "size": 3629,
          "sha512": "49fe12b9539306c0695c4e3271e3cfdf7e904d91a665eb256cc0f86c6b3c78e5b27a1bfedf51172a4d915f2a3e9daa0bfdc412ebef511edef268ae03566ab6ce",
          "sha256": "051d868621eaea7fcad8286bc90742ebca6b31f3f0759318850c3df3c138b3b7",
          "sha1": "85a50d9fd68216cc09f00bc3f88e87785c21613c",
          "md5": "f598d58db690f0b956deff64e9df7841"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosarm64/2.3.8/ktor-serialization-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosarm64/2.3.8/ktor-serialization-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosarm64/2.3.8/ktor-serialization-iosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iossimulatorarm64/2.3.8/ktor-serialization-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iossimulatorarm64/2.3.8/ktor-serialization-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iossimulatorarm64/2.3.8/ktor-serialization-iossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosx64/2.3.8/ktor-serialization-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosx64/2.3.8/ktor-serialization-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-iosx64/2.3.8/ktor-serialization-iosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-iosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-js/2.3.8/ktor-serialization-js-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-js",
        "version": "2.3.8"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-js/2.3.8/ktor-serialization-js-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-js",
        "version": "2.3.8"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-serialization-js/2.3.8/ktor-serialization-js-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-js",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-jvm/2.3.8/ktor-serialization-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-jvm/2.3.8/ktor-serialization-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-serialization-jvm/2.3.8/ktor-serialization-jvm-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-jvm",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxarm64/2.3.8/ktor-serialization-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxarm64/2.3.8/ktor-serialization-linuxarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxx64/2.3.8/ktor-serialization-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-linuxx64/2.3.8/ktor-serialization-linuxx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-linuxx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosarm64/2.3.8/ktor-serialization-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosarm64/2.3.8/ktor-serialization-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosarm64/2.3.8/ktor-serialization-macosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosx64/2.3.8/ktor-serialization-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosx64/2.3.8/ktor-serialization-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-macosx64/2.3.8/ktor-serialization-macosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-macosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-mingwx64/2.3.8/ktor-serialization-mingwx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-mingwx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-mingwx64/2.3.8/ktor-serialization-mingwx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-mingwx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosarm64/2.3.8/ktor-serialization-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosarm64/2.3.8/ktor-serialization-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosarm64/2.3.8/ktor-serialization-tvosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvossimulatorarm64/2.3.8/ktor-serialization-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvossimulatorarm64/2.3.8/ktor-serialization-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvossimulatorarm64/2.3.8/ktor-serialization-tvossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosx64/2.3.8/ktor-serialization-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosx64/2.3.8/ktor-serialization-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-tvosx64/2.3.8/ktor-serialization-tvosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-tvosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm32/2.3.8/ktor-serialization-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm32/2.3.8/ktor-serialization-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm32/2.3.8/ktor-serialization-watchosarm32-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm32",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm64/2.3.8/ktor-serialization-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm64/2.3.8/ktor-serialization-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosarm64/2.3.8/ktor-serialization-watchosarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchossimulatorarm64/2.3.8/ktor-serialization-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchossimulatorarm64/2.3.8/ktor-serialization-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchossimulatorarm64/2.3.8/ktor-serialization-watchossimulatorarm64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchossimulatorarm64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosx64/2.3.8/ktor-serialization-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosx64/2.3.8/ktor-serialization-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosx64",
        "version": "2.3.8"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-serialization-watchosx64/2.3.8/ktor-serialization-watchosx64-2.3.8.module",
        "group": "io.ktor",
        "module": "ktor-serialization-watchosx64",
        "version": "2.3.8"
      }
    }
  ]
}
