enum CaseRole {
  APPLICANT_SOLICITOR_ONE = 'APPLICANTSOLICITORONE',
  RESPONDENT_SOLICITOR_ONE = 'RESPONDENTSOLICITORONE',
  RESPONDENT_SOLICITOR_TWO = 'RESPONDENTSOLICITORTWO',
  DEFENDANT = 'DEFENDANT',
}

export default CaseRole;
