{
  "formatVersion": "1.1",
  "component": {
    "url": "../../okio/3.16.4/okio-3.16.4.module",
    "group": "com.squareup.okio",
    "module": "okio",
    "version": "3.16.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.16.4.jar",
          "url": "okio-jvm-3.16.4.jar",
          "size": 383010,
          "sha512": "1a7158538ae341b8a61fe7292506e12ca6063c5a51a1c122d0e934164395c7da585dc31b26ed88a993c47aeca89f6a854042c67a4bc7d771d35a0ece6c4dbde0",
          "sha256": "2196b993cd34dbbd919e7e01f57a4781b58bee80f86106163e287c20343a96a7",
          "sha1": "ceb794cf0bbf8d0d20f49aa91ce20db7fd77675d",
          "md5": "34d866f45bb2a65bf601cde52b72d096"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-3.16.4.jar",
          "url": "okio-jvm-3.16.4.jar",
          "size": 383010,
          "sha512": "1a7158538ae341b8a61fe7292506e12ca6063c5a51a1c122d0e934164395c7da585dc31b26ed88a993c47aeca89f6a854042c67a4bc7d771d35a0ece6c4dbde0",
          "sha256": "2196b993cd34dbbd919e7e01f57a4781b58bee80f86106163e287c20343a96a7",
          "sha1": "ceb794cf0bbf8d0d20f49aa91ce20db7fd77675d",
          "md5": "34d866f45bb2a65bf601cde52b72d096"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "okio-jvm-3.16.4-sources.jar",
          "url": "okio-jvm-3.16.4-sources.jar",
          "size": 190161,
          "sha512": "6b5cb77c7ea4ff487528a215eafe66dc66d41bc6a5b68baf0fdac7f58d169f819f04e30fb839b656d22df7fd3fe5df1fdf5d7f3c36a4653cec714230f1bd12d7",
          "sha256": "834d0ba65168b5314f447bd2403d134423c42ad1927fdcd24473b20c4fd5a7d8",
          "sha1": "f1def1873c2985b3600968b8038f1572539a4a39",
          "md5": "efaa82e2f67fecd6d0fc1fa3467bd1a7"
        }
      ]
    }
  ]
}
