{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "service-auth-provider-java-client",
    "version": "4.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "service-auth-provider-java-client-4.1.2.jar",
          "url": "service-auth-provider-java-client-4.1.2.jar",
          "size": 18652,
          "sha512": "3ac62034a6d708b47ba2f3a64a0a3aaac40c3087ed0b3143137e1763c88fde681eb8f25591cd8bcf16355e00c93eb24477828260eb758154c2b5c0b28ef4815a",
          "sha256": "506b5ce9a0ff4a8b5b38bbb5ebb4778e480263848726db0a753dc89c4192c093",
          "sha1": "929d42ccd608072b0c98f169b4ea22f0b1fdfcc6",
          "md5": "faf0e2649664307cb7a7fa0051154d17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.cloud",
          "module": "spring-cloud-starter-openfeign",
          "version": {
            "requires": "3.1.5"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "io.github.openfeign",
          "module": "feign-jackson",
          "version": {
            "requires": "12.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.warrenstrange",
          "module": "googleauth",
          "version": {
            "requires": "1.5.0"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "com.auth0",
          "module": "java-jwt",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "javax.servlet",
          "module": "javax.servlet-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "service-auth-provider-java-client-4.1.2.jar",
          "url": "service-auth-provider-java-client-4.1.2.jar",
          "size": 18652,
          "sha512": "3ac62034a6d708b47ba2f3a64a0a3aaac40c3087ed0b3143137e1763c88fde681eb8f25591cd8bcf16355e00c93eb24477828260eb758154c2b5c0b28ef4815a",
          "sha256": "506b5ce9a0ff4a8b5b38bbb5ebb4778e480263848726db0a753dc89c4192c093",
          "sha1": "929d42ccd608072b0c98f169b4ea22f0b1fdfcc6",
          "md5": "faf0e2649664307cb7a7fa0051154d17"
        }
      ]
    }
  ]
}
