enum SdoType {
  SMALL_TRACK_NO_SUM,
  SMALL_TRACK_SUM,
  SMALL_TRACK_NO_SUM_DRH,
  SMALL_TRACK_SUM_DRH,
  FAST_TRACK,
  FAST_TRACK_NIHL,
  TRAIL_NIHL,
  TRAIL = 'DECIDE_DAMAGES',
  DISPOSAL_HEARING = 'DISPOSAL',
};

export default SdoType;