{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-logging/3.0.5/kotlin-logging-3.0.5.module",
    "group": "io.github.microutils",
    "module": "kotlin-logging",
    "version": "3.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-jvm-3.0.5.jar",
          "url": "kotlin-logging-jvm-3.0.5.jar",
          "size": 43916,
          "sha512": "c9c5a06f6c1bb98838ecddb91ab815dc3be234ab13019233fb504ddb360948ce269bf32ea6be6d06ab05801c6f049262fdf83656c5b697f2b1c2ce38f10e4403",
          "sha256": "2a9477a4138487bb7fbb057ee3ac0f455b58f8d4bed94c885fa64260de59e4dc",
          "sha1": "82f2256aeedccfd9c27ea585274a50bf06517383",
          "md5": "874d1037e001e1afa916eb1acb5e5e81"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-logging-jvm-3.0.5.jar",
          "url": "kotlin-logging-jvm-3.0.5.jar",
          "size": 43916,
          "sha512": "c9c5a06f6c1bb98838ecddb91ab815dc3be234ab13019233fb504ddb360948ce269bf32ea6be6d06ab05801c6f049262fdf83656c5b697f2b1c2ce38f10e4403",
          "sha256": "2a9477a4138487bb7fbb057ee3ac0f455b58f8d4bed94c885fa64260de59e4dc",
          "sha1": "82f2256aeedccfd9c27ea585274a50bf06517383",
          "md5": "874d1037e001e1afa916eb1acb5e5e81"
        }
      ]
    }
  ]
}
