xui-webapp:
  enabled: true
  nodejs:
    imagePullPolicy: Always
    releaseNameOverride: ${SERVICE_NAME}-xui-webapp
    image: hmctspublic.azurecr.io/xui/webapp:latest
    ingressHost: xui-${SERVICE_FQDN}
    devcpuRequests: 100m
    devmemoryRequests: 512Mi
    devcpuLimits: 1
    devmemoryLimits: 1Gi
    environment:
      HEALTH_CCD_COMPONENT_API: http://${SERVICE_NAME}-ccd-api-gw/health
      HEALTH_CCD_DATA_API: http://${SERVICE_NAME}-ccd-data-store-api/health
      HEALTH_TERMS_AND_CONDITIONS_API: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal/health
      SERVICES_CCD_COMPONENT_API: http://${SERVICE_NAME}-ccd-api-gw
      SERVICES_CCD_DATA_STORE_API: http://${SERVICE_NAME}-ccd-data-store-api
      SERVICES_TERMS_AND_CONDITIONS: http://xui-terms-and-conditions-${SERVICE_FQDN}.service.core-compute-preview.internal
      JURISDICTIONS: CIVIL
      LAUNCH_DARKLY_CLIENT_ID: ~
      WA_SUPPORTED_JURISDICTIONS: "IA,PRIVATELAW"

ccd:
  ccd-data-store-api:
    java:
      imagePullPolicy: Always
      devcpuRequests: 100m
      devmemoryRequests: 2048Mi
      devmemoryLimits: 4096Mi
      environment:
        CASE_DOCUMENT_AM_API_ATTACH_DOCUMENT_ENABLED: false
        DATA_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DATA_STORE_IDAM_KEY: ${CCD_DATA_STORE_S2S_SECRET}
        DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_ps,bulk_scan_orchestrator,ccpay_bubble,ctsc_work_allocation,em_ccd_orchestrator,xui_webapp,civil_service,ccd_case_document_am_api
        IDAM_API_BASE_URL: https://idam-api.aat.platform.hmcts.net
        IDAM_OIDC_URL: https://idam-web-public.aat.platform.hmcts.net
        OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-aat2.internal:8443/openam/oauth2/realms/root/realms/hmcts
        CCD_S2S_AUTHORISED_SERVICES_CASE_USER_ROLES: civil_service
        CASE_DOCUMENT_AM_URL: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal
        IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: ${IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET}
        IDAM_DATA_STORE_SYSTEM_USER_USERNAME: ${IDAM_DATA_STORE_SYSTEM_USER_USERNAME}
        IDAM_DATA_STORE_SYSTEM_USER_PASSWORD: ${IDAM_DATA_STORE_SYSTEM_USER_PASSWORD}
        CCD_MULTIPARTY_FIX_ENABLED: true
        CCD_MULTIPARTY_LOG_LEVEL: DEBUG
        CCD_MULTIPARTY_CASE_TYPES: CIVIL
        CCD_MULTIPARTY_EVENTS: DEFENDANT_RESPONSE,ACKNOWLEDGE_CLAIM,CLAIMANT_RESPONSE
        ROLE_ASSIGNMENT_URL: http://am-role-assignment-service-aat.service.core-compute-aat.internal
      disableKeyVaults: true
      ingressHost: ccd-data-store-api-${SERVICE_FQDN}
  ccd-definition-store-api:
    java:
      imagePullPolicy: Always
      devcpuRequests: 100m
      devmemoryRequests: 512Mi
      devcpuLimits: 2
      devmemoryLimits: 1Gi
      environment:
        DEFINITION_STORE_DB_HOST: ${SERVICE_NAME}-postgresql
        DEFINITION_STORE_IDAM_KEY: ${CCD_DEFINITION_STORE_S2S_SECRET}
        IDAM_USER_URL: https://idam-web-public.aat.platform.hmcts.net
      disableKeyVaults: true
      ingressHost: ccd-definition-store-${SERVICE_FQDN}


camunda-bpm:
  enabled: true
  java:
    disableKeyVaults: true
    releaseNameOverride: ${SERVICE_NAME}-camunda
    ingressHost: camunda-${SERVICE_FQDN}
    devcpuRequests: 100m
    devmemoryRequests: 512Mi
    devcpuLimits: 1
    devmemoryLimits: 1Gi
    environment:
      CAMUNDA_API_AUTH_ENABLED: false
      CAMUNDA_DB_HOST: ${SERVICE_NAME}-postgresql
      CAMUNDA_DB_NAME: camunda
      CAMUNDA_DB_USER_NAME: ${POSTGRES_USER}
      CAMUNDA_DB_PASSWORD: ${POSTGRES_PASSWORD}
      CAMUNDA_BPM_DATABASE_SCHEMA_UPDATE: true
      S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
      CAMUNDA_DB_CONN_OPTIONS: ""
