{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.jaxrs",
    "module": "jackson-jaxrs-json-provider",
    "version": "2.17.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-base",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-jaxrs-json-provider-2.17.3.jar",
          "url": "jackson-jaxrs-json-provider-2.17.3.jar",
          "size": 15745,
          "sha512": "98ee16ebc004d0ed5a793876f1fa220804f7c705a485ae4fb1ef7f33455e6b22e36ff0acf83b87dcccfdd3412801471964d5c27f61cd3d367069c852fdd6d082",
          "sha256": "71d35524ebe7b6a350f144088cc286b7ebce8789c89b23624869b25e32075348",
          "sha1": "380a358c823a26caa214524393a28f45073b0c03",
          "md5": "19c5d2e313fa8ae3509618f4a8a67263"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.jaxrs",
          "module": "jackson-jaxrs-base",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-jaxb-annotations",
          "version": {
            "requires": "2.17.3"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.17.3"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-jaxrs-json-provider-2.17.3.jar",
          "url": "jackson-jaxrs-json-provider-2.17.3.jar",
          "size": 15745,
          "sha512": "98ee16ebc004d0ed5a793876f1fa220804f7c705a485ae4fb1ef7f33455e6b22e36ff0acf83b87dcccfdd3412801471964d5c27f61cd3d367069c852fdd6d082",
          "sha256": "71d35524ebe7b6a350f144088cc286b7ebce8789c89b23624869b25e32075348",
          "sha1": "380a358c823a26caa214524393a28f45073b0c03",
          "md5": "19c5d2e313fa8ae3509618f4a8a67263"
        }
      ]
    }
  ]
}
