{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.hmcts",
    "module": "auth-checker-lib",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.4"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-jre"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "auth-checker-lib-3.1.1.jar",
          "url": "auth-checker-lib-3.1.1.jar",
          "size": 43388,
          "sha512": "a94718d8bffdf2534d4e87854f6d8745c07cff1678b70a5d44a14a701c45a8a952ab158b02a3cb40ef51b9d26156881e3f9a68e4e7f573d4263620c8cb746ab4",
          "sha256": "6e0975e6ce97584577dd20fef2f83f179a317b263ade470f7c893bcb828a3879",
          "sha1": "e08d5c15a7e5a003fb61c50edf06040a1a68ff23",
          "md5": "9b06d651c56cfc70c69442c5df11c063"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.4.4"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt-api",
          "version": {
            "requires": "0.12.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-jre"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "3.4.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "auth-checker-lib-3.1.1.jar",
          "url": "auth-checker-lib-3.1.1.jar",
          "size": 43388,
          "sha512": "a94718d8bffdf2534d4e87854f6d8745c07cff1678b70a5d44a14a701c45a8a952ab158b02a3cb40ef51b9d26156881e3f9a68e4e7f573d4263620c8cb746ab4",
          "sha256": "6e0975e6ce97584577dd20fef2f83f179a317b263ade470f7c893bcb828a3879",
          "sha1": "e08d5c15a7e5a003fb61c50edf06040a1a68ff23",
          "md5": "9b06d651c56cfc70c69442c5df11c063"
        }
      ]
    }
  ]
}
