{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.3.7.jar",
          "url": "spring-boot-test-3.3.7.jar",
          "size": 249276,
          "sha512": "8514855c943ff1a60d6737a39ab0d0d967296405f74186b4eaf6185c3a67e6cb4897b97da4bc67e8f6811c33c72fcd802afc846a13854a1bbde8c21422c5ee0b",
          "sha256": "88c5d9f53e97fc262348f0814de28f8cefe7b2268de9dfb9c8dfc7a0a1a0e32a",
          "sha1": "fe37e1b4a6c0b517087bba62f0b1a4c26ff0b710",
          "md5": "2b1134289f5390672798fa43e7bfe4fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.16"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.3.7.jar",
          "url": "spring-boot-test-3.3.7.jar",
          "size": 249276,
          "sha512": "8514855c943ff1a60d6737a39ab0d0d967296405f74186b4eaf6185c3a67e6cb4897b97da4bc67e8f6811c33c72fcd802afc846a13854a1bbde8c21422c5ee0b",
          "sha256": "88c5d9f53e97fc262348f0814de28f8cefe7b2268de9dfb9c8dfc7a0a1a0e32a",
          "sha1": "fe37e1b4a6c0b517087bba62f0b1a4c26ff0b710",
          "md5": "2b1134289f5390672798fa43e7bfe4fa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.3.7-javadoc.jar",
          "url": "spring-boot-test-3.3.7-javadoc.jar",
          "size": 412999,
          "sha512": "eec3509c2e49d9aeb1cf573927812b50d8dd59c85d2de74207a1e51cbc02e2f21505c07f1794052c05cfa25f2812c7238520f62b1b4c4db87c5391bc6957e6ae",
          "sha256": "834d1ff7c9bdc24d1ff17495342a5cca690710e8e3eab590b18ae610a18b9ad2",
          "sha1": "907a03ed1c3c05be071c5a49ea1d7e1a59b8620a",
          "md5": "b19168373b12e23d3c28273596603c0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.3.7-sources.jar",
          "url": "spring-boot-test-3.3.7-sources.jar",
          "size": 172115,
          "sha512": "9ec52ab673109698558bbb9e059aee7d5c1f7dcd9fb0e50c3a1569ce669c1b1f9d7c8507d3faa726993218bf7f68e8dd66d46e59163ff03fa26b3aeca88a3394",
          "sha256": "89d442c3464e1130621d17908342610893b0c91c9c11281c2852376d5feaf861",
          "sha1": "af20177ab52c276fa6075a33704145625c683f59",
          "md5": "7b6b7ea0898f92333889557b91ae09cf"
        }
      ]
    }
  ]
}
