package uk.gov.hmcts.reform.civil.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class AdmitPartEmployer {
    @CCD(
            label = "## Name of employer (if employed by someone else) \n",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String employerDetailsLabel;

    @CCD(
            label = " ",
            searchable = false
    )
    private List<ListValue<EmployerDetail>> employerDetails;
}
