package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class AppealChoiceSecondDropdownB {
    @CCD(
            label = "at the appropriate appeal centre prescribed in  \n"
                            + "\n"
                            + "<a target=\"_blank\" href=\"https://www.justice.gov.uk/courts/procedure-rules/civil/rules/part52/practice-direction-52b-appeals-in-the-county-courts-and-high-court\">CPR52PDB Table B.</a> \n"
                            + "\n",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String grantedRefusedLabelLinkB;

    @CCD(
            label = "### The appellant's notice shall be filed at the appeal centre no later than 4pm on",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String appealGrantedRefusedDateLabelB;

    @CCD(
            label = " ",
            hint = "For example, 16 4 2021",
            searchable = false
    )
    private LocalDate appealGrantedRefusedDate;
}
