package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class BespokeDateHeardFinalOrders {
    @CCD(
            label = "## Bespoke range",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String bespokeRangeLabel;

    @CCD(
            label = "Enter a bespoke range of dates for hearing",
            hint = "For example, 16 4 2021, 19-20 4 2021 and 11-12 5 2021",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String bespokeRangeTextArea;
}
