package uk.gov.hmcts.reform.civil.model;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class BundleSubfolder {
    @CCD(
            label = "Subfolder Name",
            showCondition = "name=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private String name;

    @CCD(
            label = "Folder Documents",
            showCondition = "name=\"DUMMY_VALUE_TO_HIDE_FIELD\"",
            searchable = false
    )
    private List<ListValue<BundleDocument>> documents;
}
