package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum ConfirmReferToJudgeDefenceReceived implements HasLabel {
    CONFIRM("I confirm that I want to refer this decision to a judge");

    private final String label;
}
