package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@ComplexType(
        name = "courtStaffNextSteps",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum CourtStaffNextSteps2 implements HasLabel {
    NO_TASKS("There are no other tasks to complete"),

    STILL_TASKS("There are still tasks to do");

    private final String label;
}
