package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum DebtType implements HasLabel {
    MORTGAGE("Mortgage"),

    RENT("Rent"),

    COUNCIL_TAX("Council tax"),

    GAS("Gas"),

    ELECTRICITY("Electricity"),

    WATER("Water"),

    MAINTENANCE_PAYMENTS("Maintenance payments");

    private final String label;
}
