package uk.gov.hmcts.reform.civil.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum DisposalHearingMethodVideoConferenceHearingDJ implements HasLabel {
    VIDEO_THE_CLAIMANT("The claimant", "videoTheClaimant"),

    VIDEO_THE_DEFENDANT("The defendant", "videoTheDefendant"),

    VIDEO_THE_COURT("The court", "videoTheCourt");

    private final String label;

    @JsonValue
    private final String code;
}
