package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class DocumentAndName {
    @CCD(
            label = "Name of document",
            searchable = false
    )
    private String documentName;

    @CCD(
            label = "Document",
            regex = ".pdf,.txt,.doc,.dot,.docx,.rtf,.xls,.xlt,.xla,.xlsx,.xltx,.xlsb,.ppt,.pot,.pps,.ppa,.pptx,.potx,.ppsx,.jpg,.jpeg,.bmp,.tif,.tiff,.png",
            searchable = false
    )
    private Document document;

    @CCD(
            label = "Date added",
            showCondition = "document = \"DO_NOT_SHOW\"",
            searchable = false
    )
    private LocalDateTime createdDateTime;

    @CCD(
            label = "Created by",
            showCondition = "createdDateTime = \"DO_NOT_SHOW\"",
            searchable = false
    )
    private String createdBy;
}
