package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum EvidenceUploadExpertSmallClaim implements HasLabel {
    EXPERT_REPORT("Expert's report"),

    JOINT_STATEMENT("Joint Statement of Experts / Single Joint Expert Report");

    private final String label;
}
