package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class FastTrackEmployersLiability {
    @CCD(
            label = " ",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String label;

    @CCD(
            label = "Subject to any direction, ruling, or finding of the trial judge, any employer's accident report and Health and Safety Executive report with witness statements will be admissible in evidence.",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String text;

    @CCD(
            label = "****",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String line;
}
