package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class FinalOrderFurtherHearingDatesAvoid {
    @CCD(
            label = "The parties must, by 4pm on",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String datesToAvoidDatesTopText;

    @CCD(
            label = " ",
            hint = "For example, 16 4 2021",
            searchable = false
    )
    private LocalDate datesToAvoidDates;

    @CCD(
            label = "upload the dates on which they are unavailable for a hearing",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String datesToAvoidDatesBottomText;
}
