package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class GACaseLocationGAspec {
    @CCD(
            label = " ",
            searchable = false
    )
    private String region;

    @CCD(
            label = " ",
            searchable = false
    )
    private String baseLocation;

    @CCD(
            label = " ",
            searchable = false
    )
    private String siteName;

    @CCD(
            label = " ",
            searchable = false
    )
    private String address;

    @CCD(
            label = " ",
            searchable = false
    )
    private String postcode;
}
