package uk.gov.hmcts.reform.civil.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum GAHearingScheduleGAspec implements HasLabel {
    YES("Yes", "Yes"),

    NO("No", "No");

    private final String label;

    @JsonValue
    private final String code;
}
