package uk.gov.hmcts.reform.civil.model;

import uk.gov.hmcts.reform.civil.enums.PaymentStatus;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class GAPaymentDetails {
    @CCD(
            label = "Payment status",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "PaymentStatus"
    )
    private PaymentStatus status;

    @CCD(
            label = "Payment reference returned from successful Payments API call",
            searchable = false
    )
    private String reference;

    @CCD(
            label = "Payment error message returned from failed Payments API call",
            searchable = false
    )
    private String errorMessage;

    @CCD(
            label = "Payment error code returned from failed Payments API call",
            searchable = false
    )
    private String errorCode;

    @CCD(
            label = "Customer reference",
            searchable = false
    )
    private String customerReference;
}
