package uk.gov.hmcts.reform.civil.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.LocalDate;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class GAUrgencyRecordGAspec {
    @CCD(
            label = "If you confirm that the application is urgent, the court will then decide if the application is urgent",
            searchable = false
    )
    private YesOrNo generalAppUrgency;

    @CCD(
            label = "Enter the date by which this application must be considered by a judge\n",
            showCondition = "generalAppUrgency = \"Yes\"",
            searchable = false
    )
    private LocalDate urgentAppConsiderationDate;

    @CCD(
            label = "Reasons for urgency. Disclose all relevant information to the court, including any information that may undermine the need for urgency\n",
            showCondition = "generalAppUrgency = \"Yes\"",
            searchable = false,
            max = 400,
            typeOverride = FieldType.TextArea
    )
    private String reasonsForUrgency;

    @JsonProperty("ConsentAgreementCheckBox")
    @CCD(
            label = " ",
            showCondition = "generalAppUrgency = \"Yes\"",
            searchable = false
    )
    private Set<GAUrgencyConsentGAspec> consentAgreementCheckBox;
}
