package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "hearingDatesParam",
        generate = true
)
public class HearingDatesParam {
    @CCD(
            label = "Date from",
            searchable = false
    )
    private LocalDate hearingUnavailableFrom;

    @CCD(
            label = "Date to",
            searchable = false
    )
    private LocalDate hearingUnavailableUntil;
}
