package uk.gov.hmcts.reform.civil.model;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum HearingLengthEstimate implements HasLabel {
    _15_MINUTES("15 minutes", "15_MINUTES"),

    _30_MINUTES("30 minutes", "30_MINUTES"),

    _45_MINUTES("45 minutes", "45_MINUTES"),

    _1_HOUR("1 hour", "1_HOUR"),

    _2_HOURS("2 hours", "2_HOURS"),

    OTHER("Other", "OTHER");

    private final String label;

    @JsonValue
    private final String code;
}
