package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum HomeOption implements HasLabel {
    OWNED_HOME("Home they own or pay a mortgage on"),

    JOINTLY_OWNED_HOME("Jointly-owned home (or jointly mortgaged home)"),

    PRIVATE_RENTAL("Private rental"),

    ASSOCIATION_HOME("Council or housing association home"),

    OTHER("Other");

    private final String label;
}
