package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class OtherRemedyFee {
    @CCD(
            label = "Amount to pay",
            searchable = false,
            typeOverride = FieldType.MoneyGBP
    )
    private String calculatedAmountInPence;

    @CCD(
            label = "Code",
            searchable = false
    )
    private String code;

    @CCD(
            label = "Version",
            searchable = false
    )
    private String version;
}
