package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum ReasonNotSuitableSDOList implements HasLabel {
    CHANGE_LOCATION("The case should be sent to another hearing centre for directions"),

    OTHER_REASONS("Other reason");

    private final String label;
}
