package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class RecurringIncome {
    @CCD(
            label = " ",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "IncomeType"
    )
    private IncomeType type;

    @CCD(
            label = "Type of income",
            showCondition = "type = \"OTHER\"",
            searchable = false
    )
    private String typeOtherDetails;

    @CCD(
            label = "Amount received",
            searchable = false,
            typeOverride = FieldType.MoneyGBP
    )
    private String amount;

    @CCD(
            label = "Paid every:",
            searchable = false
    )
    private WeekMonthPeriod frequency;
}
