package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class RequestedCourtForTabDetailsRes {
    @CCD(
            label = "The respondent legal representative requested the following court location code.",
            searchable = false
    )
    private String requestedCourt;

    @CCD(
            label = "Court name",
            searchable = false
    )
    private String requestedCourtName;

    @CCD(
            label = "Briefly explain your reasons for requesting this Court location.",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String reasonForHearingAtSpecificCourt;

    @CCD(
            label = "Do you want to ask for the hearing to be held remotely?",
            searchable = false
    )
    private YesOrNo requestHearingHeldRemotely;

    @CCD(
            label = "Briefly explain your reasons for having a remote hearing.",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String requestHearingHeldRemotelyReason;
}
