package uk.gov.hmcts.reform.civil.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class SameRateInterestOptions {
    @CCD(
            label = " ",
            searchable = false
    )
    private SameRateInterestSelectionList sameRateInterestType;

    @CCD(
            label = "Rate you're claiming\n",
            showCondition = "sameRateInterestType = \"SAME_RATE_INTEREST_DIFFERENT_RATE\"",
            searchable = false
    )
    private Integer differentRate;

    @CCD(
            label = "Why are you entitled to this rate?\n",
            showCondition = "sameRateInterestType = \"SAME_RATE_INTEREST_DIFFERENT_RATE\"",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String differentRateReason;
}
