package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum SameRateInterestSelectionList implements HasLabel {
    SAME_RATE_INTEREST_8_PC("8%"),

    SAME_RATE_INTEREST_DIFFERENT_RATE("A different rate");

    private final String label;
}
