package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class SdoR2TrialFromTo {
    @CCD(
            label = "### Trial window",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String sdoR2TrialWindowLabel;

    @CCD(
            label = "### List from",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String listFromLabel;

    @CCD(
            label = " ",
            searchable = false
    )
    private LocalDate listFrom;

    @CCD(
            label = "### Date to",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String dateToLabel;

    @CCD(
            label = " ",
            searchable = false
    )
    private LocalDate dateTo;
}
