package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum ServeLocationOwnerTypeCoS implements HasLabel {
    FRIEND("litigation friend's"),

    SOLICITOR("solicitor's"),

    DEFENDANT("defendant's"),

    CLAIMANT("claimant's");

    private final String label;
}
