package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class SingleDateHeardFinalOrders {
    @CCD(
            label = "## Single date",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String singleDateLabel;

    @CCD(
            label = "Single date",
            hint = "For example, 16 4 2021",
            searchable = false
    )
    private LocalDate singleDate;
}
