package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class StaffDocument {
    @CCD(
            label = "Document Name",
            searchable = false
    )
    private String documentName;

    @CCD(
            label = "Document URL",
            regex = ".pdf,.txt,.doc,.dot,.docx,.rtf,.xls,.xlt,.xla,.xlsx,.xltx,.xlsb,.ppt,.pot,.pps,.ppa,.pptx,.potx,.ppsx,.jpg,.jpeg,.bmp,.tif,.tiff,.png",
            searchable = false
    )
    private Document documentLink;

    @CCD(
            label = "Document Type",
            searchable = false,
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "StaffDocumentType"
    )
    private StaffDocumentType documentType;

    @CCD(
            label = "What type of document is it?",
            showCondition = "documentType=\"OTHER\"",
            searchable = false
    )
    private String documentTypeOther;

    @CCD(
            label = "Document size",
            searchable = false
    )
    private Integer documentSize;

    @CCD(
            label = "Uploaded on",
            searchable = false
    )
    private LocalDateTime createdDatetime;
}
