package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum Track implements HasLabel {
    SMALL_CLAIM("Small claim"),

    FAST_CLAIM("Fast claim"),

    MULTI_CLAIM("Multi claim"),

    INTERMEDIATE_CLAIM("Intermediate claim");

    private final String label;
}
