package uk.gov.hmcts.reform.civil.model;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        generate = true
)
public class TrialHearingNotesDJ {
    @CCD(
            label = " ",
            searchable = false,
            typeOverride = FieldType.Label
    )
    private String label;

    @CCD(
            label = " ",
            searchable = false,
            typeOverride = FieldType.TextArea
    )
    private String input;

    @CCD(
            label = " ",
            searchable = false
    )
    private LocalDate date;
}
