package uk.gov.hmcts.reform.civil.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from CIVIL on migration; owned by this service team.
 */
@RequiredArgsConstructor
@Getter
public enum WeekMonthPeriod implements HasLabel {
    ONCE_ONE_WEEK("Every week"),

    ONCE_TWO_WEEKS("Every 2 weeks"),

    ONCE_THREE_WEEKS("Every 3 weeks"),

    ONCE_FOUR_WEEKS("Every 4 weeks"),

    ONCE_ONE_MONTH("Every month");

    private final String label;
}
