{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "5.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-metadata-5.3.2.jar",
          "url": "okhttp-5.3.2.jar",
          "size": 767,
          "sha512": "165c65503bded11490b09c46935864aa71ee8b9fc4ea1c01e1cb91b209a64af97e92d5d8fd9b4bc78209a8949a79f37ff49edd992171d25ba6f7e0d968cee87c",
          "sha256": "e720a383fdc3eb1df4aac77a085e61b7730837364151de867093fdbcafcb44aa",
          "sha1": "6891a4fd19bcab6f69fe091c2bc6077edec5258e",
          "md5": "7cefaebda364337f3770168187124f31"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "okhttp-kotlin-5.3.2-sources.jar",
          "url": "okhttp-5.3.2-sources.jar",
          "size": 383544,
          "sha512": "af1ac2417654424d5a58b401c649199132c0d88d70c577f0d37ac634730908c1856ce8b5cd6a662182d09faa755bb8335c13169c6b0435d6b0b38e868b2e5129",
          "sha256": "786e2786a94e81e4f7d6d31b63684e3f3bc395390bfabe5384ce93d91661fc57",
          "sha1": "229fa86426895820a15b31cb5f1d3398995b7a20",
          "md5": "61a2a101e35211f818a01d21b363d9ad"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../okhttp-android/5.3.2/okhttp-android-5.3.2.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-android",
        "version": "5.3.2"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../okhttp-android/5.3.2/okhttp-android-5.3.2.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-android",
        "version": "5.3.2"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../okhttp-android/5.3.2/okhttp-android-5.3.2.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-android",
        "version": "5.3.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okhttp-jvm/5.3.2/okhttp-jvm-5.3.2.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-jvm",
        "version": "5.3.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okhttp-jvm/5.3.2/okhttp-jvm-5.3.2.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-jvm",
        "version": "5.3.2"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okhttp-jvm/5.3.2/okhttp-jvm-5.3.2.module",
        "group": "com.squareup.okhttp3",
        "module": "okhttp-jvm",
        "version": "5.3.2"
      }
    }
  ]
}
