{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.7.jar",
          "url": "spring-boot-starter-security-3.3.7.jar",
          "size": 4742,
          "sha512": "08e61ed4e0f187791d49900a3ea883c4030caafd208d1fa8a6550c5a8e8f4759f98461ef63c7561cb8ce4eda89256815248ab153edcaacec4461f93b5d21d4b7",
          "sha256": "d913f3ad7a588dfe6566940d9c1dabef1fc1e1b1a8c16750eb4d415ec7f032a7",
          "sha1": "af030ae8d8ba9f5000d5e9061336b64271664b92",
          "md5": "1bc77efb527eeccd0950b8a6a00dfeac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.7"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.16"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-config",
          "version": {
            "requires": "6.3.6"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.3.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.7.jar",
          "url": "spring-boot-starter-security-3.3.7.jar",
          "size": 4742,
          "sha512": "08e61ed4e0f187791d49900a3ea883c4030caafd208d1fa8a6550c5a8e8f4759f98461ef63c7561cb8ce4eda89256815248ab153edcaacec4461f93b5d21d4b7",
          "sha256": "d913f3ad7a588dfe6566940d9c1dabef1fc1e1b1a8c16750eb4d415ec7f032a7",
          "sha1": "af030ae8d8ba9f5000d5e9061336b64271664b92",
          "md5": "1bc77efb527eeccd0950b8a6a00dfeac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.7-javadoc.jar",
          "url": "spring-boot-starter-security-3.3.7-javadoc.jar",
          "size": 4742,
          "sha512": "08e61ed4e0f187791d49900a3ea883c4030caafd208d1fa8a6550c5a8e8f4759f98461ef63c7561cb8ce4eda89256815248ab153edcaacec4461f93b5d21d4b7",
          "sha256": "d913f3ad7a588dfe6566940d9c1dabef1fc1e1b1a8c16750eb4d415ec7f032a7",
          "sha1": "af030ae8d8ba9f5000d5e9061336b64271664b92",
          "md5": "1bc77efb527eeccd0950b8a6a00dfeac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-3.3.7-sources.jar",
          "url": "spring-boot-starter-security-3.3.7-sources.jar",
          "size": 4742,
          "sha512": "08e61ed4e0f187791d49900a3ea883c4030caafd208d1fa8a6550c5a8e8f4759f98461ef63c7561cb8ce4eda89256815248ab153edcaacec4461f93b5d21d4b7",
          "sha256": "d913f3ad7a588dfe6566940d9c1dabef1fc1e1b1a8c16750eb4d415ec7f032a7",
          "sha1": "af030ae8d8ba9f5000d5e9061336b64271664b92",
          "md5": "1bc77efb527eeccd0950b8a6a00dfeac"
        }
      ]
    }
  ]
}
