package uk.gov.hmcts.reform.civil.handler.event;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.camunda.bpm.engine.RuntimeService;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import uk.gov.hmcts.reform.ccd.client.model.CaseDetails;
import uk.gov.hmcts.reform.civil.config.SystemUpdateUserConfiguration;
import uk.gov.hmcts.reform.civil.enums.CaseState;
import uk.gov.hmcts.reform.civil.event.HearingNoticeSchedulerTaskEvent;
import uk.gov.hmcts.reform.civil.handler.tasks.variables.HearingNoticeMessageVars;
import uk.gov.hmcts.reform.civil.service.CoreCaseDataService;
import uk.gov.hmcts.reform.civil.service.UserService;
import uk.gov.hmcts.reform.civil.service.data.UserAuthContent;
import uk.gov.hmcts.reform.civil.utils.HmcDataUtils;
import uk.gov.hmcts.reform.hmc.model.hearing.HearingGetResponse;
import uk.gov.hmcts.reform.hmc.model.hearing.ListAssistCaseStatus;
import uk.gov.hmcts.reform.hmc.model.unnotifiedhearings.PartiesNotified;
import uk.gov.hmcts.reform.hmc.model.unnotifiedhearings.PartiesNotifiedResponse;
import uk.gov.hmcts.reform.hmc.model.unnotifiedhearings.PartiesNotifiedServiceData;
import uk.gov.hmcts.reform.hmc.service.HearingsService;

import java.time.LocalDateTime;
import java.util.Arrays;

import static uk.gov.hmcts.reform.civil.enums.CaseState.All_FINAL_ORDERS_ISSUED;
import static uk.gov.hmcts.reform.civil.enums.CaseState.CASE_DISCONTINUED;
import static uk.gov.hmcts.reform.civil.enums.CaseState.CASE_DISMISSED;
import static uk.gov.hmcts.reform.civil.enums.CaseState.CASE_SETTLED;
import static uk.gov.hmcts.reform.civil.enums.CaseState.CASE_STAYED;
import static uk.gov.hmcts.reform.civil.enums.CaseState.CLOSED;
import static uk.gov.hmcts.reform.civil.enums.CaseState.PROCEEDS_IN_HERITAGE_SYSTEM;

@Slf4j
@Service
@RequiredArgsConstructor
public class HearingNoticeSchedulerEventHandler {

    private final UserService userService;
    private final SystemUpdateUserConfiguration userConfig;
    private final HearingsService hearingsService;
    private final RuntimeService runtimeService;
    private final ObjectMapper mapper;
    private final CoreCaseDataService coreCaseDataService;
    static final CaseState[] DISALLOWED_CASE_STATES = {
        CASE_SETTLED,
        PROCEEDS_IN_HERITAGE_SYSTEM,
        CASE_STAYED,
        CASE_DISCONTINUED,
        CASE_DISMISSED,
        CLOSED,
        All_FINAL_ORDERS_ISSUED
    };

    @Async("asyncHandlerExecutor")
    @EventListener
    public void handle(HearingNoticeSchedulerTaskEvent event) {
        String hearingId = event.getHearingId();
        try {
            processHearing(hearingId);
        } catch (Exception e) {
            log.error("Processing hearingId [{}] failed due to error: {}", hearingId, e.getMessage());
        }
    }

    private void processHearing(String hearingId) {
        HearingGetResponse hearing = hearingsService.getHearingResponse(getSystemUpdateUser().getUserToken(), hearingId);
        ListAssistCaseStatus hearingStatus = hearing.getHearingResponse().getLaCaseStatus();
        LocalDateTime hearingRxDateTime = hearing.getHearingResponse().getReceivedDateTime();

        int hearingVersion = hearing.getRequestDetails().getVersionNumber().intValue();
        log.info("Processing hearing id: [{}] status: [{}] and requested version: [{}], hearing response: [{}]",
                 hearingId, hearingStatus, hearingVersion, hearingRxDateTime);

        if (!ListAssistCaseStatus.LISTED.equals(hearingStatus)) {
            log.info("Hearing status not 'LISTED' [{}].", hearingId);
            // Hearing has moved to a state where a notice should not be generated by the automated workflow
            notifyHmc(hearingId, hearing, new PartiesNotifiedServiceData());
            return;
        }

        PartiesNotifiedResponse notifiedResponse = getLatestPartiesNotifiedResponse(hearingId);
        Integer notifiedVersion = notifiedResponse != null ? notifiedResponse.getRequestVersion() : null;
        LocalDateTime notifiedRxDateTime = notifiedResponse != null ? notifiedResponse.getResponseReceivedDateTime() : null;
        PartiesNotifiedServiceData notifiedServiceData = (notifiedResponse != null && notifiedResponse.getServiceData() != null)
            ? notifiedResponse.getServiceData() : new PartiesNotifiedServiceData();

        boolean requiresNewHearingNotice = HmcDataUtils.requiresNewHearingNotice(notifiedResponse, hearing);
        boolean alreadyNotified = HmcDataUtils.isAlreadyNotifiedResponse(
            notifiedResponse, hearingVersion, hearingRxDateTime);
        log.info(
            "Hearing [{}] requested Version [{}], response RxDate [{}], notified Version [{}], notified RxDate [{}], "
                + "requires new hearing notice [{}], already notified [{}].",
            hearingId,
            hearingVersion,
            hearingRxDateTime,
            notifiedVersion,
            notifiedRxDateTime,
            requiresNewHearingNotice,
            alreadyNotified
        );

        if (alreadyNotified) {
            log.info("Skipping hearing id: [{}] already notified for this version [{}]",
                     hearingId, hearingVersion);
            return;
        }

        if (!requiresNewHearingNotice) {
            acknowledgeUnchangedHearing(
                hearingId, hearing, hearingVersion, hearingRxDateTime, notifiedServiceData);
            return;
        }

        String caseReference = hearing.getCaseDetails().getCaseRef();
        CaseDetails caseDetails = coreCaseDataService.getCase(Long.parseLong(caseReference));
        if (isAllowedState(caseDetails.getState(), caseReference)) {
            log.info("Dispatching hearing notice task for hearing [{}].", hearingId);
            // Initiate the automated hearing notice generation and notification workflow when a valid, new,
            // or updated hearing is detected
            triggerHearingNoticeEvent(new HearingNoticeMessageVars()
                                          .setHearingId(hearingId)
                                          .setCaseId(caseReference)
                                          .setTriggeredViaScheduler(true));
            return;
        }

        log.info("Updating parties notified for changed hearing [{}].", hearingId);
        // Acknowledge and mark a hearing as "processed" in HMC without generating a notice
        notifyHmc(hearingId, hearing, notifiedServiceData);
    }

    private void acknowledgeUnchangedHearing(String hearingId, HearingGetResponse hearing, int hearingVersion,
                                             LocalDateTime hearingRxDateTime,
                                             PartiesNotifiedServiceData notifiedServiceData) {
        try {
            log.info(
                "Updating parties notified for unchanged hearing [{}], version [{}], response RxDate [{}].",
                hearingId,
                hearingVersion,
                hearingRxDateTime
            );
            // Acknowledge and mark the current HMC hearing response as "processed".
            notifyHmc(hearingId, hearing, notifiedServiceData);
        } catch (Exception ex) {
            log.warn(
                "HMC update failed for unchanged hearing [{}], version [{}], response RxDate [{}]. Reason: {}",
                hearingId,
                hearingVersion,
                hearingRxDateTime,
                ex.getMessage()
            );
        }
    }

    private static boolean isAllowedState(String state, String caseReferene) {
        try {
            CaseState caseState = CaseState.valueOf(state);
            return !Arrays.asList(DISALLOWED_CASE_STATES).contains(caseState);
        } catch (IllegalArgumentException e) {
            log.info("Case state is not a valid one {} ", caseReferene);
            return false;
        }
    }

    private void triggerHearingNoticeEvent(HearingNoticeMessageVars messageVars) {
        String hearingNoticeMessage = "NOTIFY_HEARING_PARTIES";
        runtimeService
            .createMessageCorrelation(hearingNoticeMessage)
            .setVariables(messageVars.toMap(mapper))
            .correlateStartMessage();
    }

    private UserAuthContent getSystemUpdateUser() {
        String userToken = userService.getAccessToken(userConfig.getUserName(), userConfig.getPassword());
        String userId = userService.getUserInfo(userToken).getUid();
        return new UserAuthContent().setUserToken(userToken).setUserId(userId);
    }

    private void notifyHmc(String hearingId, HearingGetResponse hearing, PartiesNotifiedServiceData serviceData) {
        var partiesNotifiedPayload = new PartiesNotified()
            .setServiceData(serviceData);
        hearingsService.updatePartiesNotifiedResponse(
            getSystemUpdateUser().getUserToken(),
            hearingId,
            hearing.getRequestDetails().getVersionNumber().intValue(),
            hearing.getHearingResponse().getReceivedDateTime(),
            partiesNotifiedPayload
        );
    }

    private PartiesNotifiedResponse getLatestPartiesNotifiedResponse(String hearingId) {
        var partiesNotified = hearingsService.getPartiesNotifiedResponses(
            getSystemUpdateUser().getUserToken(), hearingId);
        return HmcDataUtils.getLatestHearingNoticeDetails(partiesNotified);
    }
}
