{
  "formatVersion": "1.1",
  "component": {
    "group": "au.com.dius.pact.provider",
    "module": "junit5",
    "version": "4.6.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "au.com.dius.pact",
          "module": "provider",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "pactbroker",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "model",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "junit5-4.6.17.jar",
          "url": "junit5-4.6.17.jar",
          "size": 82521,
          "sha512": "dc845aed3009b8627eae34810c40ccc300607868d379a51f79f8410b7bdde99d1c7f8a30a5fca8857cccf128b54785602673be712caa8400e9dfbbb8edcf2915",
          "sha256": "df00b686806d70ec7a25a48f3c1436c7133f0e6bdba46d441930d9d55eb3db26",
          "sha1": "cb280fa5c56bb38405517b401b7f03f96061c9b3",
          "md5": "fa597a77f6a55e4d00564c53b175b7a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "1.8.22"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api"
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "excludes": [
            {
              "group": "au.com.dius.pact.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.michael-bull.kotlin-result",
          "module": "kotlin-result",
          "version": {
            "requires": "1.1.14"
          }
        },
        {
          "group": "au.com.dius.pact",
          "module": "provider",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "support",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "pactbroker",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "au.com.dius.pact.core",
          "module": "model",
          "version": {
            "requires": "4.6.17"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "org.apache.tika",
          "module": "tika-core",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-jvm",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls-certificates",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-call-logging",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-handler",
          "version": {
            "requires": "4.1.108.Final"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-json",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-xml",
          "version": {
            "requires": "4.0.18"
          }
        },
        {
          "group": "io.pact.plugin.driver",
          "module": "core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "io.github.oshai",
          "module": "kotlin-logging-jvm",
          "version": {
            "requires": "5.1.4"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5-fluent",
          "version": {
            "requires": "5.3.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20240205"
          }
        }
      ],
      "files": [
        {
          "name": "junit5-4.6.17.jar",
          "url": "junit5-4.6.17.jar",
          "size": 82521,
          "sha512": "dc845aed3009b8627eae34810c40ccc300607868d379a51f79f8410b7bdde99d1c7f8a30a5fca8857cccf128b54785602673be712caa8400e9dfbbb8edcf2915",
          "sha256": "df00b686806d70ec7a25a48f3c1436c7133f0e6bdba46d441930d9d55eb3db26",
          "sha1": "cb280fa5c56bb38405517b401b7f03f96061c9b3",
          "md5": "fa597a77f6a55e4d00564c53b175b7a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit5-4.6.17-javadoc.jar",
          "url": "junit5-4.6.17-javadoc.jar",
          "size": 497927,
          "sha512": "ea87cb6463e744d584da3d41ab1a826aac130b0dcc29801640e8d30fccc08f1ccf5e3550d6539f37ed0048e5444e27e393722f152b6cd205b934e55da1971464",
          "sha256": "baf90822aacf05e373bacfb3e62042101eea8e44003dcb7aa94365f0eb77bca2",
          "sha1": "a2f07c979df44ee9de2cc334525f3bbd31c1093a",
          "md5": "3ced6224006c512ffc5a3cc05502f5a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit5-4.6.17-sources.jar",
          "url": "junit5-4.6.17-sources.jar",
          "size": 15324,
          "sha512": "d4a17c26945ae2761623db8607e1566446838a8e88f76582a9fa1bd87cf39767b51b22829e6e7ca8cbee36e90f3fd142aa7a345ff5d873ee7e0e077d874e49ed",
          "sha256": "32a241bf8246dbdf5730867ff40ed1700a75ee864a07a03c78e298dc42aeccc2",
          "sha1": "ba5a716110b5770d8f73846dc3a0a3cbdff7bdcb",
          "md5": "ba84646d90ec26d110edd3f9ab40c413"
        }
      ]
    }
  ]
}
